### ISSUE TITLE
protocol/identify/*: undefined

### ISSUE THREAD

**Issue by Koxanybak** [libp2p/go-libp2p#1006]
<details>
<summary>I was just playing around with libp2p and trying things out and it turns out I can't build my code. I am new to libp2p so it could be just a me doing something wrong. I am using VS Code and the go language server is showing any warnings either.</summary>

The error when running "go run main.go"/"go build":
<pre>
# github.com/libp2p/go-libp2p/p2p/protocol/identify
../../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.11.0/p2p/protocol/identify/id.go:380:3: undefined: helpers.FullClose
../../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.11.0/p2p/protocol/identify/id.go:424:20: undefined: helpers.FullClose
../../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.11.0/p2p/protocol/identify/id_delta.go:29:8: undefined: helpers.FullClose
../../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.11.0/p2p/protocol/identify/peer_loop.go:132:8: undefined: helpers.FullClose
../../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.11.0/p2p/protocol/identify/peer_loop.go:153:8: undefined: helpers.FullClose
</pre>

Go version:
<pre>
go version go1.15.2 linux/amd64
</pre>

My code:
<pre>
import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/binary"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"log"
	"os"

	"github.com/joho/godotenv"
	"github.com/libp2p/go-libp2p"
	"github.com/libp2p/go-libp2p-core/crypto"
	"github.com/libp2p/go-libp2p-core/host"
	"github.com/libp2p/go-libp2p-core/network"
)
//...
// Creates a p2p node
func createNode(listenPort string) (host.Host, error) {
	priv, _, err := crypto.GenerateRSAKeyPair(2048, *new(io.Reader))
	if err != nil {
		panic(err)
	}
	fmt.Println(priv)

	opts := []libp2p.Option{
		libp2p.ListenAddrStrings(fmt.Sprintf("/ip4/127.0.0.1/tcp/%s", listenPort)),
		libp2p.Identity(priv),
	}
	node, err := libp2p.New(context.Background(), opts...)
	if err != nil {
		return nil, err
	}

	return node, nil
}

// Stream handler
func handler(s network.Stream) {
	log.Println("Got a stream I guess")
}

// Main func
func main() {
	genesisBlock := generateGenesisBlock()
	BlockChain = append(BlockChain, genesisBlock)

	err := godotenv.Load()
	if err != nil {
		log.Fatalf("Unable to load .env file: %v", err)
	}
	listenPort := flag.String("p", os.Getenv("LISTEN_PORT"), "port to listen to")

	node, err := createNode(*listenPort)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf("Listening on multiaddr: %v\n", node.Addrs())
	node.SetStreamHandler("/p2p/1.0.0", handler)

	select {}
}
</pre>
Output of "go list -m all"
</summary>
<pre>
github.com/koxanybak/ketjuvote
cloud.google.com/go v0.26.0
github.com/AndreasBriese/bbloom v0.0.0-20190306092124-e2d15f34fcf9
github.com/BurntSushi/toml v0.3.1
github.com/Kubuxu/go-os-helper v0.0.1
github.com/OneOfOne/xxhash v1.2.2
github.com/aead/siphash v1.0.1
github.com/armon/consul-api v0.0.0-20180202201655-eb2c6b5be1b6
github.com/btcsuite/btcd v0.21.0-beta
github.com/btcsuite/btclog v0.0.0-20170628155309-84c8d2346e9f
github.com/btcsuite/btcutil v1.0.2
github.com/btcsuite/go-socks v0.0.0-20170105172521-4720035b7bfd
github.com/btcsuite/goleveldb v1.0.0
github.com/btcsuite/snappy-go v1.0.0
github.com/btcsuite/websocket v0.0.0-20150119174127-31079b680792
github.com/btcsuite/winsvc v1.0.0
github.com/census-instrumentation/opencensus-proto v0.2.1
github.com/cespare/xxhash v1.1.0
github.com/client9/misspell v0.3.4
github.com/cncf/udpa/go v0.0.0-20191209042840-269d4d468f6f
github.com/coreos/etcd v3.3.10+incompatible
github.com/coreos/go-etcd v2.0.0+incompatible
github.com/coreos/go-semver v0.3.0
github.com/cpuguy83/go-md2man v1.0.10
github.com/davecgh/go-spew v1.1.1
github.com/davidlazar/go-crypto v0.0.0-20200604182044-b73af7476f6c
github.com/decred/dcrd/lru v1.0.0
github.com/dgraph-io/badger v1.6.1
github.com/dgraph-io/ristretto v0.0.2
github.com/dgryski/go-farm v0.0.0-20190423205320-6a90982ecee2
github.com/dustin/go-humanize v1.0.0
github.com/envoyproxy/go-control-plane v0.9.4
github.com/envoyproxy/protoc-gen-validate v0.1.0
github.com/flynn/noise v0.0.0-20180327030543-2492fe189ae6
github.com/fsnotify/fsnotify v1.4.7
github.com/go-check/check v0.0.0-20180628173108-788fd7840127
github.com/gogo/protobuf v1.3.1
github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
github.com/golang/mock v1.1.1
github.com/golang/protobuf v1.4.0
github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
github.com/google/go-cmp v0.4.0
github.com/google/gopacket v1.1.18
github.com/google/renameio v0.1.0
github.com/google/uuid v1.1.2
github.com/gorilla/websocket v1.4.2
github.com/gxed/hashland/keccakpg v0.0.1
github.com/gxed/hashland/murmur3 v0.0.1
github.com/hashicorp/golang-lru v0.5.4
github.com/hashicorp/hcl v1.0.0
github.com/hpcloud/tail v1.0.0
github.com/huin/goupnp v1.0.0
github.com/huin/goutil v0.0.0-20170803182201-1ca381bf3150
github.com/inconshreveable/mousetrap v1.0.0
github.com/ipfs/go-cid v0.0.7
github.com/ipfs/go-datastore v0.4.4
github.com/ipfs/go-detect-race v0.0.1
github.com/ipfs/go-ds-badger v0.2.3
github.com/ipfs/go-ds-leveldb v0.4.2
github.com/ipfs/go-ipfs-delay v0.0.0-20181109222059-70721b86a9a8
github.com/ipfs/go-ipfs-util v0.0.2
github.com/ipfs/go-log v1.0.4
github.com/ipfs/go-log/v2 v2.1.1
github.com/jackpal/gateway v1.0.5
github.com/jackpal/go-nat-pmp v1.0.2
github.com/jbenet/go-cienv v0.1.0
github.com/jbenet/go-temp-err-catcher v0.1.0
github.com/jbenet/goprocess v0.1.4
github.com/jessevdk/go-flags v1.4.0
github.com/joho/godotenv v1.3.0
github.com/jrick/logrotate v1.0.0
github.com/kami-zh/go-capturer v0.0.0-20171211120116-e492ea43421d
github.com/kisielk/errcheck v1.2.0
github.com/kisielk/gotool v1.0.0
github.com/kkdai/bstream v0.0.0-20161212061736-f391b8402d23
github.com/konsorten/go-windows-terminal-sequences v1.0.1
github.com/koron/go-ssdp v0.0.2
github.com/kr/pretty v0.2.0
github.com/kr/pty v1.1.1
github.com/kr/text v0.1.0
github.com/libp2p/go-addr-util v0.0.2
github.com/libp2p/go-buffer-pool v0.0.2
github.com/libp2p/go-conn-security-multistream v0.2.0
github.com/libp2p/go-eventbus v0.2.1
github.com/libp2p/go-flow-metrics v0.0.3
github.com/libp2p/go-libp2p v0.11.0
github.com/libp2p/go-libp2p-autonat v0.4.0
github.com/libp2p/go-libp2p-blankhost v0.2.0
github.com/libp2p/go-libp2p-circuit v0.4.0
github.com/libp2p/go-libp2p-core v0.7.0
github.com/libp2p/go-libp2p-crypto v0.1.0
github.com/libp2p/go-libp2p-discovery v0.5.0
github.com/libp2p/go-libp2p-loggables v0.1.0
github.com/libp2p/go-libp2p-mplex v0.3.0
github.com/libp2p/go-libp2p-nat v0.0.6
github.com/libp2p/go-libp2p-netutil v0.1.0
github.com/libp2p/go-libp2p-noise v0.1.1
github.com/libp2p/go-libp2p-peer v0.2.0
github.com/libp2p/go-libp2p-peerstore v0.2.6
github.com/libp2p/go-libp2p-pnet v0.2.0
github.com/libp2p/go-libp2p-secio v0.2.2
github.com/libp2p/go-libp2p-swarm v0.3.1
github.com/libp2p/go-libp2p-testing v0.3.0
github.com/libp2p/go-libp2p-tls v0.1.3
github.com/libp2p/go-libp2p-transport-upgrader v0.3.0
github.com/libp2p/go-libp2p-yamux v0.4.0
github.com/libp2p/go-maddr-filter v0.1.0
github.com/libp2p/go-mplex v0.2.0
github.com/libp2p/go-msgio v0.0.6
github.com/libp2p/go-nat v0.0.5
github.com/libp2p/go-netroute v0.1.4
github.com/libp2p/go-openssl v0.0.7
github.com/libp2p/go-reuseport v0.0.2
github.com/libp2p/go-reuseport-transport v0.0.4
github.com/libp2p/go-sockaddr v0.1.0
github.com/libp2p/go-stream-muxer v0.0.1
github.com/libp2p/go-stream-muxer-multistream v0.3.0
github.com/libp2p/go-tcp-transport v0.2.1
github.com/libp2p/go-ws-transport v0.3.1
github.com/libp2p/go-yamux v1.4.0
github.com/magiconair/properties v1.8.0
github.com/mailru/easyjson v0.0.0-20180823135443-60711f1a8329
github.com/mattn/go-colorable v0.1.1
github.com/mattn/go-isatty v0.0.5
github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
github.com/miekg/dns v1.1.31
github.com/minio/blake2b-simd v0.0.0-20160723061019-3f5f724cb5b1
github.com/minio/sha256-simd v0.1.1
github.com/mitchellh/go-homedir v1.1.0
github.com/mitchellh/mapstructure v1.1.2
github.com/mr-tron/base58 v1.2.0
github.com/multiformats/go-base32 v0.0.3
github.com/multiformats/go-base36 v0.1.0
github.com/multiformats/go-multiaddr v0.3.1
github.com/multiformats/go-multiaddr-dns v0.2.0
github.com/multiformats/go-multiaddr-fmt v0.1.0
github.com/multiformats/go-multiaddr-net v0.2.0
github.com/multiformats/go-multibase v0.0.3
github.com/multiformats/go-multihash v0.0.14
github.com/multiformats/go-multistream v0.1.2
github.com/multiformats/go-varint v0.0.6
github.com/nxadm/tail v1.4.4
github.com/onsi/ginkgo v1.12.1
github.com/onsi/gomega v1.9.0
github.com/opentracing/opentracing-go v1.2.0
github.com/pelletier/go-toml v1.2.0
github.com/pkg/errors v0.9.1
github.com/pmezard/go-difflib v1.0.0
github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4
github.com/rogpeppe/go-internal v1.3.0
github.com/russross/blackfriday v1.5.2
github.com/sirupsen/logrus v1.2.0
github.com/smola/gocompat v0.2.0
github.com/spacemonkeygo/openssl v0.0.0-20181017203307-c2dcc5cca94a
github.com/spacemonkeygo/spacelog v0.0.0-20180420211403-2296661a0572
github.com/spaolacci/murmur3 v1.1.0
github.com/spf13/afero v1.1.2
github.com/spf13/cast v1.3.0
github.com/spf13/cobra v0.0.5
github.com/spf13/jwalterweatherman v1.0.0
github.com/spf13/pflag v1.0.3
github.com/spf13/viper v1.3.2
github.com/src-d/envconfig v1.0.0
github.com/stretchr/objx v0.1.1
github.com/stretchr/testify v1.6.1
github.com/syndtr/goleveldb v1.0.0
github.com/ugorji/go/codec v0.0.0-20181204163529-d75b2dcb6bc8
github.com/whyrusleeping/go-keyspace v0.0.0-20160322163242-5b898ac5add1
github.com/whyrusleeping/go-logging v0.0.1
github.com/whyrusleeping/mafmt v1.2.8
github.com/whyrusleeping/mdns v0.0.0-20190826153040-b9b60ed33aa9
github.com/whyrusleeping/multiaddr-filter v0.0.0-20160516205228-e903e4adabd7
github.com/x-cray/logrus-prefixed-formatter v0.5.2
github.com/xordataexchange/crypt v0.0.3-0.20170626215501-b2862e3d0a77
go.opencensus.io v0.22.4
go.uber.org/atomic v1.7.0
go.uber.org/goleak v1.0.0
go.uber.org/multierr v1.6.0
go.uber.org/tools v0.0.0-20190618225709-2cfd321de3ee
go.uber.org/zap v1.16.0
golang.org/x/crypto v0.0.0-20201002170205-7f63de1d35b0
golang.org/x/exp v0.0.0-20190121172915-509febef88a4
golang.org/x/lint v0.0.0-20190930215403-16217165b5de
golang.org/x/mod v0.1.1-0.20191105210325-c90efee705ee
golang.org/x/net v0.0.0-20201002202402-0a1ea396d57c
golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
golang.org/x/sync v0.0.0-20200317015054-43a5402ce75a
golang.org/x/sys v0.0.0-20201005172224-997123666555
golang.org/x/text v0.3.3
golang.org/x/tools v0.0.0-20191216052735-49a3e744a425
golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
google.golang.org/appengine v1.4.0
google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
google.golang.org/grpc v1.31.1
google.golang.org/protobuf v1.23.0
gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15
gopkg.in/errgo.v2 v2.1.0
gopkg.in/fsnotify.v1 v1.4.7
gopkg.in/src-d/go-cli.v0 v0.0.0-20181105080154-d492247bbc0d
gopkg.in/src-d/go-log.v1 v1.0.1
gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
gopkg.in/yaml.v2 v2.2.4
gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
honnef.co/go/tools v0.0.1-2019.2.3
</pre>
Thank you for answering in advance
</details>

**Comment by aschmahmann** [comment]
@Koxanybak you are using incompatible module dependencies.

In particular, you are using go-libp2p-core v0.7.0 which has breaking changes not yet implemented in go-libp2p. When choosing dependencies I would look at the ones supported by the libraries you're using (e.g. go-libp2p, go-libp2p-pubsub, go-libp2p-kad-dht, etc.).

Try downgrading to go-libp2p-core v0.6.1 (the one referenced in this repo's go.mod file) and things should probably be fine

**Comment by Koxanybak** [comment]
Thank you for your quick answer :)

Are there any resources to check when coming across similiar issues with libp2p (ie. to check that a I am not using the wrong version of any dependency)?

**Comment by aschmahmann** [comment]
Unfortunately, I can think of off any off top of my head 😢

However, I'd say the safe rule is to try and update each of the major components you're using and let those pull in the lower level updates (e.g. update go-libp2p-pubsub which will pull in the latest version of go-libp2p and go-libp2p-core it's been tested with).

Once you've done that you can start trying updates by bumping patch versions which should always be safe (e.g. from 0.1.1 to 0.1.20) and if you're feeling adventurous and will to read release notes then you can try bumping minor versions (e.g. from 0.1.1 to 0.2.0). Major version bumps are currently quite rare and if you see them you should definitely be checking out the relevant repos for updates.
