### ISSUE TITLE
NAT traversal: Quantify number of NATT'd and thus undialable peers 

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1011]
To measure the success of our NAT traversal effort, we need to quantity how many peers are currently not dialable because they are behind a NAT.

We can do this by deploying a "Now that you've dialled me, let me dial you back and see if you are reachable" protocol on the Hydra nodes.

The Hydra code is at https://github.com/libp2p/hydra-booster.

cc @alanshaw @Stebalien @jacobheun

**Comment by marten-seemann** [comment]
Suggestion: Implement a sanity check by dialing back via TCP and via QUIC and see if the numbers match.

**Comment by aarshkshah1992** [comment]
@marten-seemann Can you explain what happens if we don't do that ? Do you mean to say that that will ensure that the reason for the dial failure is indeed NAT and not some firewall issue related to the chosen transport protocol ?

**Comment by marten-seemann** [comment]
I don't expect anything bad to happen if we just dial back via TCP. NATting *should* lead to blocking in the same way for TCP and UDP. This is mostly a sanity check (and I imagine it's not more than a few LOC to add it). If we see a large difference between dial-back success rates between TCP and QUIC though, we know that something interesting is happening.

That said, there could be some UDP blocking on the path. According to Google's numbers, this apparently happens on a few % of the connections. Using both transports would allow us to generate our own numbers.

**Comment by aarshkshah1992** [comment]
This is done.
