### ISSUE TITLE
NAT traversal: Harden STUN/AutoNAT to ensure we share our publicly dialable addresses in Identify

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1012]
- The way we do STUN in libp2p is by using the Identify protocol to get our publicly visible address from remote peers.
- We then use AutoNAT to validate which of those public addresses are actually dialable.
- We should then be exchanging those validated addresses as a part of our public addresses in Identify.

This issue is to validate that the above flow works as expected and harden it.

@Stebalien @willscott Based on your experience working with the above, please can you give some ideas on what can be improved/needs to be fixed or implemented ?

**Comment by willscott** [comment]
* [ ] We don't currently use signed multiaddrs in the flow, and should
* [ ] Autonat finds addresses to work with / request dial-back's on by querying the host. A clearer structure of incoming candidates from Ident responses and logic for when network conditions may warrant re-testing would help
* [ ] Autonat logic doesn't have any network-context information. If a node is both on a VPN, and has an external connection it may well not do the right thing.
* [ ] it would probably nice for the host to have a clearer accounting of "local interface addreses" and "externally dial-able addresses" which are advertised. The second set isn't clearly broken out at the moment.

**Comment by Stebalien** [comment]
Also see #900.

**Comment by marten-seemann** [comment]
It would be interesting to see how this interacts with UDP blackholing. According to Google's measurements a few % of clients are behind NATs / firewalls that drop all UDP traffic. It would be interesting to see what happens in this case. Obviously, such a host will only be only able to use TCP to connect to the outside world. The question is now:
* Does this peer ask an AutoNAT to validate the (local) QUIC address that it's listening on.
* Does this peer then remove this QUIC address from its address advertisements if dialing that address fails?

**Comment by marten-seemann** [comment]
This will be resolved by AutoNAT v2: https://github.com/libp2p/specs/issues/503. Closing, since we have plenty of motivation to implement that proposal.
