### ISSUE TITLE
NAT traversal: Use QUIC connection migration after we have direct a hole punched connection between peers

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1016]
We have work underway to implement QUIC hole punching as part of #1015 .

QUIC introduces Connection Migration, which allows a connection to migrate (for example) from one interface to another. All streams (and other transport state except for congestion control) are transferred to the new path.
QUIC probes a new path before switching to it, to make sure to only migrate if the new path actually has connectivity.
Depending on the specifics of the relay protocol, we’d be able to first establish a connection via the relay, initiate the hole punching (via a separate control message to the server), and then initiate a connection migration. If the hole punching worked and a new path can be established, we migrate the connection. If, for any reason, the hole punching didn’t succeed and we can’t establish a new path, we continue using the relay to forward packets.

**Alternative:** Use the MASQUE protocol for relaying QUIC.

**Comment by aarshkshah1992** [comment]
cc @marten-seemann

**Comment by marten-seemann** [comment]
DCUtR solves this in a protocol-agnostic fashion. While this would be a nice use case for QUIC connection migration, I'm not sure the benefits are worth the complexity (note that as connection migration is not guaranteed to succeed, we'd have to re-tag a connection form transient to non-transient).
