### ISSUE TITLE
NAT traversal: Support for WebRTC transport in libp2p

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1018]
Please see #188  for some historical discussions and motivations for this issue.

- A WebRTC transport will enable better connectivity between js-libp2p and go- libp2p peers as the ONLY way to accomplish that right now is through websockets.
- WebRTC also has some NAT traversal mechanisms built in (albeit, not as strong as what we can accomplish ourselves with QUIC hole punching)
- We need to review https://github.com/mtojek/go-libp2p-webrtc-star and take it to completion.
- We will have to change the use of “centralized” STAR signaling servers in the above to use relays instead for signalling. It will be something similar to https://github.com/libp2p/specs/pull/173.

Some design notes on using relays instead of STAR signalling servers can be found at:
https://github.com/libp2p/js-libp2p/issues/385#issuecomment-514300699

**Comment by aarshkshah1992** [comment]
cc @jacobheun 

Please flesh out more details here if you feel something is missing at this stage of the discussion.

**Comment by backkem** [comment]
Can you elaborate on the differences between your quic and webrtc's hole punching? Is this documented somewhere?

**Comment by aarshkshah1992** [comment]
@backkem 

IIUC, WebRTC's hole punching dosen' t work well with five tuple NATs i.e. for NATs that allow incoming UDP packets from a **ip:port** ONLY if they've sent an outbound UDP packet to that **ip:port**.

cc @willscott if you have more questions.

**Comment by aarshkshah1992** [comment]
cc @yusefnapora  for thoughts and comments.

**Comment by p-shahi** [comment]
closing in favor of https://github.com/libp2p/specs/pull/412 and https://github.com/libp2p/go-libp2p/pull/1655
