### ISSUE TITLE
NAT Traversal: Enable SO_REUSEADDR and SO_REUSEPORT for TCP transports

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1020]
- Multiple TCP sockets should be able to share the same port for TCP hole punching to work correctly.
- The socket used to connect to the STUN server, the socket used to send the SYN for the hole punch, the socket for the TCP server that’s accepting incoming connections thus need to have the `SO_REUSEADDR/PORT` options enabled on all of them.

**Comment by Stebalien** [comment]
This is already enabled by default: https://github.com/libp2p/go-reuseport, https://github.com/libp2p/go-reuseport-transport/, and https://github.com/libp2p/go-tcp-transport/.

**Comment by aarshkshah1992** [comment]
As discussed with @Stebalien , we already do this in libp2p.
