### ISSUE TITLE
NAT traversal: Use Testground for testing

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1022]
We should use Testground for testing QUIC & TCP hole punching.

This issue is to explore if it's possible and if it is, write solid tests that prove our approach works.

Quoting @raulk  on some resources that can help achieve this:

> Use Testground tarffic shaping https://docs.testground.ai/traffic-shaping And also the network package in the SDK: https://pkg.go.dev/github.com/testground/sdk-go@v0.2.5/network 
> Right now TG can do all traffic shaping that netlink allows us to do, plus simulate connected and disconnected scenarios, assign concrete IP addresses, etc.

**Comment by p-shahi** [comment]
closing in favor of https://github.com/libp2p/test-plans/issues/64
