### ISSUE TITLE
support MaxMessageSize.

### ISSUE THREAD

**Issue by bugaolengdeyuxiaoer** [libp2p/go-libp2p#1026]
I have seen that mplex has 1M MaxMessageSize and yamux can set config of MaxMessageSize,but it seems not work.
I want to send 50MB message.Maybe let yamux support this.BTW, when call stream.Read(), a byte slice as param is required,
that is not good to me. Maybe return a byte slice has readed from buffer is better.

**Comment by Stebalien** [comment]
Libp2p is currently stream oriented, not message oriented (although we're currently working on adding message orientation). You can send/receive an arbitrary amount of data on a stream. The maximum message size in mplex is a protocol level constraint on how much data can be sent in a single protocol-level message. It has no impact on your application.

In terms of the API, please familiarize yourself with how streams are used in go: https://medium.com/learning-the-go-programming-language/streaming-io-in-go-d93507931185
