### ISSUE TITLE
Disconnected context in the identify protocol

### ISSUE THREAD

**Issue by MichaelMure** [libp2p/go-libp2p#1030]
Unless I'm missing something, the identify protocol should inherit from the host's context, which would then ensure that its main loop end when the host is terminated.

At the moment this main loop is left running after the host's context get cancelled.

See https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/identify/id.go#L130

**Comment by MichaelMure** [comment]
Alternatively and similar to https://github.com/libp2p/go-libp2p/issues/1031, `Close()` is not called properly when the host is terminated. What I found is that this goroutine is left hanging after the host's context get cancelled.

**Comment by aarshkshah1992** [comment]
@MichaelMure We shut down the `Identify` service when the Host is shut down over here:

https://github.com/libp2p/go-libp2p/blob/3155ff3089c0ab5ce2af49b2501600014b6c4816/p2p/host/basic/basic_host.go#L1003

The call to `Identify.Close()` will cancel the context that Identify's loop waits for:
https://github.com/libp2p/go-libp2p/blob/3155ff3089c0ab5ce2af49b2501600014b6c4816/p2p/protocol/identify/id.go#L276

Let me know if you have concerns otherwise  otherwise I can close this.

**Comment by MichaelMure** [comment]
Here is what I see:

```go
func TestFoo(t *testing.T) {
	defer goleak.VerifyNone(t)

	ctx, cancel := context.WithCancel(context.Background())

	_, err := libp2p.New(ctx,
		libp2p.ListenAddrStrings("/ip4/0.0.0.0/tcp/1234"),
	)
	require.NoError(t, err)

	time.Sleep(10 * time.Second)

	cancel()

	time.Sleep(10 * time.Second)
}
```

```
=== RUN   TestFoo
    leaks.go:78: found unexpected goroutines:
        [Goroutine 21 in state select, with github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine on top of the stack:
        goroutine 21 [select]:
        github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc0000b5e30)
        	/home/michael/go/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:71 +0x128
        created by github.com/ipfs/go-log/writer.NewMirrorWriter
        	/home/michael/go/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:36 +0xb9
        
         Goroutine 22 in state select, with go.opencensus.io/stats/view.(*worker).start on top of the stack:
        goroutine 22 [select]:
        go.opencensus.io/stats/view.(*worker).start(0xc000146080)
        	/home/michael/go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:276 +0x100
        created by go.opencensus.io/stats/view.init.0
        	/home/michael/go/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:34 +0x68
        
         Goroutine 5 in state select, with github.com/libp2p/go-libp2p-peerstore/pstoremem.(*memoryAddrBook).background on top of the stack:
        goroutine 5 [select]:
        github.com/libp2p/go-libp2p-peerstore/pstoremem.(*memoryAddrBook).background(0xc00012a000)
        	/home/michael/go/pkg/mod/github.com/libp2p/go-libp2p-peerstore@v0.2.6/pstoremem/addr_book.go:93 +0x126
        created by github.com/libp2p/go-libp2p-peerstore/pstoremem.NewAddrBook
        	/home/michael/go/pkg/mod/github.com/libp2p/go-libp2p-peerstore@v0.2.6/pstoremem/addr_book.go:83 +0x18e
        
         Goroutine 10 in state select, with github.com/libp2p/go-libp2p/p2p/protocol/identify.(*IDService).loop on top of the stack:
        goroutine 10 [select]:
        github.com/libp2p/go-libp2p/p2p/protocol/identify.(*IDService).loop(0xc0000b6b60)
        	/home/michael/go/pkg/mod/github.com/libp2p/go-libp2p@v0.11.0/p2p/protocol/identify/id.go:204 +0x4f7
        created by github.com/libp2p/go-libp2p/p2p/protocol/identify.NewIDService
        	/home/michael/go/pkg/mod/github.com/libp2p/go-libp2p@v0.11.0/p2p/protocol/identify/id.go:151 +0x2c3
        ]
--- FAIL: TestFoo (20.58s)
FAIL
```

Leaving aside opencensus and go-log, you can see that Identify and Peerstore are left around. Now admittedly, `Close()` could/should be used, but then why accepting a context?

Also, when actually using `Close()`, the Peerstore is still left around:
```
         Goroutine 11 in state select, with github.com/libp2p/go-libp2p-peerstore/pstoremem.(*memoryAddrBook).background on top of the stack:
        goroutine 11 [select]:
        github.com/libp2p/go-libp2p-peerstore/pstoremem.(*memoryAddrBook).background(0xc000170000)
        	/home/michael/go/pkg/mod/github.com/libp2p/go-libp2p-peerstore@v0.2.6/pstoremem/addr_book.go:93 +0x126
        created by github.com/libp2p/go-libp2p-peerstore/pstoremem.NewAddrBook
        	/home/michael/go/pkg/mod/github.com/libp2p/go-libp2p-peerstore@v0.2.6/pstoremem/addr_book.go:83 +0x18e
```

Just saw your edit. I understand now using the rational of using `Close()` instead of context cancelling, but then why accept a context in the first place as it expose to this incorrect termination? Is that something that will be removed? Maybe mention in the doc that the context is not to be used for closing?

**Comment by jacobheun** [comment]
@aarshkshah1992 can you take a look at this again?

**Comment by aarshkshah1992** [comment]
@jacobheun Taking a look

**Comment by aarshkshah1992** [comment]
@MichaelMure 

Unfortunately, we haven't finished migrating completely from using the context to the `Close` method. I've added documentation regarding using the `Close` method at https://github.com/libp2p/go-libp2p/pull/1037.

That PR also introduces a change to close the PeerStore.

**Comment by BigLep** [comment]
@aarshkshah1992 : at the minimum as part of your maintenance week can you either handle this or make it clear what the next steps are please?

**Comment by marten-seemann** [comment]
We moved away from using contexts for service shutdown, so I believe this issue has become stale.
