### ISSUE TITLE
IDFromString and Pretty are not compatible

### ISSUE THREAD

**Issue by rkapka** [libp2p/go-libp2p#1038]
Assume that `id` is a valid `peer.ID`. `peer.IDFromString(id.Pretty())` generates an error, even though I'm just converting the multihash back and forth.

**Comment by rkapka** [comment]
Maybe there is a bug inside `IDFromString`?

**Comment by aarshkshah1992** [comment]
@rkapka 

The `IDFromString` simply takes the peerID type converted to a string and not the string representation of the peerID.
Here's a sample example that works:

```
import (
	"fmt"

	"github.com/libp2p/go-libp2p-core/peer"
	"github.com/libp2p/go-libp2p-peerstore/test"
)

func main() {
	pid := test.GeneratePeerIDs(1)[0]
	id, err := peer.IDFromString(string(pid))
	if err != nil {
		panic(err)
	}
	fmt.Println(id)
// Output
QmVvtzcZgCkMnSFf2dnrBPXrWuNFWNM9J3MpZQCvWPuVZf
```

I agree the API isn't intuitive here :/. 

@Stebalien @raulk Any reason this was designed this way ?

**Comment by Stebalien** [comment]
I'm not sure. We should probably rename `IDFromString` to `IDFromByteString` (keeping but deprecating the former).
