### ISSUE TITLE
Update IPFS network diagnostics with NAT type

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1043]
Once https://github.com/ipfs/go-ipfs/pull/7068 AND https://github.com/libp2p/go-libp2p/pull/1042 are merged,

we should update the network diagnostics in IPFS to also emit the NAT type to the use and corresponding explanation regarding Hole Punching.

**Comment by willscott** [comment]
Is there anything we expect an end user to be able to do based on the NAT type? it might be vaguely interesting to say, but i'm not sure if the explanation can change much as a result.

**Comment by aarshkshah1992** [comment]
@willscott Ask them to currently give up all hopes of being reachable on the Internet and also...change their ISP :)

**Comment by wenyue** [comment]
I need this feature too, I think this is useful.

**Comment by MarcoPolo** [comment]
Should this issue be move to IPFS? I don't think there's anything actionable here on the go-libp2p side.

**Comment by MarcoPolo** [comment]
I don't have permissions here. Maybe @p-shahi does?

**Comment by p-shahi** [comment]
I'll close this issue here and create a new one in IPFS (can't move issues across organizations.)
