### ISSUE TITLE
QUIC Hole punching is slow

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1045]
Will take help from @marten-seemann once I have some QLOGS that show the whole orchestration of the simultaneous connect. For some reason, QUIC hole punch usually takes 3-4x the time of TCP hole punches.

Will have the numbers and logs to back this assertion soon.

**Comment by Stebalien** [comment]
@marten-seemann a lot has changed. Is this still correct?

**Comment by marten-seemann** [comment]
As far as I can remember, I've never received any qlogs regarding this issue. @aarshkshah1992, do you remember what happened?

**Comment by marten-seemann** [comment]
Not sure what the problem was here, but QUIC hole punching works well now.
