### ISSUE TITLE
Metrics collection for Hole Punching

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1047]
Once our hole punching endeavour is in decent shape(https://github.com/libp2p/go-libp2p/issues/1039) . we should put some metrics collection code in there to measure some important stats in the wild before we distribute it to a limited group of users. Some example stats include:

- Percentage of Symmetric NATs for TCP & UDP.
- Error percentage on Cone NATs for TCP & UDP.
- Hole Punch times for TCP & UDP.
- Bandwidth consumption on Relay servers for co-ordinating the Hole Punch.

This will help us get a better idea if there's parts of the code we can fix/optimize and understand the effectiveness of the endeavour.

**Comment by aarshkshah1992** [comment]
@willscott @jacobheun 

Inviting ideas on how to collect these stats in a "centralized" data store which we can inspect later.

**Comment by willscott** [comment]
A couple options we can think about:

* we could have nodes express their inferred Nat status as an advertised 'protocol' they speak. That would then allow that to show up in negotiations when they connect to peers, and we can have a node we run in the DHT track the relative prevalence of connecting peers to get a sense of different behaviors.

* we can add log messges of that, and track the logs of the nodes we run - this isn't representative of the larger IPFS user population though.

AFAIK we don't have ipfs nodes report back telemetry, in a centralized way, and I'm against adding that. This is a decentralized system, and shouldn't have reliance on centralized systems like that.

**Comment by marten-seemann** [comment]
This is now tracked in https://github.com/libp2p/specs/issues/370.
