### ISSUE TITLE
QUIC Hole Punching: One side should simply send a UDP packet instead of a full blown connection

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1048]
As implemented in https://github.com/libp2p/go-libp2p/pull/711/commits,  QUIC hole punching will result in two direct connections between the peers as QUIC dosen't have the "simultaneous open" feature that TCP does. This is because both peers attempt a full blown QUIC connect for the hole punch.

@marten-seemann has a cool idea wherein one of the peers can send a simple UDP packet to punch a hole and the other side can attempt a full blown QUIC connection thus getting us ONLY one connection in the end, saving us one connection for every successful hole punch we do.

**Comment by aarshkshah1992** [comment]
cc @vyzo  @Stebalien @marten-seemann 

If we do this via the "pass value in the context" route, we can avoid messy interface changes.

**Comment by marten-seemann** [comment]
This was implemented in https://github.com/libp2p/go-libp2p-quic-transport/pull/194/files.
