### ISSUE TITLE
Unsure about Connecting behaviour

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#105]
I'm making this issue as a note to go investigate and test what happens in the following situation:
- the node is not connected to peer P at the time we start this
- ipfs routine A calls `host.Connect(C1, P)` 
- ipfs routine B calls `host.Connect(C2, P)`
- ipfs routine A gets cancelled, so `C1` gets cancelled.

does routine B error out? or does it continue trying to connect to the peer?

**Comment by diasdavid** [comment]
Ideally, the `switch` should keep a ref count for the amount of processes dialling to a node and only stop dialing if all of them cancel out. This is something that needs to be improved in js-libp2p as well, part of the convertion of `libp2p-switch` to a state machine.

**Comment by raulk** [comment]
Hello, libp2p devs from 2016/7! Just dug up this old issue :D libp2p 2020 has dial deduplication at the swarm level: https://github.com/libp2p/go-libp2p-swarm/blob/master/dial_sync.go. So goroutine `B` from the OP would wait for `A` to complete, in success or error, and would get the same result as `A` when that happens.
