### ISSUE TITLE
Some libp2p streams needs to use transient connections

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1050]
Once https://github.com/libp2p/go-libp2p-transport-upgrader/pull/71 and the Limited Relay work by @vyzo lands, streams need to explicitly tell the Swarm(via a context) that they are okay with using Transient connections.

Streams like Identify and the Hole punching streams should use Transient connections as the Hole punching attempt depends on Identify completion.

**Comment by aarshkshah1992** [comment]
cc @vyzo 

Now that I think about it, all streams except `Identify` should use non-transient connections. I don't think we are missing much by not talking to DHT peers that are behinds Relays anyways. Wdyt ?

**Comment by marten-seemann** [comment]
We now have transient connections and we're using them in some application protocols.

**Comment by wanjunlengfeng** [comment]
relayv2.there is a word:check for a limit provided by the relay; if the limit is not nil, then this is a limited.relay connection and we mark the connection as transient.
so I set the value into  stat.Transient = false.
 "transient connection to peer"  dispear .
how do I get the correct set way?

**Comment by marten-seemann** [comment]
@wanjunlengfeng 
1. Please don't hijack issues that have been closed for more than a year.
2. This is not a bug report nor a feature request. Please refer to the forums: https://discuss.libp2p.io/.
