### ISSUE TITLE
Integrate Limited Relay Reservations into AutoRelay with static config

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1053]
For #1039 

Once https://github.com/libp2p/go-libp2p-circuit/pull/125 lands, we need to integrate Limited Relay Reservations into `AutoRelay` so we can advertise relay addresses after making reservations.

For now, we should ONLY aim to do this for statically configured Limited Relays and NOT via discovering Limited Relay servers as the network wont have enough of them. Discovering Limited Relays is planned for a later stage.

**Comment by marten-seemann** [comment]
Fixed by #1198.
