### ISSUE TITLE
Telemetry and metrics in Limited Relays

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1054]
For https://github.com/libp2p/go-libp2p/issues/1039.

Once https://github.com/libp2p/go-libp2p-circuit/pull/125 lands, we should add telemetry and metrics collection to the Limited Relays so we can monitor them better during dog-fooding.

Some suggestions:

i.  Number of Open Circuits Per Peer.
ii. Duration (in seconds) of each relay connection.
iii. Bandwidth consumption per Circuit.
iv. Reservation duration for each peer. 
v. Number of Open reservations.
vi. Number of reservations per ASN.
vii. Number of reservations per IP.

**Comment by aarshkshah1992** [comment]
cc @vyzo .

**Comment by vyzo** [comment]
This is completely unnecessary we can do all this with structured logging and logz.io; so no need to waste time and effort.
