### ISSUE TITLE
Testground tests for simultaneous connect

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1056]
For https://github.com/libp2p/go-libp2p/issues/1039.

We need to write testground plans that test backward compatibility of the simultaneous connect feature in multistream i.e. connections should work when a peer that does/does NOT support simultaneous connect tries to dial peer that does NOT/does support simultaneous connect.

1. Peer that does NOT support simultaneous connect should be able to connect to a peer that support simultaneous connect.
2. Opposite of 1.

**Comment by aarshkshah1992** [comment]
cc @vyzo

**Comment by marten-seemann** [comment]
Duplicate of #1022.
