### ISSUE TITLE
more context wiring

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#106]
There are many different long running calls that we don't pass contexts into, for example, the IdentifyConn call in p2p/protocol/identify. We should make an effort to have contexts wired throughout the entire codebase

**Comment by Stebalien** [comment]
We now:

1. Run identify on every conn automatically.
2. Provide an `IdentifyWait(conn) <-chan struct{}` to wait for this to finish.

We've also threaded contexts through to stream creation, so I think we're good.
