### ISSUE TITLE
Swarm dosen't support a SimOpen

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#1060]
Think of a simultaneous open scenario. 

- PeerX initiates an out bound dial to PeerY and vice versa via `host.Connect`. 

- PeerX's transport sees an incoming connection on the listener and decides to cancel the outbound dial since we don't want to end up with two connections and also don't want `Swarm` to see the same connection via dial and via accept (if we decide to intercept the incoming connection in dial and send it to the `Swarm`). 

- In this case, the `Swarm` will see that the dial failed and since the incoming connection is processed/added to the Swarm on a separate `go-routine`, it might NOT be able to see this connection immediately and return an error to the caller of the `host.Connect` call. This go-routine is here:

https://github.com/libp2p/go-libp2p-swarm/blob/3563ed1f3b270bf3ab9186bed2ef21c5ab9dff8e/swarm_listen.go#L84  

- We need a way for the `Swarm` to pick up the incoming connection and return successfully to the caller if an outbound dial is cancelled by the transport because it sees an incoming connection from the same peer.

**Comment by aarshkshah1992** [comment]
cc @vyzo @Stebalien

**Comment by Stebalien** [comment]
> PeerX's transport sees an incoming connection on the listener and decides to cancel the outbound dial since we don't want to end up with two connections and also don't want Swarm to see the same connection via dial and via accept (if we decide to intercept the incoming connection in dial and send it to the Swarm).

We don't do this (or shouldn't).

We cancel dials if, and _only_ if we successfully make an outbound dial:

https://github.com/libp2p/go-libp2p-swarm/blob/3563ed1f3b270bf3ab9186bed2ef21c5ab9dff8e/swarm.go#L262-L266

See https://github.com/libp2p/go-libp2p-swarm/issues/79 for history and context.

**Comment by marten-seemann** [comment]
Fixed by (among others) https://github.com/libp2p/go-libp2p/pull/1203.
