### ISSUE TITLE
Allow Dialer To Dial With A Custom Local Address

### ISSUE THREAD

**Issue by nisdas** [libp2p/go-libp2p#1063]
Currently if a peer wants to dial a remote peer, it will use any network interface available as we use either `0.0.0.0` or `::` as the default local addresses when dialing peers. However if a peer wants to restrict all application usage to a particular network interface it isn't possible currently. Ex:

https://github.com/libp2p/go-tcp-transport/blob/master/tcp.go#L118
https://github.com/libp2p/go-tcp-transport/blob/master/tcp.go#L121

In both of the above examples, we cannot provide the dialer with a custom local address to dial with so it defaults to the ipv4/ipv6 zero addresses. This is an issue for some users as they do not want to potentially expose a certain network interface to other peers.

**Comment by Stebalien** [comment]
If you don't want to expose certain IP addresses:

1. Specify a set of IP addresses to listen on (https://pkg.go.dev/github.com/libp2p/go-libp2p?utm_source=godoc#ListenAddrs).
2. Configure your default routes so you open outbound connections via the addresses you want to use.

Does that cover it?

**Comment by nisdas** [comment]
Yeap that seems like it would be the easiest path to proceed with here, a user can restrict through the IP addresses it listens on.

**Comment by nisdas** [comment]
Ok just to clarify this step isnt possible as far as i know currently in libp2p:

> Configure your default routes so you open outbound connections via the addresses you want to use.

Which is why I opened up the issue, is there a current option through which outbound routes can be configured for a host ?

**Comment by Stebalien** [comment]
That would be an OS level setting (i.e., `ip route`). libp2p could (with a bit of work) always dial from a specific IP, but 99% of the time, the user will want to dial from all IPs _except_ a specific one. That's also something that could be implemented, but it's tricky to get right (I'd rather ask users to just configure their routes).

**Comment by nisdas** [comment]
I was hoping to avoid having users to manually configure their routes, but if its too tricky to implement at the time-being in libp2p then that is what users will have to do for now.

**Comment by Stebalien** [comment]
Just from a security perspective, it's _much_ better to do this at the OS level. I.e., drop your app into a network namespace.

But I've opened a feature request explaining how this could be implemented: https://github.com/libp2p/go-libp2p/issues/1064.

**Comment by nisdas** [comment]
Great, thanks a lot for opening the issue up to track it :+1: .
