### ISSUE TITLE
How could I know when  a peer is shutdown 

### ISSUE THREAD

**Issue by ItsFunny** [libp2p/go-libp2p#1069]
I am a newbee for this library,And I got a question for Stream 

I learned from the go-libp2p-examples 
Here Are my Questions
- I found  it will openstream every time ,should i do this in my project?
- if server A is shutdown , but client B can still send msg through stream ,Should I openNewStream and try again if i havent heard any response (`same as the last one`)
- can i hold stream for a really long time

**Comment by ItsFunny** [comment]
And if server A is shutdown , but client B can still send msg through stream , 
Should I openNewStream and try again if i havent heard any response ?

**Comment by mearaj** [comment]
Hi,
I have read the discussion on the same or may be similar question.
Hope this link may help you
[https://discuss.libp2p.io/t/how-to-check-if-a-stream-is-already-open-with-peer/249/3](https://discuss.libp2p.io/t/how-to-check-if-a-stream-is-already-open-with-peer/249/3)
Regards :)

**Comment by ItsFunny** [comment]
Hi,
Thanks for the link ;
But it seems not enough to solve my question ,  I was wandering  if I have to write  another protocol to detected whether  peer is dead or not (but I think libp2p already did this ? right ?  pingProtocol?)
Thanks anyway

**Comment by mearaj** [comment]
I have created a chat app using [Gioui](https://gioui.org/) and [Libp2p](https://github.com/libp2p/go-libp2p). The app is also published at Playstore, [Protonet](https://play.google.com/store/apps/details?id=live.protonet). Going to make it open source in a day or two. Then hopefully you and others will be able to see it's source code.
Thanks :)

**Comment by mearaj** [comment]
Hi @ItsFunny and everyone,
Here is the link to a project that uses libp2p
[Protonet](https://github.com/mearaj/protonet)
Playstore link is
[Protonet](https://play.google.com/store/apps/details?id=live.protonet)
