### ISSUE TITLE
Can we implement a chat example by hole punch

### ISSUE THREAD

**Issue by ZBoIsHere** [libp2p/go-libp2p#1071]
Recently, I read the code in branch feat/evt-based-hole-punching, and see some unit tests for hole-punch, but leak of a end-to-edge example for how to use hole punch.
Let's assume a situation, PeerA and PeerB are both behind NAT device, they can't establish a direct connection; There is Relay&Signal server which have a public IP, so we can register PeerA and PeerB to Relay&Signal server and exchange their public addr, then we try to establish a direct connection between them, if not success, we can realy their their payload through Realy&Signal server.
In our examples, their is lack a example to the situation above, so I hope that the developer can implement this example and notify us in this issue.

**Comment by Stebalien** [comment]
A relay example is here: https://github.com/libp2p/go-libp2p-examples/blob/master/relay/main.go.

Progress on hole punching is tracked in https://github.com/libp2p/go-libp2p/issues/1039.
