### ISSUE TITLE
External gateway detection seems off

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#109]
Several users have reported (and I have noticed occasionally) that the addresses we advertise for other peers to connect to us on arent quite right. For example, peers might see an address with our correct external address, but without the right external port. We should investigate and test this.

**Comment by jbenet** [comment]
NAT mapping may have changed in the time.

**Comment by bigs** [comment]
reopen if we want to re-approach this

**Comment by Stebalien** [comment]
Replaced by https://github.com/libp2p/go-libp2p/issues/383 with more details.
