### ISSUE TITLE
TestProtoDowngrade is flaky

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#1094]
>     basic_host_test.go:517: Application error 0x0

This happens when we try to write to the stream after opening it. It _sounds_ like the connection broke for some reason.

Note: this happened on windows, go 1.15.

**Comment by marten-seemann** [comment]
Application error 0x0 is triggered when we (or the peer) class `Close` on the connection.
How do I trigger this? It might be beneficial to re-run this with quic-go updated to the current version, as we've reworked error reporting recently.

**Comment by Stebalien** [comment]
It just seems to happen occasionally in CI (especially on windows).

**Comment by Stebalien** [comment]
Maybe we're closing the connection for some reason? IIRC, we _shouldn't_ be closing duplicate connections, but maybe we are?
