### ISSUE TITLE
Can we add vendor to .gitignore?

### ISSUE THREAD

**Issue by diasdavid** [libp2p/go-libp2p#11]

**Comment by whyrusleeping** [comment]
no, because we need to add those files to the repo

**Comment by diasdavid** [comment]
Aren't they always installed with `gx install`?

**Comment by whyrusleeping** [comment]
technically yes, but at least for now, thats not stable enough to use with CI (as you notice gx #23)

**Comment by whyrusleeping** [comment]
This is no longer an issue, closing
