### ISSUE TITLE
Handling connection helpers

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#110]
libp2p will soon have multiple modules that it can use to 'help' in connecting to other peers. For example, relaying a connection to a peer, or sending a message out to ask that peer to connect to you. 

We need to decide _when_ to resort to those methods. Do we try to do one of those immediately? after ten seconds of normal dialing? Try relay after normal dialing fails entirely? We also need to figure out where these mechanisms should be plugged in to.

**Comment by jbenet** [comment]
Connection estimators will help a lot-- to take several open connections and pick between them.
