### ISSUE TITLE
Run interop tests across libp2p versions

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#1107]
When testing PRs, we should test the current branch against master (or the last release?) in an interop test to make sure we don't break backwards compatibility. We _should_ be able to use the existing interop tests to do this.

Additionally, we should test this in all configurations:

* TCP, QUIC, WS.
* TCP+TLS, TCP+Noise
* TCP+Noise+Yamux, TCP+Noise+Mplex

Unfortunately, at a minimum that'll give us 5 test runs (which can luckily be done concurrently).

**Comment by BigLep** [comment]
@Stebalien : to confirm, today we have interop tests that go between go-libp2p and js-libp2p and this is about adding some go-libp2p to go-libp2p with different configurations.  You mentioned 5 test runs.  To be clear, can you enumerate what the 5 combinations are?

Also, some pointers on where to make changes would be great ([interop repo](https://github.com/libp2p/interop)?)

**Comment by Stebalien** [comment]
Hm. Should have written that down. Probably:

1. QUIC
2. TCP+TLS+Yamux (go)
3. TCP+Noise+Yamux (rust)
4. TCP+Noise+Mplex (js/rust)
5. WS+Noise+Mplex (js)

That should cover it.

**Comment by p-shahi** [comment]
Relates to https://github.com/libp2p/test-plans/pull/44

**Comment by p-shahi** [comment]
closing in favor of https://github.com/libp2p/test-plans/issues/61
