### ISSUE TITLE
slice bounds out of range

### ISSUE THREAD

**Issue by yann-sjtu** [libp2p/go-libp2p#1108]
It is too hard to reproduce. what's the possible cause?
```
panic: runtime error: slice bounds out of range [1634:65]

goroutine 1750168751 [running]:
internal/poll.(*FD).Write(0xc007523900, 0xc007e16c00, 0x41, 0x80, 0x0, 0x0, 0x0)
        C:/Go/src/internal/poll/fd_windows.go:731 +0x48b
net.(*netFD).Write(0xc007523900, 0xc007e16c00, 0x41, 0x80, 0xc00e31d440, 0x40, 0x40)
        C:/Go/src/net/fd_windows.go:164 +0x56
net.(*conn).Write(0xc003222ac8, 0xc007e16c00, 0x41, 0x80, 0x0, 0x0, 0x0)
        C:/Go/src/net/net.go:196 +0x95
github.com/libp2p/go-libp2p-secio.(*etmWriter).WriteMsg(0xc008b5ad40, 0xc00efe4a00, 0x1d, 0x20, 0x0, 0x0)
        D:/goWork/pkg/mod/github.com/libp2p/go-libp2p-secio@v0.2.2/rw.go:64 +0x2f6
github.com/libp2p/go-libp2p-secio.(*etmWriter).Write(0xc008b5ad40, 0xc00efe4a00, 0x1d, 0x20, 0xc02246c465b0e788, 0x2341900163101, 0x2701cc0)
        D:/goWork/pkg/mod/github.com/libp2p/go-libp2p-secio@v0.2.2/rw.go:34 +0x54
github.com/libp2p/go-yamux.(*Session).sendLoop(0xc00768a9a0, 0x0, 0x0)
        D:/goWork/pkg/mod/github.com/libp2p/go-yamux@v1.3.7/session.go:491 +0x246
github.com/libp2p/go-yamux.(*Session).send(0xc00768a9a0)
        D:/goWork/pkg/mod/github.com/libp2p/go-yamux@v1.3.7/session.go:403 +0x32
created by github.com/libp2p/go-yamux.newSession
        D:/goWork/pkg/mod/github.com/libp2p/go-yamux@v1.3.7/session.go:126 +0x3a2
```

**Comment by aschmahmann** [comment]
@yann-sjtu it looks like this is a pretty old version of go-libp2p given that SECIO support was dropped a while ago and that's an old version of go-yamux.

I would recommend upgrading go-libp2p (and any network you have that's relying on SECIO) and seeing if the issue recurs.

**Comment by yann-sjtu** [comment]
> @yann-sjtu it looks like this is a pretty old version of go-libp2p given that SECIO support was dropped a while ago and that's an old version of go-yamux.
> 
> I would recommend upgrading go-libp2p (and any network you have that's relying on SECIO) and seeing if the issue recurs.

Thanks. I can not find `helpers.FullClose` in the new version of go-libp2p, is it still necessary?

**Comment by aschmahmann** [comment]
@yann-sjtu nope the interfaces have been changed to make Stream closure operate a bit differently and more simply, check out the release notes for more details on changes between releases. The `helpers.FullClose` changes were made in https://github.com/libp2p/go-libp2p/releases/tag/v0.12.0
