### ISSUE TITLE
can this lib support ipcam p2p network?

### ISSUE THREAD

**Issue by fghjhuang** [libp2p/go-libp2p#1112]
i was looking for a p2p lib to make a network like this : 
1. ipcamA ===p2p server
2. app request to connect to ipcam A
3.  ipcamA ====p2p(video steaming)=====app

can this lib make like this? or any suggestion?

**Comment by Stebalien** [comment]
This issue tracker is for reporting bugs. Please ask questions at https://discuss.libp2p.io, thanks!
