### ISSUE TITLE
Making a working private bootstrap node

### ISSUE THREAD

**Issue by remobit1** [libp2p/go-libp2p#1117]
I've been scratching my head with this for a while to the point where I figured i'd pose the question since i'm clearly missing something and poking around the codebase hasn't answered it - i've been attempting to do the rendezvous example (https://github.com/libp2p/go-libp2p/tree/master/examples/chat-with-rendezvous) but instead of using the provided public bootstrap nodes at dht.DefaultBootstrapPeers, I wanted to spin up my own bootstrap node and use that instead.

As you can infer, when using the default bootstrap peers the example works just fine, but when I run a private node with bootstrapped dht and set to be a relay, nothing doing. From what I can tell it seems like when I try and spin up two nodes to use the boostrap node to grab initial ips, they only grab the bootstrap node's maddr and nothing more, while when I just build the example, the boostrap nodes are clearly retaining the ips when my nodes connect to them and passing it to the dht table of the second node.

Is there something i'm misunderstanding conceptually? Some option you have to turn on to allow a node to act like a bootstrap node? I was under the impression that as long as a node has a dht boostrapped that any could act like a 'bootstrap node' and even turning on the relay functionality was only needed when trying to connect to nodes behind natted environments...

Any advice would be appreciate, sorry for bothering you about something I should probably be able to figure out myself!

**Comment by Stebalien** [comment]
This is... a confusing subject, but it's better discussed on [discuss.libp2p.io](https://discuss.libp2p.io) where more people are likely to chime in and help.
