### ISSUE TITLE
Example for a fully featured chat application

### ISSUE THREAD

**Issue by manishmeganathan** [libp2p/go-libp2p#1120]
So, I've implemented a full chat application that was originally based on the pubsub chat example but is more featured and supports things like changing the user name and joining other rooms without having to restart the application.
The most important difference is that it features NAT traversal, active peer discovery and content routing that are enabled with the Kademlia DHT library and discovery library. The application works on two nodes on completely different networks even with either or both nodes behind a NAT.

The examples in this repository don't seem to have cover peer discovery, content routing, etc and I wanted to contribute this project towards the examples here. (This would be my first contribution to an open-source project ever). 
I would like some help with this process and would like the community to vet the project and its documentation as well. Any support or changes are welcome.

The project can be viewed on https://github.com/manishmeganathan/peerchat

**Comment by TheDiscordian** [comment]
Wow I love this!! Because it's similar, here are my related works on that for js-ipfs in browser:
* https://docs.ipfs.io/how-to/create-simple-chat-app/ (is this the example you're referring to?)
* https://chat.thedisco.zone/

I'm going to have to have a dive into how peerchat works!

**Comment by manishmeganathan** [comment]
I'm glad you like it, let me know if you have any questions. The example I was referring to is part of the examples bundled with this repository. You can find it here https://github.com/libp2p/go-libp2p/tree/master/examples/pubsub/chat.

**Comment by notassigned** [comment]
Thanks for making this. It was very helpful for me starting out in go-libp2p to have a full example that showed many of the big libp2p features working together in a simple application.

**Comment by marten-seemann** [comment]
Thank you for sharing @manishmeganathan!

I'm going to close this issue, because it looks like there's nothing actionable for go-libp2p to do here.
