### ISSUE TITLE
The port is opened using the upnp protocol, but it is not used

### ISSUE THREAD

**Issue by godcong** [libp2p/go-libp2p#1142]
<details>
<summary>Version Information</summary>
<pre>

</pre>
</details>

1. When I start the ipfs client, upnp is correctly activated.
![image](https://user-images.githubusercontent.com/2727298/127164563-acef3081-cfed-47d2-83f0-bdfebf1eb343.png)
2. But I failed to connect to the local ipfs client through the reverse link.
3. Then I try to forward the data of port 4001 to ipfs.
4. The local ipfs client is successfully connected
5. suspect that although upnp is enabled correctly, ipfs still sends data through port 4001 instead of through upnp port

my router is mi ax6000
ipfs version: 0.9.1
libp2p:v0.14.3

**Comment by Stebalien** [comment]
Given machines:

1. A: behind NAT with peer ID QmA.
2. B: dialing the peer behind the NAT.

What's the output of `ipfs id` on machine A, and what's the output of `ipfs id QmA` on machine B?

Unfortunately, a lot of NATs are buggy... libp2p tries to guess all reasonable addresses, but this doesn't always work.

**Comment by godcong** [comment]
Hope https://github.com/libp2p/go-libp2p/pull/1057 can fix this problem.
I will try again after this release.

**Comment by Stebalien** [comment]
That might let you do hole punching, but it won't fix _this_ problem.

**Comment by godcong** [comment]
> That might let you do hole punching, but it won't fix _this_ problem.

Are there any logs to track relevant information?
I want to open these logs to check

**Comment by Stebalien** [comment]
Those would be in go-libp2p-nat. You'll have to enable debug logging for the "nat" subsystem, and may want to add additional logging.

See https://github.com/ipfs/go-log/pull/120 for documentation on how to enable logging for individual subsystems.

**Comment by Stebalien** [comment]
I'm going to close this for now because there's probably nothing we can do. If you find more information, please leave a comment and we can reopen.

**Comment by godcong** [comment]
ok
