### ISSUE TITLE
Make 'BasicHost.emitters.evtLocalAddrsUpdated' stateful.

### ISSUE THREAD

**Issue by lthibault** [libp2p/go-libp2p#1145]
## Problem

Currently, subscribing to `event.EvtLocalAddrsUpdated` is not stateful, meaning that subscribers will miss the initial set of addresses emitted during host initialization.

While not a huge deal (we can just call `h.Addrs()`), this requires additional initialization outside of the subscription logic.  This is kind of annoying; I would much prefer to write:

```go
for addrsChanged := range sub.Out() {
    do_something(addrsChanged)
}
```

Currently, I have to write something akin to `setup(h.Addrs())` somewhere else.

## Solution

The solution is to pass [`eventbus.Stateful`](https://pkg.go.dev/github.com/libp2p/go-eventbus?utm_source=godoc#Stateful) to the emitter's constructor, [here](https://github.com/libp2p/go-libp2p/blob/5d7af78f0bbffa68ec8b4a8b8edc137b5f955745/p2p/host/basic/basic_host.go#L178).

Is this doable, or will it break something?  I'm happy to submit a PR if this is pre-approved in principle.

**Comment by Stebalien** [comment]
No, that seems quite reasonable. At the moment, the best approach is to:

1. Subscribe.
2. Get the current addresses.

But I agree making this stateful would simplify things. Want to make a patch?

**Comment by lthibault** [comment]
Perfect!  I'll have a patch ready shortly.

**Comment by lthibault** [comment]
@Stebalien See https://github.com/libp2p/go-libp2p/pull/1147.

Do you think it's worth making `EvtEvtLocalProtocolsUpdated` stateful as well?

**Comment by Stebalien** [comment]
Not really. The addresses one makes sense (somewhat) because it has includes _all_ addresses. The protocols one is just for protocol updates.

I say _somewhat_ for the addresses one because _ideally_ it wouldn't return "removed" addresses in the first event.
