### ISSUE TITLE
Is it possible to ignore IWANT messages at the application level?

### ISSUE THREAD

**Issue by smnzhu** [libp2p/go-libp2p#1153]
Context: https://discuss.libp2p.io/t/filtering-nodes-that-we-gossip-to/1012#:~:text=A%20more,t%20exist.

Would like to have a feature, if one doesn't yet exist, that allows me to decide at the application level whether or not to ignore an IWANT message based on the requesting peer.

This is related to https://github.com/libp2p/go-libp2p-pubsub/issues/443

**Comment by Stebalien** [comment]
Please keep forum questions to the forum.

**Comment by Stebalien** [comment]
(or just continue the discussion in go-libp2p-pubsub, this repo is the global libp2p repo)
