### ISSUE TITLE
flaky examples/relay tests

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1158]
```
 === RUN   TestMain
      logharness.go:101: saw: Okay, no connection from h1 to h3: no addresses
      logharness.go:106: did not see expected prefix "Meow! It worked!"
  --- FAIL: TestMain (4.54s)

**Comment by marten-seemann** [comment]
The problem here is the following:
`h1` and `h3` connect to `h2` (the relay). As soon as both of them have established a connection via to the relay, they try to establish a connection between each other _via the relay_. This is racy, as both `h1` and `h3` might dial using multiple transports, (temporarily) resulting in the establishment of multiple connection. Spurious connections will then be closed by the respective hosts. Now it might happen that the connection attempt between `h1` and `h3` happens before the relay learns which connection is closed.

**Comment by Stebalien** [comment]
Really? IIRC, we _don't_ close these connections anymore.

**Comment by Stebalien** [comment]
Or is this because we're canceling outbound dials once one dial succeeds? I _believe_ we can fix this in https://github.com/libp2p/go-libp2p/blob/e70d7cf245fd80b80fb539bd6753e9a8c826cb6f/p2p/host/basic/basic_host.go#L602 by trying to create a new stream if identify fails... maybe?

**Comment by marten-seemann** [comment]
> Or is this because we're canceling outbound dials once one dial succeeds?
Yes: https://github.com/libp2p/go-libp2p-swarm/blob/88ef86a16cf0bbc451c3799f63278d345aaf56ea/limiter.go#L227-L234

> by trying to create a new stream if identify fails... maybe?

Not sure if I understand your proposal. `h2` is creating a stream to `h3` (for relaying the connection from `h1` to `h3`). Where does identify come into play here?
