### ISSUE TITLE
About pre-shared keys

### ISSUE THREAD

**Issue by khalid-davis** [libp2p/go-libp2p#1162]
Hello, what do we need to do in libp2p if our pre-shared keys (private networks) is leaked? Do we need to restart all peers and give them a new pre-shared keys (private networks)?

**Comment by marten-seemann** [comment]
As I've told you [before](https://github.com/libp2p/go-libp2p-tls/issues/90#issuecomment-899342867), this is not the right place to ask support questions.

This is an issue tracker, and support requests like these waste the time of the libp2p development team. Again, https://libp2p.discuss.io would be the right place to ask questions.

**Comment by khalid-davis** [comment]
thanks. https://discuss.libp2p.io/t/about-pre-shared-keys/1023
