### ISSUE TITLE
move circuitv2 and relay packages

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1177]
This doesn't really belong in `host`, that's for `host` implementations. "relay" is there because it used to be a host wrapper (it really should move).

Maybe move _both_ to a "relay" directory? Really, the "relay" belongs in some form of "relay" package, and the "client" part belongs in a "transports" package, but we don't need to get too fancy.

_Originally posted by @Stebalien in https://github.com/libp2p/go-libp2p/issues/1174#issuecomment-914304959_

**Comment by vyzo** [comment]
We should have it in `protocol` I think, it doesn't belong in `host` and we don't need a separate package for this.

**Comment by vyzo** [comment]
Note that `relay` contains the autorelay code, it should probably be renamed as such and maybe move into `protocol` as well.

**Comment by marten-seemann** [comment]
This should have been resolved since v0.16.0.
