### ISSUE TITLE
Repo Consolidation: Transports

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1187]
The proposal is to move all transport-related repos to go-libp2p. 
To be clear, this consolidation does NOT mean that only these transports are supported. We will keep the interfaces and the methods to add new or custom handshakes / muxers / transports. libp2p will remain as extensible as it is now.

## Repositories

Security Handshakes:
* [TLS](https://github.com/libp2p/go-libp2p-tls/)
* [Noise](https://github.com/libp2p/go-libp2p-noise)

Muxers:
* yamux ([go-libp2p-yamux](https://github.com/libp2p/go-libp2p-yamux), NOT go-yamux)
* mplex ([go-libp2p-mplex](https://github.com/libp2p/go-libp2p-mplex), NOT go-mplex)

Transports:
* [QUIC transport](https://github.com/libp2p/go-libp2p-quic-transport) (not quic-go)
* [TCP transport](https://github.com/libp2p/go-tcp-transport)

Others:
* [Upgrader](https://github.com/libp2p/go-libp2p-transport-upgrader)
* TODO: add more

**Comment by Stebalien** [comment]
I'd also move the resuseport "transport" package.

But, in short

# Do it! :tada:

**Comment by marten-seemann** [comment]
What's our policy on preserving git histories? For circuitv2, we preserved the history using `git filter-tree`. We can do that as well for these repositories, but the price we'll pay is that we'll end up with a lot of commits that won't compile, as interfaces have changed over time (making it difficult to `git bisect` later).

**Comment by Stebalien** [comment]
I try to preserve history wherever possible. I'm fine with commits that don't compile. Generally, you'd just browse _master's_ history, and all of those should compile.

**Comment by marten-seemann** [comment]
Here's how the directory structure could look like.

## libp2p repo consolidation

### Transports

go-reuseport-transport => `p2p/transport/transport/go-reuseport-transport`
go-tcp-transport => `p2p/transport/transport/tcp`
go-libp2p-quic-transport => `p2p/transport/transport/quic`
go-ws-transport => `p2p/transport/ransport/websocket`

*`transport/transport` is kind of ugly*!

### Security

go-libp2p-tls => `p2p/transport/security/tls`
go-libp2p-noise => `p2p/transport/security/noise`

### Muxers

go-libp2p-yamux => `p2p/transport/muxer/yamux`
go-libp2p-yamux => `p2p/transport/muxer/yamux`

### Misc

go-libp2p-swarm => `p2p/transport/swarm`
go-libp2p-transport-upgrader => `p2p/transport/upgrader`
go-conn-security-multistream => `p2p/transport/conn-security-multistream`

@vyzo @Stebalien thoughts?

**Comment by vyzo** [comment]
why do we need the extra transport?

We could have `transport/{tcp, ...}`  and put the swarm in `net`?

**Comment by marten-seemann** [comment]
> why do we need the extra transport?

It seemed weird to have a subdirectory for the muxers, but not for the transports. Maybe there's a less generic term than "transport" that we can use? Any ideas?

> We could have transport/{tcp, ...} and put the swarm in net?

I like that!

Here's the updated table:

### Transports

go-reuseport-transport => `p2p/transport/transport/go-reuseport-transport`
go-tcp-transport => `p2p/transport/transport/tcp`
go-libp2p-quic-transport => `p2p/transport/transport/quic`
go-ws-transport => `p2p/transport/ransport/websocket`

*`transport/transport` is kind of ugly*!

### Security

go-libp2p-tls => `p2p/transport/security/tls`
go-libp2p-noise => `p2p/transport/security/noise`

### Muxers

go-libp2p-yamux => `p2p/transport/muxer/yamux`
go-libp2p-yamux => `p2p/transport/muxer/yamux`

### Net

go-libp2p-swarm => `p2p/net/swarm`
go-libp2p-transport-upgrader => `p2p/net/upgrader`
go-conn-security-multistream => `p2p/net/conn-security-multistream`

**Comment by Stebalien** [comment]
Overall, a _big_ thumbs-up from me.

> go-reuseport-transport

Hm. That's more of a helper, not a transport. It probably belongs somewhere else? Maybe `p2p/net`?

> transport/transport

1. We could get rid of the top-level transport. I.e., `p2p/security`, etc...
2. We could rename `transport/transport` to `transport/connection`.

**Comment by marten-seemann** [comment]
Thank you. Here's the updated table:

### Transports

go-tcp-transport => `p2p/transport/tcp`
go-libp2p-quic-transport => `p2p/transport/quic`
go-ws-transport => `p2p/transport/websocket`

### Security

go-libp2p-tls => `p2p/security/tls`
go-libp2p-noise => `p2p/security/noise`

### Muxers

go-libp2p-yamux => `p2p/muxer/yamux`
go-libp2p-yamux => `p2p/muxer/yamux`

go-yamux and go-mplex will not be moved.

### Net

go-libp2p-swarm => `p2p/net/swarm`
go-libp2p-transport-upgrader => `p2p/net/upgrader`
go-conn-security-multistream => `p2p/net/conn-security-multistream`
go-reuseport-transport => `p2p/net/reuseport`

**Comment by BigLep** [comment]
Note: this will go out in https://github.com/libp2p/go-libp2p/issues/1371

**Comment by marten-seemann** [comment]
v0.20.0 was released. Transports are now consolidated.
