### ISSUE TITLE
ioutil.ReadAll(stream) stuck in some cases

### ISSUE THREAD

**Issue by RukolaHasser** [libp2p/go-libp2p#1236]
I found `ioutil.ReadAll(stream)` was stuck in the `StreamHandler` in some cases, but it could be fixed by using `bufio` reader. 

For instance, in the `echo` example:
```
// doEcho reads a line of data a stream and writes it back
func doEcho(s network.Stream) error {
	buf := bufio.NewReader(s)
	str, err := buf.ReadString('\n')
	if err != nil {
		return err
	}

	log.Printf("read: %s", str)
	_, err = s.Write([]byte(str))
	return err
}
```
If you replace `bufio.NewReader(s)` with `ioutil.ReadAll(s)` here, it will hang forever for some reason. But in other examples, it just works. Does anyone know why it happens, and in what cases?

**Comment by marten-seemann** [comment]
`ioutil.ReadAll` waits for the `io.EOF`, `bufio.ReadString` waits for a certain character (`\n` in your case). I assume the sender is sending `\n`, but not closing the stream.
