### ISSUE TITLE
 Private Network Protector Error

### ISSUE THREAD

**Issue by lonnietc** [libp2p/go-libp2p#1238]
Hello,

I am working with an application that uses libp2p but when starting the application which was compiled on my Ubuntu 20.04 with go 1.17.2 but I am getting an error:

"tried to create a libp2p node with no Private Network Protector but usage of Private Networks is forced by the environment"

I tried to also export the environment variable:

 export LIBP2P_FORCE_PNET=1

but still get this error.

Any ideas what is causing this?
Thanks in advance

**Comment by marten-seemann** [comment]
It's probably because you don't have a protector configured. This is not a bug report though, so please ask this question on the [forum](https://discuss.libp2p.io/).

**Comment by 50gramx** [comment]
@marten-seemann the example chat works fine in windows, but in mac and in ubuntu, it results with the same error. No thread in forum for this. It'll be really helpful if you could show some light on this. Thanks.

`2022-03-12T02:52:03.569+0530    ERROR   p2p-config      config/config.go:113    tried to create a libp2p node with no Private Network Protector but usage of Private Networks is forced by the enviroment
2022/03/12 02:52:03 privnet: private network was not configured but is enforced by the environment`

**Comment by marten-seemann** [comment]
Again, this is not a support forum, this is an issue tracker.
You can post your question on your forum, but you won't get any help here.
