### ISSUE TITLE
Always failed with having too many open files

### ISSUE THREAD

**Issue by rukolahasser** [libp2p/go-libp2p#1243]
Hi, I created an application on top of `libp2p` and used DHT for peer discovery. But it always failed with the same error:
```
2021-11-22T05:03:53.018Z	ERROR	basichost	basic/basic_host.go:289	failed to resolve local interface addresses	{"error": "route ip+net: netlinkrib: too many open files"}
```
I raised the limit on open files to `65536`, but it still failed eventually.

I set and max connections in the code like this:
```
opt := libp2p.ConnectionManager(connmgr.NewConnManager(
		4095,
		4096,
		time.Minute,
	))
h, err := libp2p.New(
		ctx,
		options...,
	)
```
but it seemed not to work properly. Is there anything else I need to set up?

**Comment by RukolaHasser** [comment]
I forgot to mention I was using `v0.15.0`

**Comment by Stebalien** [comment]
Try checking for open files: Try using `lsof`, `fuser`, and `ls -l /proc/$MY_PID/fd`.

Possible issues:

- Are you creating multiple libp2p nodes?
- Are you opening files elsewhere?
- Are you sure the file descriptor limit got raised? Check `/proc/$MY_PID/limits`.

**Comment by marten-seemann** [comment]
Haven't heard back in more than 2 weeks. Closing this issue. Feel free to reopen with new information.
