### ISSUE TITLE
PrivateNetwork option broken by making QUIC a default

### ISSUE THREAD

**Issue by hsanjuan** [libp2p/go-libp2p#1249]
Making QUIC a default transport automatically breaks any node initialized with `PrivateNetwork`.

This should have probably been handled somehow. There is no constructor option to disable QUIC, so we are left to manually choosing the transports.

**Comment by marten-seemann** [comment]
We should:
1. if the default transports are set: disable QUIC if `PrivateNetwork` is set, then (re?) run the check if any transports are configured
2. if QUIC is configured explicitly: throw an error
