### ISSUE TITLE
go-libp2p-resource-manager panics on reserving memory

### ISSUE THREAD

**Issue by mudler** [libp2p/go-libp2p#1319]
Hi!

Thanks for libp2p, it's an awesome lib :heart: !

I've been trying to consume libp2p 0.18.0-rc2. I'm using libp2p with fallback default options, which in turns enables the resource manager, but after a while of running (typically in 1m), I'm seeing this panic in my code:

```
panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcc3205]
 goroutine 150339 [running]:
 github.com/libp2p/go-libp2p-resource-manager.(*peerScope).ReserveMemory(0x0, 0x40000, 0xc00433deff, 0x0, 0x20)
 	<autogenerated>:1 +0x5
 github.com/libp2p/go-yamux/v3.(*Session).incomingStream(0xc004339200, 0x2, 0x0, 0x0)
 	/home/runner/go/pkg/mod/github.com/libp2p/go-yamux/v3@v3.0.2/session.go:765 +0x98
 github.com/libp2p/go-yamux/v3.(*Session).handleStreamMessage(0xc004339200, 0x200000001000100, 0xc000000000, 0xc, 0xc)
 	/home/runner/go/pkg/mod/github.com/libp2p/go-yamux/v3@v3.0.2/session.go:660 +0x61a
 github.com/libp2p/go-yamux/v3.(*Session).recvLoop(0xc004339200, 0x0, 0x0)
 	/home/runner/go/pkg/mod/github.com/libp2p/go-yamux/v3@v3.0.2/session.go:648 +0x1a5
 github.com/libp2p/go-yamux/v3.(*Session).recv(0xc004339200)
 	/home/runner/go/pkg/mod/github.com/libp2p/go-yamux/v3@v3.0.2/session.go:602 +0x2b
 created by github.com/libp2p/go-yamux/v3.newSession
 	/home/runner/go/pkg/mod/github.com/libp2p/go-yamux/v3@v3.0.2/session.go:157 +0x449
```

I can reproduce this consistently in my project branch, and I had to pin back libp2p to an old version ( although, I know I can disable RSM, but I still want to use fallback defaults, without customizing too much ). As I have set up tests on GitHub action, I can also retrigger it easily to give it a go.

this is the go.mod: https://github.com/mudler/edgevpn/blob/d96ee12ebb9f2991bfdd2be940e9dfec470354ee/go.mod#L25

I'm not sure if this is something on my side which I'm doing wrong, or there is something more into it. But reverting to libp2p 0.17 doesn't cause this issue to me.

Thanks!

**Comment by vyzo** [comment]
It should be fixed in rc3, can you try it?

**Comment by mudler** [comment]
> It should be fixed in rc3, can you try it?

Confirm that it's all good now by pinning to rc3, thank you!

**Comment by mudler** [comment]
ok, catching now a race condition, opening a separate issue for it

**Comment by mudler** [comment]
Opened https://github.com/libp2p/go-libp2p/issues/1320
