### ISSUE TITLE
connmgr: flaky TestMultiplePeers

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1324]
```
  === RUN   TestMultiplePeers
      decay_test.go:220: wrong value; expected = 2670; got = 2671
  --- FAIL: TestMultiplePeers (1.08s)

**Comment by schomatis** [comment]
Assigning myself.

**Comment by schomatis** [comment]
Looking into this. After changes from https://github.com/libp2p/go-libp2p/pull/1354 I can no longer reproduce the above but get this error instead:

```
=== RUN   TestMultiplePeers
    decay_test.go:151: 
          Error:        Condition never satisfied
          Test:         TestMultiplePeers
--- FAIL: TestMultiplePeers (0.65s)

```

So will start there with an eye on the `2670` check also.

**Comment by schomatis** [comment]
@marten-seemann I think we can close this issue.

I haven't been able to reproduce the error and with a controlled number of elapsed decaying ticks (through the mock clock of https://github.com/libp2p/go-libp2p/pull/1354) this shouldn't happen again, and if it does it would no longer be a flake but an actual bug (this will be made even more explicit now with https://github.com/libp2p/go-libp2p/pull/1642).
