### ISSUE TITLE
Build error: undefined: upgrader.Upgrader (go-libp2p@v0.17.0/p2p/protocol/circuitv2/client/ client.go & transport.go)

### ISSUE THREAD

**Issue by gcemperor** [libp2p/go-libp2p#1336]
I'm trying to build the example libp2p node project from [the Getting Started with go-libp2p website](https://docs.libp2p.io/tutorials/getting-started/go/), and besides the source code provided not including defining context (**ctx**, fixed that on my own), I get this error when attempting to build the .exe in VSCode: 

**# github.com/libp2p/go-libp2p/p2p/protocol/circuitv2/client
..\go\pkg\mod\github.com\libp2p\go-libp2p@v0.17.0\p2p\protocol\circuitv2\client\client.go:32:13: undefined: upgrader.Upgrader
..\go\pkg\mod\github.com\libp2p\go-libp2p@v0.17.0\p2p\protocol\circuitv2\client\client.go:57:33: undefined: upgrader.Upgrader
..\go\pkg\mod\github.com\libp2p\go-libp2p@v0.17.0\p2p\protocol\circuitv2\client\transport.go:21:42: undefined: upgrader.Upgrader**

The offending lines seem to be these:

[32:13	upgrader  transport.Upgrader](https://github.com/libp2p/go-libp2p/blob/ccdd17f046286df0c832d8266816727b65037e67/p2p/protocol/circuitv2/client/client.go#L31)
[57:33       func New(h host.Host, upgrader transport.Upgrader) (*Client, error) {](https://github.com/libp2p/go-libp2p/blob/ccdd17f046286df0c832d8266816727b65037e67/p2p/protocol/circuitv2/client/client.go#L56)
[21:42       func AddTransport(h host.Host, upgrader transport.Upgrader) error {](https://github.com/libp2p/go-libp2p/blob/ccdd17f046286df0c832d8266816727b65037e67/p2p/protocol/circuitv2/client/transport.go#L22)

Can't run the code, can't build the binary. go mod tidy resolves the dependency issues, but I can't seem to get around this one. I'm fairly new to Go (and programming in general, but I'm sick of making hello world apps), so forgive me if this is a stupid issue. 
Any suggestions? I don't want to start commenting things out and break something.

**Comment by marten-seemann** [comment]
Please use the correct set of versions, as defined in go.mod.

**Comment by mar1n3r0** [comment]
> Please use the correct set of versions, as defined in go.mod.

Facing the same issue could you please elaborate on what is the correct set of versions and which go.mod are you referencing?

**Comment by mar1n3r0** [comment]
> Please use the correct set of versions, as defined in go.mod.

@marten-seemann Why do we need to pin earlier versions?
