### ISSUE TITLE
How can I use libp2p.EnableRelay(circuit.OptHop) in go-libp2p v0.16.0+

### ISSUE THREAD

**Issue by Poorunga** [libp2p/go-libp2p#1337]
I can't use libp2p.EnableRelay(circuit.OptHop) in go-libp2p v0.16.0+. I only see libp2p.EnableRelayService() and libp2p.EnableAutoRely(), but I can't found where to use param `circuit.OptHop`. And I can't find any guidance documents, so I need your help.

This make my p2p application cause an error like: error opening relay circuit: HOP_CANT_SPEAK_RELAY (270)

<details>
<summary>Version Information</summary>
<pre>

github.com/libp2p/go-libp2p v0.17.0
github.com/libp2p/go-libp2p-core v0.13.0
github.com/libp2p/go-libp2p-quic-transport v0.15.2
github.com/libp2p/go-libp2p-tls v0.3.1
github.com/libp2p/go-msgio v0.1.0
github.com/libp2p/go-ws-transport v0.5.0
</pre>
</details>

**Comment by marten-seemann** [comment]
Please ask questions in the [forum](https://discuss.libp2p.io/).
