### ISSUE TITLE
Gossip interoperability between go-libp2p and jvm-libp2p

### ISSUE THREAD

**Issue by ShwetaTripathi05** [libp2p/go-libp2p#1346]
As part of my exploration work, I am trying to communicate between jvm-libp2p and go-libp2p hosts using the gossip pubsub implementation. Unfortunately I am not able to achieve the desired results as I do not see the messages being received at the receiver’s end. Can I please get any leads/references on how to communicate between the two libraries using gossip pubsub?

I am not using the local mDNS service for peer discovery, rather trying an explicit connection between the hosts using the Connect() API. But event that does not seem to work.

Any leads on the issues will be appreciated!

**Comment by aschmahmann** [comment]
I'm not sure about the state of jvm-libp2p, but your [specs](https://github.com/libp2p/specs/tree/master/pubsub) are likely your friend here in terms of compatibility.

Before going into pubsub I'd also just make sure your bases are covered with simple protocols like `ping` just to make sure you've got the basic libp2p connection work properly set up.

**Comment by ShwetaTripathi05** [comment]
I was able to communicate between the two libraries using the newStream() API. And from the logs of the node it is evident that the nodes are able to ping each other (since it shows reachable status). 

For gossip implementation, I am trying to use the connect() API to make the nodes connect explicitly by passing a multiaddress of the other node. There is no error which according to me indicates that there is a connection established between the nodes. But when I try to subscribe both nodes to the same topic and try to fetch the peers it returns an empty list. I am unable to understand the missing link here.

**Comment by marten-seemann** [comment]
This is most likely an issue with jvm-libp2p, not with go-libp2p. Can you open an issue there?
