### ISSUE TITLE
Connect API between go-libp2p & jvm-libp2p returns error

### ISSUE THREAD

**Issue by ShwetaTripathi05** [libp2p/go-libp2p#1347]
I am trying to establish connection between a go-libp2p host and another jvm-libp2p host. When I use the host.connect() API from the go-libp2p node by passing the multiaddress and peerID of the jvm-libp2p node, it returns an error : “failed to negotiate security protocol: protocol not supported”.

Any help on resolution of the above error would be appreciated!

**Comment by vyzo** [comment]
sounds like jvm-libp2p only supports secio? We have deprecated that, need tls or noise.

Can you open issue in the jvm repo?

**Comment by ShwetaTripathi05** [comment]
I thought jvm-libp2p also supports noise : ref:[https://github.com/libp2p/jvm-libp2p/issues/35]. 
I shall open an issue in the jvm repo. Thanks!!

**Comment by vyzo** [comment]
noise should do just fine

**Comment by ShwetaTripathi05** [comment]
@vyzo I tried implementing noise on both sides and then tried using the connect API. It still gives the same error: _“failed to negotiate security protocol: protocol not supported”._

**Code snippet on jvm-libp2p side:**
_PrivKey key = generateKeyPair(KEY_TYPE.ED25519).component1();
Host host =  new HostBuilder()
                .protocol(new NoiseXXSecureChannel(key))
                .build();_


**Code snippet on go-libp2p side:**
_var options []libp2p.Option
priv, _, err := crypto.GenerateEd25519Key(rand.Reader)
if err == nil {
		options = append(options, libp2p.Identity(priv))
		options = append(options, libp2p.Security(noise.ID, noise.New))
	}
h, err := libp2p.New(options...)
h.Connect(ctx, *peerAddrInfo)_       //peerAddrInfo contains info regarding the jvm-libp2p node

Can you tell me where am I possibly making a mistake?

**Comment by marten-seemann** [comment]
This is most likely not a go-libp2p issue, so this is not the right place to discuss this. You might want to turn to jvm-libp2p, or to the [libp2p forums](https://discuss.libp2p.io/).
