### ISSUE TITLE
find relays stuck while retry

### ISSUE THREAD

**Issue by optman** [libp2p/go-libp2p#1359]
https://github.com/libp2p/go-libp2p/blob/13d0381768e7f115e115f4b29191cc1458fa4d36/p2p/host/autorelay/autorelay.go#L294

It should be `NewTicker`, otherwise it only fire once, and retry will stuck.

**Comment by marten-seemann** [comment]
Good thing is this code will go away very soon, as I'm working #1351 right now.

**Comment by marten-seemann** [comment]
#1351 was merged, so this issue is moot now.
