### ISSUE TITLE
Dialer.Dial takes remote peerID but does not confirm that it is peer that it connected to

### ISSUE THREAD

**Issue by Kubuxu** [libp2p/go-libp2p#137]
It potentially exposes libp2p users to MitM attack if the check isn't done manually after the Dial. We do it in go-libp2p-swarm code but if someone uses Dial directly it might be a problem.

It currently isn't done as secio handshake is done lazily on first usage.

**Comment by jackkleeman** [comment]
I have made a PR for this bug here https://github.com/libp2p/go-libp2p-conn/pull/22

**Comment by Stebalien** [comment]
This has been fixed in `go-lib2p-conn`. The next step is to remove the additional check in `go-libp2p-swarm` (maybe?).

**Comment by jackkleeman** [comment]
See https://github.com/libp2p/go-libp2p-swarm/pull/48
