### ISSUE TITLE
How to create separate network channel for already existing network?

### ISSUE THREAD

**Issue by kunalgoyal9** [libp2p/go-libp2p#1393]
Right now I have this functionality in my p2p app.

> 1. get ip from config file.
> 2. make host
> 3. connect to each peer 
> a. make connection object
> i. receiveMessageCycle
> 		periodicaly read from inbound stream and check if :
> 		aa. if message type message: call handler to check message type
> 		bb. signature: handlesignature
> 		cc. getPeerReply:: peer_service.updatePeerList: for each new peer setup connection
> ii. sendMessageCycle:
> 	aa. deque from message queue.
> 	bb. Make a frame and put message and its type as message.
> 	cc. Put it to outbound stream.
> 
> iii. sendPeersCycle:
> 	aa. call peer_service.getPeers: take connections and iterate to get public key, id, adds in arr
> 	bb. Make a frame and put arr and message type as getpeerReply
> 	cc. put the frame to the outbound stream.

Now I want to have a different parallel network apart from this. The main goal for this is to optimize the message sharing for the connected peers.

**Comment by munna0908** [comment]
Hey @kunalgoyal9, You can do that by opening libp2p streams with different protocol IDs. Feel free to open a thread in [discuss.libp2p.io](https://discuss.libp2p.io/)

**Comment by kunalgoyal9** [comment]
@munna0908 Thanks for your reply... what about handling stream? Can you please share some example on this?

**Comment by munna0908** [comment]
Create a different stream handler function for each protocol ID and register it using `SetStreamHandler`. Sample [snippet](https://gist.github.com/munna0908/b19bd8a70c72c91a76cf8af35a79c2ae)
