### ISSUE TITLE
what's the url `http://localhost:5001/api/v0/id` is provided by which service?

### ISSUE THREAD

**Issue by Frederic-Zhou** [libp2p/go-libp2p#1394]
https://github.com/libp2p/go-libp2p/blob/52d3e89ea49039b07eec0e9128c46614a975c621/examples/routed-echo/bootstrap.go#L32

run the example `go-libp2p/examples/routed-echo`  , shows the following:
```
2022/04/14 17:56:40 using local bootstrap
2022/04/14 17:56:40 Get "http://localhost:5001/api/v0/id": dial tcp [::1]:5001: connect: connection refused
exit status 1
```

what's the url `http://localhost:5001/api/v0/id` is provided by which service?

**Comment by munna0908** [comment]
Hi @Frederic-Zhou, that URL hits the local IPFS Daemon, Here is the API [doc](https://docs.ipfs.io/reference/http/api/#api-v0-id).

**Comment by Frederic-Zhou** [comment]
Thanks a lot!!!
