### ISSUE TITLE
tcp.go:196: d.rd.DialContext undefined (type reuseport.Dialer has no field or method DialContext

### ISSUE THREAD

**Issue by XnuKernPoll** [libp2p/go-libp2p#140]
Sort of self explanatory.

**Comment by lgierth** [comment]
> Sort of self explanatory.

Sometimes it's really not -- could you post the exact commands to reproduce it?

**Comment by Kubuxu** [comment]
It is, it is becase we have PR open: https://github.com/jbenet/go-reuseport/pull/17 but @jbenet isn't here to merge it.

We are already using the code, this means that you have to do `gx install; gx-go rewrite` to compile lib2p.

**Comment by XnuKernPoll** [comment]
Sorry I already fixed it using gx and forgot to update you guys I kind of feel like an idiot.

**Comment by Kubuxu** [comment]
Fixed by merge of https://github.com/jbenet/go-reuseport/pull/17
