### ISSUE TITLE
Export identify.ErrProtocolNotSupported

### ISSUE THREAD

**Issue by lthibault** [libp2p/go-libp2p#1416]
I am writing an application that supports multiple independent networks that are scoped to different "namespaces".  Namespaces are implemented as sub-protocols.  For example, one network might operate under `/my-proto/1.2.0/ns-1` while another operates under `/my-proto/1.2.0/ns-2`.

When connecting with a misconfigured namespace parameter, the application currently returns `"protocol not supported"`, which I think you'll agree is not very helpful.  I would like to handle `identify.errProtocolNotSupported` and instead something more useful, however the error is not exported from the package.

Fixing this is a trivial matter of renaming the error variable to `ErrProtocolNotSupported`.  I am happy to submit a PR if you guys give me the go-ahead.

**Comment by marten-seemann** [comment]
Where does the application return this error?
Are you sure this is identify error? This sounds more like the go-multistream error, which should be exported already.

**Comment by lthibault** [comment]
Addendum:  this would also aid in unit testing.  I currently have a unit test that does string comparison against `err.Error()` to check for unsupported protocols, which is clunky.

**Comment by lthibault** [comment]
@marten-seemann Thanks for the quick reply!  

I was grepping for the error string and found it in [identify](https://github.com/libp2p/go-libp2p/blob/0b5e1c266ec4faf532a40ec121e08acd1b2fd074/p2p/protocol/identify/peer_loop.go#L21), but you may be correct.  Investigating this now.

**Comment by lthibault** [comment]
@marten-seemann You called it.  Thanks for clearing that up.  Closing as invalid.
