### ISSUE TITLE
websocket: Origin and Content Security Policy

### ISSUE THREAD

**Issue by ghost** [libp2p/go-libp2p#1436]
`(*WebsocketTransport).Listen()` unconditionally sets `Origin`, which should only be set by the client side, while the server side should set `Location`.

Regardless of this, both Origin and Location seem to only allow one value respectively, while we want to be able to set multiple: ipfs.io, gateway.ipfs.io, *, localhost, etc.

**Comment by marten-seemann** [comment]
I believe `Origin` is not applicable in our case, as it's only used by web browsers.
