### ISSUE TITLE
autorelay: flaky TestSingleRelay

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1440]
```
  === RUN   TestSingleRelay
      autorelay_test.go:154: 
          	Error Trace:	autorelay_test.go:154
          	Error:      	Condition never satisfied
          	Test:       	TestSingleRelay
  --- FAIL: TestSingleRelay (3.66s)

**Comment by marten-seemann** [comment]
@MarcoPolo I'm working on a rewrite of the auto relay logic, so this is probably not worth spending a lot of time on. Part of the fix will be waiting for the relay service to boot up (https://github.com/libp2p/go-libp2p/pull/1438), but apparently that's not all that's going on here.

**Comment by MarcoPolo** [comment]
Okay, I'll assign this to you. Should we skip this test for now?

**Comment by MarcoPolo** [comment]
Feel free to reassign it to me if you'd like me to investigate.
