### ISSUE TITLE
holepunch: s.holePuncher is nil on close

### ISSUE THREAD

**Issue by watjurk** [libp2p/go-libp2p#1448]
## Sys info
go-libp2p@v0.19.0

## Issue
When closing holepuncher it panics when it hadn't been created yet. Let me explain:

When holepuncher is closed, then the s.holePuncher is closed no matter what: 
https://github.com/libp2p/go-libp2p/blob/5151d4b4faaae04523dd83b9377881fbc717c752/p2p/protocol/holepunch/svc.go#L148-L156

It's worth noting that s.holePuncher is a pointer that is `nil` by default:
https://github.com/libp2p/go-libp2p/blob/5151d4b4faaae04523dd83b9377881fbc717c752/p2p/protocol/holepunch/svc.go#L44-L57

And that s.holePuncher is only initialized in s.watchForPublicAddr func when some conditions are met:
https://github.com/libp2p/go-libp2p/blob/5151d4b4faaae04523dd83b9377881fbc717c752/p2p/protocol/holepunch/svc.go#L141

This is a problem because if the s.holePuncher isn't initalized and we would call s.Close then s.holePuncher.Close() would panic (because it is not designed to be "zero value" closed).

## Solution:
The simplest solution is to introduce a nil check when closing holepuncher, it will check if s.holePuncher is nil or not.

**Comment by Stebalien** [comment]
Hm. This is also a race-condition.

**Comment by watjurk** [comment]
Where is the race condition happening? I've run this code with --race enabled and no races were found.

**Comment by marten-seemann** [comment]
`s.holePuncher` might be set just when you call `Close`. We might need to introduce a mutex here.
