### ISSUE TITLE
Examples broken

### ISSUE THREAD

**Issue by lgierth** [libp2p/go-libp2p#145]
```
$ go build ./examples/hosts/
# github.com/libp2p/go-peerstream
../../../workspace/gopath/src/github.com/libp2p/go-peerstream/listener.go:112: cannot use conn (type transport.Conn) as type conn.Conn in argument to func literal:
	transport.Conn does not implement conn.Conn (missing ID method)
```

**Comment by lgierth** [comment]
It looks like the innocent-looking libp2p/go-peerstream@f8d76775634c0c49359712714d067e7208f5c79c broke this, by changing from [net.Conn](https://golang.org/pkg/net/#Conn) to [go-libp2p-interface-conn.Conn](https://github.com/libp2p/go-peerstream/commit/f8d76775634c0c49359712714d067e7208f5c79c#diff-804732da4aad8a84ebedfb545342f187R102), and same for Listener.

@whyrusleeping what needs doing?

**Comment by whyrusleeping** [comment]
@lgierth mehhhh, pull latest go-peerstream and try again? i might have forgotten to push something

**Comment by lgierth** [comment]
Thanks, that helped! PR for another little thing incoming, a typo breaking the protocol names :) https://github.com/libp2p/go-libp2p/commit/f9cd03e6257a196e4ef4c074bfdd97ea8b59d9fb#diff-d026b928f7cf219569f2970e653d8dc8L70
