### ISSUE TITLE
quic: flaky reuse tests

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1455]
```
=== RUN   TestReuseListenOnAllIPv4
      reuse_test.go:59: 
          	Error Trace:	reuse_test.go:59
          	Error:      	Condition never satisfied
          	Test:       	TestReuseListenOnAllIPv4
          	Messages:   	expected garbage collector to be running
  --- FAIL: TestReuseListenOnAllIPv4 (0.14s)

**Comment by MarcoPolo** [comment]
A run that failed: https://github.com/libp2p/go-libp2p/runs/6191379090?check_suite_focus=true

**Comment by marten-seemann** [comment]
It looks like 100ms is too short. I added some logging to see how long this takes, and occasionally, it takes _really_ long on CI.
```
=== RUN   TestReuseListenOnAllIPv6
  isGarbageCollectorRunning
  isGarbageCollectorRunning done (took 153.3857ms). Result: true
```

I'm not convinced this is why the test is failing though. I do see the
```go
require.Eventuallyf(t, isGarbageCollectorRunning, 100*time.Millisecond, 10*time.Millisecond, "expected garbage collector to be running")
```
failing without any logging output, meaning that `isGarbageCollectorRunning` was not called at all.

Anyway, it's probably a good idea to increase the timeout here... by a lot.
