### ISSUE TITLE
使用libp2p的discovery - mDNS模块的时候在腾讯云机器上可以发现节点，但是华为云上发现不了节点（没报错）

### ISSUE THREAD

**Issue by zhou-yong-long** [libp2p/go-libp2p#1464]
经过debug我发现是在https://github.com/libp2p/zeroconf的Browse方法中无法获取到dns信息，一直debug到这一层
package zeroconf 中 client.go的169-175行代码
```
msgCh := make(chan *dns.Msg, 32)
if c.ipv4conn != nil {
   go c.recv(ctx, c.ipv4conn, msgCh)
}
if c.ipv6conn != nil {
   go c.recv(ctx, c.ipv6conn, msgCh)
}
```
msgCh中没有信息返回，请问是什么问题吗？配置信息都检查过没有出错

**Comment by marten-seemann** [comment]
Sorry, I don't speak Chinese. Please post issues in English.
