### ISSUE TITLE
Stateless Computing with libp2p

### ISSUE THREAD

**Issue by faddat** [libp2p/go-libp2p#147]
Let's suppose for a moment that we have a number of building blocks, and we begin at the bottom with hardware:

* Hardware

Current (as in:  It can be touched, and even bought)
  * ![image](https://cloud.githubusercontent.com/assets/7142025/25431087/4f6a0ade-2aa9-11e7-8d0e-cfb4bd2c0efe.png)
  * Orange Pi PC

Future (sketches of the products to ensure communicating the whole idea well)
  * "Simple" Smartphone
    * stateless OS and applications loaded from a remote, distributed, secure/validated source(s)
      * all state is local
        * Distributed, encrypted backup is optional
    * IP-only voice/video/chat
    * No support for POTS

  * Laptop
        * stateless OS and applications loaded from a remote, distributed, secure/validated source(s)
      * all state is local
        * Distributed, encrypted backup is optional

* libp2p 
  * "default" choice throughout the system for p2p applications. 

* zerotier
  * What will be used to ensure networking is either private or easy depending on context

* tendermint
  * fast global and local blockchains

Applications:
* chat
* collaborative work
* voice calls
* video calls
* server swarms

API for Developers:
.....This still needs refining.  I think overall, this issue is much more refined, however.

**Comment by faddat** [comment]
I'm very interested in questions, comments, and the like.  Best way to reach me is faddat@gmail.com on google hangouts.  I'd much rather use something made using libp2p, though ;).

**Comment by diasdavid** [comment]
Hi @faddat, seems like you found the wrong repo to ask this question. You might want to open this in https://github.com/ipfs/notes/issues. Closing the issue here and look forward to see the discussion on ipfs/notes :)
