### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by QZAiXH** [libp2p/go-libp2p#1472]
Hi, I think libp2p needs to be updated with the current examples to ensure that newbies can run it correctly and learn. This is very important.
There's also the current lack of CircuitV2 examples, which I don't know what to do when two machines behind NATs run chat-with-rendezvous.

**Comment by Stebalien** [comment]
We definitely need more examples. Unfortunately, non-specific issues like this aren't directly actionable and tend to just sit around collecting dust.

Please consider submitting new examples yourself, it's a great way to learn libp2p. If you want inspiration, I recommend you take a look at how go-ipfs uses relays, etc.
