### ISSUE TITLE
Could not run example host

### ISSUE THREAD

**Issue by ramilexe** [libp2p/go-libp2p#149]
Try to run example host

```
cd examples/hosts
go build
./hosts -l 4737
```

Show:
```
I am /ip4/0.0.0.0/tcp/4737/ipfs/QmXeKRxQb2nSPMSJhZzmQNjuqkYL2YJxgKAqbieKZWkW2r
listening for connections...

```
In another console run:

```
./hosts -d /ip4/127.0.0.1/tcp/4737/ipfs/QmXeKRxQb2nSPMSJhZzmQNjuqkYL2YJxgKAqbieKZWkW2r
```

Output:
```
ERROR net/identi: did not have own public key in Peerstore id.go:172
```

How to add public key to Peerstore?

**Comment by lgierth** [comment]
Try the fixes in #146

**Comment by ramilexe** [comment]
@lgierth tried your fix. It works only if run server and client with `secio` param:
`-secio 1`

**Comment by ramilexe** [comment]
@lgierth I investigated this issue. Since you added checking public key in outgoing message in commit 65273ab3e7fd033887f5276fdb51df4028d8ebe8 you always will get this error message in log

**Comment by whyrusleeping** [comment]
I think this example has been deleted. I think we can close this issue now.
