### ISSUE TITLE
flaky TestIdentifyDeltaOnProtocolChange

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1497]
```
  === RUN   TestIdentifyDeltaOnProtocolChange
      id_test.go:409: 
          	Error Trace:	id_test.go:409
          	Error:      	Condition never satisfied
          	Test:       	TestIdentifyDeltaOnProtocolChange
  --- FAIL: TestIdentifyDeltaOnProtocolChange (1.15s)

**Comment by marten-seemann** [comment]
This has a timeout of 1s, so it's unlikely to be caused by CPU contention.

**Comment by MarcoPolo** [comment]
Do you happen to have a link to a failed run?

**Comment by marten-seemann** [comment]
Unfortunately, I don't remember when this happened. Should have posted the link here when I created the issue.

**Comment by marten-seemann** [comment]
Here's a failure of a similar test: https://github.com/libp2p/go-libp2p/runs/6495390608?check_suite_focus=true
