### ISSUE TITLE
RelayFinder should trigger a new candidate selection when a relay lost connection

### ISSUE THREAD

**Issue by nickjfree** [libp2p/go-libp2p#1512]
Correct me if i am wrong.

In refreshRelayReservation, if a relay lost connection, it will be removed from rf.relays  but it's not removed frome rf.candidates

In the worst case, if the rf.cabdidates number reached max candidates, new candidates from peerChan will not be added and no handleNewCandidates call will be triggered. 

For a node running behind an NAT firewall.  After all relays have lost connections, the node wouldn't be able to select any candidates. leaving the node unreachable.

Maybe we shoud find some way to trigger a new candidate selection when a relay lost connection. or just put that relay peer to backoff. making room for new peers from the peerChan

**Comment by marten-seemann** [comment]
The connection may have dropped for any reason. We can just try to reconnect to that node. Nodes that we can't connect to are (after a few attempts) removed from the list of candidates, which allows new nodes to be pulled in.

**Comment by marten-seemann** [comment]
Still not convinced this is an issue. Having heard nothing to the contrary from @nickjfree, I'm closing this issue. Also, this code will be refactored really soon anyway, see #1569.
