### ISSUE TITLE
noise: define API for early data

### ISSUE THREAD

**Issue by yusefnapora** [libp2p/go-libp2p#1537]
We want to be able to send "early data" in our handshake message payloads, so that we can advertise supported stream multiplexers without adding round-trip negotiations after the handshake completes.

So far, we've defined the protobuf field in the handshake payload that will carry the early data, but we also need a way to provide it when configuring the transport, and a way to retrieve the early data sent by the remote party.

For setting the early data, we could have a new interface that early data capable `SecureTransport`s would implement, e.g.

```go
type EarlyDataSender interface {
  func SetEarlyDataPayload([]byte)
}
```

Then when go-libp2p instantiates the security modules for a Host, it can type assert to see if they support this interface and inject the payload with the set of multiplexers.

We also need another interface that early data capable `SecureConn` implementations would conform to, something like

```go
type EarlyDataReceiver interface {
  func RemoteEarlyData() []byte
}
```

Then multiselect 2 could type assert on the connection & try to get the set of muxers out if the conn supports early data.

The actual interfaces should probably be defined elsewhere, since they'll be common to any crypto channel that supports early data (e.g. TLS 1.3).

When implementing, we need to take care that the early data is sent in a handshake message that supports encrypted payloads. This essentially just means we can't send it in the initiator's first `XX` message.

Now that I've typed this up, I'm starting to question whether the method to set the early data payload belongs on the transport itself, or whether it should be specialized for each connection. I was thinking that it doesn't need to be specialized, since the set of muxers is fairly static. But QUIC doesn't need a muxer, so we might want to skip sending the payload for QUIC connections. In that case, we'd need to define a new flavor of the `SecureTransport` interface that allows passing in the early data payload for each connection.

**Comment by p-shahi** [comment]
Closing this as it's addressed by https://github.com/libp2p/specs/pull/453 and implemented by https://github.com/libp2p/go-libp2p/pull/1813
