### ISSUE TITLE
nat: mapping with ListenPort as internalPort cannot be established by UPNP by some NATs

### ISSUE THREAD

**Issue by Liquoxx** [libp2p/go-libp2p#1543]
Hello libp2p-Team,

I am using libp2p.NATPortMap() to open ports by UPNP. I am basically trying it with this example: [chat with rendezvous](https://github.com/libp2p/go-libp2p/tree/master/examples/chat-with-rendezvous)

At my home the code is running perfectly. Now I changed my physical location (different router) and it fails with the following UPNP error code:

`AddPortMapping failed with code 718 (ConflictInMappingEntry)`

**Cause:** I already analyzed the cause of the problem and it seems that with my router the listening port for libp2p gets somehow used in a mapping in my router. So I will never be able to establish a port mapping to the internal port which libp2p is giving me. The corresponding code in natmgr.go:

`		port, err := strconv.ParseUint(proto.Value(), 10, 16)
		if err != nil {
			// bug in multiaddr
			panic(err)
		}
		ports[protocol][int(port)] = false`

**Workaround/Fix**: If I just assign it to a different internal port (+1), the code works again and I see that the external Port was opened in my router. I was increasing it by 1 in go-libp2p-nat   **nat.go**:
` 
        func (nat *NAT) NewMapping(protocol string, port int) (Mapping, error) {

	if nat == nil {
		return nil, fmt.Errorf("no nat available")
	}

	switch protocol {
	case "tcp", "udp":
	default:
		return nil, fmt.Errorf("invalid protocol: %s", protocol)
	}

	m := &mapping{
		intport: port + 1,
		nat:     nat,
		proto:   protocol,
	}
         ...`

**Comment by BigLep** [comment]
@Liquoxx : can you please provide:
1. Repro case
2. Router model that works
3. Router model that doesn't work

**Comment by BigLep** [comment]
Closing because it's been a month and didn't receive request repro info.
