### ISSUE TITLE
swarm: relay dials shouldn't be marked as "costly"

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#1546]
Currently, relay dials may trigger file descriptor limiting logic because they contain a TCP transport. This means:

1. We'll double-pay.
2. We could end up blocking as the relay dialer will re-entrently call back into the dialer when trying to dial the relay.

@raulk this could be related to the dial issues we're seeing.

**Comment by marten-seemann** [comment]
I believe this is not an issue any more. FDs are now tracked by the resource manager. Relay dials totally should be marked as costly though, because they are. The recently introduced dial ranking logic makes sure that we dial relay addresses last.
