### ISSUE TITLE
List all dependencies with gx deps

### ISSUE THREAD

**Issue by JustinDrake** [libp2p/go-libp2p#156]
I installed just `go-libp2p` (as opposed to `go-ipfs`) to inspect its dependencies with `gx deps`. I get the error `package QmNafAGBU21iQmLudMT2z1kqgEGhjUrNoK9a3v4azd8ei4 not found` (see below).

(Note that `gx` and `gx-go` are both installed, and `gx deps` works fine with `go-ipfs`.)

```
Justins-MacBook-Pro:go-libp2p-peer justin$ go get -d github.com/libp2p/go-libp2p
package github.com/libp2p/go-libp2p: no buildable Go source files in /Users/justin/go/src/github.com/libp2p/go-libp2p
Justins-MacBook-Pro:go-libp2p-peer justin$ cd /Users/justin/go/src/github.com/libp2p/go-libp2p/
Justins-MacBook-Pro:go-libp2p justin$ make
go get github.com/whyrusleeping/gx
go get github.com/whyrusleeping/gx-go
Justins-MacBook-Pro:go-libp2p justin$ gx deps
package QmNafAGBU21iQmLudMT2z1kqgEGhjUrNoK9a3v4azd8ei4 not found
Justins-MacBook-Pro:go-libp2p justin$ pwd
/Users/justin/go/src/github.com/libp2p/go-libp2p
```

**Comment by hsanjuan** [comment]
`make deps` first?

**Comment by JustinDrake** [comment]
Duh, thanks! 👍

**Comment by hsanjuan** [comment]
No problem! `gx deps` command-help does not clarify that it will check that the dependencies are installed or fail otherwise. You may want to open an issue on [Gx](https://github.com/whyrusleeping/gx) or make a pull request directly.
