### ISSUE TITLE
Failed to run example file

### ISSUE THREAD

**Issue by mjena** [libp2p/go-libp2p#158]
Failed to run main.go present in example folder. here is the logs
MAHESHs-Mac-mini:go-libp2p maheshjena$ go run examples/echo/main.go 
# github.com/libp2p/go-peerstream
../go-peerstream/stream.go:96: s.smuxStream.SetDeadline undefined (type streammux.Stream has no field or method SetDeadline)
../go-peerstream/stream.go:100: s.smuxStream.SetReadDeadline undefined (type streammux.Stream has no field or method SetReadDeadline)
../go-peerstream/stream.go:104: s.smuxStream.SetWriteDeadline undefined (type streammux.Stream has no field or method SetWriteDeadline)
MAHESHs-Mac-mini:go-libp2p maheshjena$

**Comment by hsanjuan** [comment]
Hi, yep sorry, this is a known issue in master. You can run `make deps` on the go-libp2p base folder to use the gx-pinned deps which allow the example to compile fine.

You can also subscribe to this thread which is related, if your interested: https://github.com/jbenet/go-stream-muxer/issues/10

**Comment by diasdavid** [comment]
Hi @mjena, this shouldn't be an issue anymore, could you try again? Let me know if you have issues and we will reopen this issue.
