### ISSUE TITLE
Allow dialing wss peers using DNS multiaddrs

### ISSUE THREAD

**Issue by aschmahmann** [libp2p/go-libp2p#1593]
# Problem

From what I can tell while we technically have WSS dialing from go-libp2p due to https://github.com/libp2p/go-ws-transport/pull/115 it's basically unusable.

Currently trying to dial some peer like `/dns4/node3.preload.ipfs.io/tcp/443/wss/p2p/QmY7JB6MQXhxHvq7dBDh4HpbH29v4yE9JRadAVpndvzySN` will result in an error like:
```
failed to dial QmY7JB6MQXhxHvq7dBDh4HpbH29v4yE9JRadAVpndvzySN:
  * [/ip4/145.40.97.77/tcp/443/wss] x509: cannot validate certificate for 145.40.97.77 because it doesn't contain any IP SANs
```

i.e. we do not make use of the DNS information in the dialing and so we run into a certificates problem because the certificate is tied to the domain name.

---

Small tool if you want to play with this and see the issue is https://github.com/aschmahmann/vole. You can run something like:

```
vole.exe bitswap check bafybeibml5uieyxa5tufngvg7fgwbkwvlsuntwbxgtskoqynbt7wlchmfm /dns4/node3.preload.ipfs.io/tcp/443/wss/p2p/QmY7JB6MQXhxHvq7dBDh4HpbH29v4yE9JRadAVpndvzySN
```

**Comment by marten-seemann** [comment]
Copying from the discussion on the PR.

To make this work properly, we should:
* stop resolving wss addresses in the host
* pass the resolver to the WebSocket transport
* not dial wss addresses if we have a TCP address from the same peer

This would also make for an excellent Testground test case.
