### ISSUE TITLE
Log invalid/suspicious activity

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/go-libp2p#1598]
Feature: go-libp2p should log suspicious activity with a canonical log prefix, so these log lines can quickly be aggregated and identified.

## Why
We want to leverage existing tools and methods as much as possible. There are off the shelf solutions that automatically block misbehaving peers from interacting with a node. Tools like [fail2ban](https://www.fail2ban.org/wiki/index.php/Main_Page) do this by scanning log files and adding firewall rules to block malicious peers. Operators may also want to see if there was any unusual activity in the logs themselves in order to investigate abnormal states (e.g. latency on the server went way up, was there any unusual peer activity?). These logs can also be aggregated and recorded in a dashboard to provide observability to node operators independent of the specific libp2p application.

In order to make use of these ecosystem of tools, libp2p needs to highlight when a peer misbehaves. Only libp2p can do this since we're talking about protocol-level semantics (i.e. a tool that just reads packets won't be able to give us this insight).

## What
go-libp2p should log suspicious events such as:

1. Failed handshake.
2. A peer hitting the stream limits.
3. A peer hitting connection limits.
4. A peer sending unexpected bytes over a stream. (e.g. a peer sending a large varint for a multistream-select protocol) 
5. A peer sending a message that fails to decode. (e.g. protobuf err) 

And maybe:
1. A lot of successful handshakes (> 10k?)
1. A lot of churn

We can even log a sample of every connection/stream created and rely on other tools to find patterns in that data. e.g. we log 1% of connections, if we see the logs show 1k connections for the same peer in a short time window we can extrapolate that we actually had 100k connection churn and we should block this peer. Note that this doesn't require any fancy logic in libp2p, it just logs at some sample.

## API for protocols
Only protocol implementations know what a misbehaving or suspicious peer looks like. go-libp2p should have an API that allows these protocol implementations to log this suspicious activity. TBD what this api should look like, but it could be as simple as exposing a canonical log line prefix that protocol implementations use when they log.

**Comment by MarcoPolo** [comment]
Here's a great technical blog that explains the value of canonical log lines: https://stripe.com/blog/canonical-log-lines

**Comment by BigLep** [comment]
@MarcoPolo : what's remaining given that https://github.com/libp2p/go-libp2p-core/pull/258 was merged?

**Comment by MarcoPolo** [comment]
https://github.com/libp2p/go-libp2p/pull/1600 and something similar in the resource manager side (https://github.com/libp2p/go-libp2p-resource-manager/pull/51)
