### ISSUE TITLE
swarm: introduce address tiers to prioritize dials

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1605]
Not all addresses are created equal, and we should be smarter when dialing:
* We should prefer IPv6 over IPv4, implementing an Happy-Eyeballs-like mechanism as described in [RFC 8305](https://datatracker.ietf.org/doc/html/rfc8305).
* When given an IP multiaddr and a DNS multiaddr to dial (for any given transport), we should start dialing the IP address immediately, and start DNS resolution concurrently.
* We should prefer QUIC over TCP. QUIC handshakes are fast (1 RTT), so giving QUIC a head start of a few hundred ms will allow us to not start the TCP handshake in the vast majority of cases.
* We need to be able to learn from failed dials. Sometimes IPv6 is blackholed, or UDP. This blackholing will apply to address _categories_ (it might work on the local network, but fail on the public internet), so the algorithm needs to be able to classify addresses.

Things to consider: it might be worth considering changing our transport interface, such that `Dial` is async and can be called with multiple addresses.

**Comment by sukunrt** [comment]
@marten-seemann we don't need to _explicitly_ disable QUIC or IPv6, right? If they're black holed we will not dial those addresses and we won't establish any incoming connections either.

**Comment by marten-seemann** [comment]
Closing this issue, since @sukunrt has successfully chewed through all of the above points. We still need to publish a blog post. I created https://github.com/libp2p/blog/issues/92 to track that.
