### ISSUE TITLE
mplex: use ReadWriteCloser instead of net.Conn

### ISSUE THREAD

**Issue by paralin** [libp2p/go-libp2p#1608]
The `github.com/libp2p/go-libp2p-core/network` package currently requires a `net.Conn` to build a Multiplexer.

This should be changed to a `io.ReadWriteCloser` so that we can operate with any two-way pipe, instead of just network conns.

The mplex multiplexer doesn't actually call any of the net.Conn funcs, see: https://github.com/libp2p/go-mplex/pull/113

**Comment by MarcoPolo** [comment]
Is this true of yamux as well?

**Comment by marten-seemann** [comment]
Closing, as https://github.com/libp2p/go-mplex/pull/113 was merged.
