### ISSUE TITLE
About go-libp2p-examples-pubsub Input

### ISSUE THREAD

**Issue by thisisSomalia** [libp2p/go-libp2p#1613]
我在终端中运行之后，聊天室输入框输入不了东西

**Comment by thisisSomalia** [comment]
Could you please tell me why to close me?In [this](https://github.com/libp2p/go-libp2p/tree/master/examples/pubsub/chat) ,after i run `go run .` ，i cannot input anything in the terminal

**Comment by marten-seemann** [comment]
Because I don't speak Chinese.

**Comment by thisisSomalia** [comment]
In [this](https://github.com/libp2p/go-libp2p/tree/master/examples/pubsub/chat) ,after i run `go run . `  i cannot input anything in the terminal.
Could you please tell me how to solve it?

**Comment by marten-seemann** [comment]
Feel free to ask on the [forum](https://discuss.libp2p.io).
