### ISSUE TITLE
Changelog for go-libp2p

### ISSUE THREAD

**Issue by JustinDrake** [libp2p/go-libp2p#162]
Is there a changelog for libp2p? As I understand there has been only a [single agent version change](https://github.com/libp2p/go-libp2p/commit/9ccbf103e02e59b12dc51cfcdc0356148d06237c#diff-98be6dba669aa4123b7ef190fe7113e8) from 0.1.0 to 3.3.4. What's the best way to keep track of libp2p versions and changes between those versions?

**Comment by JustinDrake** [comment]
I see there are roadmaps for go-libp2p and go-ipfs based around quarters (not version numbers)

https://github.com/libp2p/go-libp2p/blob/master/roadmap.md
https://github.com/ipfs/go-ipfs/blob/master/roadmap.md

**Comment by marten-seemann** [comment]
We now publish a changelog in the release notes for every release.
