### ISSUE TITLE
Add examples for a custom go-libp2p-resource-manager with go-libp2p defaults applied.

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/go-libp2p#1628]
Examples on how to initiate go-libp2p-resource-manager with custom limits and how to apply go-libp2p's default limits here.

Should happen after: https://github.com/libp2p/go-libp2p-resource-manager/pull/48

**Comment by marten-seemann** [comment]
@MarcoPolo Can we close this issue? We have a pretty detailed rcmgr README.
