### ISSUE TITLE
Interop between go/node

### ISSUE THREAD

**Issue by calummoore** [libp2p/go-libp2p#1662]
#### Version / Platform:
Go: 1.18 / github.com/libp2p/go-libp2p v0.20.3 
Node: v16.15.0 / libp2p@0.37.3-05e8e7e

#### Severity:
High

#### Description:
Using the basic chat example for both `node` and `go`, I can get it working for node-to-node and go-to-go, but when I try and communicate between node and go, I get an error.

✅ Node listener, node dialer
✅ Go listener, go dialer

❌ Node listener, go dialer

```
2022/07/26 14:57:19 failed to dial 12D3KooWCfHjvRRrnWnghuUvfunvcyaW72r8478VAxqCFdkDWrRg:
  * [/ip4/127.0.0.1/tcp/54950] failed to negotiate stream multiplexer: protocol not supported
```

❌ Go listener, node dialer

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
[AggregateError: All promises were rejected]
```
(a pretty unhelpful log message, but I've seen this before and I think it's basically when it cannot connect for whatever reason).
 

#### Steps to reproduce the error:

Install/run code in repo: https://github.com/calummoore/libp2p-go-js

#### Alt ticket raised in js-libp2p

https://github.com/libp2p/js-libp2p/issues/1307

**Comment by marten-seemann** [comment]
This is expected. go-libp2p doesn't use mplex by default, and js-libp2p doesn't support yamux (yet).
You can explicitly enable mplex by using `libp2p.Muxer` option.

**Comment by calummoore** [comment]
Thanks that's super helpful!

I added that change but for some reason, messages from `node` -> `go` show up, but message from `go` -> `node` do not. This happens regardless of which one is dialer/listener.

Any ideas what might be causing that?

**Comment by calummoore** [comment]
Needed to send bytes rather than string, it's now working!
