### ISSUE TITLE
Cannot find packages when running example

### ISSUE THREAD

**Issue by TheCodeBuccaneer** [libp2p/go-libp2p#172]
I tried to run the echo example, but i receive the message that certain pakcages cannot be found (E.g. github.com/libp2p/go-libp2p-swarm, github.com/libp2p/go-libp2p-metrics, github.com/libp2p/go-libp2p-metrics/stream, github.com/libp2p/go-libp2p-nat, github.com/libp2p/go-libp2p-loggables).

Has the example become obsolete or did something go wrong in the installation? Thanks

**Comment by lgierth** [comment]
Could you post the command and output?

**Comment by TheCodeBuccaneer** [comment]
Command is go run main.go and ax example of one of the errors is:

file: 'file:///...../Go/src/github.com/libp2p/go-libp2p/p2p/host/basic/basic_host.go'
severity: 'Error'
message: 'cannot find package "github.com/libp2p/go-libp2p-metrics" in any of:
	C:\Program Files (x86)\Go\src\github.com\libp2p\go-libp2p-metrics (from $GOROOT)
	c:\Users\.....\Go\src\github.com\libp2p\go-libp2p-metrics (from $GOPATH)'
at: '13,1'
source: ''

**Comment by CMCDragonkai** [comment]
See https://github.com/libp2p/go-libp2p/issues/175

**Comment by diasdavid** [comment]
@TheCodeBuccaneer new docs should help, see: https://github.com/libp2p/go-libp2p/blob/e7293cb509995b7154ad879f2a2100df81dad12b/README.md
