### ISSUE TITLE
Resource manager's InfiniteLimits are not infinite

### ISSUE THREAD

**Issue by SaveTheRbtz** [libp2p/go-libp2p#1721]
cc: @MarcoPolo

When using Resource manager with `InfiniteLimits` via:
```
rcmgr.NewResourceManager(rcmgr.NewFixedLimiter(rcmgr.InfiniteLimits))
```
We still seeing connections failing with `ErrResourceLimitExceeded`, likely due to the numeric overflow in [checkMemory](https://github.com/libp2p/go-libp2p/blob/master/p2p/host/resource-manager/scope.go#L83)

PS. While here it would be nice to have unittest for the `InfiniteLimits`.

**Comment by MarcoPolo** [comment]
Thanks for debugging this! I'm pretty sure the culprit is here: https://github.com/libp2p/go-libp2p/blob/master/p2p/host/resource-manager/scope.go#L87

> PS. While here it would be nice to have unittest for the InfiniteLimits.

Agreed, want to take a stab at it?

**Comment by SaveTheRbtz** [comment]
Fair enough!  I'm not the best coder but I'll try.
