### ISSUE TITLE
Provide mechanism for learning the 5 tuple of a libp2p connection

### ISSUE THREAD

**Issue by willscott** [libp2p/go-libp2p#1735]
Currently, libp2p exposes connections via the [`network.Conn`](https://github.com/libp2p/go-libp2p/blob/master/core/network/conn.go#L18) interface.

This interface allows for identification of the local and remote Multiaddr's associated with the connection, but neither the multiaddr/net package, nor any semantic description provides a way to identify the ip's and ports being used for the connection.

If a user wants to interact with firewall or system level rate limiting, they need some way to extract the ports being used for connections, and it doesn't seem like there's a helper function supporting those forms of interaction.

**Comment by willscott** [comment]
In particular, there is a [`ToNetAddr`](https://github.com/multiformats/go-multiaddr/blob/master/net/convert.go#L38) that extracts the ip addresses of multiaddrs, but there's no equivalent way generally to learn the ports.

beyond that, some protocols, like i believe [websocket](https://github.com/libp2p/go-libp2p/blob/master/p2p/transport/websocket/listener.go#L126), will return the dns name they are listening on rather than the local interface - meaning one cannot use the interface to learn the local net host and port bound for such connections.

**Comment by marten-seemann** [comment]
Can you just parse the multiaddr for the TCP / UDP component? We can’t have a function that _just_ returns the port, you still need to know if it’s a TCP or UDP port.

**Comment by Stebalien** [comment]
`ToNetAddr` will return a full `net.Addr` which can be cast to a `*net.UDPAddr` or a `*net.TCPAddr`.

**Comment by marten-seemann** [comment]
Thanks @Stebalien, I completely missed that the net.Addr contains ports.

**Comment by willscott** [comment]
I did as well 😅 

One thing I am found unclear from docs here was whether the local multiaddr on a connection was guaranteed to be the local interface address and port that was bound, or if it might be the multiaddr that was asked to be bound - which would be e.g. a dns4 address in cases like web sockets.

I'm assuming now that for a connection the localmultiaddr is being-recalculated from the inbound net.Conn and won't retain that dns named state.
