### ISSUE TITLE
Can I install go-libp2p using gx?

### ISSUE THREAD

**Issue by duomoney** [libp2p/go-libp2p#174]
The install instructions in the readme do not mention gx.

**Comment by hsanjuan** [comment]
instructions say `make` and Makefile is https://github.com/libp2p/go-libp2p/blob/master/Makefile .

So the answer is yes. Would you like to improve the README though? Contribs always welcome :)

**Comment by CMCDragonkai** [comment]
For gx installation to work without using `go get` at all, this issue would need to be fixed first: https://github.com/libp2p/go-libp2p/issues/175

**Comment by diasdavid** [comment]
When running `make deps`, go-libp2p-swarm doesn't get installed in my `$GOPATH/src/libp2p` (or `$GOPATH/src/ipfs`)??

**Comment by hsanjuan** [comment]
@diasdavid gets fetched with gx, so it's somewhere in `src/gx/.../` isn't it?

**Comment by Stebalien** [comment]
The readme now explains how to set everything up with gx so this should be solved.
