### ISSUE TITLE
Extract the basic host into its own repo

### ISSUE THREAD

**Issue by JustinDrake** [libp2p/go-libp2p#175]
I find myself pulling the whole of `go-libp2p` just to use `p2p/host/basic`. Maybe this package can be extracted into a separate repo?

**Comment by CMCDragonkai** [comment]
I was wondering why is this isn't sufficient:

```
git clone https://github.com/libp2p/go-libp2p.git
cd go-libp2p
make
make deps
go build ./examples/echo
```

Why is it that we must install this package using `get -d github.com/libp2p/go-libp2p`, just so it can find a dependency that already exists locally inside this repository.

**Comment by whyrusleeping** [comment]
@CMCDragonkai your issue is that you arent initially cloning the repo into your GOPATH so the libp2p packages cant find their other sibling packages

**Comment by Stebalien** [comment]
This question looks answered. I'm going to close it as inactive, feel free to re-open if you disagree.

**Comment by Kubuxu** [comment]
@Stebalien what about this question:
> I find myself pulling the whole of go-libp2p just to use p2p/host/basic. Maybe this package can be extracted into a separate repo?

**Comment by Stebalien** [comment]
I.. Uh.. (read the wrong question).

**Comment by Stebalien** [comment]
Using go-libp2p without this repo isn't something we're going to support We have `go-libp2p-core` for those that only want to use the components, but then they're expected to use the "blank" host: https://github.com/libp2p/go-libp2p-blankhost
