### ISSUE TITLE
Muxer selection in TLS handshake

### ISSUE THREAD

**Issue by julian88110** [libp2p/go-libp2p#1751]
This enhancement is the go/TLS implementation of the [spec#446](https://github.com/libp2p/specs/pull/446);  which is tracked by [#426](https://github.com/libp2p/specs/issues/426). 

The core idea is to perform muxer selection in the security protocol handshake process, rather than selecting muxer in a separate multistream-selection round. 

In order to implement this enhancement, I am planning to do the following: 
 1. Extend the [ConnSecurity](https://github.com/libp2p/go-libp2p/blob/master/core/network/conn.go#L39)  interface by adding a method for retrieving early data negotiated by the security protocol. This interface is implemented by several security  layer data types, including TLS, Noise, and Insecure.
 
```
    type ConnSecurity interface {
	// LocalPeer returns our peer ID
	LocalPeer() peer.ID

    type ConnSecurity interface {
	// LocalPeer returns our peer ID
	LocalPeer() peer.ID

	// LocalPrivateKey returns our private key
	LocalPrivateKey() ic.PrivKey

	// RemotePeer returns the peer ID of the remote peer.
	RemotePeer() peer.ID

	// RemotePublicKey returns the public key of the remote peer.
	RemotePublicKey() ic.PubKey

	**// Early data negotiated by the security protocol. Empty if not supported.
	EarlyData() string**
}
```
 2. Extend the Transport data type of multistream-muxer and add method to expose the muxer strings that are stored [here](https://github.com/libp2p/go-libp2p/blob/master/p2p/muxer/muxer-multistream/multistream.go#L24). 
 3. Introduce some coupling between the Multistream-muxer and security layer in the [upgrader-code](https://github.com/libp2p/go-libp2p/blob/master/p2p/net/upgrader/upgrader.go#L190), to pass the supported muxers into security protocols.
 4. After security handshake is down, the early data result will be available by the method added in step 1. 
 5. Upgrader logic is revised to use the early data, if available, to select muxer.

**Comment by marten-seemann** [comment]
Thank you for writing this up @julian88110! This sounds like a good plan.

I'm wondering if instead of an `EarlyData` method we should instead expose a `ConnectionState`, similar to what the `tls.Conn` in the standard library exposes: https://pkg.go.dev/crypto/tls#Conn.ConnectionState. One of the fields (and the only one for now) would of the returned `ConnectionState` struct would be `NegotiatedProtocol string`, but this would allow us to add more fields in the future.

**Comment by julian88110** [comment]
The ConnectionState idea is a good point, it makes it easier to extend. Yes we can definitely adopt this approach. Thanks for bringing that up!

**Comment by BigLep** [comment]
@julian88110 : if there are updates/changes to the plan in light of 2022-09-19 conversations, please update. here (or in the libp2p/specs issue if that makes more sense).

**Comment by julian88110** [comment]
@BigLep yes, the discussion results are posted in the spec issue [#454](https://github.com/libp2p/specs/issues/454).

**Comment by marten-seemann** [comment]
Discussed with @julian88110 yesterday: We target completion of this for the v0.24 release.
We'll merge #1772 as soon as it's ready (which is very soon), with the expectation that doing the equivalent change for Noise is feasible before we cut that release.

Done criteria:
* [ ] early muxer selection when using TLS (#1772)
* [ ] early muxer selection when using Noise
* [ ] double check that the [Testground cross-version test](https://github.com/libp2p/test-plans/blob/master/ping/_compositions/go-cross-versions.toml) hits these new code paths

**Comment by p-shahi** [comment]
Closed by https://github.com/libp2p/go-libp2p/pull/1772
