### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by 20zinnm** [libp2p/go-libp2p#177]
https://libp2p.io/ currently has a bad DNS record. Is the site under construction or down?

**Comment by lgierth** [comment]
Yes its A/AAAA records are gone -- @victorbjelkholm know something abut this?

**Comment by lgierth** [comment]
Apart from that, yes the site has been under construction and so far has only been a rough early work in progress.

**Comment by VictorBjelkholm** [comment]
Hm, weird. @lgierth no, I've been playing around with beta.libp2p.io only, not the main one. AFAIK, the main libp2p.io was pointing to a built version of the specs, QmVZ3hMx892KaQTNaa15E89VToRHWpdUzBX3zd41vjy5eu, from https://github.com/libp2p/website/blob/old-master/ipscend.json#L4

**Comment by VictorBjelkholm** [comment]
Wait, I was confused. I don't remember libp2p.io ever working, I don't think we ever had something there. I was confusing it with the IPLD website.

**Comment by lgierth** [comment]
Aaah yeah! We have multiformats.io and ipld.io, but never had libp2p.io up.

@20zinnm there's gonna be a proper libp2p.io website soon!
