### ISSUE TITLE
Single config codepath for ressource manager

### ISSUE THREAD

**Issue by Jorropo** [libp2p/go-libp2p#1783]
Right now the decode config helpers for ressource manager is two different codepaths.
Either autoscaling or fixed limit.

For kubo we would like to have a simple single codepaths, that would return either option (or merge the two options whatever).

**Comment by marten-seemann** [comment]
Not sure what you mean by different codepaths? Can you please clarify, ideally with function names / links to the code?

**Comment by Jorropo** [comment]
Nvm after discussing with @ajnavarro this isn't the best thing to do, it would require to force JSON on everyone most likely.
