### ISSUE TITLE
TestReuseGarbageCollect is flaky

### ISSUE THREAD

**Issue by julian88110** [libp2p/go-libp2p#1787]
Sometimes fails on Windows platform.  (go 1.18.x)

  === RUN   TestReuseGarbageCollect
      reuse_test.go:174: 
          	Error Trace:	D:\a\go-libp2p\go-libp2p\p2p\transport\quic\reuse_test.go:174
          	Error:      	Condition never satisfied
          	Test:       	TestReuseGarbageCollect
  --- FAIL: TestReuseGarbageCollect (0.55s)

<details>
<summary>Version Information</summary>
v0.23.2 
<pre>

</pre>
</details>

**Comment by marten-seemann** [comment]
Duplicate of #1682.
