### ISSUE TITLE
example/echo docs improvement re securing identity

### ISSUE THREAD

**Issue by zippy** [libp2p/go-libp2p#179]
When I follow the instructions in examples/echo/README I see warnings about identity (see below).  It would be very useful for this to be documented, and then the additional steps needed to securing the connection be added in.

> ./echo -d /ip4/127.0.0.1/tcp/1235/ipfs/QmNtX1cvrm2K6mQmMEaMxAuB4rTexhd87vpYVot4sEZzxc -l 1236
> 12:40:57.969 WARNI     swarm2: Listener not given PrivateKey, so WILL NOT SECURE conns. swarm_listen.go:83
> 2017/02/21 12:40:57 I am /ip4/127.0.0.1/tcp/1236/ipfs/QmVvtzcZgCkMnSFf2dnrBPXrWuNFWNM9J3MpZQCvWPuVZf
> 2017/02/21 12:40:57 opening stream
> 12:40:57.971 WARNI       conn: dialer %s dialing INSECURELY %s at %s!<Dialer <peer.ID VvtzcZ> ...><peer.ID NtX1cv>/ip4/127.0.0.1/tcp/1235 dial.go:138
> 12:40:57.972 ERROR net/identi: did not have own public key in Peerstore id.go:177
> 2017/02/21 12:40:57 read reply: "Hello, world!"

**Comment by hsanjuan** [comment]
You can call `./echo` with `-secio` (as shown with `-help`) and then it will use randomly generated keys to encrypt the channel. Would you like to make a PR against the README telling about this in a way you would understand?
