### ISSUE TITLE
Flaky: windows go test 1.19 runs out of memory when building peerstore code

### ISSUE THREAD

**Issue by julian88110** [libp2p/go-libp2p#1805]
go build github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoreds: C:\hostedtoolcache\windows\go\1.19.1\x64\pkg\tool\windows_amd64\cover.exe: fork/exec C:\hostedtoolcache\windows\go\1.19.1\x64\pkg\tool\windows_amd64\cover.exe: Not enough memory resources are available to process this command.
  C:\hostedtoolcache\windows\go\1.19.1\x64\pkg\tool\windows_amd64\vet.exe: fork/exec C:\hostedtoolcache\windows\go\1.19.1\x64\pkg\tool\windows_amd64\vet.exe: Insufficient system resources exist to complete the requested service.
  go build github.com/dgraph-io/badger/options: C:\hostedtoolcache\windows\go\1.19.1\x64\pkg\tool\windows_amd64\compile.exe: fork/exec C:\hostedtoolcache\windows\go\1.19.1\x64\pkg\tool\windows_amd64\compile.exe: Insufficient system resources exist to complete the requested service.
  go build github.com/dgraph-io/badger/pb: C:\hostedtoolcache\windows\go\1.19.1\x64\pkg\tool\windows_amd64\compile.exe: fork/exec C:\hostedtoolcache\windows\go\1.19.1\x64\pkg\tool\windows_amd64\compile.exe: Insufficient system resources exist to complete the requested service.
  go build golang.org/x/net/internal/timeseries: C:\hostedtoolcache\windows\go\1.19.1\x64\pkg\tool\windows_amd64\compile.exe: fork/exec C:\hostedtoolcache\windows\go\1.19.1\x64\pkg\tool\windows_amd64\compile.exe: Insufficient system resources exist to complete the requested service.
  runtime: VirtualAlloc of 2097152 bytes failed with errno=1455
  fatal error: out of memory
  
  runtime stack:
  runtime.throw({0x9f6fff?, 0xc0033d5000?})
  	c:/go/src/runtime/panic.go:1047 +0x65 fp=0x7bc73ff660 sp=0x7bc73ff630 pc=0x3f8ba5
  runtime.sysUsedOS(0xc003392000, 0x200000)
  	c:/go/src/runtime/mem_windows.go:83 +0x1c9 fp=0x7bc73ff6c0 sp=0x7bc73ff660 pc=0x3d8d69
  runtime.sysUsed(0xe208a0?, 0x100?, 0xc00002600c?)
  	c:/go/src/runtime/mem.go:77 +0x25 fp=0x7bc73ff6e0 sp=0x7bc73ff6c0 pc=0x3d8865
  runtime.(*mheap).allocSpan(0xe208a0, 0x100, 0x0, 0x1)
  	c:/go/src/runtime/mheap.go:1333 +0x615 fp=0x7bc73ff778 sp=0x7bc73ff6e0 pc=0x3e92d5
  runtime.(*mheap).alloc.func1()
  	c:/go/src/runtime/mheap.go:910 +0x65 fp=0x7bc73ff7c0 sp=0x7bc73ff778 pc=0x3e88c5
  runtime.systemstack()
  	c:/go/src/runtime/asm_amd64.s:492 +0x4e fp=0x7bc73ff7c8 sp=0x7bc73ff7c0 pc=0x4244ce
  

<details>
Go 1.19 build on windows platform
<pre>

</pre>
</details>

**Comment by marten-seemann** [comment]
Haven't seen these in a while. There's also not a lot we can do, other than migrating to IPDX-provided Windows runners (once those become available).
