### ISSUE TITLE
C. 🧠 Smart Dialing

### ISSUE THREAD

**Issue by p-shahi** [libp2p/go-libp2p#1808]
eta: 2023-05-15

- [x] https://github.com/libp2p/go-libp2p/issues/1785
- [ ] docs: https://github.com/libp2p/docs/issues/215
- [x] revisit https://github.com/libp2p/go-libp2p/pull/1898

**Comment by marten-seemann** [comment]
@p-shahi Do we still need this issue? This is better tracked by #1605.
