### ISSUE TITLE
consider using BuildPulse to track our flaky tests

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1821]
I just stumbled upon [BuildPulse](https://buildpulse.io/). Apparently it can track flaky tests (by the individual test that's failing), and give us a list of top offenders. 

It needs to be integrated with CI as shown in this example diff: https://github.com/buildpulse/buildpulse-example-go/compare/pre-buildpulse...github-actions

### Integration with Unified CI

The only problem is that we'd have to replace the `go test` command in Unified CI. I believe that could be enabled by making a small change to Unified CI by introducing a `GOTEST` configuration (environment?) variable. It would default to `go test`, but here we could set it to `gotestsum --junitfile tmp/test-results/gotestsum-report.xml`.

### Pricing

The cost for the smallest plan is $99 / month, which gives us 250k test executions per day. One libp2p test run causes roughly 10'000 tests to be run (12 * 850). Probably enough on average, but might get tight on very busy days. The next biggest plan is $249 and include 1m tests.

### Risks

* test execution is done by [gotestsum](https://gotest.tools/gotestsum), which looks and feels a bit different from the normal `go test`. It invokes `go test` under the hood though.
* their GitHub Actions produces deprecation warnings. Not an immediate problem, but not a good first impression either
* the test reports are uploaded to their servers. As I've been joking after our experience with Codecov, uploading files from a CI run is one of the hard problems of computer science. We're adding another uploader here.

### Next steps

- [x] evaluate it in a branch
- [ ] if successful, propose the required generalization to Unified CI
- [ ] use the new config option in Unified CI to enable BuildPulse here
- [ ] profit

**Comment by marten-seemann** [comment]
#1822 is now uploading results to BuildPulse, and after restarting the test for a few times, we managed to get some failures recorded. The dashboard is available at https://buildpulse.io/@libp2p/go-libp2p. I believe that everyone in the libp2p team should have access.

@MarcoPolo @p-shahi @BigLep @julian88110, what do you guys think?

**Comment by marten-seemann** [comment]
So far, this is how the dashboard looks like after manually rerunning the test > 10 times to trigger some flakes:
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/1478487/195436992-2d16dbb6-5786-4811-bec6-fe8389f65833.png">

Apparently it's also possible to get some of our build matrix information (Go version and OS, and race detector on / off) into these results, but I'm not sure yet how that would look like. It would require some `sed`-ding of the generated XML files, until BuildPulse adds a feature so this would work out of the box.

**Comment by MarcoPolo** [comment]
Overall I'm all for offloading work on to other projects :)

However, one thing that I don't like is that I can't seem to extract this data out. And I think that would be useful for measuring our progress over time. And I want to be able to present our data in certain ways for all hands and such.

I'm also missing if this gives us anything [my notebook](https://marcopolo.github.io/FlakyTests/) doesn't already provide. Granted, the notebook could do a better job of rendering all the tests and sorting by last seen/disruptions like the above table. But, I bet I could build the above dashboard in an hour or two. 

> Apparently it's also possible to get some of our build matrix information (Go version and OS, and race detector on / off) into these results, but I'm not sure yet how that would look like. It would require some sed-ding of the generated XML files, until BuildPulse adds a feature so this would work out of the box.

This can be gathered from the filename of the log (the notebook can read this).

---

I want to reiterate that I would *love* to maintain fewer things, but I don't want to give up flexibility and features. The notebook has all this data, can be easily customized and modified, and runs automatically.

**Comment by galargh** [comment]
Thanks @MarcoPolo for pointing me at the discussion 🙇 At a first glance, I don't have anything to add beyond what you already mentioned. Fewer things to maintain, flexibility empowering us to do the work - both very important things to keep in mind when making this decision. 

If we had time, I'd also suggest trying to see what other tools out there might give us what we want. However I think experimentation might be the best way forward on this.

**Comment by MarcoPolo** [comment]
quick update: I spent 30 minutes and added:
* Sort by recency + count
* Expose all flaky tests not just the top 10 in the rendered html.
* Add a .devcontainer so you can get this up in running instantly (even in codespaces)

**Comment by marten-seemann** [comment]
@MarcoPolo Thanks for updating your notebook. I agree that we don't need BuildPulse, since your notebook provides all the information.

Can we add a link to your notebook to the README? I find myself coming back to this issue to find the link. Ideally using a badge that shows the flakiness score, but if that's too much work, a simple link would do as well.
