### ISSUE TITLE
Echo demo

### ISSUE THREAD

**Issue by clanstyles** [libp2p/go-libp2p#183]
I'm trying to run the demo. I have two terminals open.

first
```
go run main.go -l 2372
```

second
```
go run main.go -d /ip4/127.0.0.1/tcp/2372/ipfs/xxx -l 2312
```

the output of the second is:
```
2017/03/07 00:19:31 opening stream
2017/03/07 00:19:31 dial to self attempted
```

and it exists.

What's w/ the dial to self attempt?

**Comment by whyrusleeping** [comment]
@clanstyles interesting, same here. I'll investigate

**Comment by whyrusleeping** [comment]
Ah, for some reason both peers are generating the same peer ID

**Comment by whyrusleeping** [comment]
I see, odd that i never ran into this before... for the non-secio setup (the default) the global rand isnt seeded.

Let me push a fix real quick

**Comment by whyrusleeping** [comment]
There, latest master should work now. Let me know if that fixes the issue for you :)

**Comment by diasdavid** [comment]
@clanstyles did it work for you? Let us know if it didn't. Closing this issue for now :)
