### ISSUE TITLE
Create integration test for libp2p early muxer negotiation

### ISSUE THREAD

**Issue by julian88110** [libp2p/go-libp2p#1836]
The code changes that are specified in [#446] changes muxer negotiation behavior, an integration test plan should be put in  place to test the correct muxer negotiation behavior.

[#446]:  https://github.com/libp2p/specs/pull/446/files

**Comment by marten-seemann** [comment]
Specifically, we should test that if the client has muxer preference `a > b` and the server has muxer preference `b < a`, TLS, Noise and multistream negotiate the same muxer.
