### ISSUE TITLE
Cloudy QUIC code (Go switch/case chain processing is different to C switch/case)

### ISSUE THREAD

**Issue by p-kraszewski** [libp2p/go-libp2p#1844]
https://github.com/libp2p/go-libp2p/blob/7465a509d01195b38d00125814457d2b37d29fd0/p2p/transport/quic/transport.go#L375

## It is not an error report!

I've spotted unobvious fragment (at least for people from C world):

```go

		case <-timer.C:
		case <-ctx.Done():
			punchErr = ErrHolePunching
```

It does **not** behave like C counterpart (it catches me off-guard from time to time). I understand the flow, but it takes some time to get the intention.

A comment or explicit `continue` would help:

```go

		case <-timer.C:
			// retry on timeout
			continue loop

		case <-ctx.Done():
			punchErr = ErrHolePunching
			break loop
```

**Comment by marten-seemann** [comment]
Go is not C. (And that's a good thing!)

I don't think we need to point this out any time this happens.
We have dozens of `switch` / `select` cases like this all over our code base.

**Comment by p-shahi** [comment]
Closing this @p-kraszewski for reasons mentioned by Marten
