### ISSUE TITLE
connmgr: Concurrent Map Misuse

### ISSUE THREAD

**Issue by p-shahi** [libp2p/go-libp2p#1847]
## Description

Reported in: https://github.com/ipfs/kubo/issues/9374#issuecomment-1296416337

When running `Kubo 0.16.0` users report a crash.
There is a provided stacktrace: 

```
WebUI: http://127.0.0.1:5001/webui
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
fatal error: concurrent map iteration and map write

goroutine 222 [running]:
github.com/libp2p/go-libp2p/p2p/net/connmgr.peerInfos.SortByValueAndStreams.func1.1(0xc0179d00f0?)
        github.com/libp2p/go-libp2p@v0.23.2/p2p/net/connmgr/connmgr.go:267 +0x6a
github.com/libp2p/go-libp2p/p2p/net/connmgr.peerInfos.SortByValueAndStreams.func1(0x16b?, 0x21b?)
        github.com/libp2p/go-libp2p@v0.23.2/p2p/net/connmgr/connmgr.go:277 +0x127
sort.partition_func({0xc0119d9370?, 0xc003e967e0?}, 0x0, 0x2d4, 0x32?)
        sort/zsortfunc.go:157 +0x191
```

https://github.com/libp2p/go-libp2p/blob/master/p2p/net/connmgr/connmgr.go#L255

## Versions affected

`Kubo 0.16.0` uses `go-libp2p v0.23.2`
But this issue could have existed for some time.

## Root Cause Analysis
```
<Once determined, fill RCA here>
```

### Open Questions:
If it's valid that concurrent goroutines need to read `peerInfos` as it's being written to, shouldn't it be locked inside the sync read write mutex?
https://github.com/libp2p/go-libp2p/blob/7465a509d01195b38d00125814457d2b37d29fd0/p2p/net/connmgr/connmgr.go#L374-L377
https://github.com/libp2p/go-libp2p/blob/7465a509d01195b38d00125814457d2b37d29fd0/p2p/net/connmgr/connmgr.go#L405-L407
https://github.com/libp2p/go-libp2p/blob/7465a509d01195b38d00125814457d2b37d29fd0/p2p/net/connmgr/connmgr.go#L456-L468

**Comment by p-shahi** [comment]
Some more logs shared here: https://github.com/ipfs/kubo/issues/9374#issuecomment-1306547871

@julian88110 @MarcoPolo would either of you like to take a look?
If the Kubo team wants this in 0.17.0 (https://github.com/ipfs/kubo/issues/9319#issuecomment-1305649994) we may need to do another patch release

**Comment by julian88110** [comment]
taking a look.

**Comment by BigLep** [comment]
Thanks @p-shahi being on top of this.  We would like to get this in [the next (0.17) Kubo release](https://github.com/ipfs/kubo/issues/9319).  The RC is on Thursday, 2022-11-10.  A patch here could come after the RC but before the final release on 2022-11-17.

**Comment by MarcoPolo** [comment]
Let's sync up @julian88110 I started this earlier today.

**Comment by MarcoPolo** [comment]
Synced up. I'll take.
