### ISSUE TITLE
Remove multistream.transport as an entity of type network.multiplexer

### ISSUE THREAD

**Issue by julian88110** [libp2p/go-libp2p#1854]
In the process of building the integration test for early muxer negotiation https://github.com/libp2p/go-libp2p/issues/1836, this enhancement came into being as suggested by @marten-seemann  while we discussed the options of making the implementation of #1851 cleaner. 

The existence of multistream.transport as a network.multiplexer type becomes an obvious obstacle of sharing muxer state info internally, especially in the concurrent context which may require locking to avoid data race. 

This issue ticket proposes to get rid of the multistream.transport entity and merge its function into the upgrader.  This solution may require fair amount of refactoring of the config and initialization code too, a lot of test code will also be affected, but in long term it should be worth the effort for simplified upgrade logic and cleaner code structure. There is no reason the multistream.transport should be a network.Transport type and be restricted to that interface, which becomes awkward in facilitating new features such as early muxer negotiation.

**Comment by BigLep** [comment]
@julian88110 : lets reference https://github.com/libp2p/go-libp2p/pull/1851#issuecomment-1302450166 in the description.

**Comment by julian88110** [comment]
> @julian88110 : lets reference [#1851 (comment)](https://github.com/libp2p/go-libp2p/pull/1851#issuecomment-1302450166) in the description.
Good point. updated the description.
