### ISSUE TITLE
autorelay: refactor `libp2p.EnableAutoRelay` option

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/go-libp2p#1866]
We should split the function into two options, one that _requires_ a list of static relays and one that _requires_ a peer source. Having options, some of which are required, is not a nice API pattern.

_Originally posted by @marten-seemann in https://github.com/libp2p/go-libp2p/issues/1852#issuecomment-1307995595_

**Comment by marten-seemann** [comment]
Suggestion: `libp2p.EnableAutoRelayWithStaticRelays([]peer.AddrInfo)` and `libp2p.EnableAutoRelayWithAutoDiscovery(func(ctx context.Context, num int) <-chan peer.AddrInfo)`?

I'd be grateful for better naming suggestions :)

**Comment by p-shahi** [comment]
@sukunrt Flagging this for you in case you are interested in taking on more issues. Thanks for all the great contributions up till now, no pressure to take this up however :pray:

**Comment by sukunrt** [comment]
sure! I'd love to!

**Comment by sukunrt** [comment]
As I understand. 

We want two new functions to configure autorelay
```
libp2p.EnableAutoRelayWithStaticRelays([]peer.AddrInfo, opts ...autorelay.Option)
libp2p.EnableAutoRelayWithPeerSource(func(ctx context.Context, numPeers int) <-chan peer.AddrInfo, opts ...autorelay.Option)
```

We would need to add the second options parameter because otherwise there would be no way of providing options like WithCircuitV1Support()

In EnableAutoRelayWithPeerSource there is a configurable mininterval for callbacks which is set to 30 seconds for static relays. Should I allow for setting this minInterval too and make the function:

```
libp2p.EnableAutoRelayWithPeerSource(func(ctx context.Context, numPeers int) <-chan peer.AddrInfo, minInterval time.Duration, opts ...autorelay.Option)
```

What should I do with the old function libp2p.EnableAutoRelay? Deprecate it or remove it?

**Comment by marten-seemann** [comment]
> We want two new functions to configure autorelay
> 
> ```
> libp2p.EnableAutoRelayWithStaticRelays([]peer.AddrInfo, opts ...autorelay.Option)
> libp2p.EnableAutoRelayWithPeerSource(func(ctx context.Context, numPeers int) <-chan peer.AddrInfo, opts ...autorelay.Option)
> ```

That's correct.



> In autorelay.WithPeerSource there is a configurable mininterval for callbacks which is set to 30 seconds in autorelay.WithStaticRelays. Should I allow for setting this minInterval too and make the function:
> 
> ```
> libp2p.EnableAutoRelayWithPeerSource(func(ctx context.Context, numPeers int) <-chan peer.AddrInfo, minInterval time.Duration, opts ...autorelay.Option)
> ```

I'd prefer to have this as a `autorelay.Option`.

> What should I do with the old function libp2p.EnableAutoRelay? Deprecate it or remove it?

If it's not too much of a hassle to keep it around (as a deprecated function), I'd say let's just deprecate it. That will make the upgrade process smoother for our users.

**Comment by sukunrt** [comment]
Can I change autorelay.WithPeerSource from 

```
func WithPeerSource(f func(ctx context.Context, numPeers int) <-chan peer.AddrInfo, minInterval time.Duration) Option 
```
to 

```
func WithPeerSource(f func(ctx context.Context, numPeers int) <-chan peer.AddrInfo) Option 
```

and set a default minInterval with autorelay.defaultConfig
