### ISSUE TITLE
security protocol ordering preference broken

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1906]
Since fx groups don't provide ordering (see https://pkg.go.dev/go.uber.org/fx#hdr-Value_Groups), we end up not adhering to the ordering of the configured security protocols.

We need to:
- [x] fix this bug
- [x] add an integration test

This is a blocker for the v0.24.0 release.

**Comment by vyzo** [comment]
fx.... lol.

**Comment by marten-seemann** [comment]
@vyzo Enjoy your told-you-so moment.

The fact that we didn't have any tests for security protocol selection is the real culprit here, as I see it.

**Comment by vyzo** [comment]
it was a small triumph :)
