### ISSUE TITLE
github.com/libp2p/go-libp2p-core/peer.IDB58Encode

### ISSUE THREAD

**Issue by chengwds** [libp2p/go-libp2p#1920]
// Deprecated: use github.com/libp2p/go-libp2p-core/peer.IDB58Decode instead.
func IDB58Decode(s string) (core.ID, error) {
	return core.IDB58Decode(s)
}

**Comment by chengwds** [comment]
peer.IDB58Decode 用什么代替
peer.IDB58Decode What to replace

**Comment by chengwds** [comment]
？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by chengwds** [comment]
peer.IDB58Decode    Many source codes use this

**Comment by p-shahi** [comment]
What is your question?

**Comment by chengwds** [comment]
peer.IDB58Decode   out of commission

**Comment by chengwds** [comment]
This is used by many online source codes    peer.IDB58Decode ，   Waste a lot of time, find the reason

**Comment by chengwds** [comment]
I am a beginner and have no basic knowledge. I am very interested in studying this and finally found it in the source code   replace    peer.Decode()

**Comment by chengwds** [comment]
https://mycoralhealth.medium.com/code-a-simple-p2p-blockchain-in-go-46662601f417

**Comment by chengwds** [comment]
Many of them are wrong, and it is difficult to solve dependence
