### ISSUE TITLE
KCP transport (reliable UDP)

### ISSUE THREAD

**Issue by ghost** [libp2p/go-libp2p#193]
Let's check it out:

https://github.com/xtaci/kcp-go

> **kcp-go** is a **Production-Grade Reliable-UDP** library for [golang](https://golang.org/). 
>
> It provides **fast, ordered and error-checked** delivery of streams over **UDP** packets, has been well tested with opensource project [kcptun](https://github.com/xtaci/kcptun). Millions of devices(from low-end MIPS routers to high-end servers) are running with **kcp-go** at present, including applications like **online games, live broadcasting, file synchronization and network acceleration**.

> 1. Optimized for **Realtime Multiplayer Games, Audio/Video Streaming**.
> 1. Compatible with [skywind3000's](https://github.com/skywind3000) C version with language specific optimizations.
> 1. **Cache friendly** and **Memory optimized** design, offers extremely **High Performance** core.
> 1. Compatible with [net.Conn](https://golang.org/pkg/net/#Conn) and [net.Listener](https://golang.org/pkg/net/#Listener), easy to use.
> 1. [FEC(Forward Error Correction)](https://en.wikipedia.org/wiki/Forward_error_correction) Support with [Reed-Solomon Codes](https://en.wikipedia.org/wiki/Reed%E2%80%93Solomon_error_correction)
> 1. Packet level encryption support with [AES](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard), [TEA](https://en.wikipedia.org/wiki/Tiny_Encryption_Algorithm), [3DES](https://en.wikipedia.org/wiki/Triple_DES), [Blowfish](https://en.wikipedia.org/wiki/Blowfish_(cipher)), [Cast5](https://en.wikipedia.org/wiki/CAST-128), [Salsa20]( https://en.wikipedia.org/wiki/Salsa20), etc. in [CFB](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_Feedback_.28CFB.29) mode.
> 1. **O(1) goroutines** created for the entire server application, minimized goroutine context switch.

It's used by Lantern and Syncthing among others

**Comment by whyrusleeping** [comment]
Yeah, i'd love to try this out. Should be fairly simple to plug it in

**Comment by whyrusleeping** [comment]
They also have a multiplexer: https://github.com/xtaci/smux

**Comment by whyrusleeping** [comment]
Easy enough to plug the muxer in, it passes our test suite too: https://github.com/whyrusleeping/go-smux-smux

**Comment by whyrusleeping** [comment]
Only rough part of plugging kcp in seems to be that their `net.Addr` method isnt quite compliant, it just returns a udp addr. So i may have to fork it and change that

**Comment by diasdavid** [comment]
Oh wow, this looks sweet! https://github.com/xtaci/smux. I like this team, they modularize things!

**Comment by Stebalien** [comment]
Ooh nice! Personally, I wouldn't bother with KCP given that QUIC is around the corner (unless QUIC doesn't work out) but their SMUX library looks great and can be used over TCP.

**Comment by paralin** [comment]
I have implemented an initial version of a KCP transport, looking for comment.

 https://github.com/paralin/go-libp2p-kcp

Not tested yet.

**Comment by paralin** [comment]
I have finished my KCP transport implementation, it uses smux to basically build a mock-tcp connection. From my initial tests with even the default configs the performance is quite impressive.

https://github.com/paralin/go-libp2p-kcp

I replicated the echo example, with GRPC over the connection as a bonus (so, UDP[KCP[SMUX[GRPC]]]`).

**Comment by whyrusleeping** [comment]
@paralin Hey! Great work there. A couple things:

- Not sure why the smux package is used in the transport itself, we can have that separately as a muxer package. KCP is reliable on its own, right?
- It would be really great to be able to dial out using the same socket we listen on. This would save a ton of file descriptors. As implemented, each dial would create a new socket. Not sure if kcp lets us do this, but we were able to with utp
- We should start looking at using plugins to add transports to libp2p without having to rebuild ipfs.

**Comment by paralin** [comment]
@whyrusleeping Not sure why, but without smux in place libp2p wouldn't work at all over KCP. I suspected it was because: "Control messages like SYN/FIN/RST in TCP are not defined in KCP, you need some keepalive/heartbeat mechanism in the application-level." For this reason I believe we need some kind of SYN/ACK in the transport level, although we really shouldn't need it. I just haven't had a chance yet to write any tests to figure out the issue.

We can pass a PacketConn to KCP, so establishing a socket dialing out with SO_REUSE should be fine.

In terms of plugins this should be easy with the existing interfaces and the Go plugin mechanism.

**Comment by whyrusleeping** [comment]
Interesting... I'll bet it's something like "the other side doesn't get the
connection until we send a packet". If you could investigate that further
it would be really helpful.

On the plugins, if we get that working, then we can also add tor and webrtc
transports :)

**Comment by whyrusleeping** [comment]
@paralin Do you think you could take a look at adding a `Libp2pTransportPlugin` to ipfs? 

Right now we just have `IpldPlugin`s: https://github.com/ipfs/go-ipfs/blob/master/plugin/loader/initializer.go#L21
But we're working on adding a new set of plugins for turning logs into execution traces: https://github.com/ipfs/go-ipfs/pull/4506

The tricky part here is that we would likely have to have some global `DefaultTransports` array in libp2p that the plugin would append to, then the libp2p constructor would need to use those.

If you don't have time or don't want to, no worries, I figured I would ask here anyways, and someone else could pick it up :)

**Comment by paralin** [comment]
I'd be happy to, but I'm a bit busy at the moment so it'll be a little while.

**Comment by paralin** [comment]
@whyrusleeping Please have a look at https://github.com/paralin/go-libp2p-kcp/issues/1 re/KCP integration with reusable UDP file descriptors (assuming the CC didn't send you a notification).

**Comment by Stebalien** [comment]
(QUIC has shipped)
