### ISSUE TITLE
Proposal: consider conventional commits + squash merge for go-libp2p

### ISSUE THREAD

**Issue by p-shahi** [libp2p/go-libp2p#1931]
### Proposal

Consider using conventional commits: https://www.conventionalcommits.org/en/v1.0.0/#summary and squash merging PRs for go-libp2p

### Motivation
Both of these improve commit history quality:

* Commit messages formatted with "feat", "fix", "chore", "docs", etc make it easier for maintainers, contributors/users to wade through the commit history. They tell what the commit was related to at a glance. This can augment the current style where the core component is prepended to the commit messages and give additional context.
  * We already do this in some cases see: https://github.com/libp2p/go-libp2p/pull/1875
  * Can enable use to use Release please (like rust-libp2p) https://github.com/googleapis/release-please
* Squash merging will help tidy up the commit history. 
  * this can be done by doing "squash and merge" through the GitHub UI
  * When diffing two branches/tags here: https://github.com/libp2p/go-libp2p/compare/v0.23.4...master it makes it easier to read. Good article here: https://blog.dnsimple.com/2019/01/two-years-of-squash-merge/
* Help automate 

### References
* Conventional commits
  * Both rust-libp2p (https://github.com/libp2p/rust-libp2p/issues/3054) and js-libp2p use this. Providing us added motivation to adopt this.

Thoughts: @MarcoPolo @marten-seemann

**Comment by MarcoPolo** [comment]
I think this is a good idea. 

We already use squash merges, but it would be great to enforce this.

For conventional commits, I would love to see this. Especially the tooling that can give folks context whether something is a breaking api change or not at a glance.

**Comment by MarcoPolo** [comment]
When https://github.com/libp2p/github-mgmt/issues/81 is closed, I suggest we try this for a bit. If we can enforce having the component name in there as well that would be a nice bonus.

**Comment by p-shahi** [comment]
Here's the PR to enforce conventional commits in go-libp2p: https://github.com/libp2p/github-mgmt/pull/125

I suggest we enable this after 0.26.0

@marten-seemann are you open to trying it out?

**Comment by p-shahi** [comment]
Closing per: https://github.com/libp2p/github-mgmt/pull/125#discussion_r1119378423
