### ISSUE TITLE
Enable specifying infinite limits with a more "intuitive" magic number like -1

### ISSUE THREAD

**Issue by BigLep** [libp2p/go-libp2p#1935]
I know programmatically one can use [inifiteLimits](https://github.com/libp2p/go-libp2p/blob/9fad5b06dde6438feaf82f626a4e47e7f5695c58/p2p/host/resource-manager/limit_defaults.go#L532).  In the Kubo case where users are defining their limits via config/JSON, it would be useful to have another value that denotes infinity like "-1".  Certainly Kubo can create its own infinity value but we'd need to do the conversion when setting up the resource manager and reading limits back out from it.  I assume this will be pretty common for other applications building on top of go-libp2p which is what I'm proposing putting it into go-libp2p itself. 

Context: this came as part of handling user reports after enabling the resource manager by default in Kubo: https://github.com/ipfs/kubo/issues/9442

**Comment by marten-seemann** [comment]
This should be covered by #2000. The magic number is not -1, but "unlimited" (in the JSON serialization).
