### ISSUE TITLE
Allow Listening on a Public Address for a libp2p Host

### ISSUE THREAD

**Issue by daryakaviani** [libp2p/go-libp2p#1939]
Per a conversation with @marten-seemann, libp2p hosts should be updated to facilitate listening on a public IP address. Currently, I am configuring a libp2p host as a server and another as a listener, with the intention to perform TCP between them.

I am passing the following options into the listener libp2p host instance:

```
[]libp2p.Option{
	identity,
	libp2p.AddrsFactory(func(m []multiaddr.Multiaddr) []multiaddr.Multiaddr {
		return multiaddr.FilterAddrs(m, manet.IsPublicAddr)
	}),
	libp2p.Transport(tcp.NewTCPTransport),
	libp2p.ListenAddrStrings(fmt.Sprintf("/ip4/%s/tcp/%d", publicIP, portNumber)),
	libp2p.ForceReachabilityPrivate(),
	libp2p.EnableAutoRelay(),
	libp2p.StaticRelays([]peer.AddrInfo{serverAddrInfo}),
	libp2p.EnableHolePunching(),
}
```

However, upon attempting to connect to the server host, I am met with the following error:
```
2022-12-08T03:12:33.367Z	DEBUG	p2p-holepunch	holepunch/svc.go:95	waiting until we have at least one public addresspeer12D3KooWERzr6bH4vHqc89JuEeWnQcE1vkEA6PdnrexvNXZqtJ8Y
2022/12/08 03:12:33 Error creating host: failed to listen on any addresses: [listen tcp4 54.176.166.203:1090: bind: cannot assign requested address]
```
It seems that it is not possible for `ListenAddrStrings` to take in a non-zero public address for the host to listen on. Would appreciate if this could be updated!

cc @marten-seemann

**Comment by marten-seemann** [comment]
So, after thinking about this for a bit more, I think I got this wrong yesterday. The node doesn't own the public IP (the NAT does), so it can't listen on it.

The problem we're running into here is that the hole puncher service waits until it the node has discovered (via the Identify protocol) some public addresses: https://github.com/libp2p/go-libp2p/blob/2c82176c35be49a887482382c2056a27a727c7d3/p2p/protocol/holepunch/svc.go#L93-L107

This is fine if the node is establishing a lot of connections to other nodes, as it will quickly learn its public addresses. It doesn't work in your use case, as your node is not doing that.

The "correct" solution would probably be to use a `NATManager`, but I checked and that doesn't work with the hole puncher. We'll need to rework address management at some point...

To solve your problem, @daryakaviani, I confirmed that the following is working
```go
func main() {
	identify.ActivationThresh = 0
	h, err := libp2p.New(
		libp2p.ListenAddrStrings("/ip4/0.0.0.0/tcp/1234"),
		libp2p.Transport(tcp.NewTCPTransport),
		libp2p.ForceReachabilityPrivate(),
		libp2p.EnableHolePunching(),
	)
	if err != nil {
		log.Fatal(err)
	}

	// an IPFS bootstrap node
	ai, err := peer.AddrInfoFromString("/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ")
	if err != nil {
		log.Fatal(err)
	}
	if err := h.Connect(context.Background(), *ai); err != nil {
		log.Fatal(err)
	}

       select {}
}
```

The crucial part here is `identify.ActivationThresh = 0`, telling the node to accept any address learned via the Identify protocol as a public address, even if it was just reported to you by a single node. In a p2p setting, trusting a single node is obviously not a good idea, but since you trust your orchestrator node, it works.

Instead of connecting to an IPFS bootstrap node, you could also connect to your orchestrator node to learn the public node, replacing the first step in your setup where you establish a raw (non-libp2p) TCP connection.

Does this work for you?

**Comment by daryakaviani** [comment]
@marten-seemann Thanks for the quick turnaround. Hm, it seems to have fixed the issue for connecting with the orchestrator server host, but I'm wondering if this configuration poses a problem when trying to create streams between the client hosts.

I used my orchestrator node's libp2p host to create a DHT. Next, I created two client hosts: one dialer and one listener. I then attempted to form a TCP stream between them, but I'm getting an I/O timeout.

Output from orchestrator server host (works):
```
2022/12/09 09:16:48 Server ID: 12D3KooWBk4p8n6vWfRn3hWzXHPbor61TzLDskBeSd5c8anwWtVr
2022-12-09T09:16:48.139Z        DEBUG   p2p-holepunch   holepunch/svc.go:95     waiting until we have at least one public addresspeer12D3KooWDYhonMhW4t3be6PKMLgRmp7U1RYc59nvxsE9V1ASrV6B
2022/12/09 09:16:48 Host ID: 12D3KooWDYhonMhW4t3be6PKMLgRmp7U1RYc59nvxsE9V1ASrV6B
2022/12/09 09:16:48 Server ready.
2022-12-09T09:19:30.965Z        DEBUG   p2p-holepunch   holepunch/svc.go:107    Host now has a public address. Starting holepunch protocol.
```

Output from listener host:
```
2022/12/09 09:19:26 Created host with ID 12D3KooWKujiFnDTroimQWtQckXotMM1SC6eaLCWs6AUsEH5V2aw...
2022/12/09 09:19:26 Connecting to server {12D3KooWDYhonMhW4t3be6PKMLgRmp7U1RYc59nvxsE9V1ASrV6B: [/ip4/3.101.133.148/tcp/1234]}...
2022-12-09T09:19:26.435Z	DEBUG	p2p-holepunch	holepunch/svc.go:95	waiting until we have at least one public addresspeer12D3KooWKujiFnDTroimQWtQckXotMM1SC6eaLCWs6AUsEH5V2aw
2022/12/09 09:19:26 Connected to server.
2022-12-09T09:19:26.733Z	DEBUG	p2p-holepunch	holepunch/svc.go:107	Host now has a public address. Starting holepunch protocol.
2022/12/09 09:19:29 Advertising to DHT...
2022/12/09 09:19:29 Advertised to DHT.
```

Output from dialer host:
```
2022/12/09 09:19:30 Created host with ID 12D3KooWPJ2bRX1kuTWobdfxpAk7RuBPVER5yhc8kFwbACcEgvB4...
2022/12/09 09:19:30 Connecting to server {12D3KooWDYhonMhW4t3be6PKMLgRmp7U1RYc59nvxsE9V1ASrV6B: [/ip4/3.101.133.148/tcp/1234]}...
2022-12-09T09:19:30.200Z	DEBUG	p2p-holepunch	holepunch/svc.go:95	waiting until we have at least one public addresspeer12D3KooWPJ2bRX1kuTWobdfxpAk7RuBPVER5yhc8kFwbACcEgvB4
2022/12/09 09:19:30 Connected to server.
2022-12-09T09:19:30.482Z	DEBUG	p2p-holepunch	holepunch/svc.go:107	Host now has a public address. Starting holepunch protocol.
2022/12/09 09:19:33 Finding listener from DHT...
2022/12/09 09:19:33 Found listener: {12D3KooWKujiFnDTroimQWtQckXotMM1SC6eaLCWs6AUsEH5V2aw: [/ip4/3.101.118.238/tcp/1234]}
2022/12/09 09:19:33 Connecting to listener...
2022/12/09 09:19:38 Error connecting to listener: failed to dial 12D3KooWKujiFnDTroimQWtQckXotMM1SC6eaLCWs6AUsEH5V2aw:
* [/ip4/3.101.118.238/tcp/1234] dial tcp4 0.0.0.0:1234->3.101.118.238:1234: i/o timeout
2022/12/09 09:19:41 Finding listener from DHT...
2022/12/09 09:19:41 Found listener: {12D3KooWKujiFnDTroimQWtQckXotMM1SC6eaLCWs6AUsEH5V2aw: [/ip4/3.101.118.238/tcp/1234]}
2022/12/09 09:19:41 Connecting to listener...
2022/12/09 09:19:41 Error connecting to listener: failed to dial 12D3KooWKujiFnDTroimQWtQckXotMM1SC6eaLCWs6AUsEH5V2aw:
* [/ip4/3.101.118.238/tcp/1234] dial backoff
2022/12/09 09:19:44 Finding listener from DHT...
2022/12/09 09:19:44 Found listener: {12D3KooWKujiFnDTroimQWtQckXotMM1SC6eaLCWs6AUsEH5V2aw: [/ip4/3.101.118.238/tcp/1234]}
2022/12/09 09:19:44 Connecting to listener...
2022/12/09 09:19:45 Error connecting to listener: context deadline exceeded
```

As you can see, the DHT allows the dialer to identify the correct listener and its public address using the orchestrator host. However, when it tries to connect to the listener with a simple `h.Connect(ctx, listenerAddrInfo)`, there is a `i/o timeout` followed by a resultant `dial backoff`. Could this because of the suggested configurations of the hosts? Or that it appears to be attempting the connection from a private IP?

I've added you to the [implementation repo](https://github.com/daryakaviani/on-demand-dots) if this is helpful.

**Comment by marten-seemann** [comment]
I'm not sure, there are a lot of moving parts with the added DHT. Maybe it would be easier to (for now) not have a DHT, but exchange the address explicitly?

**Comment by daryakaviani** [comment]
I see. That could work, but for now I wrote a working hole punching lib from scratch. Will revisit this if we need any features specific to libp2p such as decentralized relays. Closing the issue since the original question was addressed!
