### ISSUE TITLE
Lampshade crypto channel

### ISSUE THREAD

**Issue by ghost** [libp2p/go-libp2p#194]
- https://github.com/getlantern/lampshade
- https://godoc.org/github.com/getlantern/lampshade

> Package lampshade provides a transport between Lantern clients and proxies that provides obfuscated encryption as well as multiplexing. The protocol attempts to be indistinguishable in content and timing from a random stream of bytes, and mostly follows the OBFS4 threat model - https://github.com/Yawning/obfs4/blob/master/doc/obfs4-spec.txt#L35

This is a crypto channel for stream connections.

**Comment by Stebalien** [comment]
We've implemented Noise, TLS, and QUIC, and are unlikely to work on more crypto channels in the near future.
