### ISSUE TITLE
identify: simplify implementation by removing peer tracking

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#1965]
Identify currently deduplicates deltas sent to peers that we hold multiple connections to. This creates a lot of complexity in the implementation of the protocol.

It would be nice if we could simplify the logic to act on connections instead. There'd be no complicated tracking logic: start handling a connection when it's opened / accepted, and handle it until it is closed.

I measured how frequent duplicate connections really are by running Kubo both on my local machine (behind a CGNAT) and on a public server. The highest number of peers with duplicate connections I've come across was duplicates to 9 peers out of a total of 159, but that value quickly dropped as connections churned. For the vast majority of the time, we had duplicate connections to about 1% of the peers.
I expect that the number of duplicates will drop even further once we implement a smarter dialing logic (https://github.com/libp2p/go-libp2p/issues/1785), although we will never be able to _completely_ eliminate them, given that two peers dialing each other at exactly the same time will end up with two connections.

@vyzo @Stebalien quick sanity check, does this make sense?

**Comment by Stebalien** [comment]
IIRC, this wasn't about _duplicates_ but more about ordering. I believe a lot of this logic was trying to handle dead connections, etc.

**Comment by marten-seemann** [comment]
What about introducing a sequence number in the `Delta` message: https://github.com/libp2p/go-libp2p/blob/82315917f76ca1e9e1c3aca3ad957080f0ac870c/p2p/protocol/identify/pb/identify.proto#L5-L10

Senders could set it to the current timestamp (this would be completely stateless), and receivers could ignore messages where the sequence number is smaller than the last sequence number they received.

**Comment by Stebalien** [comment]
That would be the correct solution, yes. I believe the current version may have been my attempt to work around the issue without breaking network compatibility? But yes, we should just have sequence numbers.

Note: we technically also need to handle skips.

**Comment by Stebalien** [comment]
Also see https://github.com/libp2p/specs/issues/500. We should be able to just leave a stream open...

**Comment by marten-seemann** [comment]
The problem is what happens when we have two connections: We receive message N+2 on one connection (skipping N+1), then we receive N+1 on the other one. Now it's not correct to apply N+1 any more (only applying N+1 _and_ N+2 sequentially would be correct). But this means that the receiver would have to buffer messages that it already applied, just in case a message was skipped.
