### ISSUE TITLE
How to install deps?

### ISSUE THREAD

**Issue by jaynagpaul** [libp2p/go-libp2p#198]
I'm trying to run ./examples/http-proxy, but it seems like gx-go hasn't rewrote the package paths.
I have run in the go-libp2p folder:
`make deps`
`make`
`gx-go rewrite`
Yet all imports are still of the form gx/impfs/HASH/PACKAGE_NAME

**Comment by diasdavid** [comment]
Hi @jaynagpaul, the steps to run it are:

```
# from the go-libp2p folder
> make gx        # to install gx
> make deps    # to rewrite all of the imports to use gx
> go build ./examples/http-proxy
> ./http-proxy
```

I just run through this and worked, wanna try again?

**Comment by VictorBjelkholm** [comment]
@jaynagpaul if you want to use the normal go imports instead of gx, you should use the command `gx-go uw` (for unwrite) and you'll end up with normal imports.

It's advisable to use gx though, as you can be sure you're getting the right version of libraries that way.
