### ISSUE TITLE
Return protocol ID that is not supported in error message.

### ISSUE THREAD

**Issue by renaynay** [libp2p/go-libp2p#1988]
It would be convenient if the protocol ID that is not supported by the remote peer is returned as well in the error message. 

Current: 

`protocol not supported`

Desired:

`protocol not supported: <protocol_ID>`

**Comment by marten-seemann** [comment]
Not opposed to it, but is this particularly useful? You know which protocol(s) you were trying to negotiate when you receive this error.

If we wanted to add the protocol IDs, we'd run into #1886 again.

This is a go-multistream issue, not a go-libp2p issue by the way. Moving it there.

**Comment by p-shahi** [comment]
moved to https://github.com/multiformats/go-multistream/issues/94 closing this
