### ISSUE TITLE
Multiaddrs with peer ID are not considered dialable

### ISSUE THREAD

**Issue by masih** [libp2p/go-libp2p#2001]
A multiaddr can optionally contain the peer ID, i.e. `../p2p/<peer-ID>`. When such multiaddrs are added to the libp2p host peerstore, they are not considered to be dialable, and filtered on `host.Connect` resulting in `no good addresses` error.

For example, the following test fails with error `no good addresses`:

```go 
func TestHost_ConnectWithMultiaddrAndID(t *testing.T) {
	host, err := libp2p.New()
	require.NoError(t, err)
	pid, err := peer.Decode("12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC")
	require.NoError(t, err)

	addrWithPid, err := multiaddr.NewMultiaddr("/ip4/209.94.92.6/tcp/24001/p2p/" + pid.String())
	require.NoError(t, err)

	host.Peerstore().AddAddr(pid, addrWithPid, peerstore.PermanentAddrTTL)

	addrs := host.Peerstore().Addrs(pid)
	t.Log(addrs)

	err = host.Connect(context.Background(), peer.AddrInfo{ID: pid})
	require.NoError(t, err)
}

```

While this one succeeds:

```go
func TestHost_ConnectWithMultiaddr(t *testing.T) {
	host, err := libp2p.New()
	require.NoError(t, err)
	pid, err := peer.Decode("12D3KooWNSRG5wTShNu6EXCPTkoH7dWsphKAPrbvQchHa5arfsDC")
	require.NoError(t, err)

	addrWithPid, err := multiaddr.NewMultiaddr("/ip4/209.94.92.6/tcp/24001")
	require.NoError(t, err)

	host.Peerstore().AddAddr(pid, addrWithPid, peerstore.PermanentAddrTTL)

	addrs := host.Peerstore().Addrs(pid)
	t.Log(addrs)

	err = host.Connect(context.Background(), peer.AddrInfo{ID: pid})
	require.NoError(t, err)
}
```

The only difference being that the multiaddr added to peerstore in the first test contained peer ID.

In the specific case above, looks like the address is being filtered by `CanDial` of `TcpTransport` which uses [this](https://github.com/libp2p/go-libp2p/blob/master/p2p/transport/tcp/tcp.go#L154) matcher.

Is this behaviour expected and or documented? Otherwise, it seems surprising that a valid multiaddr being successfully added to the peerstore and yet no good address are found on connection.

**Comment by MarcoPolo** [comment]
This is definitely a foot gun that has bitten me as well. Thanks for the issue. Should be a straight forward fix.

**Comment by sukunrt** [comment]
Can I pick this up?
