### ISSUE TITLE
calling `Connect` to a peerID not in the peerstore panics

### ISSUE THREAD

**Issue by willscott** [libp2p/go-libp2p#2005]
a call is made to `Connect` on a [routed host](https://github.com/libp2p/go-libp2p/blob/master/p2p/host/routed/routed.go#L48). In this case within the boost / filecoin system.

In some cases the peer being connected to may not have addresses.

Expected behavior: Error that the connection cannot be made.
Actual behavior: `panic: runtime error: index out of range [-1]`

Stack:
```
goroutine 764909 [running]:
github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoremem.(*addrSegments).get(...)
	~github.com/libp2p/go-libp2p@v0.23.2/p2p/host/peerstore/pstoremem/addr_book.go:49
github.com/libp2p/go-libp2p/p2p/host/peerstore/pstoremem.(*memoryAddrBook).Addrs(0x0?, {0x0?, 0x10994b000?})
	~github.com/libp2p/go-libp2p@v0.23.2/p2p/host/peerstore/pstoremem/addr_book.go:327 +0x164
github.com/libp2p/go-libp2p/p2p/host/routed.(*RoutedHost).Connect(0x140003e8e20, {0x108676ac0, 0x1400073fc80}, {{0x0, 0x0}, {0x0, 0x0, 0x0}})
	~github.com/libp2p/go-libp2p@v0.23.2/p2p/host/routed/routed.go:63 +0x150
```

**Comment by marten-seemann** [comment]
That can only happen when the peer ID is empty, right?
https://github.com/libp2p/go-libp2p/blob/5b5eea45d3ce8d265742d18578824ec857c07533/p2p/host/peerstore/pstoremem/addr_book.go#L48-L50

**Comment by willscott** [comment]
good catch - it looks like this is a degenerate case when being asked to connect to `peer.AddrInfo{}`.

**Comment by marten-seemann** [comment]
We definitely shouldn't panic here, but I'd suspect there's also a bug in your code somewhere if you're asking us to connect to an empty peer ID.
