### ISSUE TITLE
Make identify protocol Resource Manager aware.

### ISSUE THREAD

**Issue by ajnavarro** [libp2p/go-libp2p#2013]
We should make identify protocol Resource Manager aware, handling correctly local RM errors.

**Comment by MarcoPolo** [comment]
We may not know the error is due to resource management on the other end. It could be that the peer simply decided not to talk to us. 

We can handle our local RM errors, but not remote ones.

**Comment by ajnavarro** [comment]
Updated the issue description.

**Comment by marten-seemann** [comment]
> handling correctly local RM errors.

@ajnavarro Why is the the current handling of local errors incorrect?

**Comment by ajnavarro** [comment]
Because is not handling resource manager errors at all (retries or any possible way that can help to maximize rm usage)

**Comment by marten-seemann** [comment]
I'm going to close this issue. I don't think there's anything we can do here - we won't even know if the error that occurred is a resource management error (for remote errors), unless we're on QUIC and we parse the error message.
