### ISSUE TITLE
Libp2p tutorials and demos

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#202]
I would like to start pushing for more demos and tutorials on working with libp2p. If you have any ideas on what sort of content you want to see, please let us know here!

**Comment by lgierth** [comment]
Two categories of tutorials:

- How to use libp2p
  - chat application? :)
- How to develop libp2p
  - navigating where stuff is
  - creating patches for some component
  - adding and testing a new transport

**Comment by VictorBjelkholm** [comment]
Yeah, would be useful to have a walk-through of terminology used (with links to more information), how the concepts are being used and how they tie together and for what reason. Might be easier to explain with explicit use-cases, like chat application.

Might be a fun idea to have a tutorial for writing your own IPFS-lite as well, to be able to explain how libp2p ties into IPFS.

**Comment by nvonpentz** [comment]
Yes, I examples would be helpful.  Specifically I am looking of an example demonstrating how to establish a connection between two computers behind NAT.

**Comment by larskluge** [comment]
Currently all golang examples demonstrate libp2p on localhost only. It would be great to have a basic example that goes beyond client <> server and demonstrates the power of libp2p. mdns/discovery, if necessary w/ Circuit Relay. An example as @nvonpentz asks for too. 

@diasdavid any chance you could translate one of your more advanced JS examples here? The interfaces are too different for me w/ 0-day-experience to do it myself. Happy to help and contribute for better examples.

**Comment by avive** [comment]
Please consider this little example - I think it will be useful for real world p2p apps written in go: https://github.com/libp2p/go-libp2p/pull/249

**Comment by agahEbrahimi** [comment]
@whyrusleeping A tutorial that has Nat Traversal, Discovery, Content/peer routing, and transport would be perfect.

**Comment by agahEbrahimi** [comment]
@whyrusleeping That would be perfect. (does it work over the internet?)

**Comment by whyrusleeping** [comment]
Yeah, it should work over the internet, just have to make sure your swarm listen addresses are 0.0.0.0 (or some external address) and not 127.0.0.1

**Comment by whyrusleeping** [comment]
@agahEbrahimi it would need to be passed as an option to the libp2p constructor. I didnt expose it as a command flag in my tutorial

**Comment by Stebalien** [comment]
There is now an entire examples directory.
