### ISSUE TITLE
Can we know the performance of network of the libp2p?

### ISSUE THREAD

**Issue by Shawn-Huang-Tron** [libp2p/go-libp2p#2032]
I know there are some prometheus metrics like tcp_connection_duration_* that can show us the network stablility.
But i wonder if you developers have something else that can measure the whole network?

**Comment by p-shahi** [comment]
Hi thanks for creating this issue. General open ended questions like these are better asked in the discussion forum at discuss.libp2p.io
You can see some measurements of network stability here: https://kademlia-exporter.max-inden.de/d/-avwMhsik/kademlia-exporter?orgId=1
