### ISSUE TITLE
http: libp2p + http

### ISSUE THREAD

**Issue by p-shahi** [libp2p/go-libp2p#2034]
eta: 2023-08-31

Tracking issue for an implementation of https://github.com/libp2p/specs/pull/508 

```[tasklist]
### Tasks
- [ ] https://github.com/libp2p/js-libp2p/issues/1648
- [ ] https://github.com/libp2p/go-libp2p/pull/2438
```

**Comment by peterwillcn** [comment]
How to support HTTPS proxy using libp2p?

**Comment by peterwillcn** [comment]
Please Merged https://github.com/Zartenc/httpsproxy Implement https proxy

**Comment by p-shahi** [comment]
@peterwillcn please stop spamming this issue

**Comment by quickhatche** [comment]
Hi @p-shahi has this milestone been completed? ETA shows end of May but this is still open

**Comment by p-shahi** [comment]
@quickhatche Updated

**Comment by quickhatche** [comment]
Hi @p-shahi Checking to see if this one need to be closed or ETA updated?

**Comment by MarcoPolo** [comment]
Updated eta for end of this month.

**Comment by p-shahi** [comment]
closed via https://github.com/libp2p/go-libp2p/pull/2438
