### ISSUE TITLE
Go 1.19: use atomic.Bool

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2043]
We're using `atomic.{U}Int{32,64}` to store a 0 or a 1 at a few places across the code base. We should replace these with the `atomic.Bool` introduced in Go 1.19, as this will make the code easier to read.

This can be done as soon as Unified CI is updated and we've dropped support for Go 1.18.

**Comment by marten-seemann** [comment]
#2073 was just merged, so this is ready to go now. @sukunrt Do you want to give it a shot?

**Comment by sukunrt** [comment]
yes! I'll pick this after https://github.com/libp2p/go-libp2p/issues/2056
