### ISSUE TITLE
Metrics should be able to accept a prometheus registerer parameter

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/go-libp2p#2047]
Instead of always using the default registerer.

**Comment by sukunrt** [comment]
Should I add An option to create a metrics tracer with a given registrar like done in eventbus metrics? 
https://github.com/libp2p/go-libp2p/blob/master/p2p/host/eventbus/basic_metrics.go#L96-L100

```
func MustRegisterWith(reg prometheus.Registerer) MetricsTracerOption {
	return func(s *metricsTracerSetting) {
		s.reg = reg
	}
}
```

**Comment by marten-seemann** [comment]
I'd be in favor of renaming the option. `MustRegisterWith` sounds like it's a global function (which it isn't really, it's an option), and it also sounds like it could panic. Better: `WithRegisterer`.

If I understand correctly, when allowing multiple `prometheus.Registerer`s, we need to be careful with the `sync.Once`. We need to register once _with every `Registerer`_.

We probably need to introduce some kind of metrics helper: A (thread-safe) set to keep track of which `Registerer`s we've already registered with.

**Comment by sukunrt** [comment]
Agreed on ```WithRegisterer```. 
Why do we need to register just once? The prometheus Registerer interface has a Register method which would give an error ```AlreadyRegisteredError``` on reregistration. We can ignore this error and panic/propagate other errors when doing registerer.Register. Is this good enough?

**Comment by marten-seemann** [comment]
> Why do we need to register just once? The prometheus Registerer interface has a Register method which would give an error `AlreadyRegisteredError` on reregistration. We can ignore this error and panic/propagate other errors when doing registerer.Register. Is this good enough?

Looks like I didn't look closely enough at the Prometheus API. This is even better! Catching `AlreadyRegisteredError` and panicking for all others sounds reasonable to me.
