### ISSUE TITLE
metrics: make it easier to update / discover Grafana dashboard

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2055]
Currently all of our Grafana dashboards are available right next to the instrumented code. 
They are:
* [swarm](https://github.com/libp2p/go-libp2p/blob/master/p2p/net/swarm/grafana-dashboards/swarm.json)
* [eventbus](https://github.com/libp2p/go-libp2p/blob/master/p2p/host/eventbus/grafana-dashboards/eventbus.json)
* [resource-manager](https://github.com/libp2p/go-libp2p/blob/master/p2p/host/resource-manager/obs/grafana-dashboards/resource-manager.json)
* [identify](https://github.com/libp2p/go-libp2p/pull/2069/files#diff-6c19b257ba3054d4f415bf581870ee279f98c2ab42cd5a7fc1a07c708eac7920)

We need to make it as easy as possible for our users to import all the dashboards. At the moment, we define 3 dashboards (swarm, rcmgr, eventbus), but with #1356, we'll soon have ~10 dashboards.

One option to simplify things a bit would be to create a single `dashboards` directory in the root directory that holds all dashboards. Users would still have to open every JSON file and copy-paste it into their Grafana instance, but at least they don't have to walk our directory tree.

Another option would be to evaluate the grafana.com import option:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/1478487/216792365-2f92e0af-70af-43f6-880b-c07f34bf1a4d.png">
Apparently you can import a dashboard by URL or by ID. Unfortunately, a URL pointing to a GitHub repository doesn't work, it has to be a grafana.com URL. Maybe there's an easy way to publish our dashboards on grafana.com via a GitHub Action when we cut a release?

**Comment by MarcoPolo** [comment]
We should also have a README in that directory.

**Comment by MarcoPolo** [comment]
This is done with all dashboards in a single folder. We can't have a single one-click to import all the dashboards with what Grafana provides.
