### ISSUE TITLE
Go 1.19: use atomic.Pointer instead of atomic.Value

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2056]
There's a few places in our codebase where we're currently using an `atomic.Value`:
```
p2p/net/connmgr/decay.go
41:     lastTick atomic.Value

p2p/net/mock/mock_stream.go
34:     protocol atomic.Value

p2p/host/autonat/autonat.go
36:     status atomic.Value

p2p/net/swarm/swarm_stream.go
27:     protocol atomic.Value

p2p/net/swarm/swarm.go
149:    streamh atomic.Value
```

Go 1.19 added a `atomic.Pointer`, which makes use of generics, and allows us to do a type-safe atomic store and load operation. We should replace all uses of `atomic.Value` with `atomic.Pointer`.

This can be done as soon as Unified CI is updated and we've dropped support for Go 1.18.

**Comment by marten-seemann** [comment]
#2073 was just merged, so this is ready to go now. @sukunrt Do you want to give it a shot?

**Comment by sukunrt** [comment]
sure! I'll pick this.
