### ISSUE TITLE
RoutedHost.NewStream should ensure we have the means to connect to the peer

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p#207]
Currently, RoutedHost.NewStream directly delegates the call to the underlying (basic) host. 
The idea is that if we don't currently have any open connections to the peer, the basic host will automatically open a connection using Dial and the addresses in the Peerstore.

And that's exactly the problem: if we have not previously had a connection to the peer, then we are likely not to have any address for the peer either. So when the dial is attempted, it will not find any addresses and fail.

This issue directly hinders the usage of relay addresses in the form `/ipfs/QmRelay/p2p-circuit/ipfs/QmPeer` and instead forces us to explicitly specify the address of the the relay (or have previously connected to it somehow).

**Comment by vyzo** [comment]
summoning @Stebalien @whyrusleeping @lgierth

**Comment by vyzo** [comment]
Note that this also hinders the utility of active relays, as they won't be able to dial peers without any prior connection to them.

**Comment by vyzo** [comment]
cc @dryajov

**Comment by Stebalien** [comment]
Good catch!

---

> Note that this also hinders the utility of active relays, as they won't be able to dial peers without any prior connection to them.

Does #208 also fix this issue?

**Comment by vyzo** [comment]
>    Note that this also hinders the utility of active relays, as they won't be able to dial peers without any prior connection to them.

> Does #208 also fix this issue?

Yes, provided the relay is added to a RoutedHost.
