### ISSUE TITLE
drop support for circuit v1

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2075]
We're retired all Circuit v1 Relays a few months ago. rust-libp2p [has dropped support](https://github.com/libp2p/rust-libp2p/pull/2549) and js-libp2p [is dropping support](https://github.com/libp2p/js-libp2p/pull/1533) for v1 support. We should do the same in go-libp2p.

**Comment by fahimbagar** [comment]
Hi @marten-seemann :wave: 

This is the PR for this remove support for Circuit Relay v1 protocol: https://github.com/libp2p/go-libp2p/pull/2083

Let me know if I'm missing something there. Thanks

**Comment by marten-seemann** [comment]
@fahimbagar Please comment on the issue before picking up the work. I already have a branch that removed support, just hadn’t pushed the changes. That’s now wasted duplicate work.

**Comment by fahimbagar** [comment]
Understood. I can close the PR, no worries. I'm just trying to understand the `libp2p` deeper.

**Comment by marten-seemann** [comment]
Hi @fahimbagar! Sorry for the misunderstanding. We're actually really happy about new contributors, so please don't take this the wrong way.

We have a bunch of issues with the "help wanted" label, those are generally good ones to get started on the code base. Let me know if you want to pick up any of those (either on the issue, or message me on our [Slack](https://filecoin.io/slack)).

**Comment by fahimbagar** [comment]
> Hi @fahimbagar! Sorry for the misunderstanding. We're actually really happy about new contributors, so please don't take this the wrong way.

It's my fault :sweat_smile: I should ask before I pick up any of the issues. 

> We have a bunch of issues with the "help wanted" label, those are generally good ones to get started on the code base. Let me know if you want to pick up any of those (either on the issue, or message me on our [Slack](https://filecoin.io/slack)).

Sure, I'll try to see the help-wanted issues sometime this week. Thanks for the information, Marten.
