### ISSUE TITLE
swarm metrics: connection counting seems broken

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2113]
<img width="1648" alt="image" src="https://user-images.githubusercontent.com/1478487/219556309-6ce4ca22-7b02-45e6-a4f8-352951447cd1.png">

While at the same time:
```
❯ ipfs swarm peers | wc
   1487    1487  135713
```

config:
```
  "Swarm": {
    "AddrFilters": null,
    "ConnMgr": {
      "GracePeriod": "20s",
      "HighWater": 1500,
      "LowWater": 900,
      "Type": "basic"
    },
```

**Comment by sukunrt** [comment]
Do you have a long running node? 
On my setup the primary source of divergence is ```MetricsTracer.ClosedConnection``` not being called when two dials succeed and one of them is dropped [here](https://github.com/libp2p/go-libp2p/blob/master/p2p/net/swarm/limiter.go#L222-L225)

We can just call ```MetricsTracer.ClosedConnection``` there or we can move the OpenedConnection call to ```swarm.addConn```
