### ISSUE TITLE
Why the default lowWater/highWater of ConnMgr value is 600 and 900?

### ISSUE THREAD

**Issue by Shawn-Huang-Tron** [libp2p/go-libp2p#2140]
Why the default lowWater/highWater value is 600 and 900? How does this value caculate?  If we have a 3,000,000's node in our private network. Which level we should set to be better?

**Comment by marten-seemann** [comment]
It's the value that has been used for the longest time in go-ipfs. I'm not aware of any research on what's the best value is, so other values might work as well / might work even better.
