### ISSUE TITLE
holepunch: race condition with identifyWait

### ISSUE THREAD

**Issue by sukunrt** [libp2p/go-libp2p#2163]
Currently holepunch calls hs.ids.IdentifyWait(conn) inside the netNotifee.Connected call. 
But IdentifyWait requires netNotifee.Connected call to identify to be completed. 

https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/holepunch/holepuncher.go#L262

Swarm doesn't guarantee any ordering on notifcations. The notifees are obtained from map keys.

**Comment by marten-seemann** [comment]
Is that a race condition? The `IdentifyWait` is called in a Go routine. Wouldn't it just wait until it has received the swarm notification?

**Comment by sukunrt** [comment]
no. IdentifyWait assumes the Connected call is completed before calling identifyWait.
https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/identify/id.go#L347

The entry is added here
https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/identify/id.go#L889

**Comment by sukunrt** [comment]
the relevant identifyWait line is this. 
https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/identify/id.go#L352

**Comment by marten-seemann** [comment]
Can you explain how things go wrong when this race condition is triggered?

**Comment by sukunrt** [comment]
we will skip this block where we try to direct dial before hole punch 
https://github.com/libp2p/go-libp2p/blob/master/p2p/protocol/holepunch/holepuncher.go#L110
