### ISSUE TITLE
autorelay: deadlock in tests

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2167]
https://github.com/libp2p/go-libp2p/actions/runs/4321376917/jobs/7542536126

**Comment by sukunrt** [comment]
Sorry. I introduced this here: 
https://github.com/libp2p/go-libp2p/pull/2164

The deadlock is swarm.disconnect has swarm.notifee lock and calls disconnected on relay service which depends on relay service lock
The relay service Close has relay service lock and calls swarm.stopNotify which depends on swarm.notifee lock.
