### ISSUE TITLE
Tor / Onion transport option for libp2p + GossipSub

### ISSUE THREAD

**Issue by thesheepcat** [libp2p/go-libp2p#2172]
I ask the possibility to expose a libp2p host as TOR / onion service, on a specific onion address.

Here ( https://github.com/berty/go-libp2p-tor-transport ) some work has been done but the repo is not anymore mantained and, to me, it would be better to have an embedded module on the official go-libp2p repo.

We are going to need it because we need to create a decentralized network (decentralized group messaging) based on GossipSub where we expose some bootstrapper nodes via TOR hidden_service (address: XXXXXXXXXXXXXXXXXXXXXXXXXXXX.onion) to protect bootstrapper identity.

Users will activate their nodes which connect to 10 bootstrapper onion addresses and start sending messages; even users have to be protected by TOR (i already checked libp2p supports onion3 addresses in multiaddress elaboration); eventually, they can use torify.

**Comment by marten-seemann** [comment]
This has been discussed before. You’re free to fork any existing Tor transport, but we won’t encourage use by moving it into the main repository. libp2p is quite aggressive in determining and broadcasting your public addresses, so unless you’re really, really careful, a Tor transport will not give you the privacy protection users will be searching for when they find a Tor transport here.

**Comment by master255** [comment]
@marten-seemann Tor is used not only to anonymize, but also to bypass Internet blockades.

@thesheepcat For complete anonymization, use i2p.
