### ISSUE TITLE
identify metrics: track agent and protocol version

### ISSUE THREAD

**Issue by sukunrt** [libp2p/go-libp2p#2182]
Track AgentVersion and ProtocolVersion and transport used per connection.

**Comment by marten-seemann** [comment]
How do you make sure that this doesn't become an attack vector? The inputs are controlled by the attacker? Ar you planning to introduce a whitelist?

**Comment by p-shahi** [comment]
Copying 
> tracking agent version is a difficult since it's a user controlled field, so an attacker can generate lots of agent versions which would lead to creation of a lot of prometheus time series on our end.
@marten-seemann has some ideas around a useful construct where we allow applications to specify a regex. However we can take that up after we finish the initial set of metrics.

https://github.com/libp2p/go-libp2p/issues/2103#issuecomment-1478999013

**Comment by p-shahi** [comment]
closing in favor https://github.com/libp2p/go-libp2p/issues/2205
