### ISSUE TITLE
Bitswap problems over websocket transport since switch to nhooyr websocket

### ISSUE THREAD

**Issue by hannahhoward** [libp2p/go-libp2p#2188]
Bug: attempting to fetch UnixFS files over bitswap with peers that only expose websockets will fail on large blocks. Note: this is all of Elastic IPFS/Web3.storage

Steps To Reproduce:

Build Kubo v0.18.0:

Start the daemon:
```
./cmd/ipfs/ipfs daemon
```

```
./cmd/ipfs/ipfs get bafybeiarntxetfbzpyp7baj7kqvqljrn5uyoobq2y4b3zegbbem5joazgy 
```
This is a CID I stored on web3.storage. It works.

Now switch to Kubo master and do the same. It now hangs.

Heavy debugging identifies the following error generated in the websocket conn: `failed to read: read limited at 32769 bytes` -- this comes from here I believe: https://github.com/nhooyr/websocket/blob/master/read.go#L385

Note that actually everything works fine until we get to the first 1MB raw block, I assume because it's over that limit.

This was originally discovered in Lassie and in debugging why it couldn't fetch while Kubo 0.18.0 could, I found that Kubo master couldn't either.

**Comment by p-shahi** [comment]
flagging this for @MarcoPolo 

It looks like it has a connection read limit set to 32768 bytes + one more byte in case of a fin frame:
https://github.com/nhooyr/websocket/blob/master/read.go#L69

There also seems to be this issue that a user ran into yesterday with the limit: https://github.com/nhooyr/websocket/issues/382 which shows an option to disable the read limit (but no ETA for a release)

**Comment by BigLep** [comment]
Thanks for finding and reporting @hannahhoward .

Thanks for jumping onto it @MarcoPolo .

Please make sure we get a regression test for this added.  Ideally we could apply such a test to all transports.

**Comment by BigLep** [comment]
Thanks @MarcoPolo for getting the PR out.  What timeline are you thinking here for merging and getting it released?  I'm asking since it's important for the Kubo 0.19 release (prevent regression) and impacting Rhea/Lassie work.  Assuming @marten-seemann is out, who else would you like to pull in?

**Comment by MarcoPolo** [comment]
Thanks for the review @hannahhoward. If @marten-seemann doesn't get to it by eod, I'll merge and cut a patch release for Kubo with this.

**Comment by p-shahi** [comment]
Released in https://github.com/libp2p/go-libp2p/releases/tag/v0.26.3
