### ISSUE TITLE
websocket: closing a connection may block for 5s

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2201]
See https://github.com/nhooyr/websocket/issues/355 for details. This might block the connection manager loop and the `swarm.Close` for a long time, if we have a lot of WebSocket connections and this happens multiple times.
Not sure how realistic this is in practice, but I wouldn't want to risk it.

**Comment by MarcoPolo** [comment]
Could we read the rest of the frame and discard before calling close as a temporary workaround?
