### ISSUE TITLE
metrics: observed address mgr

### ISSUE THREAD

**Issue by p-shahi** [libp2p/go-libp2p#2203]
Number of activated addresses: IP Version + Transport
Nat Type: (Unknown, Symmetric, Cone)

**Comment by sukunrt** [comment]
I'm tracking these from holepunch metrics. We are only interested in activated addresses. Tracking at observedAddressManager leads to a lot of book keeping like ```wasActivatedBefore``` ```isActivatedNow``` everywhere. 

At the moment we are only interested in public address counts by ipversion and transport for holepunches, so my approach feels okay.

**Comment by sukunrt** [comment]
>I'm tracking these from holepunch metrics. We are only interested in activated addresses. Tracking at observedAddressManager leads to a lot of book keeping like wasActivatedBefore isActivatedNow everywhere.

I have changed this strategy. It is better to track these from observed address manager. I don't remember what my reasoning was here, but I think there's a way to do this that's hopefully not too complicated.
