### ISSUE TITLE
Cannot advertise WebTransport with externally known addresses (external static IP + port forwarding, dns, etc.)

### ISSUE THREAD

**Issue by aschmahmann** [libp2p/go-libp2p#2223]
When running a go-libp2p host behind a NAT with port forwarding enabled or another environment where the user might know more about the addresses to advertise than go-libp2p has been able to discover (e.g. DNS addresses) users pass in their addresses via the `AddrsFactory` option https://github.com/libp2p/go-libp2p/blob/8c466ab7f8d0e1eb12ea8a23933e77d25190a81a/options.go#L260

As I understand it the `AddrsFactory` takes in the list of addresses that go-libp2p thinks it should be advertising and then allows the user to modify that list (e.g. override/remove elements, add new ones, etc.). The multiaddrs processed and returned by this function are ones that do not have the `/p2p/<peerID>` suffix.

Unfortunately, this behavior doesn't work for WebTransport since naively adding an additional `/ip4/1.2.3.4/udp/1234/quic-v1/webtransport` will be broken due to the lack of WebTransport certificates that are not added internally by go-libp2p. This is not something the user can reasonably deal with by passing the certificates themselves without understanding (and replicating) the internal go-libp2p mechanism for managing WebTransport certificates (having deterministic certificates generated with timestamps based on dividing time into fixed intervals) or finding some awkward workaround (e.g. having a loopback webtransport listener and then reading the certificates go-libp2p has emitted for the loopback listener and feeding it back into the `AddrsFactory`).

**Comment by BigLep** [comment]
@p-shahi : I know I missed go-libp2p triage.  Was this discussed at all?  Given it's relevant for IPFS Thing demos, I wanted to set expectations for people on whether it will get picked up soon or not.

https://filecoinproject.slack.com/archives/C03FFEVK30F/p1679935514021119

**Comment by MarcoPolo** [comment]
We didn't talk about this. Both prithvi and I were a bit sick so we concluded. early. I can tal now.
