### ISSUE TITLE
Peerstore interfaces should accept contexts

### ISSUE THREAD

**Issue by guseggert** [libp2p/go-libp2p#2231]
The [peerstore](https://github.com/libp2p/go-libp2p/blob/master/core/peerstore/peerstore.go) family of interfaces currently don't accept any Go contexts, despite performing IO. This means that, for example, the "pstoreds" package which implements a datastore-backed peerstore can't propagate contexts into the backing datastore.  Example: 

https://github.com/libp2p/go-libp2p/blob/8c466ab7f8d0e1eb12ea8a23933e77d25190a81a/p2p/host/peerstore/pstoreds/addr_book.go#L54

This means that the datastore can't respect context cancelations and any values stored in the context are also lost (ex. tracing metadata).

**Comment by marten-seemann** [comment]
Didn't we have a PR for that at some point?
