### ISSUE TITLE
flaky interop tests

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2244]
Example: https://github.com/libp2p/go-libp2p/actions/runs/4626672358/jobs/8183677493?pr=2242

**Comment by marten-seemann** [comment]
I've [disabled](https://github.com/libp2p/go-libp2p/actions/workflows/interop-test.yml) the interop test. It's failing practically all of our builds.

**Comment by MarcoPolo** [comment]
It's not flaky, it just flat out fails. Fix here: https://github.com/libp2p/test-plans/pull/164
