### ISSUE TITLE
Generic request-response protocol framework in go-libp2p

### ISSUE THREAD

**Issue by 0xbillw** [libp2p/go-libp2p#2258]
I noticed that there is a framework implementation of the request-response protocol in the library of rust-libp2p and it is used in Substrate project. However, there is no corresponding implementation in go-libp2p.
The multipro example of go-libp2p is somewhat similar, but very different: it uses two protocol-ids (one request and one response each) to create two new streams to complete the request and response.
I feel that doing so is neither efficient nor concise. If go-libp2p can provide a request-response implementation similar to rust-libp2p, it would be even better. Then, protocols implemented in two languages at the application layer can be seamlessly integrated.
Welcome to any reply, thanks!

**Comment by MarcoPolo** [comment]
We're working towards this. Right now the feeling is to adopt HTTP semantics for request and response. There's a lot of advantages to that, I won't repeat them here but the discussion is happening at https://github.com/libp2p/specs/pull/508.

If you want something very simple, and don't care for HTTP semantics it's very easy to make a simple request response using just streams. Write some data to a stream, close the write side, then wait to read data. That's it. This should interoperate with rust-libp2p's request-response framework just fine.

**Comment by MarcoPolo** [comment]
Closing this as it's better addressed by #2034. Feel free to reach out again if you still have questions.
