### ISSUE TITLE
quic: panic on error in listener Accept

### ISSUE THREAD

**Issue by sukunrt** [libp2p/go-libp2p#2259]
originally reported here: 
https://github.com/ipfs/kubo/issues/9693

The sequence of events that causes this is:

```list.Accept``` errors here https://github.com/libp2p/go-libp2p/blob/v0.26.4/p2p/net/swarm/swarm_listen.go#L129

and error in list.Accept has closed the listener accept loop already here:
https://github.com/libp2p/go-libp2p/blob/v0.26.4/p2p/transport/quic/virtuallistener.go#L108-L120
with `sendErrAndClose`

The defer cleanup in swarm_listen closes ```virtuallistener``` here https://github.com/libp2p/go-libp2p/blob/master/p2p/net/swarm/swarm_listen.go#L117

which causes panic here: https://github.com/libp2p/go-libp2p/blob/v0.26.4/p2p/transport/quic/virtuallistener.go#L73
as it checks for entry from ```muxer``` map which was removed by `sendErrAndClose`

**Comment by MarcoPolo** [comment]
So this is an issue with closing twice? Once in the error from accept and once on shutdown?

**Comment by sukunrt** [comment]
yes. Accept implicitly closes the listener on error via `sendErrAndClose` and the shutdown cleanup func explicitly closes it. 

I don't know why Accept is erroring though.

**Comment by marten-seemann** [comment]
Wild guess: might be related to https://github.com/quic-go/quic-go/issues/1737?

**Comment by MarcoPolo** [comment]
Easy fix could be to make sure we only close once. Still unclear we get the original error in `Accept` though.
