### ISSUE TITLE
Log error in accept

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/go-libp2p#2264]
https://github.com/libp2p/go-libp2p/blob/8313917571fec7d26813ff437013fde6f48659f7/p2p/net/swarm/swarm_listen.go#L130

ignore swarm close errors.

**Comment by nikumbgo12345** [comment]
@MarcoPolo i am new to libp2p and trying to contribute , not sure what you mean by the description , have created a PR could you please review and guide

**Comment by marten-seemann** [comment]
@nikumbgo12345 This issue was already assigned to @MarcoPolo. Maybe pick one of the [help wanted](https://github.com/libp2p/go-libp2p/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22) issues instead?
