### ISSUE TITLE
Feature request: Add logging before returning errors to the caller

### ISSUE THREAD

**Issue by vernonr3** [libp2p/go-libp2p#2265]
The go idiom of returns throughout a function or method is good for avoiding nasty code smells like heavily indented logic.

But lots of 
`
if err != nil{ 
    // no intervening debug statement
    return args... , err
} 

`
exist.

When many clients may use the interface and/or the error cascades up through numerous levels it gets confusing. It makes it harder than it should be for non experts to know where the original source of an error was. It doesn't matter how good the textual explanation in the error was if it isn't displayed until much later.

I found a number of examples of this working through #2220. 

I'll submit individual pull requests to add an explanatory debug statement referencing this issue where I found this was confusing.

**Comment by vernonr3** [comment]
I can see one doesn't want to repeat the same log message multiple times. But wouldn't a better pattern would be to log the error at close to the origin as possible - and bubble the error upwards.

**Comment by MarcoPolo** [comment]
I agree with @marten-seemann here. This isn't idiomatic Go. I do appreciate the thought and time put into explaining your points.

I don't have much to add, but I'll link this post: https://mediocregopher.com/posts/a-simple-rule-for-better-errors 

> A function sending back an error should not include information the caller could already know.

The caller could decide to log the error, logging the error is not the responsibility of the callee.

I'm closing this issue as wontfix.
