### ISSUE TITLE
Connectedness events are not submitted by mocknet

### ISSUE THREAD

**Issue by Wondertan** [libp2p/go-libp2p#2267]
After https://github.com/libp2p/go-libp2p/pull/1574, the `Network` is now responsible for emitting such events. However, only `Swarm` was updated to emit them, and the only second implementation, `mocknet` was not. There are projects in the ecosystem that uses `mockent` and for whom updating to v0.27 will break tests because of this.

Additionally, the tests that depend on `swarm/testing` will break as well due to the reason @vyzo mentioned in [here](https://github.com/libp2p/go-libp2p/pull/1574#discussion_r884115720). The user now has two instantiate the EventBus themselves and pass two both the host constructor and the `GenSwarm`, but if I understand correctly this is part of a larger issue https://github.com/libp2p/go-libp2p/issues/1993.

**Comment by marten-seemann** [comment]
`mocknet` is unmaintained and only kept for backwards compatiblity. If you want to submit a fix though, I'd be happy to review.

**Comment by Wondertan** [comment]
I am sure Lotus depends on it, and they will likely want to update to v0.27.

I can submit a patch but in weeks from now.

**Comment by MarcoPolo** [comment]
Thanks for the PR, I'll review :)

What do you think about a in-memory transport? It would let us run all the same code as normal, but use Go channels/runtime to do the actual network part of it. It'll probably behave more realistically and use less code than mocknet.

For prior art, rust-libp2p has an in-memory transport.
