### ISSUE TITLE
How do I get Android methods?

### ISSUE THREAD

**Issue by master255** [libp2p/go-libp2p#2282]
With the command gomobile bind -target=android I was able to get the aar file. But there are no methods in it. How to work with it?
Or how to compile the library so that there are methods? Maybe there is some key for this somewhere?

**Comment by marten-seemann** [comment]
I'm not familiar with gomobile and compilation for Android. It's not a build target that we're actively trying to support.

**Comment by master255** [comment]
@marten-seemann Ok. Now we need to understand why there are no methods. Is it probably because there are no public methods in the library?

**Comment by marten-seemann** [comment]
Please refer to the Godoc. There are plenty of exported methods.

Closing this issue since Android is not an actively support build target.

**Comment by p-shahi** [comment]
@master255 I don't think you are alone, there has been interest in the past few years (a quick search of libp2p android does yield results); however, first class support for Android is not a currently a priority/on our roadmap. We have limited resources as team and not a lot of domain expertise here. That said, this area seems ripe for you and other community members to champion

Please also take a look at https://github.com/ipfs-shipyard/gomobile-ipfs/

**Comment by master255** [comment]
@p-shahi I don't need ipfs. I need libp2p.
There's a kotlin version. But it doesn't work either https://github.com/libp2p/jvm-libp2p/issues/274

Some kind of developer conspiracy. They program something there but don't let anyone use it.

**Comment by p-shahi** [comment]
@master255 IPFS uses libp2p under the hood, I assume you'll find something helpful there.
No conspiracy, just being realistic about time and priority constraints. Trying to help you out but won't engage any further.

**Comment by master255** [comment]
@p-shahi https://github.com/ipfs-shipyard/gomobile-ipfs - Is it possible to use this project with it?

> No conspiracy, just being realistic about time and priority constraints.

When I do a release, at least it runs

**Comment by master255** [comment]
And I'm looking for a way to use this library with a minimum of Java\Kotlin code. Only by autogenerating, as it is possible in Libtorrent.

**Comment by MarcoPolo** [comment]
Berty is doing something similar, maybe their codebase could give you some pointers: https://github.com/berty/berty

**Comment by master255** [comment]
@MarcoPolo Thank you for this example. But it's complicated for someone who doesn't know gomobile. Your project is complicated, so we need something easier. Working methods in gomobile would be fine.

Perhaps you can do something to help at least start creating these methods? I need to at least understand why I don't have any methods at all. Perhaps there are? I don't understand)))

This is what I got. https://mega.nz/file/g5VCXTLY#MgMbm_FkcKorUIw3Ojn9fuPrNmAZr3lGU5sPyzLcvVY

**Comment by master255** [comment]
Solved the problem with this code:

`package mobile

import (
	"context"
	"fmt"
	"github.com/libp2p/go-libp2p/p2p/net/connmgr"
	"log"
	"time"

	"github.com/libp2p/go-libp2p"
	dht "github.com/libp2p/go-libp2p-kad-dht"
	"github.com/libp2p/go-libp2p/core/crypto"
	"github.com/libp2p/go-libp2p/core/host"
	"github.com/libp2p/go-libp2p/core/routing"
	"github.com/libp2p/go-libp2p/p2p/security/noise"
	libp2ptls "github.com/libp2p/go-libp2p/p2p/security/tls"
)

type MobileLibp2p struct {
	node *host.Host
}

func StartLibp2p() *MobileLibp2p {
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// To construct a simple host with all the default settings, just use `New`
	h, err := libp2p.New()
	if err != nil {
		panic(err)
	}
	defer h.Close()

	log.Printf("Hello World, my hosts ID is %s\n", h.ID())

	// Now, normally you do not just want a simple host, you want
	// that is fully configured to best support your p2p application.
	// Let's create a second host setting some more options.

	// Set your own keypair
	priv, _, err := crypto.GenerateKeyPair(
		crypto.Ed25519, // Select your key type. Ed25519 are nice short
		-1,             // Select key length when possible (i.e. RSA).
	)
	if err != nil {
		panic(err)
	}

	var idht *dht.IpfsDHT

	connmgr, err := connmgr.NewConnManager(
		100, // Lowwater
		400, // HighWater,
		connmgr.WithGracePeriod(time.Minute),
	)
	if err != nil {
		panic(err)
	}
	h2, err := libp2p.New(
		// Use the keypair we generated
		libp2p.Identity(priv),
		// Multiple listen addresses
		libp2p.ListenAddrStrings(
			"/ip4/0.0.0.0/tcp/9000",      // regular tcp connections
			"/ip4/0.0.0.0/udp/9000/quic", // a UDP endpoint for the QUIC transport
		),
		// support TLS connections
		libp2p.Security(libp2ptls.ID, libp2ptls.New),
		// support noise connections
		libp2p.Security(noise.ID, noise.New),
		// support any other default transports (TCP)
		libp2p.DefaultTransports,
		// Let's prevent our peer from having too many
		// connections by attaching a connection manager.
		libp2p.ConnectionManager(connmgr),
		// Attempt to open ports using uPNP for NATed hosts.
		libp2p.NATPortMap(),
		// Let this host use the DHT to find other hosts
		libp2p.Routing(func(h host.Host) (routing.PeerRouting, error) {
			idht, err = dht.New(ctx, h)
			return idht, err
		}),
		// If you want to help other peers to figure out if they are behind
		// NATs, you can launch the server-side of AutoNAT too (AutoRelay
		// already runs the client)
		//
		// This service is highly rate-limited and should not cause any
		// performance issues.
		libp2p.EnableNATService(),
	)
	if err != nil {
		panic(err)
	}
	defer h2.Close()

	// The last step to get fully up and running would be to connect to
	// bootstrap peers (or any other peers). We leave this commented as
	// this is an example and the peer will die as soon as it finishes, so
	// it is unnecessary to put strain on the network.

	/*
		// This connects to public bootstrappers
		for _, addr := range dht.DefaultBootstrapPeers {
			pi, _ := peer.AddrInfoFromP2pAddr(addr)
			// We ignore errors as some bootstrap peers may be down
			// and that is fine.
			h2.Connect(ctx, *pi)
		}
	*/
	log.Printf("Hello World, my second hosts ID is %s\n", h2.ID())
	return &MobileLibp2p{
		node: &h,
	}
}
`
