### ISSUE TITLE
Android 12 does not work UPNP, NAT-PMP

### ISSUE THREAD

**Issue by master255** [libp2p/go-libp2p#2288]
I use [my code](https://github.com/libp2p/go-libp2p/issues/2282#issuecomment-1546903352) to compile the Android library.
I run Mobile.startLibp2p() and under Android 8 ports 9000 UPNP, NAT-PMP open, but under Android 12 not.

We already had this problem on the Libtorrent project. There it was about new ifaddrs sockets. They fixed it quickly there https://github.com/arvidn/libtorrent/pull/7396/files

How to fix it here?

**Comment by master255** [comment]
@marten-seemann All I want to know now is. Will this bug be fixed in the near future or not? 

Library with[ my host creation code](https://github.com/libp2p/go-libp2p/issues/2282#issuecomment-1546903352). It opens upnp ports on Android 29- and does not open on Android 30+.
Now all modern devices run mostly on Android 30+.
https://mega.nz/file/c4lw0ZRQ#wczWFPW3BPBRtOOZ_5n9ynVpUoc59iMTg1ZUODx_YsI

**Comment by marten-seemann** [comment]
I have no experience with Android development, and I'm not sure I fully understand the problem here. quic-go already uses ifaddrs for deciding which interface a packet should be sent on. Not sure if that's enough to fix this problem

The libp2p team at PL has other priorities at the moment, and we won't be able to work on this any time soon. If you want to submit a patch to go-libp2p, I'd be happy to review though.

**Comment by master255** [comment]
@marten-seemann You don't need to program in Android. This problem needs to be solved in Go. Android has only one line of code to run: Mobile.startLibp2p()

You need to install gomobile on your Linux. 
Then create a file mobile.go in the mobile directory. Put my code there. Run the compilation of gomobile: gomobile bind -target=android -o /mnt/c/Users/User/Documents/MyAndroidApplication/app/libs/libp2p.aar

Then add this line to the Android build.gradle file:
implementation files('libs/libp2p.aar')
In the start of the application add Mobile.startLibp2p()
Run the project on your Android 10-(device. An emulator is not suitable).
Make sure that upnp ports are open.
Run the project on Android 11+ and make sure that the ports are not open.

**Then change the Go library so that the ports start to open.**

If you have any questions, ask me.

**Comment by marten-seemann** [comment]
> You need to install gomobile on your Linux. Then create a file mobile.go in the mobile directory. Put my code there. Run the compilation of gomobile: gomobile bind -target=android -o /mnt/c/Users/User/Documents/MyAndroidApplication/app/libs/libp2p.aar
> 
> Then add this line to the Android build.gradle file: implementation files('libs/libp2p.aar') In the start of the application add Mobile.startLibp2p() Run the project on your Android 10-(device. An emulator is not suitable). Make sure that upnp ports are open. Run the project on Android 11+ and make sure that the ports are not open.

This is a lot to ask for. Especially for people who don't own an Android device.

As I've said before, the team currently has other priorities. We're happy to review a PR, but other than that, I'm afraid we won't be able to solve your problems for you.

**Comment by master255** [comment]
@marten-seemann Now I think the problem is not with the port types, but with the requests to the router to open the upnp port.

**Comment by p-shahi** [comment]
@master255 I'm going to close this issue for the same reasons mentioned. Supporting android is not a priority.

**Comment by master255** [comment]
@marten-seemann @p-shahi  I haven't figured out how nat works in libp2p.
Started looking at more examples and realized that upnp works on Android 11+.

Great library! Solves a lot of problems in the world of decentralization. Thanks for developing it!
