### ISSUE TITLE
identify: consider dropping the protocol version

### ISSUE THREAD

**Issue by p-shahi** [libp2p/go-libp2p#2294]
Go through old kubo and libp2p versions that implemented the identify protocol versions, cross reference in probelabs to see which are still in use, and see if we can drop the `/ipfs/0.1.0` protocol version altogether

**Comment by mxinden** [comment]
For what it is worth, I can not find a version of rust-libp2p that ever supported `/ipfs/0.1.0`. Already since https://github.com/libp2p/rust-libp2p/pull/116 rust-libp2p uses `/ipfs/id/1.0.0`.

**Comment by marten-seemann** [comment]
This was dropped in https://github.com/libp2p/go-libp2p/pull/461, almost 5 years ago. This should be safe to remove now.

**Comment by marten-seemann** [comment]
@achingbrain Would this change break compatibility with js-libp2p versions?

**Comment by achingbrain** [comment]
It should be fine - js-libp2p only uses the protocol version field as peer metadata and doesn't act on it
