### ISSUE TITLE
TestRateLimiting random failure

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#23]
https://travis-ci.org/ipfs/go-libp2p/jobs/113809892

**Comment by Stebalien** [comment]
Unfortunately, I was able to reproduce this once fairly easily so I know it's still a problem. But... I can't reproduce it again :(.

**Comment by anacrolix** [comment]
I'm not able to reproduce this `github.com/libp2p/go-libp2p/p2p/net/mock`? with or without the race detector and 100s of runs. Also the Travis log is no longer accessible.
