### ISSUE TITLE
Default setting can reverse the connection direction

### ISSUE THREAD

**Issue by frystal** [libp2p/go-libp2p#2302]
Hi!

When i test test the go-libp2p, i find that the dial fucntion will always make a connection to the target peer with the Direction "Outbound".  And the NewStream function will uses the dial function to make a connection to the target peer if there is not activate conntions. Thus, i can reverse the connection direction from Inbound to Outbound by closing the connection before the local peer execude the NewStream function.

For instance, i set up two nodes A and B. Both of  the nodes run the default libp2p instance.  I set the node B will call the NewStream to A after 5 seconds. I first make a TCP connection from A to B. For B, it will have an Inbound connection from A. Then A closes the TCP connection by sending EOF to B. After 5 seconds the B call the NewStream function and make an Outbound connection to A.  

I think it can be a bug in the libp2p since the attacker can control the connection direction

**Comment by marten-seemann** [comment]
This behavior is correct, as it accurately reports the directionality of the underlying connection.
