### ISSUE TITLE
update quic-go to v0.36.1

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2318]
quic-go just released a major refactor of the connection establishment API: https://github.com/quic-go/quic-go/releases/tag/v0.35.0.

This upgrade will require some work, since we now can't (and must not) reuse the same `net.UDPConn` for multiple dial / listen calls. Before v0.35.0 this was the way to reuse one underlying connection, but now this behavior is made explicit via the `quic.Transport`.

**Comment by marten-seemann** [comment]
@MarcoPolo Would you be able to take this issue? It would be great to see if the new quic-go API is actually usable and understandable by someone who hasn't designed it.

**Comment by MarcoPolo** [comment]
Can do

**Comment by marten-seemann** [comment]
We should hold off on v0.36.0, since there's still a GSO issue that needs to be resolved: https://github.com/quic-go/quic-go/issues/3911. We can go ahead with v0.35.1 though, there's no breaking API change between v0.35.1 and v0.36.0 that would concern us in libp2p, so that upgrade will be trivial.

**Comment by marten-seemann** [comment]
[quic-go v0.36.1](https://github.com/quic-go/quic-go/releases/tag/v0.36.1) disables GSO by default, and should be safe to use in go-libp2p.
