### ISSUE TITLE
Use CancelWithCause in swarm.dialPeer for better metrics reporting

### ISSUE THREAD

**Issue by sukunrt** [libp2p/go-libp2p#2321]
By using https://pkg.go.dev/context#CancelCauseFunc in swarm.dialPeer we can detect if we cancelled because we received a connection while tracking metrics. This will help us understand if we are cancelling because we received a connection or because the caller cancelled the call for some reason. 

Since this type is not available in go 1.19 we might have to wait till go1.21 to tackle this.

**Comment by marten-seemann** [comment]
This is unblocked now, since we switched to Go 1.20. @sukunrt, should we get this into the v0.31 release?

**Comment by sukunrt** [comment]
Yeah, it'd be nice to get this in. Thanks for the reminder. I've raise a PR.
