### ISSUE TITLE
DedupAddrs should not allocate

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/go-libp2p#2323]
Sort.Slice will allocate unfortunately :( 
https://github.com/golang/go/issues/17332

```
func BenchmarkDedupAddrs(b *testing.B) {
	b.ReportAllocs()
	tcpAddr := ma.StringCast("/ip4/127.0.0.1/tcp/1234")
	quicAddr := ma.StringCast("/ip4/127.0.0.1/udp/1234/quic-v1")
	wsAddr := ma.StringCast("/ip4/127.0.0.1/tcp/1234/ws")
	addrs := []ma.Multiaddr{tcpAddr, quicAddr, tcpAddr, quicAddr, wsAddr}
	for i := 0; i < b.N; i++ {
		addrs = DedupAddrs(addrs)
	}
}
```

_Originally posted by @sukunrt in https://github.com/libp2p/go-libp2p/pull/2322#discussion_r1214801840_

**Comment by sukunrt** [comment]
I just wanted to fix the comment. 
fix here: https://github.com/libp2p/go-libp2p/pull/2350
The allocations are low(3/op) so it's fine to leave it as is. Converting it to an O(n^2) in place algorithm might lead to performance issues. It is an overkill implementing a custom no allocation O(nlgn) algorithm for this.

**Comment by marten-seemann** [comment]
Are you sure there’s a performance penalty for a O(N^2) for small N? I’d expect it to be negligible for typical values of N.

**Comment by marten-seemann** [comment]
There's https://pkg.go.dev/golang.org/x/exp/slices, which provides allocation-free sorting. I created #2395 to make use of that package.
