### ISSUE TITLE
consider reverting peerstore context changes

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2327]
I just merged #2312, and tried building Kubo. This is creating build errors all over the place (Kubo itself, Kademlia, Gossipsub). Upgrading libp2p will be extremely painful if we cut a release now.

I'm wondering if we really need this. Does respecting cancelations actually make sense if we don't get any result back from the peerstore that a call failed (e.g. an error on `Put`)? Now we can set a context with deadline, but we have no idea if the change was actually committed when that call returns.

What was the motivation behind #2231 anyway?

cc @chaitanyaprem @sukunrt @MarcoPolo

**Comment by chaitanyaprem** [comment]
I did not expect it would break multiple things.
As you have mentioned above, context would only be required in case of database backed peer store. I was not aware that this is not used by many, but i do agree with your point as mentioned in  https://github.com/libp2p/go-libp2p/issues/2329 .

Sorry for the trouble.

**Comment by marten-seemann** [comment]
@chaitanyaprem No need to be sorry. Actually, this is our fault. We didn’t clearly think through the implications of this when we marked this issue as “help wanted”. I’m sorry.
