### ISSUE TITLE
Too long a period of Advertise

### ISSUE THREAD

**Issue by master255** [libp2p/go-libp2p#2348]
@marten-seemann @MarcoPolo [Libtorrent's instructions](https://www.libtorrent.org/dht_store.html) say to republish every hour.
The [code here](https://github.com/libp2p/go-libp2p/blob/1b0df37769a6c5ffa0e2db0d1cd3d59cb443e65b/p2p/discovery/routing/routing.go#L36) does it every 3 hours.
I checked. This is a bug. If re-publish every 3 hours, the information is unavailable to those who connect. Since DHT works about the same as Libtorrent and Libtorrent is a more stable library, I think it is necessary to change to publishing once every 1 hour. Otherwise, it won't work.

**Comment by marten-seemann** [comment]
We're not using the libtorrent DHT, we're using https://github.com/libp2p/go-libp2p-kad-dht.

**Comment by master255** [comment]
@marten-seemann But the working principle is the same. And I could not get the data the next day after publishing in this way. So the period is too long.

**Comment by marten-seemann** [comment]
It depends on how long records are stored and on the churn rate in the network. ProbeLab has extensive measurement regarding those.
