### ISSUE TITLE
ci: add a link checker GitHub Action cron job

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2364]
We have a lot of Markdown here that contains links. We should consider using a link checker to make sure that links remain up-to-date. For example https://github.com/gaurav-nelson/github-action-markdown-link-check.

**Comment by marten-seemann** [comment]
This should have caught #2363.

**Comment by marten-seemann** [comment]
@p-shahi Could you help us set up that automation? Using a cron job once per day (or every couple of days) is probably the best approach here.

**Comment by SahibYar** [comment]
please review this PR https://github.com/libp2p/go-libp2p/pull/2406
