### ISSUE TITLE
Question about adjusting delay in mdns implementation

### ISSUE THREAD

**Issue by elarivie** [libp2p/go-libp2p#2368]
#### Location

https://github.com/libp2p/go-libp2p/blob/2d490caf44c913e315a4ef056ec38ad7da4aa49d/examples/chat-with-mdns/mdns.go#L25

#### Description

Hello,

I am new to libp2p and have been exploring the mdns functionality using the provided example. While going through the code, I came across a [comment](https://github.com/libp2p/go-libp2p/blob/2d490caf44c913e315a4ef056ec38ad7da4aa49d/examples/chat-with-mdns/mdns.go#L25) that suggests the mdns process is triggered every hour. The comment also mentions that this setting is suitable for the example but may need adjustment in a real scenario.

However, I couldn't find any explicit way to adjust this delay in the code. It appears that the comment might be outdated and no longer applicable.

Upon reviewing the [commit history](https://github.com/libp2p/go-libp2p/pull/1161/files/81c5b23e7cb565c25c2767cec456eba3bc27679c#diff-eb97aa374232efd54cbbf8b3fdc84696f4e2d0af3938f987afeb1dede1123eb4), I discovered that there was a legacy implementation of mdns where the signature of the NewMdnsService function changed. The time delay parameter of one hour was removed:

Old signature:

```go
ser, err := discovery.NewMdnsService(ctx, peerhost, time.Hour, rendezvous)
```

New signature:

```go
ser, err := discovery.NewMdnsService(peerhost, rendezvous)
```

Based on this change, I have a few questions regarding the behavior of the mdns service:

Is the mdns service now only triggered once on start, rather than at regular intervals?
How long does the mdns service listen for responses? Should we periodically trigger a new mdns call, and if so, how?
Is it recommended to periodically close the mdns service after a certain delay and relaunch it?

I would appreciate any clarification on these points to help me understand the updated behavior of the mdns implementation in libp2p.

Thank you for your assistance.

Best regards

**Comment by marten-seemann** [comment]
The one hour comes from https://datatracker.ietf.org/doc/html/rfc6762#section-5.2, doesn't it?

**Comment by elarivie** [comment]
@marten-seemann Thanks for your quick response,

looking into [mdns.go](https://github.com/libp2p/go-libp2p/blob/master/p2p/discovery/mdns/mdns.go) I don't see any reference to the one hour delay, the whole mdns call seems to be done once on start-up, **and never again**

is the correct usage of the library is to call start() multiple time?... something like:
```
ser, err := discovery.NewMdnsService(peerhost, rendezvous)
defer ser.Close()
for {
    ser.Start()
    time.Sleep(...) // At least an hour to respect the rfc6762 see quote below
}
```

From rfc6762

> When the interval between queries reaches or exceeds 60 minutes, a
   querier MAY cap the interval to a maximum of 60 minutes, and perform
   subsequent queries at a steady-state rate of one query per hour.

**Comment by marten-seemann** [comment]
That's the responsibility of the mdns implementation.
