### ISSUE TITLE
quic: drop support for QUIC draft-29

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2369]
This doesn't require a quic-go update including https://github.com/quic-go/quic-go/pull/3903, we can just disable it in the `quic.Config`. See https://github.com/ipfs/kubo/issues/9496 for context.

**Comment by p-shahi** [comment]
quic-v1 was added 6 months ago in 0.24.0 https://github.com/libp2p/go-libp2p/releases/tag/v0.24.0
There will be failures in nodes that only support draft-29, the nodes that don't speak quic-v1 will instead dial using TCP.
This is in scope for kubo 0.22 per https://github.com/orgs/ipfs/projects/16/views/3?filterQuery=iteration%3A%22kubo+0.22%22+quic

**Comment by p-shahi** [comment]
done in https://github.com/libp2p/go-libp2p/pull/2487
