### ISSUE TITLE
Hole Punching: Is there any example for hole punching usage?

### ISSUE THREAD

**Issue by uzqw** [libp2p/go-libp2p#2378]
I have read the code of this project for a week, but still don't know  how to use the function of hole punching.
In my opinion, it has three machines to finish this work, but I can't find help from the test code and examples related to hole punching.
Anyone can help?

**Comment by sukunrt** [comment]
rust libp2p has a nice overview for hole punching: https://docs.rs/libp2p/latest/libp2p/tutorials/hole_punching/index.html

If you want to understand how holepunching works you can read the specs here: https://github.com/libp2p/specs/blob/master/relay/DCUtR.md

If you want to know more about the theory, there's a short paper: https://research.protocol.ai/publications/decentralized-hole-punching/seemann2022.pdf

To enable hole punching in libp2p you just need to start the host with the `libp2p.EnableHolePunching` option, if your node is private it should start hole punching automatically when another peer connects to it. 

I'm closing this as these questions are better served by https://discuss.libp2p.io/
or #libp2p-implementers on the [filecoin slack](https://filecoinproject.slack.com/)

**Comment by uzqw** [comment]
@sukunrt Thank you ~  you helped me a lot !
