### ISSUE TITLE
identify: stuck at reading multistream header

### ISSUE THREAD

**Issue by dennis-tra** [libp2p/go-libp2p#2379]
I recently updated [`Nebula`](https://github.com/dennis-tra/nebula) to use `go-libp2p` v0.28.0. Further, when I crawl another peer, I started to explicitly wait for the Identify exchange to complete before extracting data from the peerstore.

Over the weekend, I saw that two crawls, which usually take ~5m, didn't terminate after >12h. I extracted a `goroutine` dump which is attached below.

From that dump, I found out that one of the 1,000 crawl-workers is waiting to receive an event from a channel:

<img width="410" alt="image" src="https://github.com/libp2p/go-libp2p/assets/11836793/c440db29-14b9-441f-aa86-fa38a7dc971e">

I dug deeper into what it's waiting for and found that it should be [this `select`- statement](https://github.com/dennis-tra/nebula/blob/2317f90c8fbdba9107b2f36503df842b0e1d9532/pkg/crawl/crawl_p2p.go#L229). Here the excerpt:

```go
select {
case <-ctx.Done():
   // ...
case <-c.host.IDService().IdentifyWait(conn):
   // ...
}
```

So, it's waiting for the `identify` exchange to complete. If I interpret the goroutine dump correctly, it's hanging at:

- [`SelectProtoOrFail`](https://github.com/libp2p/go-libp2p/blob/5e3fc8aedfdba9679921f9bb2d12f953d9e7a873/p2p/protocol/identify/id.go#L425)
- [`readMultistreamHeader`](https://github.com/multiformats/go-multistream/blob/5b2f48e2db22aa1db90bb5a21aa4e6702d4ee33c/client.go#L66) (`go-multistream`)
- [`ReadNextToken`](https://github.com/multiformats/go-multistream/blob/5b2f48e2db22aa1db90bb5a21aa4e6702d4ee33c/client.go#LL331C14-L331C27) (`go-multistream`)

It seems like it can't read the multistream header from the identify stream. My hypotheses: 1) the remote peer is just super slow to respond, or 2) something hung internally, or 3) something else?

I had expected some of the various timeouts across the stack to kick in (transport dial timeouts, security handshake timeouts, connection timeouts, etc.) and cancel the exchange.

My fix, for now, is to time out after 15s:

```go
timeoutCtx, cancel := context.WithTimeout(ctx, 15*time.Second)
defer cancel()

select {
case <-timeoutCtx.Done():
   // ...
case <-c.host.IDService().IdentifyWait(conn):
   // ...
}
```

However, I think this leaks resources if the above happens again.

Hyper speculative: If this proves to be not and issue on my end, could this be abused in a slowloris-like fashion?

---

[goroutine.zip](https://github.com/libp2p/go-libp2p/files/11782197/goroutine.zip)

**Comment by Wondertan** [comment]
We had similar issues a while ago, and the core reason is explained in https://github.com/libp2p/go-libp2p/issues/2361. This behavior happens when remote peer deadlocks during the connection handling in Swarm. In the linked case, it happens because the Swarm't deadlocked on emitting the event. [This](https://github.com/libp2p/go-libp2p/pull/2373) may also explain this, so trying on future v0.28.1 is worth a shot.

**Comment by MarcoPolo** [comment]
I'm still curious what caused the original hang.
