### ISSUE TITLE
transport tests: flaky TestMoreStreamsThanOurLimits test

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2384]
https://github.com/libp2p/go-libp2p/actions/runs/5331320944/jobs/9659013128

```
=== RUN   TestMoreStreamsThanOurLimits/WebSocket
      transport_test.go:468: 
          	Error Trace:	/home/runner/work/go-libp2p/go-libp2p/p2p/test/transport/transport_test.go:468
          	Error:      	Not equal: 
          	            	expected: 1024
          	            	actual  : 1023
          	Test:       	TestMoreStreamsThanOurLimits/WebSocket
```

**Comment by marten-seemann** [comment]
This test is flaking a lot, and currently responsible for roughly half of our CI failures:
<img width="505" alt="image" src="https://github.com/libp2p/go-libp2p/assets/1478487/8f18152b-158f-45c6-b46d-9b6423e3a345">

**Comment by MarcoPolo** [comment]
Hmm even webtransport flakes here. Let me rethink this test.
