### ISSUE TITLE
make deps not work.

### ISSUE THREAD

**Issue by jerry-sl** [libp2p/go-libp2p#240]
#### follow docments step.
```
make 
make deps
```

#### got results:

```
successfully found all deps for go-libp2p
  - go-libp2p depends on go-semver (QmcrrEpx3VMUbrbgVroH3YiYyUS5c4YAykzyPJWKspUYLa)
successfully found all deps for go-semver
[done] [install] go-semver                QmcrrEpx3VMUbrbgVroH3YiYyUS5c4YAykzyPJWKspUYLa 0s
  - go-libp2p depends on mdns (QmWSvDKkcno2UyDg13rUBwWfhRsdj7uR3daAq57VoG5QeN)
[1 / 2] fetched dep: go-net
[2 / 2] fetched dep: dns
successfully found all deps for mdns
  - mdns depends on dns (QmWchsfMt9Re1CQaiHqPQC1DrZ9bkpa6n229dRYkGyLXNh)
successfully found all deps for dns
[done] [install] dns                      QmWchsfMt9Re1CQaiHqPQC1DrZ9bkpa6n229dRYkGyLXNh 0s
  - mdns depends on go-net (QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC)
  - Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ not found locally, fetching into /home/jerry/go/src/gx/ipfs/Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ
[get ] [fetch]   go-text                  Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ
[2 / 104] 0sFound previously failed fetch, cleaning up...
  - fetching Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ via ipfs api
```

#### computer environments:

```
$ go version
go version go1.9.2 linux/amd64

$ which go
/usr/local/go/bin/go

$ echo $GOPATH
/home/jerry/go
```

**Comment by Stebalien** [comment]
Hm. It may not have been pinned properly. Could you try again?

**Comment by jerry-sl** [comment]
Tried many times, got some result.  

My computer was behind firewall, golang.org was blocked. I installed crypto, net, tools, text by first pull down from github.com. Copy  $GOPATH/src/github.com/golang/(crypto, net, tools, text) to $GOPATH/src/golang.org/x/(crypto, net, tools, text).  Finally use go install to install these package.

```
$ go install text
```
failed with error: "can't load package: package text: no Go files in /usr/local/go/src/text"

**Comment by Kubuxu** [comment]
@jerry-sl go tools by default work with `GOPATH` as reference, you have to prefix them with `.` to get them to use current directory.

**Comment by Stebalien** [comment]
> My computer was behind firewall, golang.org was blocked.

Is ipfs.io blocked? That's where we try to download gx packages form.

**Comment by jerry-sl** [comment]
ipfs.io is not blocked.  I try go-libp2p on my mac os x, it worked. 
 Ubuntu 17.10 still not work.  
Now i have a worked box, i will close this issue. Thanks for helps.
