### ISSUE TITLE
Race in TestDirectDialWorks

### ISSUE THREAD

**Issue by MarcoPolo** [libp2p/go-libp2p#2411]
https://github.com/libp2p/go-libp2p/actions/runs/5470148505/jobs/9959884856?pr=2410#step:10:1703

@sukunrt any chance this is related to smart dialing changes?

**Comment by sukunrt** [comment]
This test is super hacky. 

```
	// mark all addresses as public
	cpy := manet.Private4
	manet.Private4 = []*net.IPNet{}
	defer func() { manet.Private4 = cpy }()
```

It's related to black hole detection. We check whether an address is public or not when checking for black hole status. That check depends on manet.Private and this test modifies manet.Private. 

I need to check why there is no synchronisation between that check in swarm.dialAddr and this write in defer. 

We can skip this test for now, or keep it as is. Once https://github.com/libp2p/go-libp2p/pull/2403 is in, we can modify this test to disable black hole detection.
