### ISSUE TITLE
examples: chat-with-mdns example should open only 1 stream per peer

### ISSUE THREAD

**Issue by sukunrt** [libp2p/go-libp2p#2418]
Currently both the sides call this [line](https://github.com/libp2p/go-libp2p/blob/master/examples/chat-with-mdns/main.go#L127) leading to two streams. For this particular app this behaviour is not observable but as an example in the repo it is very confusing. We should fix it to call `NewStream` from only one side. 

Originally reported here: https://filecoinproject.slack.com/archives/C03K82MU486/p1688981568223099

**Comment by dhairya0904** [comment]
Hi
I would like to fix this issue. Can anyone please explain, what needs to be done here?

**Comment by MarcoPolo** [comment]
Thanks! The original comment has context. Did you run into any issues?

**Comment by Halimao** [comment]
@sukunrt Hi sir, just opened an pr to close this issue, thanks for your review😀
