### ISSUE TITLE
identify/id.go: `filterAddrs` should not be used

### ISSUE THREAD

**Issue by wlynxg** [libp2p/go-libp2p#2440]
In the Identify service code, I noticed that the filterAddrs function was added in the June update, which is used in the following context:
```go
func (ids *idService) consumeMessage(mes *pb.Identify, c network.Conn, isPush bool) {
        ......
	ids.Host.Peerstore().AddAddrs(p, filterAddrs(addrs, c.RemoteMultiaddr()), ttl)
        ......
}
```
About the filterAddrs function:
```go
// filterAddrs filters the address slice based on the remove multiaddr:
// * if it's a localhost address, no filtering is applied
// * if it's a local network address, all localhost addresses are filtered out
// * if it's a public address, all localhost and local network addresses are filtered out
func filterAddrs(addrs []ma.Multiaddr, remote ma.Multiaddr) []ma.Multiaddr {
	if manet.IsIPLoopback(remote) {
		return addrs
	}
	if manet.IsPrivateAddr(remote) {
		return ma.FilterAddrs(addrs, func(a ma.Multiaddr) bool { return !manet.IsIPLoopback(a) })
	}
	return ma.FilterAddrs(addrs, manet.IsPublicAddr)
}
```

I believe that this function should not be used to filter out private network addresses, as it can lead to the following problem:
When two nodes are both behind the same NAT with a public IP address, using this filter function will cause the DHT nodes to only store the public IP addresses of the two nodes. When the two nodes establish a connection, they will send packets to each other's public IP addresses. However, most routers do not support [NAT loopback](https://en.wikipedia.org/wiki/Network_address_translation#NAT_hairpinning) ( also known as NAT loopback or NAT reflection), which can cause the packets sent between the two nodes to be discarded by the router, resulting in a failed connection between the nodes.

**Comment by marten-seemann** [comment]
Your analysis is correct, but this is an exceedingly rare occasion. On the other hand, we were seeing tons and tons of spurious dials to localhost and local addresses from nodes that are not on the same network.

**Comment by wlynxg** [comment]
> Your analysis is correct, but this is an exceedingly rare occasion. On the other hand, we were seeing tons and tons of spurious dials to localhost and local addresses from nodes that are not on the same network.

Thank you for your response.

First of all, I think your purpose of filtering intranet addresses is completely correct. It helps reduce invalid data packets sent by clients and also helps conceal the details of the intranet where the node resides.

Secondly, I believe that for DHT nodes, they should maintain a pure functionality of storing and querying data. I have noticed that older DHT nodes do not perform intranet address filtering. By adding this filtering behavior to new nodes while old nodes do not filter, it creates uncertainty in client behavior.

I think the decision of whether to filter intranet addresses should be made by the party publishing and receiving the data. We can add an option for regular nodes to choose whether to filter intranet addresses, which might be a good approach.

**Comment by marten-seemann** [comment]
Yes, nodes should be more careful what they advertise to the DHT. However, we can't just trust that they're doing that, nodes might be misbehaving (some of them even intentionally). That's why we need to do filtering on the client side as well.
