### ISSUE TITLE
webrtc: run on the same UDP socket as QUIC

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#2446]
In principle, there's nothing that would prevent us from running WebRTC, QUIC and WebTransport on the same UDP socket.
I'm not sure if the Pion API would allow us to do that though.

This will require https://github.com/quic-go/quic-go/issues/3929.

**Comment by lidel** [comment]
@MarcoPolo anything left to do here, or was this fixed in
- https://github.com/libp2p/go-libp2p/pull/2889
- https://github.com/libp2p/go-libp2p/pull/2936 
?
