### ISSUE TITLE
ecdsa.GenerateKey non-deterministic in 1.20

### ISSUE THREAD

**Issue by maiph** [libp2p/go-libp2p#2447]
Not really a bug now but giving awareness of a potential issue.
Go 1.20 made crypto/ecdsa.GenerateKey non-deterministic https://github.com/golang/go/issues/58637, just wanted to leave a notice here since the lib is using it [here](https://github.com/libp2p/go-libp2p/blob/4c897e0769fbe7b74c3e7e941eee9527921548b0/core/crypto/ecdsa.go#L53C1-L54)

<details>
<summary>Version Information</summary>
<pre>

</pre>
</details>

**Comment by marten-seemann** [comment]
We've been building with Go 1.20 for the last ~5 months, and haven't run into any problems.
