### ISSUE TITLE
Relay reconnection doesn't work

### ISSUE THREAD

**Issue by master255** [libp2p/go-libp2p#2452]
@marten-seemann @MarcoPolo @sukunrt @Stebalien @raulk 
[I figured out how to connect via Relay.](https://gist.github.com/master255/c63091a1b05a67ed33c8c248f748fd0f) I use autorelay with automatic peer search and static peers. The peers do not repeat.
Scenario:
Server - without NATPortMap
Two clients with NATPortMap and white ip address that have access to the server and are relays.
And a client that is in 4G and has no open ports and cannot contact the server directly.

All computers are powered on. I turn on the client that is on 4G and it quickly connects to the server.
Then I turn off the client completely and immediately start it up again. The client goes into an endless loop trying to connect to the server.

However, if I wait about 5 minutes before turning the client on, it connects to the server fine.
It turns out that the server or relays do not allow the client to connect to the server frequently through relays (there are no such problems in the same network)

Question: what setting or what should be closed so that the client in 4G could quickly reconnect to the server through relays????
Perhaps the server does not know that the client has left the program and thinks that the client wants to establish a second connection and therefore does not allow it to do so. How to fix it?

**Comment by marten-seemann** [comment]
Please stop randomly tagging people.

**Comment by master255** [comment]
@marten-seemann These are all people from protocol labs. I checked

**Comment by marten-seemann** [comment]
There’s no need to tag us, no matter where we’re working. It’s just spammy.

**Comment by master255** [comment]
@marten-seemann But why won't anyone help me?

**Comment by marten-seemann** [comment]
We're all busy developers working on various parts of the libp2p stack. We will reply to your issue at some point, but don't expect a response within hours. No amount of tagging us will expedite your issue.

It would also help if you'd put more effort into writing up your issue clearly, and doing some debugging yourself.

**Comment by master255** [comment]
@marten-seemann Maybe I should have waited a little longer. Now, with two relays the connection with the server is more stable. And it is possible to turn off the application and immediately turn it on. The connection is there.

I think that would be enough for me to answer - is there even such a mechanism to notify the server when the connection is closed via relay? Or timings? At least in general terms?
