### ISSUE TITLE
quicreuse tries to access non-existing config value

### ISSUE THREAD

**Issue by bahner** [libp2p/go-libp2p#2479]
Since quic-go was updated 5 days, ago - I think this was when it hit. Thes errors started occuring. I have spent some days debugging, but I'm at a lost for ideas. I think maybe this might be more disjunctive errors, but I feel like this is something that should be looked into.

I can't in any way debug more in the running application. And I can't get more info out of the compiler. I have really tried.

The error is caused by libp2p.New() without any config or with some sane defaults specified.

# github.com/libp2p/go-libp2p/p2p/transport/quicreuse
../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.29.2/p2p/transport/quicreuse/config.go:20:45: undefined: quic.VersionDraft29
../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.29.2/p2p/transport/quicreuse/connmgr.go:186:22: undefined: quic.VersionDraft29
../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.29.2/p2p/transport/quicreuse/connmgr.go:187:49: undefined: quic.VersionDraft29
../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.29.2/p2p/transport/quicreuse/connmgr.go:255:14: undefined: quic.OptimizeConn
../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.29.2/p2p/transport/quicreuse/listener.go:49:50: undefined: quic.VersionDraft29
../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.29.2/p2p/transport/quicreuse/listener.go:92:53: conn.ConnectionState().TLS.ConnectionState undefined (type tls.ConnectionState has no field or method ConnectionState)
../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.29.2/p2p/transport/quicreuse/quic_multiaddr.go:23:12: undefined: quic.VersionDraft29
../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.29.2/p2p/transport/quicreuse/quic_multiaddr.go:38:19: undefined: quic.VersionDraft29

**Comment by MarcoPolo** [comment]
You've updated quic-go to a version that's incompatible with go-libp2p v0.29.x. Downgrade to quic-go v0.36.x.

We have a PR that updates quic-go (#2478) but until that's merged, you won't be able to use the newer version of quic-go.
