### ISSUE TITLE
examples:https-proxy:on a separate machine

### ISSUE THREAD

**Issue by outprog** [libp2p/go-libp2p#248]
i run `./http_proxy` on machine A, output:
```
Proxy server is ready
libp2p-peer addresses:
/ip4/192.168.254.62/tcp/12000/ipfs/QmXBuLYVmDK2cKGLUnnku3TkJytQopeqip6SfUJzggjuyy
```

then, run 
```
./http_proxy -d /ip4/192.168.254.62/tcp/12000/ipfs/QmXBuLYVmDK2cKGLUnnku3TkJytQopeqip6SfUJzggjuyy
```
on machine B, output:
```
Proxy server is ready
libp2p-peer addresses:
/ip4/127.0.0.1/tcp/12001/ipfs/QmNd9xzbysiAfqhavp1SYUPKiccvR4GiBqkfwANHEeQC8Q
proxy listening on  127.0.0.1:9900
```

now, type 
```
curl -x "127.0.0.1:9900" "http://ipfs.io/ipfs/QmfUX75pGRBRDnjeoMkQzuQczuCup2aYbeLxz5NzeSu9G6"
```
on machine B, it's not work. output:
```
2017/11/27 11:45:45 dial attempt failed: <peer.ID Nd9xzb> --> <peer.ID XBuLYV> dial attempt failed: operation timed out
```

is this network problem? how can i fix it? thank u!

**Comment by Stebalien** [comment]
Probably. You'll have open tcp/12000 on machine A's firewall (and this will only work if those machines are on the same network as you're using private IP addresses).

**Comment by zqqq** [comment]
I have the same err,
After my test, not a firewall problem！
`func makeRandomHost(port int) host.Host {
	priv, pub, err := crypto.GenerateKeyPair(crypto.RSA, 2048)
	if err != nil {
		log.Fatalln(err)
	}
	pid, err := peer.IDFromPublicKey(pub)
	if err != nil {
		log.Fatalln(err)
	}
	//	listen, err := ma.NewMultiaddr(fmt.Sprintf("/ip4/127.0.0.1/tcp/%d", port))
	//	if err != nil {
	//		log.Fatalln(err)
	//	}
	ps := ps.NewPeerstore()
	ps.AddPrivKey(pid, priv)
	ps.AddPubKey(pid, pub)
	**n, err := swarm.NewNetwork(context.Background(),
		nil, pid, ps, nil)**
	if err != nil {
		log.Fatalln(err)
	}
	return bhost.New(n)
}`

n, err := swarm.NewNetwork(context.Background(),
		**nil**, pid, ps, nil)  

on makeRandomHost 
Initialization, do not listen, such as initialization is completed, and then listen alone, so that you can connect successfully.

**Comment by outprog** [comment]
yes, it's not a firewall problem. First time, i just change proxy.go on remote peer(remote machine)
```
listen, err := ma.NewMultiaddr(fmt.Sprintf("/ip4/127.0.0.1/tcp/%d", port))
```
to
```
listen, err := ma.NewMultiaddr(fmt.Sprintf("/ip4/0.0.0.0/tcp/%d", port))
```
use `0.0.0.0` can listen all ip. but it's not work.
last, i change proxy.go on both peer(remote machine and local machine), it's work. All machines use `0.0.0.0`.

```
                                                                                                    XXX
                                                                                                   XX  XXXXXX
                                                                                                  X         XX
                                                                                        XXXXXXX  XX          XX XXXXXXXXXX
                  +----------------+                +-----------------+              XXX      XXX            XXX        XXX
 HTTP Request     |                |                |                 |             XX                                    XX
+----------------->                | libp2p stream  |                 |  HTTP       X                                      X
                  |  Local peer    <---------------->  Remote peer    <------------->     HTTP SERVER - THE INTERNET      XX
<-----------------+                |                |                 | Req & Resp   XX                                   X
  HTTP Response   |  libp2p host   |                |  libp2p host    |               XXXX XXXX XXXXXXXXXXXXXXXXXXXX   XXXX
                  +----------------+                +-----------------+                                            XXXXX
```

**Comment by Stebalien** [comment]
I see. Yeah, that's either a bug or something that should be documented clearly. It looks like you can't dial out of an interface you're not listening on.

**Comment by Stebalien** [comment]
Scratch that, it should still work (we have a fallback dialer).

**Comment by Stebalien** [comment]
Could you try changing *only* the listen address, not the proxy address, and see what happens?

**Comment by outprog** [comment]
@Stebalien 
Yes, only the listen address, it's work. I think if want other meachine use peer's http proxy, then need change the proxy address.

**Comment by outprog** [comment]
By the same, `./example/echo`, if we want to run it on a separate machine, must changing ip on both local and remote.

**Comment by Stebalien** [comment]
@whyrusleeping is this intended?

**Comment by whyrusleeping** [comment]
@Stebalien Its not necessarily intended. I just generally restrict demo applications to only listen on localhost
