### ISSUE TITLE
Wrong type for anonymous func in identify/id.go

### ISSUE THREAD

**Issue by bahner** [libp2p/go-libp2p#2480]
compile fails. I have no idea what causes the error. But it seems lilke an obvious error.

../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.29.2/p2p/protocol/identify/id.go:559:25: type func(a multiaddr.Multiaddr, b multiaddr.Multiaddr) bool of func(a, b ma.Multiaddr) bool {…} does not match inferred type func(a multiaddr.Multiaddr, b multiaddr.Multiaddr) int for func(a E, b E) int
../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.29.2/p2p/protocol/identify/obsaddr.go:217:22: type func(first *observedAddr, second *observedAddr) bool of func(first, second *observedAddr) bool {…} does not match inferred type func(a *observedAddr, b *observedAddr) int for func(a E, b E) int

**Comment by MarcoPolo** [comment]
Are you using Go 1.21? This looks like the change that was made in the slices package to the compare fn type. 

Go 1.21 isn't supported until we release a new version with #2478 .

Please include your environment and a repro.

**Comment by bahner** [comment]
hepp! yes. I was just about to write: This works in go1.19, but not with go1.2*

**Comment by bahner** [comment]
Related to this, I take it. https://github.com/libp2p/go-libp2p/issues/2369

**Comment by marten-seemann** [comment]
This has been reported multiple times and has since been fixed.

**Comment by chenjia404** [comment]
I use go 1.20.7 same situation
