### ISSUE TITLE
The question about go-libp2p 0.29.2, line 559 is func SortFunc(x S, cmp func(a, b E) bool)

### ISSUE THREAD

**Issue by xfengw** [libp2p/go-libp2p#2490]
In golang, func SortFunc(x S, cmp func(a, b E) **int**), and in go-libp2p0.29.2, line 559 is func SortFunc(x S, cmp func(a, b E) **bool)**
slices.SortFunc(addrs, func(a, b ma.Multiaddr) bool { return bytes.Compare(a.Bytes(), b.Bytes()) == -1 })
![line559](https://github.com/libp2p/go-libp2p/assets/18342414/e62fac8c-68e9-4147-b167-4ddcf6f38ec9)

**Comment by marten-seemann** [comment]
@xfengw, I've told you before, please stop. As the other issues you've reported, this has already been fixed.
