### ISSUE TITLE
Last release with discovery

### ISSUE THREAD

**Issue by lonnietc** [libp2p/go-libp2p#2503]
I have an older Golang project that uses go-libp2p but it needs the last version with discovery included as I want to test it with the original files before updating things.

I  get the error:

```
 github.com/libp2p/go-libp2p/p2p/discovery: module github.com/libp2p/go-libp2p@latest found (v0.29.2), but does not contain package github.com/libp2p/go-libp2p/p2p/discovery
```

Any help would be greatly apprecated
Thanks in advance.

**Comment by marten-seemann** [comment]
It's right here, only containing sub-packages though: https://github.com/libp2p/go-libp2p/tree/master/p2p/discovery
