### ISSUE TITLE
Add test using goleak

### ISSUE THREAD

**Issue by p-shahi** [libp2p/go-libp2p#2517]
Adding a test using goleak seems like a good idea as well.

_Originally posted by @marten-seemann in https://github.com/libp2p/go-libp2p/issues/2514#issuecomment-1690915038_
            
Add a goleak tests to catch issues like https://github.com/libp2p/go-libp2p/issues/2514
It seems like we have some existing goleak tests in the peerstore https://github.com/libp2p/go-libp2p/blob/5622bc35c25d8bba01f57797729d73eb82f60983/p2p/host/peerstore/pstoremem/inmem_test.go#L78

**Comment by MarcoPolo** [comment]
Done with #2118
