### ISSUE TITLE
mDNS discovery announces on the wrong interface

### ISSUE THREAD

**Issue by ghost** [libp2p/go-libp2p#253]
It seems like mDNS discovery only picks up the "first" interface that libp2p finds, i.e. usually the first one that's printed on ipfs startup. In my case, that's OpenVPN's tun0, but not the LAN's wifi0. Other interfaces aren't considered, so discovery is half broken in those cases.

We should probably apply some simple heuristics to decide which interfaces look like they're probably a LAN.

```
> IPFS_LOGGING=debug ipfs daemon |& grep mdns
```

**Comment by lgierth** [comment]
```
> IPFS_LOGGING=debug ipfs daemon |& grep mdns
16:11:09.294 DEBUG       mdns: starting mdns query mdns.go:130
16:11:09.295 DEBUG       mdns: Handling MDNS entry: 10.45.2.6:4001 QmZhKsV96AnqCynGhrygUuGRHsqdQY73yufXtdikkSZRy6 mdns.go:152
16:11:09.295 DEBUG       mdns: got our own mdns entry, skipping mdns.go:160
16:11:14.295 DEBUG       mdns: mdns query complete mdns.go:143
```

**Comment by djkazic** [comment]
👍 I've run into this as well, it's a problem on Android devices where a multiplexing interface may appear with an IP that isn't reachable from anything but the host device. When this address gets advertised, it's a bad time
