### ISSUE TITLE
mDNS discovery announces ephemeral ports

### ISSUE THREAD

**Issue by ghost** [libp2p/go-libp2p#254]
I've seen that a while ago:

```
19:03:19.522 DEBUG       mdns: Handling MDNS entry: 192.168.43.135:36191  mdns.go:147
```

We should only ever announce what's in Addresses.Swarm or Addresses.Announce

**Comment by marten-seemann** [comment]
We're announcing the addresses of all interfaces we're listening on: https://github.com/libp2p/go-libp2p/blob/1e31d705331dce904c8f0202d45e0178eff7a919/p2p/discovery/mdns/mdns.go#L113

I believe this is correct, albeit slightly suboptimal (we could have a separate mDNS service per interface).
