### ISSUE TITLE
identify: dns addresses shouldn't be filtered out

### ISSUE THREAD

**Issue by richard-ramos** [libp2p/go-libp2p#2550]
I'm dialing a node I have at `/dns4/node-01.do-ams3.status.prod.statusim.net/tcp/30303/p2p/16Uiu2HAm6HZZr7aToTvEBPpiys4UxajCTU97zj5v7RNR2gbniy1D` and after Identify is executed, when I tried to retrieve the peer addresses from the peer store, the peer was not returning any address at all.

Is this expected behavior? Notice in line 1001 the filter function  manet.IsPublicAddr is being used which will only take into account IP addresses and not DNS4 addresses.

https://github.com/libp2p/go-libp2p/blob/9f14eb71580e358c485b700d576014015e86cd15/p2p/protocol/identify/id.go#L994-L1002

**Comment by richard-ramos** [comment]
For more context on why this could be a problem:
I'm using `basicHost.Connect` to connect to that node with dns4 multiaddress. `Connect` will add the dns4 address to the peerstore with a `TempAddressTTL` as it can be seen [here](https://github.com/libp2p/go-libp2p/blob/9f14eb71580e358c485b700d576014015e86cd15/p2p/host/basic/basic_host.go#L722). However, later Identify protocol will [filter out all the addresses](https://github.com/libp2p/go-libp2p/blob/9f14eb71580e358c485b700d576014015e86cd15/p2p/protocol/identify/id.go#L772) returned by Identify, ignoring the `dns4` multiaddresses, and [expire all `TempAddressTTL`](https://github.com/libp2p/go-libp2p/blob/9f14eb71580e358c485b700d576014015e86cd15/p2p/protocol/identify/id.go#L775) effectively removing from the peer store the dns4 address used to dial the node

**Comment by sukunrt** [comment]
Nice catch! This is a bug. We should keep the dns address if the peer provides us with one. 

The fix loop simple to me, check if it's an IP address before doing the filtering, do you want to submit a fix?

**Comment by sukunrt** [comment]
Thanks @richard-ramos for reporting. I'd like to get this fix in the next patch release so I'm taking this up. If you're interested in contributing, see issues with [help-wanted label](https://github.com/libp2p/go-libp2p/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22)

**Comment by richard-ramos** [comment]
Thank you, @sukunrt! :)
