### ISSUE TITLE
Race condition in chat-with-rendezvous example due to adding peer async

### ISSUE THREAD

**Issue by leblowl** [libp2p/go-libp2p#2554]
Hi, I'm just getting into libp2p and following the code in chat-with-rendezvous. It looks like there is a race condition when first connecting to a bootstrap node and then immediately advertising via routing discovery. It looks like this race condition arises because peers are added to the RoutingTable asynchronously.

In the chat-with-rendezvous example, we call `Connect` to connect to a boostrap node:
https://github.com/libp2p/go-libp2p/blob/9f14eb71580e358c485b700d576014015e86cd15/examples/chat-with-rendezvous/chat.go#L137

And then immediately after call `Advertise`:
https://github.com/libp2p/go-libp2p/blob/9f14eb71580e358c485b700d576014015e86cd15/examples/chat-with-rendezvous/chat.go#L150

By the time Connect returns, it doesn't appear that it's guaranteed that the connected peer is added to the RoutingTable. And if there aren't any peers in the RoutingTable, Advertise fails. One could repeat Advertise until it succeeds, but to me it seems like that shouldn't be expected of callers and that Connect should add peers to the RoutingTable before it returns or there should be some other async notification when a peer has been added. Is there a reason why Connect shouldn't add peers to the RoutingTable synchronously?

In most cases, with multiple remote bootstrap nodes, you probably wouldn't notice the race condition. But with only a single localhost bootstrap node, it's easy to demonstrate on my system.

<details>
<summary>Version Information</summary>
<pre>
github.com/libp2p/go-libp2p v0.31.0
</pre>
</details>

**Comment by master255** [comment]
But the example uses standard bootstrap nodes. So the example is correct.

**Comment by leblowl** [comment]
Hi, it looks like standard bootstrap nodes are optional in the example:
https://github.com/libp2p/go-libp2p/blob/9f14eb71580e358c485b700d576014015e86cd15/examples/chat-with-rendezvous/flags.go#L59

But I wouldn't worry too much about whether or not the example is correct. I
think the main issue is that it seems odd that after connecting to a peer they
are not immediately added to the routing table. It looks like communication with
the DHT is async:
https://github.com/libp2p/go-libp2p/blob/0509445ff4a6e35cea6ebafb98a5902064fd9837/p2p/protocol/identify/id.go#L404

Without sync or a separate notification, I think the user would have to loop
until an advertise succeeds, which doesn't seem ideal.

Since I'm new to the project, I'm curious if there is a good reason for it or a
better way to use the library that I'm not aware of. Perhaps it's an
area that can be improved and might be something interesting to work on.

**Comment by master255** [comment]
No bootstrap nodes are not optional there, but mandatory.
And it's not interesting to deal with such primitive examples.

**Comment by sukunrt** [comment]
Not sure if the race is an issue as [Advertise](https://github.com/libp2p/go-libp2p/blob/master/p2p/discovery/util/util.go#L34)  will keep on retrying. So when the peer is added to the routing table the call should succeed. 

A sync `ConnectAndAddToRoutingTable` method might make sense depending on your use case but you can add such a method to your code. If it's widely required this method would belong in the [DHT repo](https://github.com/libp2p/go-libp2p-kad-dht).
