### ISSUE TITLE
DNSAddr does not respect transport-specific DNS resolution

### ISSUE THREAD

**Issue by aschmahmann** [libp2p/go-libp2p#2562]
## Problem

Dialing a DNSAddr multiaddr that somewhere down the recursion chain forwards to an address type that handles DNS specially (e.g. WSS) does not work because the host over-resolves the address.

Example:
- Dial `/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb` (but only have WSS as a supported transport)
- This will resolve to `/dns4/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb`
- Which will resolve to `/ip4/147.75.87.27/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb`
- Which will fail due to an invalid TLS certificate

However: dialing `/dns4/am6.bootstrap.libp2p.io/tcp/443/wss/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb` directly works fine.

## Potential Fix

This is effectively a continuation of #1597, but accounting for DNSAddr recursion. I suspect the fix that will help here is to keep doing the type of check we do in https://github.com/libp2p/go-libp2p/blob/0509445ff4a6e35cea6ebafb98a5902064fd9837/p2p/net/swarm/swarm_dial.go#L305-L318 not just at the top layer of address resolution, but also in the recursive DNSAddr resolution function https://github.com/libp2p/go-libp2p/blob/0509445ff4a6e35cea6ebafb98a5902064fd9837/p2p/net/swarm/swarm_dial.go#L344

cc @dennis-tra (thanks for finding out something was going wrong here 😄)

**Comment by marten-seemann** [comment]
Very interesting. Looks like the transport-specific name resolution is bypassed altogehter, since looking at `/dnsaddr/...`, we don't know it will resolve to a wss address. We'll need to do that check recursively.

Fix incoming.

**Comment by marten-seemann** [comment]
Getting the fix merged took us a while, but it's merged now, and will be included in the v0.32 release later this week.
