### ISSUE TITLE
libp2p/go-libp2p@v0.31.0/p2p/net/upgrader/upgrader.go:328:37: undefined: mss.SelectWithSimopenOrFail

### ISSUE THREAD

**Issue by kehiy** [libp2p/go-libp2p#2567]
I'm trying to update go-libp2p in my project to the latest version.
But I got this error after updating:
```
go build -ldflags "-X github.com/pactus-project/pactus/version.build=`git rev-parse --short=8 HEAD`" -o ./build/pactus-daemon ./cmd/daemon
# github.com/libp2p/go-libp2p/p2p/net/upgrader
../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.31.0/p2p/net/upgrader/upgrader.go:328:37: undefined: mss.SelectWithSimopenOrFail
make: *** [Makefile:30: build] Error 1
```

**Comment by marten-seemann** [comment]
The release is fine. The problem is that you upgraded transitive dependences, specifically go-multistream.

**Comment by kehiy** [comment]
@marten-seemann so, what can I do?

**Comment by gotoeasy** [comment]
> @marten-seemann so, what can I do?
> 
> > I used `go get -u all`

I encountered the same issue. Using go get -u all didn't work for me. Here's how I solved it:

I deleted the go.sum file, removed all the require entries from the go.mod file, and then run go mod tidy

**Comment by kehiy** [comment]
@gotoeasy thank you so much.
