### ISSUE TITLE
Switch mdns library

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#257]
Either (a) switch to a fork or, even better, switch to https://github.com/grandcat/zeroconf. The current library is unmaintained and has at least one data race (and parts of it are incomprehensible).

**Comment by Stebalien** [comment]
Closing in favor of #623.

**Comment by kpp** [comment]
Why not switch to https://github.com/hashicorp/mdns ? https://github.com/whyrusleeping/mdns is a fork of https://github.com/hashicorp/mdns and https://github.com/hashicorp/mdns fixed some data races.

**Comment by Stebalien** [comment]
We've fixed all the ones fixed upstream.

**Comment by kpp** [comment]
Where?

**Comment by Stebalien** [comment]
https://github.com/whyrusleeping/mdns/commit/9d49aa4bf4b2dada709ec1c3390cef586036eafe

Looking at a diff between the two versions, it looks like the only remaining change we need is the ability to turn off (or redirect) logging. We should probably upstream that and then get off the fork (eventually).

**Comment by kpp** [comment]
> whyrusleeping/mdns@9d49aa4

Mutex is a bad solution because of:

```
$ go vet
# github.com/whyrusleeping/mdns
./client.go:165:41: call of logf copies lock value: github.com/whyrusleeping/mdns.client contains sync.Mutex
```

> Looking at a diff between the two versions, it looks like the only remaining change we need is the ability to turn off (or redirect) logging.

What do you mean? I am new to go
