### ISSUE TITLE
Echo example: yamux potentially broken

### ISSUE THREAD

**Issue by paralin** [libp2p/go-libp2p#258]
I'm seeing the same error as in #164 in my app -

```
B> through /ip4/172.17.0.2/tcp/8085 (got <peer.ID USHmgZ>): Multiple errors: close tcp4 172.17.0.9:59630->172.17.0.2:8085: use of closed network connection
```

Use of closed network connection - I think internally the ipv4 connection is closed, but then reused somewhere.

This issue started when I added the yamux transport, like in the Echo demo.

**Comment by Stebalien** [comment]
Is something actually failing to work? You can get that error if you, e.g., try to write/read (or, in some cases, close) a connection after or while closing a connection (which can happen under perfectly normal conditions).

(although, if we're printing that out as an error, we may want to consider reducing the log level).

**Comment by paralin** [comment]
This is an internal issue in libp2p, not me writing on a closed connection - I have the same issue with the echo demo, like in #164. Every time you run the dialer it prints this error.

**Comment by paralin** [comment]
I can't reproduce it anymore, a few days later. I think there is still some kind of internal bug in the yamux integration that may cause this though. Might be worth looking into it. I'll post again if I see it happen.

**Comment by Stebalien** [comment]
> Every time you run the dialer it prints this error.

But did it still connect (we conservatively double close connections all over the place)? Actually, that error looks truncated (at the beginning). Is there more?

**Comment by Stebalien** [comment]
Assuming the missing part of that error is `misdial to <peer.ID $Something>` where `$Something != USHmgZ`, you were probably not passing the correct peer ID on the client side. The full error is:

"misdial to <some peer> through <some address> (got <other peer>): <additional errors>"

**Comment by paralin** [comment]
You might be right. I haven't seen it again since, but I've been careful to copy/paste the peer ID each time. I'll close this for now, thanks for the help.
