### ISSUE TITLE
Unable to discover peers through Bootstrap node

### ISSUE THREAD

**Issue by b00f** [libp2p/go-libp2p#2616]
First of all, I would like to thank you for this amazing library. We are using Libp2p for the [Pactus](https://github.com/pactus-project/pactus) blockchain, and everything has been smooth so far. However, recently, we have been observing strange behavior that is causing a kind of blockage for us.

Once the number of nodes in our network increases (we currently have around 30-50 nodes), new joiners can't discover other peers. The procedure is as follows: new joiners connect to [bootstrap](https://github.com/pactus-project/pactus/blob/34eff4ff1e7ac05ed54bc8c4e78c3d61566d816c/network/bootstrap.go#L89) nodes (4 nodes), and later they can get information about the other nodes. This works most of the time, but when the bootstrap nodes have reached their maximum connection limit (this is my guess), once a new node tries to connect to a bootstrap node, the [connection is established](https://github.com/pactus-project/pactus/blob/34eff4ff1e7ac05ed54bc8c4e78c3d61566d816c/network/notifee.go#L32), but that's it. There is no protocol negotiation, and the bootstrap node doesn't advertise or send any other peer addresses to the new joiner.

I could easily reproduce this issue by keeping only one bootstrap address and trying to connect to it. As I mentioned, the connection is established but stops there.

===
UPDATE:

Based on the log, we have 59 connections in the Bootstrap node.
It is likely that the number of nodes should be higher:
```
check connectivity _network={59} peers=59
```

From the log from both bootstrap node and client node, I can see that Bootstrap node [disconnect](https://github.com/pactus-project/pactus/blob/34eff4ff1e7ac05ed54bc8c4e78c3d61566d816c/network/notifee.go#L53) from the client, but the client doesn't and keep [connected](https://github.com/pactus-project/pactus/blob/34eff4ff1e7ac05ed54bc8c4e78c3d61566d816c/network/notifee.go#L31).

<details>
<summary>LibP2P v0.31.0</summary>
<pre>

</pre>
</details>

**Comment by master255** [comment]
Peer addresses are looked up in the entire DHT, not just in bootstrap nodes. Bootstrap nodes it is necessary only to get the full list of nodes. Nothing else.
We have a known bug when there are not enough resources. Perhaps [this will help you ](https://github.com/libp2p/go-libp2p/issues/2367#issuecomment-1686129801)

**Comment by sukunrt** [comment]
@b00f Can you run with debug logs enabled? Debug logs can be enabled with the environment variable, `GOLOG_LOG_LEVEL=debug`

>Based on the log, we have 59 connections in the Bootstrap node.

Can you check your resource manager limits? It is very unlikely that 59 is your resource manager connection limit, but there's no harm in checking.

**Comment by b00f** [comment]
@sukunrt and @master255,

Thank you for your suggestions and help. We tried to mitigate this issue by defining [limits](https://github.com/pactus-project/pactus/pull/788), and by adding more nodes from the [community as bootstrap node](https://github.com/pactus-project/pactus/pull/764/files).

As of now, we have approximately 400-500 computers running Pactus, and the network has become quite stable.

**Comment by Jorropo** [comment]
@b00f have you tried using a connmgr to prune peers ?
If you are using `go-libp2p-kad-dht` you don't need to keep alive connections with bootstrappers after the first contact.

**Comment by master255** [comment]
@Jorropo Why might the network outgrow the limits?
Aren't limits designed to prevent this from happening?
Why can't we have a maximum of 1000 peers and when new ones appear, delete the old ones? 
Or use some algorithm to reduce the number of peers?
Is there really no way to beat the limits without increasing them indefinitely?

**Comment by b00f** [comment]
Limiting the connections only mitigates the issue. If the bootstrap node reaches its limit, it can't open new connections.
Perhaps the bootstrap should have a configuration option to operate in seeder mode.

**Comment by Jorropo** [comment]
@master255 
> Why can't we have a maximum of 1000 peers and when new ones appear, delete the old ones?

That my point that what https://pkg.go.dev/github.com/libp2p/go-libp2p#ConnectionManager do.

**Comment by marten-seemann** [comment]
Closing since @Jorropo's explanation is correct. The connection manager is responsible for pruning connections. A bootstrap node could be configured with a low low watermark and a high high watermark, which would create a lot of churn of peers.

**Comment by b00f** [comment]
> A bootstrap node could be configured with a low low watermark and a high high watermark, which would create a lot of churn of peers.

So, you're suggesting to set a higher watermark (let's say 1024) and a lower watermark (let's say 256). 
In this scenario, when the connections reach their limit, a new peer attempting to connect will still be rejected because the connections are at their maximum limit. Did I miss anything here? 
When a peer subject to churn in Connection Manager?

**Comment by marten-seemann** [comment]
The connection manager doesn't reject any connections. It just triggers a pruning run once the high watermark is reached (or surpassed).

Make sure to configure the resource manager to allow more connections than the high watermark. The resource manager _will_ block connections once you reach the limit, and if you set the limit too low, you'll never trigger the connection manager's pruning logic.

**Comment by b00f** [comment]
Based on your explanation, the Low Water Mark and Minimum Connection can be the same, but the High Water Mark  should be set higher than Maximum Connection (probably by half the difference between High_WM and Low_WM?):

```
            Low WM                      High WM  
Con Mgr:    |-------------------------->|
Res Mgr:    |---------------------------|-------->|
            Min Conn                             Max Conn
```

**Comment by marten-seemann** [comment]
Correct for high wm and max conn, but the resource manager doesn't have a min conn setting.
