### ISSUE TITLE
go-libp2p v0.33

### ISSUE THREAD

**Issue by sukunrt** [libp2p/go-libp2p#2623]
### ETA: Week of Feb 19

WebRTC:
- [x] #2615 

Misc:
- [x] #2650 

QUIC:
- [x] https://github.com/libp2p/go-libp2p/pull/2710

Optional
- [ ] https://github.com/libp2p/go-libp2p/issues/2703

### TLS encryption for TCP by default
For TCP Connections, the default encryption scheme has been changed from noise to TLS for better performance. See [PR](https://github.com/libp2p/go-libp2p/pull/2650) for details. 

*Note:* When making TCP connections to nodes that only support noise this will add 1 extra round trip for connection establishment. If you wish to avoid this and keep noise the default, configure your node to prefer noise over TLS like
```go
	node, err := libp2p.New(
        ... other options
		libp2p.Security("/noise", noise.New),
		libp2p.Security("/tls/1.0.0", libp2ptls.New),
	)
```

### Misc

- WebRTC streams now wait for a FIN_ACK before closing data channels. For more details see the specs PR: https://github.com/libp2p/specs/pull/582 
- Removed unused public function `crypto.GenerateEKeyPair`. This was used in SECIO which has been long deprecated. 
- This release drops support for go1.20.

## Changelog

< changelog generated by scripts/mkreleaselog >

## ✅ Release Checklist

- [ ] **Stage 0 - Finishing Touches**
    - [ ] Go through relevant libp2p repos looking for unreleased changes that should make it into the release. If you find any, cut releases.
    - [ ] Run `go get -u ./...` to see if there are any out-of-date deps that look important. If there are, bubble them. Try to avoid _directly_ updating indirect deps in go-libp2p's `go.mod` when possible.
- [x] **Stage 1 - Release**
  - [x] Publish the release through the GitHub UI, adding the release notes. Some users rely on this to receive notifications of new releases.
  - [ ] Announce the release on the [discuss.libp2p.io](https://discuss.libp2p.io).
- [ ] **Stage 2 - Update Upstream**
  - [ ] Update the examples to the final release
  - [ ] Update the upstream dependencies to the final release and create PRs.
    - [ ] [filecoin-project/lotus](https://github.com/filecoin-project/lotus)
    - [ ] [go-libp2p-kad-dht](https://github.com/libp2p/go-libp2p-kad-dht/)
    - [ ] [go-libp2p-pubsub](https://github.com/libp2p/go-libp2p-pubsub) (In case of breaking changes.)
    - [ ] [ipfs/kubo](https://github.com/ipfs/kubo)
  - [ ] Add new release to interop tester in [test-plans](https://github.com/libp2p/test-plans/)
- [ ] Make required changes to the release process.

**Comment by p-shahi** [comment]
Should we update to the latest 0.41.0 version of quic-go https://github.com/quic-go/quic-go/releases/tag/v0.41.0 instead of a dot release of 0.40?
