### ISSUE TITLE
Excessive thread creation

### ISSUE THREAD

**Issue by master255** [libp2p/go-libp2p#2629]
https://github.com/libp2p/go-libp2p/blob/4e2a16dd3f4f980bf9429572b3d2aed885594ec4/p2p/discovery/mdns/mdns.go#L183

There is no need to create a thread in the library. The application programmer has the right to decide whether to process data sequentially or to create a thread for this purpose.

**Comment by marten-seemann** [comment]
See https://github.com/libp2p/go-libp2p/pull/1221.

**Comment by master255** [comment]
I just deleted the "go" in my Libp2p and continued writing code.
And your Libp2p still has the creation of goroutine. And other discovery modules do not have goroutine creation, when passing peer.
Your Libp2p code is not fixed, but mine is. It's my role to tell you about the problem. But I noticed you don't listen to me at all. It's my duty to give you a chance. How you use it is up to you.
