### ISSUE TITLE
High network usage

### ISSUE THREAD

**Issue by b00f** [libp2p/go-libp2p#2633]
Based on reports from some users, they have been experiencing approximately 2 to 3 GB of network usage daily. This is quite shocking for us, as we have made efforts to manage network usage.

We understand that broadcasting messages involves numerous messages in LibP2P, and perhaps the network usage should be higher than what a node sends or receives. However, we have precise data on the number of bytes each node has sent or received, and this data is accurate. Based on the reports we have received, it appears that network usage is high. Please refer to the following reports for more details:

```
Time of these reports: 12:00 AM, 3 Nov

Network started at: 01/11/2023, 16:45:33
Total bytes sent: 67,459,008
Total bytes received: 323,169,743

Network started at: 28/10/2023, 17:33:52
Total bytes sent: 131,916,203
Total bytes received: 1,494,646,215

Network started at: 30/10/2023, 13:53:01
Total bytes sent: 326,838,903
Total bytes received: 823,059,957

Network started at: 02/11/2023, 01:12:28
Total bytes sent: 6,493,628
Total bytes received: 224,221,587
```

It's important to note that each node has different usage patterns due to the time they start their node and their specific configuration. The question we have is: Is there any way to adjust LibP2P settings to reduce network usage? We would appreciate any thoughts or suggestions on this matter.

=== 
UPDATE:

After investigating 2 bootstrap nodes and report of `docker stats`, we have these data:

```
Docker NET I/O 
51.1GB / 44.6GB

Node info:
Started at    2023-10-29 11:47:05 +0000 UTC
Total Sent Bytes    536,913,092
Total Received Bytes    1,017,455,513

---- 

Docker NET I/O 
34.8GB / 30.8GB

Node info:
Started at    2023-10-30 1:53:01 +0000 UTC
Total Sent Bytes   331,730,717
Total Received Bytes    831,066,676
```

Each bootstrap nodes has connections between 128-256 nodes.

**Comment by master255** [comment]
I don't think it has anything to do with the DHT. In any case, you can make your own DHT network and have only the traffic that it is necessary for you and your users.

**Comment by marten-seemann** [comment]
Is this internet traffic or does it include mDNS traffic?

**Comment by b00f** [comment]
There is no mDNS enables at those servers (off by default).

**Comment by marten-seemann** [comment]
Can you try enabling the bandwidth counter: https://github.com/libp2p/go-libp2p/blob/master/core/metrics/bandwidth.go? It's a swarm option, and should allow you to find out which protocol and peer are responsible for the traffic.

**Comment by b00f** [comment]
Thanks for your suggestion. We were not aware oft this option. We will enable it and will share the result here.

However, we tried to reduce the traffic in the latest [release](https://pactus.org/2023/11/12/release-0-17-0.html) through these modifications:

1. Removing the Signature (64 bytes).
2. Removing the PID author (38 bytes).
3. Defining the Message ID as the first 20 bytes of the message hash.
4. Introducing a new type of node: Node Gossip (experimental).

Node Gossip nodes are a type of node that gossips the message. Meanwhile, non-gossip nodes only consume incoming messages, and they don't broadcast the message. This is experimental, but it appears to be working fine so far.

There are some questions:

1. In certain situations (like block announcements), consensus nodes might produce the exact message with the exact message ID. We assumed that identical messages emitted by different nodes would be ignored by the network, but it seems that this is not the case. We still observe nodes receiving the same message repeatedly. Any thoughts on this?

2. It appears that the node gossip sends messages to all nodes, regardless of whether they have the message or not. Is there any way to reduce outgoing traffic? I'm not sure, but maybe using the `WithFloodPublish(false)` config could help?

**Comment by marten-seemann** [comment]
Can you post the gossipsub-related question in the gossipsub repo please? And please let me know what insights you get from the `BandwidthReporter`.

**Comment by b00f** [comment]
Unfortunately, we were unable to install the metrics using `BandwidthReporter`. 
I've been told that it didn't reveal any new information. 
We apologize if our efforts couldn't be of assistance in this case.
