### ISSUE TITLE
Peer Discovery Fail

### ISSUE THREAD

**Issue by vikram722** [libp2p/go-libp2p#2634]
trying out the  pubsub rendezvous basic chat example provided by libp2p.

Trying it Out.... all nodes in the localhost running in diff ports

Node1: Bootstrap peer
Node2 connects to node 1
Node3 connects to node 1

All are subscribed to the same topic , all nodes receive the published msg, but node 2 cannot discover anything rather than itself, and same for all nodes, it just connects to the boot node , thats it,  peer discovery just returns its own peer id .
Can some one pls help me with this. Thanks

**Comment by avp1598** [comment]
Hi @vikram722 I am facing the same issue, did you find a solution?
