### ISSUE TITLE
version 0.32.1 mdns issue

### ISSUE THREAD

**Issue by kehiy** [libp2p/go-libp2p#2654]
We have a project which is using libp2p for networking.

After updating from version 0.31.0 to 0.32.1. our mdns tests going to fail `sometimes`.
But most of the time they pass. Before updating there weren't any failures in mdns tests.

this is the line that makes this issue:
https://github.com/pactus-project/pactus/blob/920046cba22fa016cb1f504209ffefbc2a31b594/network/mdns_test.go#L27

when we start the network. should receive event returns a time out! (other tests are ok with this, also MDNS test before updating)

the should receive event function:
https://github.com/pactus-project/pactus/blob/920046cba22fa016cb1f504209ffefbc2a31b594/network/network_test.go#L84

**Comment by kehiy** [comment]
I need to mention the only change is updating the libp2p version.

**Comment by kehiy** [comment]
@marten-seemann @sukunrt can you have a check?

**Comment by marten-seemann** [comment]
No need to tag us, we're all subscribed to the issue notifications here.

Regarding your mDNS issue, I find it surprising that you're seeing any difference between v0.31.0 and v0.32.1. There were no changes to mDNS whatsover: https://github.com/libp2p/go-libp2p/compare/v0.31.0...v0.32.1. There were also no changes to the zeroconf library we're using: https://github.com/libp2p/zeroconf.

There were however some changes to the Happy Eyeballs logic for TCP in v0.32.0: https://github.com/libp2p/go-libp2p/releases/tag/v0.32.0. Can you check if a TCP connection attempt is happening at all, and if so, if it is failing for any reason?

**Comment by kehiy** [comment]
nope, I don't think there is a TCP connection attempt. I need to check better, also the issue is from some function that waits for an event.
thank you for your help.

**Comment by kehiy** [comment]
I changed the listening address and added UDP in IPv4 and 6. it's fixed now and works well.
