### ISSUE TITLE
Make WebRTC non experimental

### ISSUE THREAD

**Issue by sukunrt** [libp2p/go-libp2p#2657]
Currently WebRTC has been deployed with an experimental tag and has the following caveat:  https://github.com/libp2p/go-libp2p/blob/master/p2p/transport/webrtc/transport.go#L4-L7

```
// While we're fairly confident that the implementation correctly implements the specification,
// we're not making any guarantees regarding its security (especially regarding resource exhaustion attacks).
// Fixes, even for security-related issues, will be conducted in the open.
```

We should remove aim to experimental tag and make this transport enabled by default.

**Comment by marten-seemann** [comment]
To make WebRTC a default transport:
1. We need to be sure that the resource usage is acceptable (see #1917), both in our code and in the underlying Pion WebRTC and SCTP stack.
1. #2615 needs to be resolved and merged.
1. Deployment experience that shows actual usage of the WebRTC transport would be nice. Even better if it comes with metrics.

We should consider bundling this with WebRTC private-to-private. It seems like the above points would most likely be satisfied for both WebRTC flavors at the same time.

**Comment by SgtPooki** [comment]
any update on webrtc @sukunrt ?

**Comment by sukunrt** [comment]
Targeting release next week.
