### ISSUE TITLE
bad golang package name

### ISSUE THREAD

**Issue by bronze1man** [libp2p/go-libp2p#266]
here is a some source code I copyed from the example:
```
package main

import (
	"github.com/libp2p/go-libp2p-peer"
	"crypto/rand"
	"github.com/libp2p/go-libp2p-crypto"
	"github.com/libp2p/go-libp2p-peerstore"
	"github.com/multiformats/go-multiaddr"
	"github.com/libp2p/go-libp2p-swarm"
	"context"
	"github.com/libp2p/go-libp2p/p2p/host/basic"
)

func main(){
	// Generate an identity keypair using go's cryptographic randomness source
	priv, pub, err := crypto.GenerateEd25519Key(rand.Reader)
	if err != nil {
		panic(err)
	}

	// A peers ID is the hash of its public key
	pid, err := peer.IDFromPublicKey(pub)
	if err != nil {
		panic(err)
	}

	// We've created the identity, now we need to store it.
	// A peerstore holds information about peers, including your own
	ps := peerstore.NewPeerstore()
	ps.AddPrivKey(pid, priv)
	ps.AddPubKey(pid, pub)

	maddr, err := multiaddr.NewMultiaddr("/ip4/127.0.0.1/tcp/9000")
	if err != nil {
		panic(err)
	}
	// Make a context to govern the lifespan of the swarm
	ctx := context.Background()

	// Put all this together
	netw, err := swarm.NewNetwork(ctx, []multiaddr.Multiaddr{maddr}, pid, ps, nil)
	if err != nil {
		panic(err)
	}

	myhost := basichost.New(netw)
	_ = myhost
}
```

I have to remove all package rename stuff from the example, because that make me confuse.So I add the example that the package name is "directly" import.
The base name of directory is not the same as the "short" package name make it difficult to find the reference from the real package directory from the source code.
"github.com/libp2p/go-libp2p-crypto" "crypto.GenerateEd25519Key(rand.Reader)" 
And your "crypto" is the same as the std package "crypto", it make the `idea` feel bad even when just include the "github.com/libp2p/go-libp2p-crypto" package.

I think following name rule is better to read and find the package (from a very large code base):
"github.com/libp2p/goLibp2pPeer" "goLibp2pPeer.IDFromPublicKey(pub)"
"github.com/libp2p/goLibp2pCrypto" "goLibp2pCrypto.GenerateEd25519Key(rand.Reader)"

**Comment by lgierth** [comment]
It's not neccessary to rename the actual packages or repos, since you can give imports in golang a custom name:

```go
import (
  p2pswarm "github.com/libp2p/go-libp2p-swarm"
  p2pbhost "github.com/libp2p/go-libp2p/p2p/host/basic"
)
```

Let me know if this answers your question.

**Comment by bronze1man** [comment]
@lgierth
Sorry. I am too stupid, my head do not have enough memory to deal with it.
Your solution make me difficult to read the code, because I need to remember the import in my head with each source file when I read the source code between several files.
And my head just do not have enough memory to deal with it.

And my IDE `idea` can not auto add import when i copy code from another place.
I think the only solution is to rename the actual packages and repos.

I think the import package rename stuff should use only when two "short" package name "accidentally" be the same.(the package name data race case)
The "short" package name should not be the same on purpose.

**Comment by bronze1man** [comment]
Just look at the comment:

https://github.com/libp2p/go-libp2p/issues/263#issuecomment-358236500

where do i import the "msmux" and "yamux" ? 
"goSmuxMultistream" and "goSmuxYamux" should be much better.

**Comment by lgierth** [comment]
My point is that you can give exactly these names to the imports.

```
import (
    goSmuxMultistream "github.com/libp2p/go-smux-multistream"
)
```

**Comment by Stebalien** [comment]
In terms of convention:

1. We prefix our libraries with `lang-` because we have many implementations in different languages.
2. Mixed-case go package names are unusual.

So, if we were to start over, we'd probably use names like `libp2p_crypto`, `libp2p_peer`, etc.

However, we'd *still* recommend specifying package names because it's nice being able to read a single source file and know, for sure, what's happening instead of having to make assumptions about package names.

Regardless, at this point, we're going to stick with the current convention of "set the package name yourself" because the refactor required would be a lot of work for too little gain.

**Comment by bronze1man** [comment]
Thanks.
So I know that the convention is much more important than readable code to this project.

By the way, I will do the refactor work myself with auto code read and write tool if I think this project is useful to me.
