### ISSUE TITLE
go-libp2p-asn-util adds ~4MiB to builds and increases build times, even in configurations where it will never be used

### ISSUE THREAD

**Issue by prestonvanloon** [libp2p/go-libp2p#2664]
I've found that go-libp2p-asn-util is linked to production binaries that import libp2p, even when they do not use any of the relay functionality that needs this util. This is due to interfaces being linked from `protocol/circuitv2/relay`. This util seems to be responsible for as much as 4MiB in the final build and it seems to increase our production build time by 19%. This is because it has a rather large array which our static checks and pgo have to grind through. 

Please consider refactoring use of this dependency such that users of go-libp2p do not have to import it unless they are actually using it.

**Comment by prestonvanloon** [comment]
@marten-seemann -- it was surprising to me too. I think that our use of pgo is causing the compiler to work very hard to find optimizations in this file.

There are two ideas that come to mind:

1) Can we use go's embedding functionality instead of a generated array? That would solve the build time issue (i think)
2) Can we refactor things such that this library is only imported when the options are configured by the user? i.e. only when specific libp2p functionality is added to the host that would need to identify ASNs.

Here's a look at our build graph where we were seeing this library imported whenever we imported go-libp2p. Ideally, importing go-libp2p wouldn't link to asnutil unless requesting those options. 

![Screenshot_2023-12-08_11-00-20](https://github.com/libp2p/go-libp2p/assets/7246818/0c2062b8-05f6-4a0a-a81f-4d479409983e)

**Comment by Jorropo** [comment]
While working on fixing this, I figured out that our code is broken.
It assumes that all ranges we get are valid CIDR however they are not.
```
2001:200:700::	2001:200:8ff:ffff:ffff:ffff:ffff:ffff	2500	JP	WIDE-BB WIDE Project
```
is:
```
2001:200::/33
2001:0200:800::/37
```
It seems https://iptoasn.com/ is merging adjacent ranges together in one line.

**Comment by Jorropo** [comment]
I sent https://github.com/libp2p/go-libp2p-asn-util/pull/33 which fixes the bug and the performance issue.

**Comment by prestonvanloon** [comment]
Thanks @Jorropo! I haven't tested it yet, but that PR looks like a huge improvement. The embedding technique satisfies my original complaint and I am pleased to see such a performance improvement. Well done!
