### ISSUE TITLE
如何搭建dht服务器，没有找到相关的代码，请问有没有热心大佬给个地址或者方法

### ISSUE THREAD

**Issue by xingkongwangbin** [libp2p/go-libp2p#2676]
* 如何搭建dht服务器，没有找到相关的代码，请问有没有热心大佬给个地址或者方法

* 可以这里联系也可以发送邮箱13731754667@163.com

**Comment by xingkongwangbin** [comment]
```bash
                "/dnsaddr/bootstrap.libp2p.io/p2p/QmcZf59bWwK5XFi76CZX8cbJ4BhTzzA3gU1ZjYZcYW3dwt",
		"/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
		"/ip4/104.131.131.82/udp/4001/quic/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ",
		"/dnsaddr/bootstrap.libp2p.io/p2p/QmNnooDu7bfjPFoTZYxMNLWUQJyrVwtbZg5gBMjTezGAJN",
		"/dnsaddr/bootstrap.libp2p.io/p2p/QmQCU2EcMqAqQPR2i9bChDtGNJchTbq5TbXJJ16u19uLTa",
		"/dnsaddr/bootstrap.libp2p.io/p2p/QmbLHAnMoJPWSCR5Zhtx6BHJX9KiKNN6tpvbUcqanj75Nb",
```
请问这种dht服务器如何搭建

**Comment by godcong** [comment]
1. you need by a domain
2. setting the domain txt rule. see detail https://github.com/multiformats/multiaddr/blob/master/protocols/DNSADDR.md

**Comment by Jorropo** [comment]
@godcong this isn't needed.

@xingkongwangbin any DHT node that is participating in the DHT can be here.
This example shows this working: https://github.com/libp2p/go-libp2p/tree/master/examples/chat-with-rendezvous
Here is bootstrap saving in Kubo (we collect people we happen to connect to and use them for the next bootstrap): https://github.com/ipfs/kubo/pull/8856
