### ISSUE TITLE
Auto Relay Doesn't Work in libp2p Network

### ISSUE THREAD

**Issue by amirvalhalla** [libp2p/go-libp2p#2681]
Hi,

In the [Pactus Blockchain Network](https://github.com/pactus-project/pactus), we're using `go-libp2p` as our `p2p` network. However, we are currently facing an issue with auto relay, even though we have configured everything as mentioned in the `libp2p` documents and examples. Despite setting up metrics, etc., we don't observe any relay traffic.

You can review the relevant code [here](https://github.com/pactus-project/pactus/blob/main/network/network.go) in the `newNetwork` method where we initialize `libp2p`.

**Comment by sukunrt** [comment]
Difficult to debug without more info. 
What does this log say? https://github.com/pactus-project/pactus/blob/main/network/network.go#L312

Can you run it with logs for autorelay enabled?
GOLOG_LOG_LEVEL="autorelay=debug"

**Comment by amirvalhalla** [comment]
> Difficult to debug without more info. What does this log say? https://github.com/pactus-project/pactus/blob/main/network/network.go#L312
> 
> Can you run it with logs for autorelay enabled? GOLOG_LOG_LEVEL="autorelay=debug"

We made a mistake regarding the relay, and the issue has been identified. Thanks.
