### ISSUE TITLE
Add Transient as a "connectedness" state

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#2692]
This will let users:

1. Quickly detect if the connection to a peer is transient.
2. Detect transitions from transient to "full" connections (and back) via events.

**Comment by Stebalien** [comment]
Needed for https://github.com/ipfs/boxo/pull/526

**Comment by sukunrt** [comment]
Can we do? 
>Detect transitions from transient to "full" connections (and back) via events.

I'm not sure if we can guarantee ordering between notifications for two different connections. The only guarantee right now is that disconnect on a connection is after connect. This behavior I believe was changed in https://github.com/libp2p/go-libp2p/pull/2373/files
