### ISSUE TITLE
\network\rcmgr.go:166:27: network.NullResourceManager (type) is not an expression

### ISSUE THREAD

**Issue by leon37084762** [libp2p/go-libp2p#2702]
# github.com/libp2p/go-libp2p-core/network go\pkg\mod\github.com\libp2p\go-libp2p-core@v0.20.1\network\rcmgr.go:166:27: network.NullResourceManager (type) is not an expression
i use go libp2p write a sample code ,but this issue happen ,how to fix this problem?

**Comment by Jorropo** [comment]
`github.com/libp2p/go-libp2p-core` is not used anymore, replace it with `github.com/libp2p/go-libp2p/core`

**Comment by sukunrt** [comment]
Please reopen this if you have problems with the solution @jorropo suggested.
