### ISSUE TITLE
Deprecate or improve documentation for crypto.GenerateEKeyPair

### ISSUE THREAD

**Issue by sukunrt** [libp2p/go-libp2p#2709]
In dropping support for go1.20 I came across `crypto.GenerateEKeyPair`. https://github.com/libp2p/go-libp2p/blob/master/core/crypto/key.go#L129

It looks like no one is using this and some time in the past it was used for SECIO. It also has the cryptic comment `Used in the identify module`. 

@marten-seemann @Stebalien any details you can share about this?

**Comment by Stebalien** [comment]
Yeah, it was used in secio for forward secrecy. IMO, it can safely be removed and nobody's likely to care.

**Comment by Stebalien** [comment]
(search of local code + grep.app revealed no users other than secio)
