### ISSUE TITLE
TestMdnsDiscovery fails

### ISSUE THREAD

**Issue by magik6k** [libp2p/go-libp2p#271]
I'm not sure where to start debugging this.

Arch Linux / No {nf,ip}tables / go1.9.3

```
--- FAIL: TestMdnsDiscovery (2.07s)
        mdns_test.go:51: dial attempt failed: failed to dial <peer.ID VJcuj6> (default failure)
FAIL
FAIL    github.com/libp2p/go-libp2p/p2p/discovery       2.104s
```

**Comment by Stebalien** [comment]
I was able to reproduce this. Our mDNS library is known to be racy (data races) so this isn't that surprising. See #257.

**Comment by Stebalien** [comment]
Closing in favor of #623.
