### ISSUE TITLE
Why the pubsub doesn't work in my case?

### ISSUE THREAD

**Issue by xiguamee** [libp2p/go-libp2p#2712]
Hello! I am trying to build a blockchain implement with libp2p. When I come to deal with the blocks transmission, I found that the pubsub model doesn't work.

  Can you tell me that what would effect the success of pubsub? And can you help me check my code? Thank you!

My code is work on wails lib, I set 2 peers at local. I let B make a sub to a topic and A pub a block to the same topic, but B didn't get the block.

Here's my function for pub and sub:

```
func (a *App) MineAndPublish() {
	fmt.Println("触发MineAndPublish")
	newblock := a.MineTest()
	ctx := context.Background()
	// 创建一个pubsub服务
	ps, err := pubsub.NewGossipSub(ctx, *local.host)
	if err != nil {
		panic(err)
	}
	// 订阅新区块主题
	topic, err := ps.Join("newblock")
	if err != nil {
		panic(err)
	}
	block, _ := json.Marshal(newblock)
	fmt.Println("信息长度:", len(block))
	err = topic.Publish(ctx, block)
	if err != nil {
		panic(err)
	}
	fmt.Println("mined and successfully published")
}

func (a *App) StartReceiveNewBlock() {
	fmt.Println("触发StartReceiveNewBlock")
	ctx := context.Background()
	// 创建一个pubsub服务
	ps, err := pubsub.NewGossipSub(ctx, *local.host)
	if err != nil {
		panic(err)
	}
	// 订阅新区块主题
	topic, err := ps.Join("newblock")
	if err != nil {
		panic(err)
	}
	sub, err := topic.Subscribe()
	if err != nil {
		panic(err)
	}
	// 从主题接收信息
	go func() {
		for {
			fmt.Println("waiting for new block")
			msg, err := sub.Next(ctx)
			if err != nil {
				panic(err)
			}
			fmt.Println("receive new block:", string(msg.Data))
		}
	}()
}
```

**Comment by xiguamee** [comment]
OK, I think I'v solved this problem.

I conneted the two peers earier than do a sub before. Now I try to do a sub when they initialize themselves and then connect each other. It works.

But I don't understand the principle in it. Can someone tell me why? Thank you!

**Comment by sukunrt** [comment]
I think this would be better addresses in https://github.com/libp2p/go-libp2p-pubsub

**Comment by sukunrt** [comment]
Please reopen if you feel this should be addressed here.

**Comment by master255** [comment]
https://github.com/libp2p/go-libp2p-pubsub/issues/546#issuecomment-2221738787
