### ISSUE TITLE
Quic-go removed config field causes compilation error

### ISSUE THREAD

**Issue by linted** [libp2p/go-libp2p#2739]
The latest version of Quick-Go removes the `RequireAddressValidation` callback in the config struct. https://github.com/quic-go/quic-go/pull/4253

An update will need to be made to remove this field from the quicreuse transport to avoid compilation errors.
https://github.com/libp2p/go-libp2p/blob/164adb40fef9c19774eb5fe6d92afb95c67ba83c/p2p/transport/quicreuse/config.go#L15

```
# github.com/libp2p/go-libp2p/p2p/transport/quicreuse
../../../../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.33.0/p2p/transport/quicreuse/config.go:15:2: unknown field RequireAddressValidation in struct literal of type quic.Config
```

<details>
<summary>Version Information</summary>
<pre>
github.com/libp2p/go-libp2p v0.33.0
github.com/libp2p/go-libp2p-asn-util v0.4.1
github.com/libp2p/go-libp2p-testing v0.12.0
github.com/quic-go/qpack v0.4.0
github.com/quic-go/qtls-go1-20 v0.3.4
github.com/quic-go/quic-go v0.42.0
github.com/quic-go/webtransport-go v0.6.0
</pre>
</details>

**Comment by Jorropo** [comment]
Would be fixed by #2740
