### ISSUE TITLE
[Hole Punching] - Implementation Example

### ISSUE THREAD

**Issue by AfonsoBatista7** [libp2p/go-libp2p#2761]
Is there currently any available NAT Transversal Hole Punching implementation example in Go? I saw it is in Rust but I didn't find it, in Go. If it doesn't exist yet, does someone have some recommendations or links on how I could implement one?

**Comment by wlynxg** [comment]
Enable the holepunch module by passing in Option:
https://github.com/libp2p/go-libp2p/blob/a2da8e026995ec6792554c0ee0942ef119c07753/options.go#L536

**Comment by wlynxg** [comment]
You can enable the holepunch module like this:
```go
libp2p.New(libp2p.EnableHolePunching())
```

**Comment by AfonsoBatista7** [comment]
> You can enable the holepunch module like this:
> 
> ```go
> libp2p.New(libp2p.EnableHolePunching())
> ```
Thanks!!

But how could I provide a public relay server address so that my peer could perform the hole punching with another peer?

I found this option to pass on the EnableHolePunching function and on it I can provide peer addrs info... do you know if thats it? 
 ```
libp2p.New(libp2p.EnableHolePunching(libp2p.EnableAutoRelayWithStaticRelays())
```

**Comment by wlynxg** [comment]
If you want to use a fixed Relay node address, you can write like this:
```go
var nodes []peer.AddrInfo
for _, s := range []string{"node1 info","node2 info"} {
    addrInfo, err := peer.AddrInfoFromString(s)
    if err != nil {
        panic(err)
    }
    nodes = append(nodes, *addrInfo)
}
libp2p.New(libp2p.EnableAutoRelayWithStaticRelays(nodes), libp2p.EnableHolePunching())
```

**Comment by AfonsoBatista7** [comment]
@wlynxg What does the EnableHolePunching do? does it only create a Node that can perform the hole punching? 
I ask this so I can understand what I still have to do to have it all working (Peer A behind NAT to be able to connect directly to Peer B behind NAT).

Thank you for your responses btw!

**Comment by wlynxg** [comment]
`EnableHolePunching` causes libp2p to load the holepunch module, which is enabled when a libp2p node finds itself behind a NAT via `AutoNAT`. When you establish a relay connection, the hole punching module will work and try to upgrade to a direct connection, which is the `DCUtR` protocol defined by libp2p.

These things are all done automatically inside libp2p, so you only need to enable holepunch through `EnableHolePunching` when creating the node, and use `EnableAutoRelayWithStaticRelays` to load the relay node address. Then libp2p will automatically perform hole drilling when establishing a connection with another node.

**Comment by wlynxg** [comment]
When a node is connected to the DHT network, the node will automatically exchange information with other nodes through the Identify protocol. In this process, the node will obtain its own public network egress address through information exchange.

So you just need to first link nodes A and B to the DHT network, then node B then connects to a relay server, and then node A connects to node B through the relay node. Later, nodes A and B will automatically try the holepunch logic.

**Comment by AfonsoBatista7** [comment]
Sorry to bother you again, but I'm trying to make the DHT work right now, and I already saw some examples, so I've been trying to implement it... I use this code to connect to some Default Bootstrap Peers:

```go
	if err = kademliaDht.Bootstrap(ctx); err != nil {
		logCallback(fmt.Sprintf("Failed to bootstrap the DHT: %s\n", err))
	}

	// Let's connect to the bootstrap nodes first. They will tell us about the
	// other nodes in the network.
	var wg sync.WaitGroup
	for _, peerAddr := range dht.DefaultBootstrapPeers {
		logCallback(fmt.Sprintf("Connecting to bootstrap node: %s\n", peerAddr))
		peerinfo, _ := peer.AddrInfoFromP2pAddr(peerAddr)
		wg.Add(1)
		go func() {
			defer wg.Done()
			if err := h.Connect(ctx, *peerinfo); err != nil {
				logCallback(fmt.Sprintf("Connection failed: %s\n", err))
			} else {
				logCallback(fmt.Sprintf("Connected to peer %s", peerinfo.ID))
			}
		}()
	}
	wg.Wait()
```

after, if I try to open another console to run peer B, it will also connect to the Bootstrap peers and populate the DHT but if I try to find peer A on it by providing his peer ID it says that he can't find it. I don't know if I need to do something else so that peer A and B can find each other on the DHT.

**Comment by MarcoPolo** [comment]
I'm not sure why it isn't working for you. From what I see it seems generally correct.

Take a look at the [chat with rendezvous](https://github.com/libp2p/go-libp2p/blob/8f999f00f723e1d0d501d4c2b10ac9e7d9ada2b1/examples/chat-with-rendezvous/chat.go) example. It should be doing something similar.

Also you could try using kubo to debug things. I find Kubo's `ipfs routing findpeer <peerid>` helpful to check if a node has inserted itself into the routing table correctly.

**Comment by wlynxg** [comment]
For node A, you are missing the program to broadcast data to the DHT. You need to add the following code:
```go
import (
	"context"
	"io"
	"log"
	"net"

	"github.com/libp2p/go-libp2p"
	dht "github.com/libp2p/go-libp2p-kad-dht"
	"github.com/libp2p/go-libp2p/core"
	"github.com/libp2p/go-libp2p/core/peer"
	"github.com/libp2p/go-libp2p/p2p/discovery/routing"
	"github.com/libp2p/go-libp2p/p2p/discovery/util"
)

func main() {
        // the code you have implemented to connect to the DHT node
        ......

        // you need to broadcast node A’s information to the DHT network here
	discovery := routing.NewRoutingDiscovery(kademliaDht)
	util.Advertise(ctx, discovery, h.ID().String())

	select {}
}
```

For node B, you can query the information of node A through the following code:
```go
import (
	"context"
	"io"
	"log"
	"net"

	"github.com/libp2p/go-libp2p"
	dht "github.com/libp2p/go-libp2p-kad-dht"
	"github.com/libp2p/go-libp2p/core"
	"github.com/libp2p/go-libp2p/core/peer"
	"github.com/libp2p/go-libp2p/p2p/discovery/routing"
	"github.com/libp2p/go-libp2p/p2p/discovery/util"
)

func main() {
        // the code you have implemented to connect to the DHT node
        ......

        // query information about node A
	discovery := routing.NewRoutingDiscovery(kademliaDht)
        peerChan, err := routingDiscovery.FindPeers(ctx, "node A's ID")
	if err != nil {
		panic(err)
	}

	for peer := range peerChan {
                ......
        }
}
```

**Comment by wlynxg** [comment]
Are you using the code below to expose node information to DHT?
```go
discovery := routing.NewRoutingDiscovery(kademliaDht)
util.Advertise(ctx, discovery, h.ID().String())
```

**Comment by AfonsoBatista7** [comment]
Yes Yes
![image](https://github.com/libp2p/go-libp2p/assets/61472117/b5d175e1-bb7f-4e7f-820e-361fee5ea648)

**Comment by wlynxg** [comment]
When querying nodes, do you use peerID.String() or the original peerID? (Because peerID and peerID.String() values are different)

**Comment by AfonsoBatista7** [comment]
Ok, I have been testing, and neither with peerID or peerID.String() I can find peer B...
I also tested searching for the host peer (when in peer A, search for peer A ID) after it has been advertised, and it finds it sometimes, other times it doesn't, which is weird...

This is the code I'm using to find my own peer:
```go
	if err = kademliaDht.Bootstrap(ctx); err != nil {
		logCallback(fmt.Sprintf("Failed to bootstrap the DHT: %s\n", err))
	}

	// Let's connect to the bootstrap nodes first. They will tell us about the
	// other nodes in the network.
	var wg sync.WaitGroup
	for _, peerAddr := range dht.DefaultBootstrapPeers {
		peerinfo, _ := peer.AddrInfoFromP2pAddr(peerAddr)
		wg.Add(1)
		go func() {
			defer wg.Done()
			if err := h.Connect(ctx, *peerinfo); err != nil {
				logCallback(fmt.Sprintf("Connection failed: %s\n", err))
			} else {
				logCallback(fmt.Sprintf("Connected to peer %s", peerinfo.ID))
			}
		}()
	}
	wg.Wait()

	logCallback("Advertising ourselves...")
	discovery = routing.NewRoutingDiscovery(kademliaDht)
	util.Advertise(contextVar, discovery, h.ID().String())

	peerChan, err := discovery.FindPeers(contextVar, h.ID().String())
	if err != nil {
		panic(err)
	}

	for peer := range peerChan {
		logCallback(fmt.Sprintf("Found peer %s\n", peer.ID))
		for addr := range peer.Addrs {
			logCallback(fmt.Sprintf("%s\n", peer.Addrs[addr]))
		}
	}
```

And this is the function I use to search for Peer B, I print to Peer B console his ID and I pass it to this function on Peer A as the destination:
```go
func connectToPeerAction(h host.Host, destination string) (*bufio.ReadWriter, error) {

	peerChan, err := util.FindPeers(contextVar, discovery, destination)
	if err != nil {
		panic(err)
	}

	for peer := range peerChan {
		logCallback(fmt.Sprintf("Found peer %s\n", peerChan[peer].ID))
		for addr := range peerChan[peer].Addrs {
			logCallback(fmt.Sprintf("%s\n", peerChan[peer].Addrs[addr]))
		}
	}
```

Any suggestions?

**Comment by AfonsoBatista7** [comment]
> I'm not sure why it isn't working for you. From what I see it seems generally correct.
> 
> Take a look at the [chat with rendezvous](https://github.com/libp2p/go-libp2p/blob/8f999f00f723e1d0d501d4c2b10ac9e7d9ada2b1/examples/chat-with-rendezvous/chat.go) example. It should be doing something similar.
> 
> Also you could try using kubo to debug things. I find Kubo's `ipfs routing findpeer <peerid>` helpful to check if a node has inserted itself into the routing table correctly.

@MarcoPolo yes, I'm already using some parts of that example, only the rendezvous part I removed because I don't want that on my project, for now I just wanted to try having 2 nodes to be able to find each other on their DHT so that they can Connect directly.

**Comment by AfonsoBatista7** [comment]
After a lot of testing and trial and error, I GOT THE DHT WORKING :D! Thanks a lot, guys! 
The error was because of the context var... while I was testing different things I deleted some important parts... so I had to come back to an early version and just start again. And it worked, so what @wlynxg and @MarcoPolo said should work.

Now I need to put the Hole Punching working... I'll come back when I have more questions...

**Comment by MarcoPolo** [comment]
Let's continue on [discussions](https://github.com/libp2p/go-libp2p/discussions). Closing this issue as there's nothing to do.

**Comment by iGwkang** [comment]
@MarcoPolo @wlynxg @AfonsoBatista7 
Hello, excuse me.
I have studied it for a long time, but I can't find a solution. I hope you can help me. Thank you !

I tried modifying the `chat-with-rendezvous` code. Added `NATPortMap`, `EnableHolePunching`, `EnableAutoRelayWithStaticRelays`
![image](https://github.com/user-attachments/assets/1a765be4-c68f-48f8-af92-a47476912f3e)

Host A run:
```bash
chat -listen /ip4/0.0.0.0/tcp/6666 -peer /ip4/public_ip/tcp/9876/p2p/12D3KooWP2soRwZSeaYabBvbRS76DNYzxqcKvimqKbMJRtHhNAra
```
Host B run:
```bash
chat -listen /ip4/0.0.0.0/tcp/6668 -peer /ip4/public_ip/tcp/9876/p2p/12D3KooWP2soRwZSeaYabBvbRS76DNYzxqcKvimqKbMJRtHhNAra
```
Host A and Host B are in different LANs, that is, behind NAT.

Here is my simple Bootstrap and Relay server code:
```go
relay1, err := libp2p.New(libp2p.ListenAddrStrings("/ip4/0.0.0.0/tcp/9876"))
if err != nil {
	log.Printf("Failed to create relay1: %v", err)
	return
}

_, err = relay.New(relay1, relay.WithInfiniteLimits())
if err != nil {
	log.Printf("Failed to instantiate the relay: %v", err)
	return
}
_, err = dht.New(context.Background(), relay1, dht.Mode(dht.ModeServer))
if err != nil {
	log.Printf("Failed to create DHT: %v", err)
	return
}

_, err = autonat.New(relay1)
if err != nil {
	log.Printf("Failed to create AutoNAT: %v", err)
	return
}

fmt.Printf("[*] Your Bootstrap ID Is: /ip4/%s/tcp/%v/p2p/%s\n", "0.0.0.0", 9876, relay1.ID().String())

select {}
```


After running, I found that the hole punching did not work. Host A and Host B could find each other, but could not establish a connection.

![image](https://github.com/user-attachments/assets/ebb54050-2a9a-45c0-b289-965da4c4b9d4)

**Comment by AfonsoBatista7** [comment]
@iGwkang 
Hey man :D
Idk if this will help but this is the code I am using for my relay:

`	
        sourceMultiAddrTCP, _ := multiaddr.NewMultiaddr("/ip4/0.0.0.0/tcp/4001")
	sourceMultiAddrUDP, _ := multiaddr.NewMultiaddr("/ip4/0.0.0.0/udp/4001/quic-v1")

	// libp2p.New constructs a new libp2p Host.
	// Other options can be added here.
	return libp2p.New(
		libp2p.ListenAddrs(sourceMultiAddrTCP, sourceMultiAddrUDP),

		// Attempt to open ports using uPNP for NATed hosts.
		libp2p.NATPortMap(),
		libp2p.EnableHolePunching(),
		libp2p.EnableNATService(),

		libp2p.EnableRelayService(),
	)
`

**Comment by iGwkang** [comment]
@AfonsoBatista7 

Still can't connect successfully, please note that Host A and Host B are behind different firewalls and both are cone NAT.
I feel like HolePunching holes isn't working.

![image](https://github.com/user-attachments/assets/2885a01b-437d-4906-8d28-cdd018ed2e21)

![image](https://github.com/user-attachments/assets/af4b3b8a-b547-4977-b850-bf02e963dc5d)

**Comment by AfonsoBatista7** [comment]
> @AfonsoBatista7
> 
> Still can't connect successfully, please note that Host A and Host B are behind different firewalls and both are cone NAT. I feel like HolePunching isn't working.
> 
> ![image](https://private-user-images.githubusercontent.com/35400668/349885654-2885a01b-437d-4906-8d28-cdd018ed2e21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjU2NTUsIm5iZiI6MTcyMTkyNTM1NSwicGF0aCI6Ii8zNTQwMDY2OC8zNDk4ODU2NTQtMjg4NWEwMWItNDM3ZC00OTA2LThkMjgtY2RkMDE4ZWQyZTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE2MzU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwNjc3MzdlZDFiMmE0NzU2NzJlZGIyMjNhYzE1N2QxOTNkNGM4Yjk1NTUwNjE5YWZhZWE0YzhhNDM3NjAwMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bgQRCSVTE1ZElpHpvxtFp2GJScNQ-TjhmLcDrFW0lmc)
> 
> ![image](https://private-user-images.githubusercontent.com/35400668/349885414-af4b3b8a-b547-4977-b850-bf02e963dc5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MjU2NTUsIm5iZiI6MTcyMTkyNTM1NSwicGF0aCI6Ii8zNTQwMDY2OC8zNDk4ODU0MTQtYWY0YjNiOGEtYjU0Ny00OTc3LWI4NTAtYmYwMmU5NjNkYzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE2MzU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNzQ0MjEyNWRlNTYyMTc3MjA4NmM0ZDM3ZjhmZjQ2ZTBhYTZjYWIzN2Y2MzBmYmE3OGViYjc0MmFjMDVlNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zDYWCxRycKX7o47xxiCJs_xuvefFCZl8aNdODUX8H5Y)

Sorry for the late reply...
I think the relay node need to be a public node, both Host A and B (behind NATs) need to be able to dial to the relay node.
Only this way, both node A and B will be able to connect to each other, by performing the hole punch through the relay peer

Can your host A and B dial the relay peer?

**Comment by iGwkang** [comment]
@AfonsoBatista7 I have specified the relay node.
https://github.com/libp2p/go-libp2p/discussions/2884

Do you have any sample code that can hole punching properly for me to refer to?
Thank you so mach. ❤

**Comment by NanoRed** [comment]
@iGwkang Hi have you solve this yet? i have the same problem

**Comment by iGwkang** [comment]
@NanoRed Sorry, I have given up using go-libp2p.
I spent up to a month on this issue, and no matter what I did, I couldn't succeed.
