### ISSUE TITLE
Disabled using gorilla/websocket version 1.5.1

### ISSUE THREAD

**Issue by wlynxg** [libp2p/go-libp2p#2762]
gorilla/websocket 1.5.1 is a problematic version. 
There will be many logs about websocket, and they seem to have introduced some problematic capabilities in this version. The specific information can be viewed at: https://github.com/gorilla/websocket/issues/880

When I use the new version of libp2p, many websocket logs similar to this are output on the terminal:
```bash
2024/04/10 20:15:47 websocket: failed to close network connection: close tcp 192.168.1.1:36880->147.75.87.27:443: use of closed network connection
```

**Comment by MarcoPolo** [comment]
Thanks for the context. It seems like they are reverting the problematic commit, and will reintroduce it in parts with fixes. It seems fine to revert and wait for the changes to be reintroduced.
