### ISSUE TITLE
Allow Option to set quic.Config{}.KeepAlivePeriod

### ISSUE THREAD

**Issue by zeisler** [libp2p/go-libp2p#2779]
I'm requesting the ability to set the KeepAlivePeriod for quic connections. https://github.com/libp2p/go-libp2p/blob/0385ec924bad172f74a74db09939e97c079b1420/p2p/transport/quicreuse/config.go#L14

When rebooting an upstream node and I'd like the downstream node to notice it's disconnected quicker so it can find a new node.

**Comment by marten-seemann** [comment]
Are you familiar with QUIC Stateless Resets? They should solve this problem: https://quic-go.net/docs/quic/transport/#stateless-reset

**Comment by zeisler** [comment]
Does this mean that as long as the private key is constant this should already work?

**Comment by marten-seemann** [comment]
Yes, and the stateless reset key is derived from the node's libp2p (private) key: https://github.com/libp2p/go-libp2p/blob/0385ec924bad172f74a74db09939e97c079b1420/config/quic.go#L19-L30
