### ISSUE TITLE
P2P technical suggestion: Use the birthday paradox to improve brute force scanning to achieve symmetrical punching

### ISSUE THREAD

**Issue by introspection3** [libp2p/go-libp2p#2782]
[https://tailscale.com/blog/how-nat-traversal-works](https://tailscale.com/blog/how-nat-traversal-works
)
![image](https://github.com/ntop/n2n/assets/12368358/c10ebcdc-824a-4988-89f2-8fbac1ec462b)

**Comment by Jorropo** [comment]
I remember talking about this with other peoples before.

For TCP we would need a way to cheaply send many TCP SYN packets (such as by using a raw socket) but then transition one of them to a "real" TCP connection as we like using the kernel's network stack for TCP. The overhead of asking the kernel to do 1024 TCP connections is too high for many applications (just the fd cost is already a big barrier).
For UDP it might require a bit of hacking in quic-go or how we interface with it but given this is userland it's far more realistic.

Timing might also be an issue as you need to send all of your probes before your NAT starts receiving to get full effectiveness, you might also need to pace probes to avoid cheap WiFi routers dropping packets.
This means the most holepunchable networks are wired high speed LAN with slow speed WAN (or high speed but high geographical distance so ping is higher).

However currently the holepunch success rate is lower than it should be. afaik there are still IPv6 issues even tho it's supposed to be much easier to holepunch.
We would also need more state management, probably in the autonat client to detect our external visible port range

**Comment by MarcoPolo** [comment]
Feel free to run this yourself and report back on your results. I'm curious how it would fare in hole punching cell networks :)

I'm going to close this issue since it's not something we're going to work on anytime soon. Feel free to open a discussion to continue discussing.
