### ISSUE TITLE
`blankhost.WithEventBus()` does not work as expected

### ISSUE THREAD

**Issue by sink772** [libp2p/go-libp2p#2786]
I wanted to test my p2p module that is using `Host.EventBus().Subscribe(&event.EvtPeerConnectednessChanged{})`.
So I wrote a test code like the following to set the same eventbus to both swamt and blankhost.
```
    bus := eventbus.NewBus()
    sw := swarmt.GenSwarm(t, swarmt.EventBus(bus))
    h := bhost.NewBlankHost(sw, bhost.WithEventBus(bus))
```
But my test code failed to get the EvtPeerConnectednessChanged notification.

Looking into the `NewBlankHost` below, it does not set `config.eventBus` anywhere.
https://github.com/libp2p/go-libp2p/blob/0385ec924bad172f74a74db09939e97c079b1420/p2p/host/blank/blank.go#L65-L72

I think the above code should be modified as follows.
```
--- a/p2p/host/blank/blank.go
+++ b/p2p/host/blank/blank.go
@@ -65,6 +65,7 @@ func NewBlankHost(n network.Network, options ...Option) *BlankHost {
        bh := &BlankHost{
                n:    n,
                cmgr: cfg.cmgr,
+               eventbus: cfg.eventBus,
                mux:  mstream.NewMultistreamMuxer[protocol.ID](),
        }
        if bh.eventbus == nil {
```

**Comment by MarcoPolo** [comment]
Funny enough, we actually just fixed that in a separate PR an hour after you submitted the issue.

**Comment by sink772** [comment]
So where is the separate PR?

**Comment by MarcoPolo** [comment]
It's merged. Look at the same spot in the code on master

**Comment by sink772** [comment]
Ok, I confirmed.
