### ISSUE TITLE
Query: Where is the bootstrap package in the latest version?

### ISSUE THREAD

**Issue by paulwizviz** [libp2p/go-libp2p#2802]
I am new to the library. I was told there is a bootstrap package to support bootstrap-based discovery.

**Comment by sukunrt** [comment]
I think you are looking for [go-libp2p-kad-dht](https://github.com/libp2p/go-libp2p-kad-dht
) 
Here is the bootstrap peers option for it: 
https://github.com/libp2p/go-libp2p-kad-dht/blob/master/dht_options.go#L275

For mdns based discovery look at https://pkg.go.dev/github.com/libp2p/go-libp2p/p2p/discovery/mdns

**Comment by gammazero** [comment]
@paulwizviz I think you are looking for https://github.com/ipfs/boxo/blob/main/bootstrap/bootstrap.go
Docs: https://pkg.go.dev/github.com/ipfs/boxo@v0.21.0/bootstrap
