### ISSUE TITLE
More demos like js-libp2p ???

### ISSUE THREAD

**Issue by BenDerPan** [libp2p/go-libp2p#283]
Is there more examples with go-libp2p ? such as nat-traversal, pub-sub, chat, peer-and-content-routing... 
The js version has all of it , is there any go version ?

**Comment by deckbsd** [comment]
Hello @BenDerPan ,
as far as i know there aren't that kind of example in go at this time. All are in [examples](https://github.com/libp2p/go-libp2p/tree/master/examples)

**Comment by BenDerPan** [comment]
thx :)   @deckbsd , Is there any blockchain example based on go-libp2p?

**Comment by deckbsd** [comment]
@BenDerPan  Yes, for example [holochain](https://holochain.org/) ,all the ones that use IPF ([Filecoin](https://filecoin.io/) ), ...

**Comment by BenDerPan** [comment]
@deckbsd  that's great! thx!!!

**Comment by whyrusleeping** [comment]
Hey @BenDerPan, aside from the examples in the examples directory, is there anything in particular you would like to see?

I recently pushed an experiment in creating a blockchain using libp2p and ipfs here: https://github.com/whyrusleeping/toychain

And I'm working on a new example/tutorial for a pubsub based chat here: https://gist.github.com/whyrusleeping/169a28cffe1aedd4419d80aa62d361aa

**Comment by BenDerPan** [comment]
Hi @whyrusleeping , really great，I am looking for more practicing examples with go-libp2p, and I want  try to build a blockchain application with it.  This 
 document is very good[https://gist.github.com/whyrusleeping/169a28cffe1aedd4419d80aa62d361aa](https://gist.github.com/whyrusleeping/169a28cffe1aedd4419d80aa62d361aa) , I will try with it.

**Comment by deckbsd** [comment]
@whyrusleeping great ! Btw i don't know where to post this, but there is a little mistake in your code :
When we want to connect to peer, it's  
``if p.ID == host.ID() {``
not
``if p == host.ID() {``

**Comment by whyrusleeping** [comment]
@deckbsd ah yeah, thanks. Transcription error :)

**Comment by Stebalien** [comment]
https://github.com/libp2p/go-libp2p/tree/master/examples
