### ISSUE TITLE
failed to listen on any addresses: [listen tcp4 192.0.2.0:0: bind: The requested address is not valid in its context.]

### ISSUE THREAD

**Issue by ModdersAssociation** [libp2p/go-libp2p#2836]
This bug tracker is only for actionable bug reports and feature requests. Please direct any questions to https://discuss.libp2p.io or to our Matrix (#libp2p:matrix.org) or IRC (#libp2p on freenode) channels.

If you don't get an immediate response, please keep trying.

**Comment by sukunrt** [comment]
`192.0.2.0` is a documentation only IP address. You will not be able to listen successfully on it.
