### ISSUE TITLE
Peer discovery not working with mocknet on and go-multiaddr v0.12.4

### ISSUE THREAD

**Issue by sstanculeanu** [libp2p/go-libp2p#2837]
Hello,

While trying to update our dependency of go-libp2p from `v0.28.2` to `v0.34.0`(please find below a capture with old + new versions of the libs :point_down: ), we noticed that the peer discovery does not work anymore with mocknet.

Digging a bit deeper, we localized the issue: it looks like the hardcoded ip6 multiaddr from [GenPeerWithOptions](https://github.com/libp2p/go-libp2p/blob/v0.34.0/p2p/net/mock/mock_net.go#L88) is not compatible anymore with the latest release of `go-multiaddr` with the newly added [ip6 restriction](https://github.com/multiformats/go-multiaddr/pull/235). `isPublic` is now always false [here](https://github.com/multiformats/go-multiaddr/blob/v0.12.4/net/private.go#L143) for the hardcoded address.

This leads to the multiaddr not being saved into the peerstore, thus peer discovery not working.

I've created a simple test in order to highlight the issue, which can be found on [this repo](https://github.com/sstanculeanu/test-libp2p).

![image](https://github.com/libp2p/go-libp2p/assets/34831323/d8519902-b4c7-4810-ac91-cb5ca0ed5127)

Thanks

**Comment by sukunrt** [comment]
This will be fixed by v0.35.1
It's fixed on master by #2820

**Comment by sstanculeanu** [comment]
Re-tested with master branch, looks good :pray:

**Comment by sukunrt** [comment]
V0.35.1 is out!
