### ISSUE TITLE
discovery: not allowing limit to be 0

### ISSUE THREAD

**Issue by guillaumemichel** [libp2p/go-libp2p#2859]
https://github.com/libp2p/go-libp2p/blob/ad7da3b5bfb46fde977911bf3546d5028e473a32/p2p/discovery/routing/routing.go#L65-L68

Is there a reason why we don't want a limit equal to `0` in `FindPeers`? In [`FindProvidersAsync`](https://github.com/libp2p/go-libp2p-kad-dht/blob/25d299e64f3cb9a3da337e9d4af1a1b722ae503d/routing.go#L491-L496), a `count` of `0` allows to return all the discovered provider records.

As a result, a caller of `FindPeers` willing to retrieve all provider records would have to provide an arbitrary large value, which seems odd since this feature is already implemented by `FindProvidersAsync`.

**Comment by sukunrt** [comment]
This makes sense. ContentRouting interface does specify that count 0 should be considered as all. Want to raise a PR?

**Comment by guillaumemichel** [comment]
Yes, I'll open a PR
