### ISSUE TITLE
libp2p.New returns a host. Meaning users have to import a different package

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#287]
This is a weird bit of developer UX. But the main constructor here returns a type that is not in this package, making it a little awkward to work with. Not sure if we should add a type alias or something here to make it easier or what.

**Comment by marten-seemann** [comment]
We could alias the `go-libp2p-core.Host` to `go-libp2p.Host`, but I doubt that users will be able to build an application without importhing -core at some point.
