### ISSUE TITLE
chat with rendezvous

### ISSUE THREAD

**Issue by sekomer** [libp2p/go-libp2p#2880]
hi, im trying to build a toy blockchain to learn fundamentals. I want to use libp2p for communicating nodes. (I tried couple of things, correct me if I tell anything wrong below)

 I tried `pub/sub` example, but that was communicating over a relay node, peers doesn't directly communicating each other but messages coming from a single bootstrapper node.

Then I tried `chat with mdns` example, I could do the things I want to do using it, but then I realized I cannot use that globally, its only for LAN network.

Then I switched to `chat with rendezvous` example, it seems like it can solve my problem, but I cannot run the nodes, im getting the following error, immediately after starting the first node.

My question is, for my case, which examples should I rely on for communicating the nodes in my blockchain? And if its the `chat with rendezvous` example, how I can fix the error below :D 

thanks in advance

```
❯ ./chat -listen /ip4/127.0.0.1/tcp/6660
2024-07-21T10:39:52.993+0300    INFO    rendezvous      chat-with-rendezvous/chat.go:105    Host created. We are:12D3KooWBQ7KY3cVKWkD2RipSnjvyRCLG9K9AnbWGgG1SXvn7JQp
2024-07-21T10:39:52.994+0300    INFO    rendezvous      chat-with-rendezvous/chat.go:106    [/ip4/127.0.0.1/tcp/6660]
2024-07-21T10:39:52.995+0300    WARN    dht/RtRefreshManager    rtrefresh/rt_refresh_manager.go:187  failed when refreshing routing table2 errors occurred:
        * failed to query for self, err=failed to find any peer in table
        * failed to refresh cpl=0, err=failed to find any peer in table


2024-07-21T10:39:53.995+0300    INFO    rendezvous      chat-with-rendezvous/chat.go:139    Announcing ourselves...
2024-07-21T10:39:54.881+0300    WARN    rendezvous      chat-with-rendezvous/chat.go:162    Connection failed:failed to dial: failed to dial 12D3KooWHd3ChdBbiz3QWia88aqKAU96frBUe9oG9ZFisVG43sxg: all dials failed
  * [/ip4/127.0.0.1/tcp/6666] dial tcp4 127.0.0.1:6666: connect: connection refused
2024-07-21T10:39:54.882+0300    WARN    rendezvous      chat-with-rendezvous/chat.go:162    Connection failed:failed to dial: failed to dial 12D3KooWKuEHWABqirJckwjEEYFEovNn8jXGWcM48Q4BRtkwUxH3: all dials failed
  * [/ip4/127.0.0.1/tcp/6661] dial tcp4 127.0.0.1:6661: connect: connection refused
2024-07-21T10:39:54.883+0300    WARN    rendezvous      chat-with-rendezvous/chat.go:162    Connection failed:failed to dial: failed to dial 12D3KooWNLF2ymqWj8vPf2MqJS7DYyJYRFBCdUz1SoYUVnXKtpT9: all dials failed
  * [/ip4/127.0.0.1/tcp/6666] dial tcp4 127.0.0.1:6666: connect: connection refused
2024-07-21T10:39:54.885+0300    WARN    rendezvous      chat-with-rendezvous/chat.go:162    Connection failed:failed to dial: failed to dial 12D3KooWEcWgbFQUK649kU99dPkTtFUhpfr7aqKQUa5sFHE7UDzR: all dials failed
  * [/ip4/127.0.0.1/tcp/6668] failed to negotiate security protocol: peer id mismatch: expected 12D3KooWEcWgbFQUK649kU99dPkTtFUhpfr7aqKQUa5sFHE7UDzR, but remote key matches 12D3KooWPgMWkfKuVF8uzpJKsYqpMozXN6HXzibtHV7KVmdD8z2W
2024-07-21T10:39:55.665+0300    WARN    net/identify    identify/id.go:434      failed to identify 12D3KooWRAchpsWrf4wwpRH7xHgB3HFgWFxz8xc8PcPfMbNJXrj3: Application error 0x1 (remote): conn-161376243: system: cannot reserve inbound connection: resource limit exceeded
2024-07-21T10:39:55.954+0300
```

**Comment by iGwkang** [comment]
Hi, 
This example uses the default guide node, and the default bootstrap node seems to be unable to connect, which requires self  built bootstrap nodes.
This is my example code:
```go
	prvKey, _, err := crypto.GenerateKeyPairWithReader(crypto.RSA, 2048, rand.Reader)
	if err != nil {
		log.Println(err)
		return
	}

	relay1, err := libp2p.New(libp2p.Identity(prvKey), libp2p.ListenAddrStrings("/ip4/0.0.0.0/tcp/9876", "/ip4/0.0.0.0/udp/9876/quic-v1"))
	if err != nil {
		log.Printf("Failed to create relay1: %v", err)
		return
	}

	_, err = relay.New(relay1)
	if err != nil {
		log.Printf("Failed to instantiate the relay: %v", err)
		return
	}
	_, err = dht.New(context.Background(), relay1, dht.Mode(dht.ModeServer)) //
	if err != nil {
		log.Printf("Failed to create DHT: %v", err)
		return
	}
	fmt.Printf("[*] Your Bootstrap ID Is: /ip4/%s/tcp/%v/p2p/%s\n", "0.0.0.0", 9876, relay1.ID().String())
```

You can specify the bootstrap node by specifying the `-peer` parameter.
But I found that this example is not have  holepunching, even if the EnableHolePunching is added, it will not take effect.
That's what I've been exploring, I'm not sure at the moment why the hole punching isn't working.
https://github.com/libp2p/go-libp2p/issues/2878
https://github.com/libp2p/go-libp2p/issues/2761#issuecomment-2235971016

**Comment by sekomer** [comment]
@iGwkang thanks buddy,

I am trying to build a blockchain, therefore each node should be behaving same, when someone wants to join the p2p network, I want each of the nodes to act as a bootstrap node, is this possible with this example and your solution after initial start of the network, and some number of peers are active?

**Comment by mgazza** [comment]
Is there any update to this, i want to do something similar and hitting the same issue

**Comment by JackBekket** [comment]
> @iGwkang thanks buddy,
> 
> I am trying to build a blockchain, therefore each node should be behaving same, when someone wants to join the p2p network, I want each of the nodes to act as a bootstrap node, is this possible with this example and your solution after initial start of the network, and some number of peers are active?

Nice idea

You don't have to be all nodes as bootstrap nodes, it does not make any sense. every node is already storing local dht table, so it won't be an issue

Bootstrup nodes however, in a contradiction to miner's nodes, should have a public dedicated IP and it's cannot be under NAT. This thing is also should be *always* up.

If you are familiar with torrent, then think about bootstrap nodes as a torrent tracker, and if you are familiar with ethereum v.2, then think of it as a Beacon nodes.

Other (miners) nodes in your network can be behind the NAT and also it can go *offline* very often, so you just can't use it as bootstrap nodes


Also tell me more about your blockchain project?

**Comment by JackBekket** [comment]
> Hi, This example uses the default guide node, and the default bootstrap node seems to be unable to connect, which requires self built bootstrap nodes. This is my example code:
> 
> ```go
> 	prvKey, _, err := crypto.GenerateKeyPairWithReader(crypto.RSA, 2048, rand.Reader)
> 	if err != nil {
> 		log.Println(err)
> 		return
> 	}
> 
> 	relay1, err := libp2p.New(libp2p.Identity(prvKey), libp2p.ListenAddrStrings("/ip4/0.0.0.0/tcp/9876", "/ip4/0.0.0.0/udp/9876/quic-v1"))
> 	if err != nil {
> 		log.Printf("Failed to create relay1: %v", err)
> 		return
> 	}
> 
> 	_, err = relay.New(relay1)
> 	if err != nil {
> 		log.Printf("Failed to instantiate the relay: %v", err)
> 		return
> 	}
> 	_, err = dht.New(context.Background(), relay1, dht.Mode(dht.ModeServer)) //
> 	if err != nil {
> 		log.Printf("Failed to create DHT: %v", err)
> 		return
> 	}
> 	fmt.Printf("[*] Your Bootstrap ID Is: /ip4/%s/tcp/%v/p2p/%s\n", "0.0.0.0", 9876, relay1.ID().String())
> ```
> 
> You can specify the bootstrap node by specifying the `-peer` parameter. But I found that this example is not have holepunching, even if the EnableHolePunching is added, it will not take effect. That's what I've been exploring, I'm not sure at the moment why the hole punching isn't working. #2878 [#2761 (comment)](https://github.com/libp2p/go-libp2p/issues/2761#issuecomment-2235856645) [#2761 (comment)](https://github.com/libp2p/go-libp2p/issues/2761#issuecomment-2235971016)

Oh, thanks, so default IPFS bootstrap nodes doesn't work anymore, cause of too many connections and now we have to run bootstrap nodes for ourselves?

**Comment by sekomer** [comment]
> > @iGwkang thanks buddy,
> > I am trying to build a blockchain, therefore each node should be behaving same, when someone wants to join the p2p network, I want each of the nodes to act as a bootstrap node, is this possible with this example and your solution after initial start of the network, and some number of peers are active?
> 
> Nice idea
> 
> You don't have to be all nodes as bootstrap nodes, it does not make any sense. every node is already storing local dht table, so it won't be an issue
> 
> Bootstrup nodes however, in a contradiction to miner's nodes, should have a public dedicated IP and it's cannot be under NAT. This thing is also should be _always_ up.
> 
> If you are familiar with torrent, then think about bootstrap nodes as a torrent tracker, and if you are familiar with ethereum v.2, then think of it as a Beacon nodes.
> 
> Other (miners) nodes in your network can be behind the NAT and also it can go _offline_ very often, so you just can't use it as bootstrap nodes
> 
> Also tell me more about your blockchain project?

thanks a lot, I already solved my problem and created a simple p2p network by tinkering the docs and examples!
