### ISSUE TITLE
BasicConnMgr exceed high water

### ISSUE THREAD

**Issue by sekomer** [libp2p/go-libp2p#2886]
hi, im configuring my basic connection manager as follows

```go
	connmgr, err := connmgr.NewConnManager(
		2, // Lowwater
		3, // HighWater,
		connmgr.WithGracePeriod(time.Second),
	)
```

im printing all the peers to console in every 5 seconds as following
```go

	go func() {
		ticker := time.NewTicker(5 * time.Second)

		for range ticker.C {
			pxr := h2.Peerstore().PeersWithAddrs()
			fmt.Println("peerstore", pxr)

			fmt.Print("\n")

			peers := h2.Network().Peers()
			fmt.Println("network peers", peers)

			fmt.Print("\n\n")
		}
	}()
```

and this is a following output of mine
```
peerstore 
12D3KooWCyuB4jMgrrvyXsx1B4isJaLRrssRt2AtFSsS2dFM8A4F, 12D3KooWNYi374e57E4aAQZX6UWf27xqPMUQXWz7tKd9d4KN7zjL, 12D3KooWJftVae2Rg7ZvKq5YgRoFMT2xzcnW8G35pDb5PqVR9sfE, 12D3KooWK6YwYhN8AX4KpgTUGcNXBjfF1dbh1ur3PyFCwZsthM9J, 12D3KooWE7Ccy9LgsFuuUpnhd7P8cCBMxiaBLUuqTmQw7aWzPBas, 12D3KooWQYHdUYTB8aKFBm9Pbpbpiez8cYbRCELzovVT7TG8Lnpx, 12D3KooWFeQryuc13tJPSZkXBSo7nVUw7iExvxZ2WwDi5iP3419M, 12D3KooWBJEAfL1iC9jjGMjWCnaKMjEMT7Q3M6ASH9SU4YChCU78, 12D3KooWCcXnCfztuUP8Nm7Gg5RBmht1XRcLapJ2PKfDtB8MvY4w, 12D3KooWBWFaqUHtPccTFMmpwFjVF6EXjpBrAjcyCiFpEsY1J1Ub, 12D3KooWQzijU42FHfiaNuuoS7k59BX9LSyTjbBsYRhzzATK2myb, 12D3KooWLJEDGyFiFDwpR4iExyk2zypU6gsyQKhP1equ8C2hcS35, 12D3KooWPPGj9yjpVNjNkg8JHeciTYzMWCPFtFujD5QuGfffitdK

network peers [
12D3KooWBWFaqUHtPccTFMmpwFjVF6EXjpBrAjcyCiFpEsY1J1Ub 12D3KooWCcXnCfztuUP8Nm7Gg5RBmht1XRcLapJ2PKfDtB8MvY4w 12D3KooWQzijU42FHfiaNuuoS7k59BX9LSyTjbBsYRhzzATK2myb 12D3KooWLJEDGyFiFDwpR4iExyk2zypU6gsyQKhP1equ8C2hcS35 12D3KooWJftVae2Rg7ZvKq5YgRoFMT2xzcnW8G35pDb5PqVR9sfE 12D3KooWPPGj9yjpVNjNkg8JHeciTYzMWCPFtFujD5QuGfffitdK 12D3KooWBJEAfL1iC9jjGMjWCnaKMjEMT7Q3M6ASH9SU4YChCU78 12D3KooWFeQryuc13tJPSZkXBSo7nVUw7iExvxZ2WwDi5iP3419M 12D3KooWCyuB4jMgrrvyXsx1B4isJaLRrssRt2AtFSsS2dFM8A4F ]
```

as you can see, peerstore has 13 items, but active peers has 9, and its never exceeding 9, whats wrong here? are there a hard limitation for low/high water?

ps: for some nodes, number of network peers equal to peerstore, and its above the limit, why?

heres my node
```go
	h2, err := libp2p.New(
		// Use the keypair we generated
		libp2p.Identity(priv),
		// Multiple listen addresses
		libp2p.ListenAddrStrings(
			fmt.Sprintf("/ip4/0.0.0.0/tcp/%s", *port),      // regular tcp connections
			fmt.Sprintf("/ip4/0.0.0.0/udp/%s/quic", *port), // a UDP endpoint for the QUIC transport
		),
		// support TLS connections
		libp2p.Security(libp2ptls.ID, libp2ptls.New),
		// support noise connections
		libp2p.Security(noise.ID, noise.New),
		// support any other default transports (TCP)
		libp2p.DefaultTransports,
		// Let's prevent our peer from having too many
		// connections by attaching a connection manager.
		libp2p.ConnectionManager(connmgr),
		// Attempt to open ports using uPNP for NATed hosts.
		libp2p.NATPortMap(),
		// Let this host use the DHT to find other hosts
		libp2p.Routing(func(h host.Host) (routing.PeerRouting, error) {
			idht, err = dht.New(context.Background(), h, dht.Mode(dht.ModeServer))
			return idht, err
		}),
		libp2p.EnableNATService(),
	)
```

**Comment by munna0908** [comment]
@sekomer ConnectionManager always tries to maintain connections within the provided limits, but it's possible for a node to exceed these limits due to a grace period for new connections.

Regarding entries in the peerstore, every time a peer performs a handshake with a remote peer, the remote peer's information is added to the peerstore. In this case, the kDHT protocol might have led to new connections.

I hope I have answered your question. For any further help, please open a thread in the discussion [forum](https://discuss.libp2p.io)

**Comment by sekomer** [comment]
thx @munna0908 

then i want to ask you, am i printing the information im looking for?
does the `peers := h2.Network().Peers()` line get the active peers connected with me?

and one more question, im trying to build my own blockchain, and i want to use libp2p for communicating my nodes, i used libp2p-host example as base, do you think this is the correct way to go? or are there any better examples to follow, such as pubsub, relay, etc

**Comment by munna0908** [comment]
Yeah, `h2.Network().Peers()` returns the list of connected peers. To build a p2p networking module for a blockchain protocol, you can use the following libp2p sub-modules:

**Peer Discovery**: Routing [Discovery](https://pkg.go.dev/github.com/libp2p/go-libp2p@v0.35.4/p2p/discovery/routing) using kDHT

**Block & Transaction Broadcast**: [PubSub](https://pkg.go.dev/github.com/libp2p/go-libp2p-pubsub)

**Direct communication between peers**: streams or [libp2p-rpc](https://github.com/libp2p/go-libp2p-gorpc)

The examples repo is a good place to start; it has examples covering all the above sub-modules. For further reference, you can check the [polygon-edge](https://github.com/0xPolygon/polygon-edge/tree/develop/network) implementation.

**Comment by sukunrt** [comment]
ConnectionManager only implements soft limits. You can call `connmgr.Protect` to protect a connection from being closed by the connection manager. 

In this case, the dht is most likely protecting connections.

**Comment by sekomer** [comment]
@munna0908 @sukunrt 
you guys are awesome, thank you! <3
