### ISSUE TITLE
Build failure (gx dependencies)

### ISSUE THREAD

**Issue by mildred** [libp2p/go-libp2p#29]
Since commit 7b48e5bc4d25c1d43d950fe40760eb028a273180 I am unable to build this package. More specifically `./p2p/net/swarm/addr`. The first problem is:

```
# github.com/ipfs/go-libp2p/p2p/net/swarm/addr
p2p/net/swarm/addr/addr.go:70: cannot use split[0] (type "gx/ipfs/QmcobAGsCjYt5DXoq9et9L8yR8er7o7Cu3DTvpaq12jYSz/go-multiaddr".Multiaddr) as type "github.com/jbenet/go-multiaddr".Multiaddr in argument to manet.IsIP6LinkLocal:
	"gx/ipfs/QmcobAGsCjYt5DXoq9et9L8yR8er7o7Cu3DTvpaq12jYSz/go-multiaddr".Multiaddr does not implement "github.com/jbenet/go-multiaddr".Multiaddr (wrong type for Decapsulate method)
		have Decapsulate("gx/ipfs/QmcobAGsCjYt5DXoq9et9L8yR8er7o7Cu3DTvpaq12jYSz/go-multiaddr".Multiaddr) "gx/ipfs/QmcobAGsCjYt5DXoq9et9L8yR8er7o7Cu3DTvpaq12jYSz/go-multiaddr".Multiaddr
		want Decapsulate("github.com/jbenet/go-multiaddr".Multiaddr) "github.com/jbenet/go-multiaddr".Multiaddr
```

When I look at the code, the failure is normal. The package `gx/ipfs/QmQB7mNP3QE7b4zP2MQmsyJDqG5hzYE2CL8k1VyLWky2Ed/go-multiaddr-net` uses `github.com/jbenet/go-multiaddr` while libp2p uses the incompatible package `gx/ipfs/QmcobAGsCjYt5DXoq9et9L8yR8er7o7Cu3DTvpaq12jYSz/go-multiaddr`.

Both are very similar but the `Multiaddr` type from the gx package is different from the `Multiaddr` type from the github package.

We should probably update `gx/ipfs/QmQB7mNP3QE7b4zP2MQmsyJDqG5hzYE2CL8k1VyLWky2Ed/go-multiaddr-net` to use `gx/ipfs/QmcobAGsCjYt5DXoq9et9L8yR8er7o7Cu3DTvpaq12jYSz/go-multiaddr` instead of `github.com/jbenet/go-multiaddr`

Also, this might not be the right place for this discussion, but I am worrying about the go package names that encode the download location. Both github and gx. Go has a feature to enable any domain (not just GitHub) to be part of an import path (see [Remote import paths](https://golang.org/cmd/go/#hdr-Remote_import_paths)). Perhaps we should use the ipfs.io domain for our packages and have gx integrate into that scheme. The package name would be the same, regardless of where it comes from, IPFS or GitHub.

**Comment by whyrusleeping** [comment]
I think this has since been resolved.
