### ISSUE TITLE
DHT: go-libp2p v0.34 breaks TestRTEvictionOnFailedQuery in the DHT

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#2911]
To reproduce, download go-libp2p-kad-dht and run:

```bash
go test -run TestRTEvictionOnFailedQuery
```

See: https://github.com/libp2p/go-libp2p-kad-dht/pull/974

Note: That PR updates a bunch of deps, but I've narrowed it down to libp2p v0.33 to v0.34.

**Comment by sukunrt** [comment]
Based on this: https://github.com/libp2p/go-libp2p-kad-dht/pull/974#issuecomment-2274322375
This should be fixed in go-libp2p-kad-dht. Closing a custom constructed basic host should not close the swarm as the host didn't create the swarm.

**Comment by Stebalien** [comment]
Oh.... I see. Although I disagree, giving a swarm to a host transfers ownership.

**Comment by sukunrt** [comment]
You're right. 


`host.Connect` should fail after closing the host
