### ISSUE TITLE
Break examples out into a new repo

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#292]
This should reduce the code size of this repo *and* reduce the number of dependencies.

**Comment by Kubuxu** [comment]
I am not sure this is the right thing.
There were discussions previously about what form this repo should take. I can't recall conclusions of them.

@lgierth what do you think?

**Comment by Stebalien** [comment]
So, one motivation is that the DHT currently depends on this repo so we can't add any examples that use the DHT. (see #278). We could, alternatively:

* Put that example in the DHT repo.
* Move the parts of go-libp2p that the DHT actually needs (for tests) in a separate repo.
* Figure out a better way to deal with test dependencies (multiple gx packages in a single repo).

**Comment by anacrolix** [comment]
Looks like this was done in #381.
