### ISSUE TITLE
libp2p on gitter

### ISSUE THREAD

**Issue by upperwal** [libp2p/go-libp2p#294]
Sorry for posting it in the issues. Don't know any other way. 

Is it possible to have a separate gitter (or any other) chat room for libp2p like ifps. Could be in the same community (ifps). It could help developers to ask quick questions/discussions and not open an issue for the same. If you already have something like this, please let me know.

@Stebalien @jbenet @diasdavid

**Comment by Stebalien** [comment]
We have an IRC chat room (#libp2p on irc.freenode.net). I wasn't even aware of the ipfs gitter, most of us hang out on the #ipfs IRC channel on irc.freenode.net.

**Comment by upperwal** [comment]
Got it. Thanks!
