### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by hsanjuan** [libp2p/go-libp2p#296]
For newcomers, it would be great that https://godoc.org/github.com/libp2p/go-libp2p#New showed how to use the `New` method and the config options, and explained how to get a working default libp2p node.

This is the entrypoint documentation for the whole go-libp2p project.

**Comment by upperwal** [comment]
Totally agree but is it necessary to include explanations in the source code. Is it possible to have a wiki with sample code explaining how libp2p works. libp2p/specs repo could also be merged into that.

**Comment by marten-seemann** [comment]
This should be covered by https://docs.libp2p.io/.
