### ISSUE TITLE
Transport + Swarm refactor

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#297]
Moved from https://github.com/libp2p/go-libp2p-transport/issues/21 for visibility.

Related to #279 (but this one is *just* about the refactor itself, not the overall task of QUIC + TLS + refactor).

State: In review. go-ipfs currently builds and runs (well) with these patches.

Branch `feat/refactor` in:

* [x] [ipfs/go-ipfs](https://github.com/ipfs/go-ipfs)
  * [x] PR open
  * [x] Reviewed
  * [x] Merged
* [x] [libp2p/go-libp2p-metrics](https://github.com/libp2p/go-libp2p-metrics)
  * [x] PR open - https://github.com/libp2p/go-libp2p-metrics/pull/12
  * [x] Reviewed - @whyrusleeping 
  * [x] Merged
* [x] [libp2p/go-libp2p-swarm](https://github.com/libp2p/go-libp2p-swarm)
  * [x] PR open -  https://github.com/libp2p/go-libp2p-swarm/pull/63
  * [x] Reviewed - @Kubuxu, @whyrusleeping, @magik6k
  * [x] Merged
* [x] [libp2p/go-libp2p-circuit](https://github.com/libp2p/go-libp2p-circuit)
  * [x] PR open - https://github.com/libp2p/go-libp2p-circuit/pull/33
  * [x] Reviewed - @vyzo 
  * [x] Merged
* [x] [libp2p/go-ws-transport](https://github.com/libp2p/go-ws-transport)
  * [x] PR open - https://github.com/libp2p/go-ws-transport/pull/31
  * [x] Reviewed
  * [x] Merged
* [x] [libp2p/go-libp2p-kad-dht](https://github.com/libp2p/go-libp2p-kad-dht) -- netutil changes + changed notification guarantees.
  * [x] PR open - https://github.com/libp2p/go-libp2p-kad-dht/pull/126
  * [x] Reviewed
  * [x] Merged
* [x] [libp2p/go-libp2p-netutil](https://github.com/libp2p/go-libp2p-netutil)
  * [x] PR open - https://github.com/libp2p/go-libp2p-netutil/pull/19
  * [x] Reviewed
  * [x] Merged
* [x] [multiformats/go-multiaddr-net](https://github.com/multiformats/go-multiaddr-net)
  * [x] PR open - https://github.com/multiformats/go-multiaddr-net/pull/37
  * [x] Reviewed
  * [x] Merged
* [x] [libp2p/go-libp2p-net](https://github.com/libp2p/go-libp2p-net)
  * [x] PR open - https://github.com/libp2p/go-libp2p-net/pull/23
  * [x] Reviewed
  * [x] Merged
* [x] [libp2p/go-libp2p](https://github.com/libp2p/go-libp2p)
  * [x] PR open - https://github.com/libp2p/go-libp2p/pull/299
  * [x] Reviewed - @whyrusleeping (although this could use another review)
  * [x] Merged
* [x] [libp2p/go-libp2p-transport](https://github.com/libp2p/go-libp2p-transport)
  * [x] PR open - https://github.com/libp2p/go-libp2p-transport/pull/29
  * [x] Reviewed
  * [x] Merged
* [x] [libp2p/go-floodsub](https://github.com/libp2p/go-floodsub) -- netutil changes
  * [x] PR open - https://github.com/libp2p/go-floodsub/pull/73
  * [x] Reviewed
  * [x] Merged
* [x] [libp2p/go-addr-util](https://github.com/libp2p/go-addr-util) -- Remove AddrUsable (the swarm should be responsible for this...)
  * [x] PR open - https://github.com/libp2p/go-addr-util/pull/11
  * [x] Reviewed - @whyrusleeping
  * [x] Merged
* [x] [libp2p/go-libp2p-secio](https://github.com/libp2p/go-libp2p-secio)
  * [x] PR open - https://github.com/libp2p/go-libp2p-secio/pull/28
  * [x] Reviewed - @Kubuxu
  * [x] Merged
* [x] [libp2p/go-libp2p-interface-pnet](https://github.com/libp2p/go-libp2p-interface-pnet)
  * [x] PR open - https://github.com/libp2p/go-libp2p-interface-pnet/pull/9
  * [x] Reviewed - @Kubuxu, @whyrusleeping 
  * [x] Merged
* [x] [libp2p/go-tcp-transport](https://github.com/libp2p/go-tcp-transport)
  * [x] PR open - https://github.com/libp2p/go-tcp-transport/pull/23
  * [x] Reviewed
  * [x] Merged
* [x] [libp2p/go-libp2p-pnet](https://github.com/libp2p/go-libp2p-pnet)
  * [x] PR open - https://github.com/libp2p/go-libp2p-pnet/pull/19
  * [x] Reviewed - @whyrusleeping, @Kubuxu
  * [x] Merged

Branch `master` in the new repos:

* [libp2p/go-conn-security-multistream](https://github.com/libp2p/go-conn-security-multistream): multistream security multiplexer
  * [x] Reviewed - @whyrusleeping 
* [libp2p/go-conn-security](https://github.com/libp2p/go-stream-security): stream security interfaces
  * [x] Reviewed - @whyrusleeping 
* [libp2p/go-reuseport-transport](https://github.com/libp2p/go-reuseport-transport): base transport for all TCP reuseport transports
  * [x] Reviewed - @whurusleeping (done), @Kubuxu
* [libp2p/go-libp2p-transport-upgrader](https://github.com/libp2p/go-libp2p-transport-upgrader): stream transport to full libp2p transport upgrader
  * [x] Reviewed  - @whyrusleeping 

Deprecated packages:

* [libp2p/go-libp2p-interface-conn](https://github.com/libp2p/go-libp2p-interface-conn): will merge what is left with go-libp2p-net, the distinction between this package, go-libp2p-net, and go-libp2p-transport always confused me anyways so I'm glad to see one of them go.
* [libp2p/go-libp2p-conn](https://github.com/libp2p/go-libp2p-conn): mostly replaced by go-stream-transport
* [libp2p/go-peerstream](https://github.com/libp2p/go-peerstream): merged into swarm

Known Issues:

* Simultaneous dial problems are worse. This is caused by a combination of reuseport and TCP simultaneous open. The fact that it has gotten *worse* probably stems from a timing issue (lots of code cleanup so timing is probably more predictable).
* We no longer treat half-closed streams as fully closed for the purposes of tracking them in the swarm. This means users *must* listen for the EOF on a stream after calling close. I've added two new functions to go-libp2p-net to help with this (FullClose and AwaitEOF).

**Comment by Stebalien** [comment]
Done!

**Comment by dignifiedquire** [comment]
🎉 congrats @Stebalien for slaying another 🐉

**Comment by lgierth** [comment]
All hail @Stebalien <3

**Comment by dirkmc** [comment]
Amazing 🎉
