### ISSUE TITLE
pnet: misleading error `errShortNonce` during ECONNRESET on Read

### ISSUE THREAD

**Issue by davidhadas** [libp2p/go-libp2p#2970]
While using a PrivareNetwork (psk) between peers, a general errShortNonce error is returned:
`failed to negotiate security protocol: privnet: could not read full nonce`
The actual reason for the failure is obscured. 

For example, when the connection was reset (probably by the peer) .
 
As a minimum the original error (ECONNRESET in this case) should be wrapped as part of the retuned error.

**Comment by sukunrt** [comment]
>As a minimum the original error (ECONNRESET in this case) should be wrapped as part of the retuned error.

That makes sense. Want to open a PR?
