### ISSUE TITLE
`BasicHost` submits `EvtLocalAddressesUpdated`  but addresses were not changed

### ISSUE THREAD

**Issue by Wondertan** [libp2p/go-libp2p#2972]
### Context
I am running a test network in the k8s cluster, and while debugging an orthogonal issue, I observed unexpected behavior.

### Bug (?)
To my knowledge, the addresses of running pods do not change. Also, the logs below show that the addresses on every event are constant, however  `BasicHost` still submits the  `EvtLocalAddressesUpdated` .

### Trace
The trace was from PubSub node spamming `go-libp2p-pubsub@v0.12.0/pubsub.go:698 already have connection to peer`, triggered by `EvtPeerIdentificationCompleted`, initiated by identify push from a peer, prompted by `BasicHost` background loop on the peer detecting address changes. 

However, as per identify logs on the PubSub node, the addresses didn't change, and the exact same log with the same address repeats over and over, potentially suggesting that diffing logic in [makeUpdatedAddrsEvent](https://github.com/libp2p/go-libp2p/blob/9038a72c4863778e6a26814aab201cee6d93d640/p2p/host/basic/basic_host.go#L498) has a bug.
> DEBUG	net/identify	identify/id.go:832 received listen addrs for 12D3KooWQHiNsPQoiRMnixa1SzEMUukJo3r1UQ7tZaxH8kjMSm7L: [/ip4/151.115.12.199/udp/2121/quic-v1 /ip4/151.115.12.199/tcp/2121 /ip4/100.64.42.71/tcp/2121 /ip4/100.64.42.71/udp/2121/quic-v1 /ip4/100.64.42.71/udp/2121/quic-v1/webtransport/certhash/uEiCRTETNTiCP0LDvirFICa3zihf3qB14vOa6F7N-GoFntQ/certhash/uEiAr9jX-WLX19pVfR5MY1vL2y_ytxxcRQNPtCfE6oVlH_Q /ip4/100.64.42.71/udp/2121/quic-v1/webtransport/certhash/uEiCRTETNTiCP0LDvirFICa3zihf3qB14vOa6F7N-GoFntQ/certhash/uEiAr9jX-WLX19pVfR5MY1vL2y_ytxxcRQNPtCfE6oVlH_Q]

I couldn't find a way to inspect the state of the peer submitting the identify push with logs, and the only data point is the log from the peer above.

**Comment by sukunrt** [comment]
I'm unable to reproduce this. Is it possible that the id pushes were triggered by Local Protocols Updated event?

**Comment by Wondertan** [comment]
Hello @sukunrt! That would suggest we have a constant loop that registers and unregisters some protocol(s), which might be a bug on our side. From the top of your head, do you know how to check this?

**Comment by Wondertan** [comment]
Ok, metrics should help here
