### ISSUE TITLE
Issue build android version

### ISSUE THREAD

**Issue by Ja7ad** [libp2p/go-libp2p#2997]
When build android version got error undefined for package `anet`.

```shell
# command-line-arguments
./main.go:10:17: undefined: anet.Interfaces
```

This package used by:

```
github.com/pion/webrtc/v3 v3.3.0
github.com/pion/transport
```

Currenly in `github.com/pion/webrtc/v3 v3.3.4` this issue has been fixed.

- https://github.com/wlynxg/anet/issues/7
- https://github.com/pion/webrtc/blob/dc1f8ffd1c1b5c6cb21ea2a57230f1f38a975d4c/go.mod#L18

<details>
<summary>Version Information</summary>
<pre>
v0.36.5
</pre>
</details>

**Comment by MarcoPolo** [comment]
Could you please submit a patch that updates the needed dependencies and make sure it works? Thanks!
