### ISSUE TITLE
Allow users to create a New mDNS Discovery service with context as an argument to make it cancellable

### ISSUE THREAD

**Issue by phillipahereza** [libp2p/go-libp2p#3073]
Currently, the [NewMdnsService](https://github.com/libp2p/go-libp2p/blob/8423de3a64f17f6bec18bf57b472e5a3615883db/p2p/discovery/mdns/mdns.go#L53C6-L53C20) function creates a new context, meaning it cannot be cancelled from the calling function.

To maintain compatibility, I suggest adding a new function, `NewMdnsServiceWithContext(ctx context.Context, host host.Host, serviceName string, notifee Notifee)`, that accepts a context as an argument.

**Comment by MOHANKUMAR-IT** [comment]
This will be useful , as currently there is no cancel option

**Comment by sukunrt** [comment]
You can use the `Close` method to close the service. Explained here too: https://github.com/libp2p/go-libp2p/pull/3089#issuecomment-2522799377
