### ISSUE TITLE
Received a `stateless reset with token ...` appears during stream usage

### ISSUE THREAD

**Issue by wlynxg** [libp2p/go-libp2p#3077]
<details>
<summary>Version Information</summary>
<pre>
github.com/libp2p/go-libp2p v0.36.2
</pre>
</details>
When I use libp2p to open a stream to transfer data, I occasionally get the error 

```bash
received a stateless reset with token 355abd61fe97299be595e62a4b052db6
````

This error does not appear when the stream is opened, but during the use of the stream.

It often occurs when I frequently restart the same libp2p node. 

I would like to know what caused this error

**Comment by marten-seemann** [comment]
This might be helpful: https://quic-go.net/docs/quic/transport/#stateless-reset

**Comment by wlynxg** [comment]
Thank you very much for your help.

I read the document you mentioned and the description of Stateless Reset in the associated RFC9000 10.3.
I have a few questions after reading them and I hope you can help me answer them.

1. In my understanding, Stateless Reset is a means for the server to quickly terminate old connections. But why do I also receive a Stateless Reset packet when my libp2p instance is restarted?
2. I looked at libp2p's use of the QUIC protocol, and I found that for TLS, libp2p seems to generate it from the peer ID?
3. Is it because of this special processing that the QUIC connection of the restarted libp2p is considered an old connection, so it receives a Stateless Reset packet?

**Comment by wlynxg** [comment]
Thanks again for your help, my problem has been solved.
