### ISSUE TITLE
Which Ports Need to Be Opened for libp2p in a Mandatory Firewall?

### ISSUE THREAD

**Issue by Ja7ad** [libp2p/go-libp2p#3097]
I noticed that `go-libp2p` uses different ports to connect to other nodes.

```
 1330298            root  652u  IPv4 266053404      0t0  TCP 23.109.234.125:21888->142.61.131.16:21888 (ESTABLISHED)
 1330298            root  653u  IPv4 266053839      0t0  TCP 23.109.234.125:21888->111.76.109.19:21888 (ESTABLISHED)
 1330298            root  654u  IPv4 266053347      0t0  TCP 23.109.234.125:21888->122.90.163.168:21888 (ESTABLISHED)
 1330298            root  656u  IPv4 266045717      0t0  TCP 23.109.234.125:44826->33.27.37.129:21888 (ESTABLISHED)
 1330298            root  657u  IPv4 266056787      0t0  TCP 23.109.234.125:21888->62.115.26.183:21888 (ESTABLISHED)
```

**Port in question:** 44826

What is the purpose of this port? Additionally, which ports do I need to open on the firewall to ensure proper reachability for `go-libp2p`?

**Comment by p-shahi** [comment]
I believe 44826 is an ephemeral outbound port that was dynamically assigned by the OS.
If you enable [hole punching](https://docs.libp2p.io/concepts/nat/hole-punching/) you'll be able to ensure proper reachability for your node behind a NAT/firewall
