### ISSUE TITLE
make deps doesn't work

### ISSUE THREAD

**Issue by moqiang02** [libp2p/go-libp2p#310]
When I run `make deps`, I get an error:
dial tcp 31.13.72.54:443: getsockopt: connection timed out

computer environments:
```
ubuntu 16.04.4
Go version: go1.9.2 linux/amd64
```
I'm sure I can access such domains as ipfs.io/golang.org
![2018-04-12 22-05-06](https://user-images.githubusercontent.com/8550791/38683381-e57415dc-3e9f-11e8-82bc-b717a3aeee15.png)

**Comment by Stebalien** [comment]
You're DNS is being hijacked somewhere along the way. 31.13.72.54 is a Facebook IP address. Do you have any proxies configured in your browser to allow you to connect to ipfs.io? Try running:

```go
> ping ipfs.io
```

What IP address do you see?

**Comment by moqiang02** [comment]
I used the shadowsocks+Privoxy agent and I was hijacked by DNS. When I ping ipfs.io on the local server, the ip shows 199.59.150.11. When I use a U.S. server ping, the displayed ip is 217.182.195.23. This is a problem with China Great Firewall. Thank you!

**Comment by Stebalien** [comment]
See https://github.com/whyrusleeping/gx/issues/91.
