### ISSUE TITLE
Remove init functions

### ISSUE THREAD

**Issue by Ja7ad** [libp2p/go-libp2p#3123]
Hello,

There are multiple `init` functions in this package. You can find a list of them [here](https://github.com/search?q=repo%3Alibp2p%2Fgo-libp2p%20func%20init()&type=code).

Using `init` functions in a public package is considered bad practice. For example, see this explanation [here](https://www.bytesizego.com/blog/init-function-golang). `init` functions can introduce hidden behavior that is difficult for applications to detect.

We suggest enhancing the package by cleaning up the `init` functions and adopting best practices to improve security.

**Comment by b00f** [comment]
It particularly raises security concerns for applications, as there might be some initialization occurring without the application's awareness.

**Comment by Ja7ad** [comment]
cc https://github.com/libp2p/go-libp2p-kad-dht/issues/1008

**Comment by vyzo** [comment]
no sorry, this is fear mongering.

Modules need to initialize somehow.
