### ISSUE TITLE
Bootsrapper Nodes

### ISSUE THREAD

**Issue by agahEbrahimi** [libp2p/go-libp2p#315]
Hi, 

Do all bootstrapping nodes hold a DHT for the multiaddress of all other nodes?

Thank you

**Comment by Stebalien** [comment]
Sorry, could you expand on that question a bit?

**Comment by agahEbrahimi** [comment]
Do all of the nodes that are bootrstrapper nodes hold the kad-dht table which holds the multiadress of all other nodes that have previously connected to the network?

**Comment by Stebalien** [comment]
@agahEbrahimi ah. No, they don't. They hold some but not all. The trick is, you connect to a bootstrapper node, learn a few new addresses, connect to those, learn some more, etc. We do this by searching for a non-existent peer in the DHT. While we'll never find the peer we're looking for, we *will* end up connecting to a bunch of random nodes participating in the DHT.

**Comment by agahEbrahimi** [comment]
And after finding all those addresses you can use Nat Traversal, and content routing in order to find a specific file and who holds that file?

**Comment by Stebalien** [comment]
> And after finding all those addresses you can use Nat Traversal, and content routing in order to find a specific file and who holds that file?

*Some* NAT traversal methods, yes (NAT traversal is a category).
