### ISSUE TITLE
Is Relay(circuit) transparent to application?

### ISSUE THREAD

**Issue by anticpp** [libp2p/go-libp2p#316]
I have read the [Relay specs](https://github.com/libp2p/specs/blob/master/3-requirements.md#32-relay), also test codes as [relay_test.go](https://github.com/libp2p/go-libp2p-circuit/blob/master/relay_test.go).

It seems that using the Relay way is not `transparent` to my codes? 

Which means I have to write codes:

1. Try using a direct way
2. If 1) fail, try using relay way

Like: 
```
s, err := host.NewStream(context.Background(), peerID, "/echo/1.0.0")
if err!=nil {
    r := NewRelay(context.Background(), host)
    r.DialPeer(rctx, rinfo, dinfo)
    ....
}

```

If this is true, I think this is a little complex to application codes, or something I have mis-understand?

**Comment by vyzo** [comment]
Relay, once configured in libp2p, is transparent in the sense that it automatically connects to relay addresses.

**Comment by whyrusleeping** [comment]
@anticpp the relay is transparent. It is embedded inside the host as a transport, so if you try to dial a relay address, you will automatically use the relay.

However, it is not yet automatic. You need to explicitly specify a relay address for the peer you wish to relay a connection to

**Comment by Stebalien** [comment]
AutoRelay has been created (although it doesn't always work all that well at the moment). #1039 replaces this.
