### ISSUE TITLE
mocknet flaky under stress

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#32]
I beleive there is a bug in the mocknet hosts somewhere. When putting it under stress i get strange failures (messages appear to go places they arent wanted). Switching to using testnet tcp backed hosts fixes the problems.

**Comment by anacrolix** [comment]
Are there unit tests or CIs that you can refer to us?

**Comment by Stebalien** [comment]
Hm. We should probably just close this. We've fixed a bunch of connectivity, race, etc. issues since this was filed.
