### ISSUE TITLE
dep vendoring

### ISSUE THREAD

**Issue by iNDicat0r** [libp2p/go-libp2p#321]
`dep init -gopath` doesn't vendor the packages, is there any alternative ?

**Comment by upperwal** [comment]
libp2p uses [gx](https://github.com/whyrusleeping/gx-go)
try
```
make
make dep
```

**Comment by iNDicat0r** [comment]
Hi @upperwal 
I mean after `make deps` with gx, to vendor using `dep` .

**Comment by Stebalien** [comment]
We don't currently support `dep`. We're looking into getting `gx` working with `dep` but, for now, you can use something like https://github.com/karalabe/ungx.

**Comment by iNDicat0r** [comment]
@Stebalien thanks
