### ISSUE TITLE
libp2p.NoSecurity in echo example refactoring

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/go-libp2p#327]
https://github.com/libp2p/go-libp2p/blob/cfe6ab54b7587d0279689b80a589674fdfde8ea5/examples/echo/main.go#L52

@Stebalien What's `libp2p.NoSecurity` on line 52?  I can't find the string "NoSecurity" defined anywhere in the libp2p org ([this search](https://github.com/search/advanced?q=org%3Alibp2p+NoSecurity)).  Is it just a constant intended to mean something like nil or zero?

**Comment by Stebalien** [comment]
@mgoelzer that's an option only available in the refactor branch. It's defined here:

https://github.com/libp2p/go-libp2p/blob/cfe6ab54b7587d0279689b80a589674fdfde8ea5/options.go#L74-L82

**Comment by mgoelzer** [comment]
@Stebalien Thank you!  I feel dumb now :-)

Code works great and playing with it has been educational, so thank you.
