### ISSUE TITLE
Host example README out of sync with code

### ISSUE THREAD

**Issue by galgalesh** [libp2p/go-libp2p#333]
The [host example](https://github.com/libp2p/go-libp2p/tree/master/examples/libp2p-host) readme seems to be out of date. The code was changed later, but the readme wasn't updated.

**Comment by whyrusleeping** [comment]
@galgalesh Ah, thanks! We will try and get it fixed asap

**Comment by zaibon** [comment]
I was looking for me first contribution to the project, seems like a good place to start. So I edited the readme of the example with the new code: https://github.com/libp2p/go-libp2p/pull/348

**Comment by whyrusleeping** [comment]
Thanks a bunch @zaibon :) Always great to have more contributors! Adding a link to the options for further reading sounds good to me, I already merged your first PR, so go ahead and send another one

**Comment by zaibon** [comment]
There you go: https://github.com/libp2p/go-libp2p/pull/349

**Comment by bigs** [comment]
@zaibon Set, thanks!
