### ISSUE TITLE
very large number of "protocol mux failed: connection reset" errors

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#339]
I'm playing around with debugging connectivity issues, and i'm seeing a lot of these errors coming out of basichost. It could be normal, but it definitely seems a bit odd. I'm opening this issue to track finding the cause and determining whether or not this is a deeper issue.

**Comment by whyrusleeping** [comment]
cc @bigs @Stebalien

**Comment by Stebalien** [comment]
Could be TCP port scans (if this is happening when negotiating secio).

**Comment by Stebalien** [comment]
That is:

1. Someone opens a TCP connection to us (e.g., to see if we're an IPFS node, or just to do a port scan).
2. They immediately close it.
3. We try to negotiate secio.
4. That obviously fails because the connection has been reset.

---

Alternatively, this could be evil ISPs resetting our connections when we open too many (Comcast did this for a while in an attempt to break bittorrent).

**Comment by whyrusleeping** [comment]
@Stebalien but i'm seeing these without a listener. I'm only dialing outwards.

**Comment by whyrusleeping** [comment]
also see notes on: https://github.com/libp2p/go-libp2p-kad-dht/issues/139#issuecomment-394254310

**Comment by whyrusleeping** [comment]
"connection reset" is coming from yamux. It really means that the stream was reset, not the connection. Thanks yamux.

**Comment by Stebalien** [comment]
Where does the "protocol mux failed" come from?

**Comment by Stebalien** [comment]
Ah... Lazy negotiation.

**Comment by Stebalien** [comment]
Ah, no, I know *exactly* where this is coming from. A peer is trying to connect via a protocol you don't speak (probably bitswap). After you refuse to speak any of the requested protocols, the peer (correctly) hangs up with a reset. We should ignore these.

**Comment by Stebalien** [comment]
Actually, should we be nice on encountering an unsupported protocol? We *could* nicely close the connection but that takes more time.

**Comment by whyrusleeping** [comment]
No, we can't do that. I think we previously had a bug caused by that, where we would open a stream and start writing to it, and since the other side didnt support the protocol and only *closed* it, we never found out, and just kept writing into the void.

**Comment by whyrusleeping** [comment]
Overall, I think this error i'm seeing here isnt really a problem. Just took a little while to figure out what it actually meant

**Comment by Stebalien** [comment]
I'm going to at least improve the error message.

**Comment by whyrusleeping** [comment]
do it. You can change the world.
