### ISSUE TITLE
[Feature Request] Common Stream handler for dialler and listener

### ISSUE THREAD

**Issue by upperwal** [libp2p/go-libp2p#340]
**What happens right now:** If peer ```A``` and ```B``` executes ```SetStreamHandler(f)``` and then ```A``` executes ```NewStream(B)```. ```A``` gets ```inet.Stream``` object whereas ```B``` could use the stream from ```f(stream)``` function. Although ```A``` and ```B``` set the stream handler to ```f``` it is only invoked for ```B```. 

It would be good to have a common stream handler function for both dialler and listener. This would give consistency while writing code for both the node.

We can create a public endpoint for ```findHandler``` function and add
```go
hf := h.Mux().FindHandler(selected)

if hf != nil {
  go hf.Handle(selected, s)
}
``` 
just before retuning from the ```NewStream``` function.

```NewStream``` still returns ```inet.Stream``` and if someone is using it the code won't break.

@Stebalien @whyrusleeping let me know what you think. I would be happy to open a PR and do any tests to see if this breaks something.

**Comment by whyrusleeping** [comment]
@upperwal what is your usecase here? If i'm understanding you right, then this becomes really difficult to actually use. 

Say I want to open a stream to you and send you a message. So i create the message, then call `NewStream(You)`. Now, somewhere, the `StreamHandler` with my stream to you gets called in my code. I have to somehow get the message I was going to send to you into that handler, which seems like it would add a lot of extra cruft to the operation.

**Comment by upperwal** [comment]
@whyrusleeping My use case would be to develop a package using which user's can easy spawn a new node with custom protocols.

Something like this: https://github.com/upperwal/go-libp2p-protocol/blob/master/example/ping.go
This code implements ping protocol on top of libp2p (different from p2p/protocol/ping).

It gives you an interface like
```go
// Create a new libp2p host
host, err := libp2p.New(context.Background(), libp2p.Defaults)
if(err != nil) {
	panic(err)
}

proto := protocol.Protocol {
  Name: "name_your_protocol",
  Version: 1,
  Run: func(stream net.Stream, init bool) {
    // use init to differentiate between dialler and listener peer. 
    // init == true (peer who called AddPeer)

    fmt.Println("Stream opened to ", stream.Conn().RemotePeer())
  },
}

// This function will return you an extended host.
// It contains the host (xHost.Host) and a slice of protocols (xHost.Protocol)
xHost := protocol.SetProtocol(host, []protocol.Protocol{proto})

// Now you can add a peer.
// It will add the peer to the peerstore and open a stream.
// Protocol.Run function will will be invoked for both the peers.
xHost.AddPeerWithAddr("/ip4/127.0.0.1/tcp/51912/ipfs/QmbHvB9A2vLMno9LWkWnwnRHa5Fcjnogsq8nzgiooKfJTM")
// or
xHost.AddPeer(pi peerstore.PeerInfo)
```

```init``` is used to differentiate dialler and listener or who initialised the connection. Could help in #345

**Comment by upperwal** [comment]
Currently I am hacking it by passing ```true``` after call to ```NewStream```

```go
s, err := eh.Host.NewStream(context.Background(), info.ID, pid)
go func(stream net.Stream) {
	pr.Run(stream, true)
}(s)
```

and ```false``` if the stream handler is invoked. 
```go
host.SetStreamHandler(pid, func(stream net.Stream) {
	pr.Run(stream, false)
})
```

**Comment by whyrusleeping** [comment]
@upperwal but i'm still not getting the practical usecase. Whatever code goes in the run function there will always have an:
```
if init {
  // do these things
} else {
  // do this other set of things
}
```

I don't think it makes sense to try and mash them together like this.

If you want to make a nice protocol abstraction interface like that, I'd say have two 'Run' functions, separating out the initiator handler and the receiver handler.

**Comment by upperwal** [comment]
@whyrusleeping true, ```if``` and ```else``` would be required if the code/logic diverges but if its common then it would be easy. No issues, I can work with the current implementation by creating a wrapper around it. Thanks. :relaxed:
