### ISSUE TITLE
Yamux -race issues -> Update yamux from upstream

### ISSUE THREAD

**Issue by hsanjuan** [libp2p/go-libp2p#341]
There is a race issue that was fixed upstream in hashicorp/yamux/master, which we fork in https://github.com/whyrusleeping/yamux

Just tracking this here.

**Comment by Stebalien** [comment]
@hsanjuan I've bubbled yamux 1.0.7 to go-ipfs. Has this been fixed?

**Comment by hsanjuan** [comment]
ah yes, i bubbled it in the end..
