### ISSUE TITLE
add information to connections about origin

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#345]
Given a connection, i should be able to tell if it was an incoming or an outgoing connection.

**Comment by whyrusleeping** [comment]
also, while we're at it, having this info on streams would be pretty useful too.

**Comment by bigs** [comment]
Perhaps we add `Dialer()` to the `Conn` interface? Tempting to encode as a boolean, but probably more semantically meaningful to use an enum (`LOCAL`, `REMOTE`) or simply return a peer `ID`.

**Comment by Stebalien** [comment]
I'm also tempted to add a more general purpose "Stat" method returning some kind of:

```go
type Direction int
const (
    DirUnknown Direction = iota 
    DirInbound
    DirOutbound
)
type Stat struct {
    Direction Direction
    ...
    ...
    Extra map[interface{}]interface{} // to be filled in by the transport.
}
```

That way, we don't have to keep adding methods.

**Comment by bigs** [comment]
Yeah, I really like that @Stebalien 👍

**Comment by upperwal** [comment]
Initiating a connection and a stream are two different things, right?

**Comment by Stebalien** [comment]
Yes. However, both streams and connections *have* initiators.

**Comment by upperwal** [comment]
So having direction stats in both connections and streams would be useful.
