### ISSUE TITLE
Shared-memory Transport

### ISSUE THREAD

**Issue by paralin** [libp2p/go-libp2p#350]
I'm thinking about implementing a transport that uses shared memory and a CAS lock-less queue to do IPC. Or maybe used named pipes.

Is anyone aware of any same-machine transport work done on libp2p?

**Comment by marten-seemann** [comment]
New transports can be added by implementing the [transport interface](https://github.com/libp2p/go-libp2p-core/blob/2711d5a459ca8b33d027de90fbda21fe82d464c7/transport/transport.go#L47-L88).

**Comment by paralin** [comment]
@marten-seemann this issue was from 2018, 3 years ago

the question was specifically about shared-memory transport implementations :)
