### ISSUE TITLE
RoutedHost should search for addrs when none of the addrs we tried worked

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#351]
Currently, if we have at least one address, we try that and never search the DHT. We should search the DHT. Ideally, we'd search in parallel after some timeout but that's tricky. The simple solution is to:

1. Try dialing with the addresses we have.
2. If that fails, get some more addresses.
3. If we now have *new* addresses, try dialing with those.

**Comment by jmintb** [comment]
I would like to have a crack at this task. I think it makes sense to also add tests that cover this case, there is no test file in the go-libp2p/p2p/host/routed folder. Should I put one there or is there somewhere else that the routed host is tested?

**Comment by Stebalien** [comment]
> Should I put one there or is there somewhere else that the routed host is tested?

That's the correct place to test this (for now).

Note: The *real* fix will probably require some refactoring. I'm steadily coming to the conclusion that we should be passing a pluggable router down into the Network (swarm). Really, we should probably be wrapping the peerstore with a router.

However, that's not a simple fix...

**Comment by raulk** [comment]
With the new dial pipeline being worked on here https://github.com/libp2p/go-libp2p-swarm/pull/88, a `RoutedHost` could use a Dial `Planner` that falls back to a DHT lookup when all addresses failed. It would be trivial to implement, I think.

**Comment by marten-seemann** [comment]
This was fixed by https://github.com/libp2p/go-libp2p/pull/1835.
