### ISSUE TITLE
How to use udp instead of tcp in multiaddress

### ISSUE THREAD

**Issue by jimmy9065** [libp2p/go-libp2p#353]
I'm studying this example and try to make it fit my own project.
In my project, there are several NAT devices between the proxy server and the proxy client. So I need to do a NAT traverse to make them connected.
I choose to use the  UDP punching hole to do the NAT traverse. Thus I need to set udp instead tcp in the multiaddress like this:
Changed:

> libp2p.ListenAddrStrings(fmt.Sprintf("/ip4/127.0.0.1/tcp/%d", port)))

To:

> libp2p.ListenAddrStrings(fmt.Sprintf("/ip4/127.0.0.1/udp/%d", port)))

However, After I run the program, I get error like this:

> failed to listen on any addresses: [no transport for protocol]

So I just want to if I did something wrong here or udp is just not supported by the library right now for transport protocol?

Thank you. Hope I make myself clear on this.

**Comment by Stebalien** [comment]
We do not currently have any UDP based transports. We are working on adding QUIC support but QUIC multiaddrs will have the form `/ip4/127.0.0.1/udp/PORT/quic`.

FYI, we *do* have several NAT traversal mechanisms and are working on more.

1. To work around full-cone NATs, we reuse the source port for all TCP connections and, when we establish a connection to some endpoint, we ask the endpoint for the ip/port *they* observe us using. We then tell the network to connect to us at this address.
2. For NATs that support UPnP or NATPMP, we have a go-libp2p-nat package that handles port mapping.
3. We have a relay transport (go-libp2p-circuit). However, while you can always manually *dial* through a relay to another node, we don't currently have any support for automatically picking a good relay (so we won't do this automatically).

**Comment by raulk** [comment]
I'm lacking the history context here, but adding raw UDP support (no QUIC) would involve creating a "glue" `UDPTransport` similar to [go-tcp-transport](https://github.com/libp2p/go-tcp-transport/) that bridges the `Transport` interface with [go-multiaddr-net](https://github.com/multiformats/go-multiaddr-net)?

@Stebalien would love your 2 cents here.

**Comment by Stebalien** [comment]
So, there are two parts to this:

1. Packet protocols. We currently don't have any packet protocol support but we'd like them. To do that, we'd need some way to define packet transports. IIRC, @lgierth was working on this for a bit but he's taking the quarter off.
2. Streaming over UDP. That is, we'd start with a UDP connection, and then keep upgrading (using multistream) until we get a fully featured connection.

However, we still have to think carefully about the abstractions involved.

**Comment by raulk** [comment]
@Stebalien thanks for the clarification! 👍 

Regarding (1), I found the [multigram](https://github.com/multiformats/multigram/tree/draft1) proposal which is intended as the multistream counterpart for datagram sockets.

About (2), I'm not sure I follow. Wouldn't multistream negotiations and SecIO behave well on top of a message-oriented transport? After all they use varint-delimited writes. If the application guarantees that all its messages are below 64kb in length (after encapsulating in multiplexer, etc.), wouldn't we be able to use datagrams straightaway? (leaving aside the fact that the _stream_ nomenclature might be a misnomer)

^^ that is assuming that `UDPConn.Write()` ends up creating a message and calling `sendmsg()` for us.

**Comment by bkolad** [comment]
@raulk - yes we can check out QUICK, thx for the suggestion.

**Comment by marten-seemann** [comment]
> The minimum MTU is actually quite a bit smaller than 64Kib (really, you can only expect ~1KiB`).

Google performed some measurements for this, and they concluded that 1370 bytes is safe for IPv4 UDP packets (which is the value Chrome now uses for QUIC packets).

> The main benefits over QUIC are:
> 1. We can fire and forget (no state).
> 1. We don't have to establish a session first.

There's currently a QUIC extension being defined that allows unreliable messages. We'd still have to do the handshake (we need that if we want to encrypt stuff anyway, unless we want to do some asymmetric crypto).

**Comment by bkolad** [comment]
@raulk & @Stebalien 
tried to use quic but now experiencing 
https://github.com/libp2p/go-libp2p-quic-transport/issues/33 

we are using "go get", any plans to  fix go-libp2p-quic-transport with go-get?

**Comment by marten-seemann** [comment]
This is unfortunately due to the fact that the QUIC protocol is not stable yet, and quic-go therefore doesn’t expose any stable QUIC version numbers. Please see https://github.com/lucas-clemente/quic-go for more details.
Every now and then, we publish a new release of quic-go, with a dedicated version number. However, this version number is only supported by this one release commit.

Once the QUIC protocol (and the implementation) become stable, it will be possible to install and use via go get.

**Comment by Stebalien** [comment]
> There's currently a QUIC extension being defined that allows unreliable messages. 

This would be so awesome...

> This is unfortunately due to the fact that the QUIC protocol is not stable yet, and quic-go therefore doesn’t expose any stable QUIC version numbers.

What if we used a *fork* of quic-go for now, or something like that. It would be really nice to be able to use the QUIC transport without gx.

**Comment by marten-seemann** [comment]
> > This is unfortunately due to the fact that the QUIC protocol is not stable yet, and quic-go therefore doesn’t expose any stable QUIC version numbers.
>
> What if we used a fork of quic-go for now, or something like that. It would be really nice to be able to use the QUIC transport without gx.

We can use plain old dependency vendoring here. I opened https://github.com/libp2p/go-libp2p-quic-transport/issues/41.

**Comment by Stebalien** [comment]
(closing because this is more of a discussion and isn't worth tracking)
