### ISSUE TITLE
make deps doesn't work

### ISSUE THREAD

**Issue by Arbusz** [libp2p/go-libp2p#354]
what's wrong with this?
---
go get github.com/whyrusleeping/gx
go get github.com/whyrusleeping/gx-go
gx --verbose install --global
make: gx: Command not found
Makefile:10: recipe for target 'deps' failed
make: *** [deps] Error 127
---
my env is under here
---
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/arbus/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build410778714=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"

**Comment by Stebalien** [comment]
It expects `$GOPATH/bin/` to be in your `$PATH`.

**Comment by Arbusz** [comment]
It did work. Thank you.

**Comment by hktalent** [comment]
vi ~/.bashrc
and to end
```
OLD_GO_PATH=/root/go
OLD_GO_BIN="$OLD_GO_BIN/bin"
export GOPATH="$OLD_GO_PATH"
export GOBIN="$OLD_GO_BIN"
export PATH=$PATH:$GOBIN
```
source ~/.bashrc

so is ok
@Arbusz @Stebalien 
#402

**Comment by Stebalien** [comment]
@hktalent please file a new issue with the exact error you're seeing.
