### ISSUE TITLE
go get github.com/whyrusleeping/gx error

### ISSUE THREAD

**Issue by Holt666** [libp2p/go-libp2p#355]
Install
> go get -d github.com/libp2p/go-libp2p/...
> cd $GOPATH/src/github.com/libp2p/go-libp2p
> make

in this case, make do not work, my golang use brew install and version is (go version go1.10.3 darwin/amd64)
reymondtudeMacBook-Pro:go-libp2p reymondtu$ make
go get github.com/whyrusleeping/gx
package golang.org/x/crypto/blake2s: unrecognized import path "golang.org/x/crypto/blake2s" (https fetch: Get https://golang.org/x/crypto/blake2s?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/crypto/sha3: unrecognized import path "golang.org/x/crypto/sha3" (https fetch: Get https://golang.org/x/crypto/sha3?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
make: *** [gx] Error 1

**Comment by reymondtu** [comment]
I think this is china GFW problem，but after use https_proxy , other problem:

reymondtudeMacBook-Pro:go-libp2p reymondtu$ make
go get github.com/whyrusleeping/gx
go tool asm: exit status 2
flag provided but not defined: -V
usage: asm [options] file.s
Flags:
  -D value
    	predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
    	include directory; can be set multiple times
  -S	print assembly and machine code
  -debug
    	dump instructions as they are parsed
  -dynlink
    	support references to Go symbols defined in other shared libraries
  -e	no limit on number of errors reported
  -o string
    	output file; default foo.6 for /a/b/c/foo.s on amd64
  -shared
    	generate code that can be linked into a shared library
  -trimpath string
    	remove prefix from recorded source file paths
# internal/race
flag provided but not defined: -std
usage: compile [options] file.go...
  -%	debug non-static initializers
  -+	compiling runtime
  -A	for bootstrapping, allow 'any' type
  -B	disable bounds checking
  -D path
    	set relative path for local imports
  -E	debug symbol export
  -I directory
    	add directory to import search path
  -K	debug missing line numbers
  -M	debug move generation
  -N	disable optimizations
  -P	debug peephole optimizer
  -R	debug register optimizer
  -S	print assembly listing
  -V	print compiler version
  -W	debug parse tree after type checking
  -asmhdr file
    	write assembly header to file
  -buildid id
    	record id as the build id in the export metadata
  -complete
    	compiling complete package (no C or assembly)
  -cpuprofile file
    	write cpu profile to file
  -d list
    	print debug information about items in list
  -dynlink
    	support references to Go symbols defined in other shared libraries
  -e	no limit on number of errors reported
  -f	debug stack frames
  -g	debug code generation
  -h	halt on error
  -i	debug line number stack
  -importmap definition
    	add definition of the form source=actual to import map
  -installsuffix suffix
    	set pkg directory suffix
  -j	debug runtime-initialized variables
  -l	disable inlining
  -largemodel
    	generate code that assumes a large memory model
  -linkobj file
    	write linker-specific object to file
  -live
    	debug liveness analysis
  -m	print optimization decisions
  -memprofile file
    	write memory profile to file
  -memprofilerate rate
    	set runtime.MemProfileRate to rate
  -msan
    	build code compatible with C/C++ memory sanitizer
  -newexport
    	use new export format (default true)
  -nolocalimports
    	reject local (relative) imports
  -o file
    	write output to file
  -p path
    	set expected package import path
  -pack
    	write package file instead of object file
  -r	debug generated wrappers
  -race
    	enable race detector
  -s	warn about composite literals that can be simplified
  -shared
    	generate code that can be linked into a shared library
  -ssa
    	use SSA backend to generate code (default true)
  -trimpath prefix
    	remove prefix from recorded source file paths
  -u	reject unsafe code
  -v	increase debug verbosity
  -w	debug type checking
  -wb
    	enable write barrier (default true)
  -x	debug lexer
make: *** [gx] Error 2

**Comment by Stebalien** [comment]
What version of go do you have?

**Comment by anazh** [comment]
me too , go version = go1.10.2 darwin/amd64

**Comment by Stebalien** [comment]
@anazh the first issue is the GFW. Are you experiencing the second issue as well (with go tool asm)?

**Comment by wanyvic** [comment]
you need to cross the GFW
