### ISSUE TITLE
ZeroPrefixLen(id []byte) will always return j * 8 + 7, j=non-zero-index-of-1(id)?

### ISSUE THREAD

**Issue by tracymacding** [libp2p/go-libp2p#361]
ZeroPrefixLen(id []byte) implemention:
```
func ZeroPrefixLen(id []byte) int {
    for i := 0; i < len(id); i++ {
	for j := 0; j < 8; j++ {
	    if (id[i]>>uint8(7-j))&0x1 != 0 {
	        return i*8 + j
	    }
	}
    }
    return len(id) * 8
}
```
if id is not all 0, the first '1' index in id is x, then the function always return x*8 + 7, does this make any help, why not return x directly ?

Function ZeroPrefixLen() is called by commonPrefixLen(a, b ID) which caculate distance between node a and b, it then make the distance as the bucket id of RoutingTable, according to ZeroPrefixLen, there are only 160 buckets (if node id is 160 bit), so too many nodes will be located to the same bucket, how to slove this problem?

**Comment by Stebalien** [comment]
> if id is not all 0, the first '1' index in id is x, then the function always return x*8 + 7, does this make any help, why not return x directly ?

It's actually counting the number of zero bits before the first 1 bit. `x` is the number of zero *bytes* before the first non-zero bytes. We then multiply `x` by `8` to get the number of zero *bits* and then add the number of zero bits before the first one bit in the first non-zero byte.

> so too many nodes will be located to the same bucket, how to slove this problem?

That's actually how Kademlia (the DHT we use) works. Half of the nodes on the network are in the first bucket, 1/4th are in the second bucket, 1/8th are in the third bucket, etc.

See: https://en.wikipedia.org/wiki/Kademlia

**Comment by tracymacding** [comment]
Yeah，I got it, thank you very much! @Stebalien
