### ISSUE TITLE
[question] are peer ids authenticated?

### ISSUE THREAD

**Issue by florianlenz** [libp2p/go-libp2p#362]
Hi,

I have a simple question. Are peers ids authenticated (AFAIK the peer id is the multihash of the public key - so by signing some data you can verify that the peer id is really the valid id of the peer)?

**Comment by Stebalien** [comment]
They are the hash of the peer's public key. What do you mean by "authenticated"? In general, if you want to check the identity of a peer you're talking to, you can just check `some_stream.Conn().RemotePeer()`. The peer address it returns has been authenticated.
