### ISSUE TITLE
Default listeners

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#377]
It would be nice to enable listening by default (i.e., fill in some reasonable listen addresses) as not doing this tends to confuse users. However, we'll want to make it easy to *turn this off*.

**Comment by upperwal** [comment]
@Stebalien I am on it.

Adding a new element in this array with a new default function
https://github.com/libp2p/go-libp2p/blob/9e5ef7a4e6ced5eb5eb9982b2a0541b331ba5387/defaults.go#L59-L83

```go
var DefaultListenAddrs = func(cfg *Config) error {
	defaultListenAddr, err := multiaddr.NewMultiaddr("/ip4/0.0.0.0/tcp/0")
	if err != nil {
		return err
	}
	return cfg.Apply(ListenAddrs(defaultListenAddr))
}
```

> However, we'll want to make it easy to turn this off.

What do you mean by this? If a user adds a new ListenAddr will it be appended to ```ListenAddrs  []ma.Multiaddr``` or the default will be overwritten?

**Comment by Stebalien** [comment]
I mean we need to make it easy to override the default. Putting it in the `deafults` variable with a correct "fallback" function will do the trick. However, we'll also have to think about what we want to do if the user manually specifies transports as we can't currently just "do the right thing" for random transports.

**Comment by upperwal** [comment]
Got it. For now I am adding ```/ip4/0.0.0.0/tcp/0``` as the default ListenAddrs.

**Comment by Stebalien** [comment]
Thanks @upperwal!
