### ISSUE TITLE
Extending chat example to support peer discovery

### ISSUE THREAD

**Issue by upperwal** [libp2p/go-libp2p#379]
@Stebalien @whyrusleeping 

As many people are confused of how chat example is p2p. I wanted to extend it by including peer discovery using kad-dht as shown in bootstrapping example by @whyrusleeping. I have the code ready but it depends on ```go-libp2p-kad-dht``` module and as @Stebalien specified, we have a circular dependency with that module. Can you clarify if that still exists. If yes then what to do?

@bigs are you refactoring #332 in the near future? If yes, I won't be extending chat example because you will anyhow cover peer discovery.

**Comment by bigs** [comment]
@upperwal sorry for the delay here. that's actually set, i just need to do some reflog spelunking to fix a wonky merge. that will be done end of week!

**Comment by upperwal** [comment]
@bigs Cool. You proceed with your merge. 👍

**Comment by gpestana** [comment]
I have put together a standalone example of how to use go-libp2p `mdns` peer discovery : https://github.com/gpestana/net/tree/master/go-libp2p/mdns. 

Happy to make a PR and add it to `/examples` if relevant.

**Comment by bigs** [comment]
@upperwal update here, i've un-borked the merge so that should land soon

**Comment by upperwal** [comment]
@bigs Awesome. But don't you think including tor will add complexity to the example. Many people might be unfamiliar with tor and they might be coming here keeping p2p in mind. Maybe another example to demonstrate adding a new transport i.e. OnionTransport

What I like is different examples each covering different features but building on one another. 
What do you think?

**Comment by bigs** [comment]
not against that! i did make an effort to factor out the tor logic into its
own methods to keep it as vanilla as is possible. what do you think?

**Comment by upperwal** [comment]
@bigs this should work. Barrier to entry should be minimal.

**Comment by dotaheor** [comment]
It looks if I run two separated instances for the example https://github.com/gpestana/net/tree/master/go-libp2p/mdns in the same local network, they can discover each other, but couldn't connect to each other.

The following is the modified main function:
```
func main() {
	host1, cancel := newHost(8000)
	defer cancel()

	printKnownPeers(host1)

	dtx1 := context.Background()
	h1discService, err := discovery.NewMdnsService(dtx1, host1, time.Second, "_host-discovery")
	if err != nil {
		log.Fatal(err)
	}
	defer h1discService.Close()

	h1handler := &rspHandler{host1}
	h1discService.RegisterNotifee(h1handler)

	time.Sleep(time.Second * 8)

	// now both peers know each other
	printKnownPeers(host1)
}
```

The output for one instance:
```
$ ./go-p2p 

host QmYmGNBzAcQ6g4qEaRmKxuLJs5t7adV9J1v1tYSuaDbnGn knows:
 >> QmYmGNBzAcQ6g4qEaRmKxuLJs5t7adV9J1v1tYSuaDbnGn

host <peer.ID YmGNBz> connecting to <peer.ID YCwPWv>... (blocking)
Error when connecting peers: dial attempt failed: failed to dial <peer.ID YCwPWv> (default failure)

host QmYmGNBzAcQ6g4qEaRmKxuLJs5t7adV9J1v1tYSuaDbnGn knows:
 >> QmYmGNBzAcQ6g4qEaRmKxuLJs5t7adV9J1v1tYSuaDbnGn
 >> QmYCwPWvii7zkKiQR3nVi54RFWjfNvQnUQK8bGCyfxeRqe
```

The output for the other instance:
```$ ./go-p2p 

host QmYCwPWvii7zkKiQR3nVi54RFWjfNvQnUQK8bGCyfxeRqe knows:
 >> QmYCwPWvii7zkKiQR3nVi54RFWjfNvQnUQK8bGCyfxeRqe

host <peer.ID YCwPWv> connecting to <peer.ID YmGNBz>... (blocking)
Error when connecting peers: dial attempt failed: <peer.ID YCwPWv> --> <peer.ID YmGNBz> dial attempt failed: context deadline exceeded

host <peer.ID YCwPWv> connecting to <peer.ID YmGNBz>... (blocking)
Error when connecting peers: dial backoff

host QmYCwPWvii7zkKiQR3nVi54RFWjfNvQnUQK8bGCyfxeRqe knows:
 >> QmYCwPWvii7zkKiQR3nVi54RFWjfNvQnUQK8bGCyfxeRqe
 >> QmYmGNBzAcQ6g4qEaRmKxuLJs5t7adV9J1v1tYSuaDbnGn
```

**Comment by gpestana** [comment]
@dotaheor, I created a PR with the mDNS peer discovery here: https://github.com/libp2p/go-libp2p-examples/pull/2  

This thread was originally opened to discuss dht peer discovery, not local network peer discovery. Sorry for the plug and messing up the discussion. Let's keep the conversation about mDNS and local network peer discovery in the go-libp2p-examples [PR](https://github.com/libp2p/go-libp2p-examples/pull/2).

**Comment by upperwal** [comment]
@dotaheor new issue will be good for this. 

Shifted here: libp2p/go-libp2p-examples#3
