### ISSUE TITLE
use a separate stream for every ping

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#391]
Pings should be delivered independent of each other. It doesn't make a difference on transports that introduce HoL between streams, but it does on transports that offer streams at the transport level (i.e. QUIC).

**Comment by Stebalien** [comment]
I'm not sure about this. We want an accurate RTT and, while, we should keep the overhead of new streams to near-zero, I wouldn't like to depend on it. Maybe I'm just being paranoid.

**Comment by marten-seemann** [comment]
Where do you see the biggest overhead?
At the transport level, streams are basically for free (at least in QUIC). The amount of data sent will increase a bit, since we'll have to send the protocol ID (which is currently 16 bytes) on every stream, but I don't think that this really hurts, since a ping packet will still be small (16 bytes protocol ID + 32 bytes ping payload), much smaller than a typical MSS.

**Comment by bigs** [comment]
do we think this is good to go? should we do some profiling?
