### ISSUE TITLE
don't turn off logging

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p#392]
https://github.com/libp2p/go-libp2p/blob/cc70c4be36f765ba9fb92d6e0528722773af607d/p2p/discovery/mdns.go#L68 turns off logging completely.
quic-go uses the go standard logger (but introduces a log level which can be set via an env variable, so quic-go is quiet by default). However, this line prevents quic-go from logging at all.

**Comment by marten-seemann** [comment]
The issue here is that mdns logs **a lot**. We definitely need a way to shut it up.

I see two practical ways to do so:

1. use [go-log](https://github.com/ipfs/go-log) for mdns, and log everything at the lowest log level, i.e. debug. Maybe that's still too noisy though.
2. modify mdns such that it doesn't log any more. Shouldn't be too much work, it's just 11 log statements in total.

@whyrusleeping, wdyt?

**Comment by Stebalien** [comment]
Wow, yeah, we shouldn't do that. We've been trying to switch to a newer fork of our current MDNS library to fix some other issues (races) but... https://github.com/grandcat/zeroconf/issues/38.

It may be worth it to just fork.
