### ISSUE TITLE
make deps doesn't work

### ISSUE THREAD

**Issue by Raggafra** [libp2p/go-libp2p#402]
I get this message while trying to execute make deps inside go-libp2p directory:
gx --verbose install --global
make: gx: No such file or directory
make: *** [deps] Error 1
![screen shot 2018-08-22 at 10 48 31](https://user-images.githubusercontent.com/5746917/44453277-f8d54900-a5f8-11e8-8309-c27fc7fdba56.png)

**Comment by raulk** [comment]
@Raggafra – have you tried adding `$GOPATH/bin` to your `$PATH`? See https://gist.github.com/molivier/271bba5d67de1583a8e3.

**Comment by Stebalien** [comment]
(closing for tracking purposes, feel free to ask followups)
