### ISSUE TITLE
Latest Peerstore Commit Broke Default.go

### ISSUE THREAD

**Issue by terenc3t** [libp2p/go-libp2p#414]
This [commit](https://github.com/libp2p/go-libp2p-peerstore/pull/32) has broken default.go. Here is the error:

```
github.com/libp2p/go-libp2p
# github.com/libp2p/go-libp2p
../../libp2p/go-libp2p/defaults.go:44:48: not enough arguments in call to peerstore.NewPeerstore
	have ()
	want (peerstore.KeyBook, peerstore.AddrBook, peerstore.PeerMetadata)
```

**Comment by raulk** [comment]
@terenc3t We have merged breaking changes to `master` today. The 1.x gx release line stays with the old API. Are you using gx for this dependency?

**Comment by terenc3t** [comment]
I'm looking at this file
https://github.com/libp2p/go-libp2p/blob/master/defaults.go#L44

Can you point to me the file with the fix?

**Comment by Stebalien** [comment]
@raulk let's make fixing this a priority. Unfortunately, many of our users don't use `gx` (because it's a pain) so we can't rely on it (yet). In the future, we'll add `go.mod` support and can rely on vgo we don't have that yet.

**Comment by Stebalien** [comment]
Nevermind... I'll handle this. The gx crap will be a nightmare (35 packages).

**Comment by raulk** [comment]
@stebalien I can take care of fixing this tomorrow EU morning. Apologies.

I thought we were safe due to gx package versioning, but I now realise that many downstream users are pointing at our github packages directly.

**Comment by Stebalien** [comment]
This should now be fixed.

**Comment by terenc3t** [comment]
Confirm this is fixed. Thanks guys.
