### ISSUE TITLE
Places where IPFS names or types are leaking into libp2p

### ISSUE THREAD

**Issue by ghost** [libp2p/go-libp2p#417]
libp2p should not depend in any way on IPFS.  In an ideal world, a `grep -r "ipfs"` of the entire libp2p org should return no results.

Running list of stuff we should fix:
1.  Need `/p2p/` multiaddr in addition to `/ipfs/`
2.  https://github.com/libp2p/go-libp2p-kad-dht/blob/d8e3e7f674cb84a95dc42e353cb51fe56df0059c/dht.go#L44

**Comment by bigs** [comment]
just a note, `ipfs` will remain in some areas for protocol strings, etc

**Comment by marten-seemann** [comment]
We've replaced all occurrences, except for protocol strings, and the default user agent.
