### ISSUE TITLE
communication between both NATS

### ISSUE THREAD

**Issue by dlnuwlx** [libp2p/go-libp2p#418]
Hi experts
1.Dose libp2p support ICE or ICE-like?  I can not find the code from libp2p repo,
2. Does it need  to the third node as hole-server  if ICE-like feature have been implimented?

**Comment by vyzo** [comment]
yes, we have [p2p-circuit](https://github.com/libp2p/go-libp2p-circuit/)

You can enable it with a constructor option, but you'll also need some relay nodes (the bootstrap peers play this role in ipfs).

**Comment by dlnuwlx** [comment]
Thanks!  Can p2p-circuit support  stun protocol?  Dose it support to transfer data directly between both NATS

**Comment by vyzo** [comment]
It uses an intermediate relay node to transport the data -- it's like TURN.

**Comment by dlnuwlx** [comment]
Thanks！ Got it!
