### ISSUE TITLE
Maybe we need a ICE implementation for libp2p.

### ISSUE THREAD

**Issue by xux1217** [libp2p/go-libp2p#424]
Hi,
    In China, most of our network access points are behind several NAT, so we can't use UPNP or NAT-PMP to broadcast the listening port.
    Maybe we need a ICE server to help the libp2p nodes connecting with each other under the several NAT.
    Do you have a plan to implement it? If not, maybe we will do it and submit the PR to you.
    The traversal NAT method is too important for us.

Ref:
    This is the newest ICE protocol: https://tools.ietf.org/html/rfc8445

**Comment by mgoelzer** [comment]
@xux1217  We do have support for NAT traversal.  You may find [this comment](https://github.com/libp2p/go-libp2p/issues/375#issuecomment-407122416) helpful, as well as the rest of that issue.

Also, take a look at the NAT Traversal section at https://github.com/libp2p/libp2p/blob/master/REQUIREMENTS.md.  It's not perfectly up to date right now, but it gives you a sense.

Closing but feel free to reopen if this did not answer your question.

**Comment by xux1217** [comment]
Hi, I have seen the comment and your plan. And I think we need the stun server of libp2p actually. There are some reasons:

1. These are lots of NAT devices in China, because we don't have enough public ip address.
2. STUN server can help us to confirm a peer use which type NAT router, and guide us how to connect the peer more best.
3. In my understand, just use the observed IP to connect only available in Full Cone NAT, but actually the Restricted Cone NAT and Port Restricted Cone NAT also can be directly connected by extra code.
4. If we resolve above three NAT scene, the 85% of NAT problems would be resolved. And rest problems can use relay node to resolve.

I think we can start an optional function "STUN protocol" when start libp2p server. And other peers can use this node to confirm the NAT type by themselves. And then, when they announce their  ID information, they also can announce their NAT type and guide other peers how to connect them.

Finally, if there is a node X want to connect to a peer Y and both of these behind of different Port Restricted Cone NAT , X can send a request message to the "STUN server" node(have a public ip) and the "STUN server" node send this message to Y. Then Y just send a udp message to the ip:port of X and X can directly connect to Y after sleep some millisecond or just ask Y is it ready via the "STUN server" node. 

We hope libp2p have this function, maybe we can help you implement it. As you see, most of people in China are need this function.
