### ISSUE TITLE
Go-lang required version

### ISSUE THREAD

**Issue by strangepowers** [libp2p/go-libp2p#429]
I noticed that in some go-lang versions I get this error:

```
../github.com/multiformats/go-multiaddr/varint.go:6:2: cannot find package "math/bits" in any of:
	/usr/local/Cellar/go/1.8.3/libexec/src/math/bits (from $GOROOT)
	~/go/src/math/bits (from $GOPATH)
```

Is there a list of the supported go versions or do we just need to use the latest version?

**Comment by Stebalien** [comment]
In general, we depend on the latest release. This should still work with go 1.10 for now but we're planning on switching to go 1.11 soon (it has a feature that will allow us to delete a bunch of code).
