### ISSUE TITLE
Optimize Yamux

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#435]
It turns out that yamux is *significantly* limiting our performance (https://github.com/libp2p/go-libp2p/issues/432). My guess right now is that it's internal congestion control is way too limiting. As far as I can tell, it makes absolutely no attempt to *learn* the actual transfer rate and instead limits us to a relatively small amount of un-acked data.

**Comment by vyzo** [comment]
I wonder if this could be simply addressed by increasing the yamux window size.

**Comment by Stebalien** [comment]
For now, yes. However, the correct solution is really to adjust it based on how full the receive buffer is getting (for any individual stream).

**Comment by vyzo** [comment]
Did some quick tests, and increasing the window size does indeed increase throughput for large transfers.

This is relatively easy to do, by creating a config object and setting the max window size field; the default is 256KB.

**Comment by Stebalien** [comment]
In go-ipfs, we use 512KiB.

**Comment by vyzo** [comment]
More specifically, there is almost a 2x decrease in time that it takes to transfer 1GB in localhost by setting the windows size to something large (10MB).

**Comment by vyzo** [comment]
And something more reasonable, 1MB, gives a 1.25x decrease.

**Comment by vyzo** [comment]
As a minimal first step, I would recommend increasing our default window size to 1MB.

**Comment by vyzo** [comment]
Ok, rerun my tests with multiple runs -- there is no diff between 1MB window and 10MB window.

Numbers for transferring 1GB in localhost:
- default window size: 0.515s
- 1MB: 0.401s
- 10MB:  0.399s

**Comment by Stebalien** [comment]
> Numbers for transferring 1GB in localhost:

Running this on the internet will likely give wildly different numbers. This buffer size is, unfortunately, directly affected by RTT.

**Comment by vyzo** [comment]
Yeah, the window size should be adaptive.

**Comment by marten-seemann** [comment]
This has been resolved. Yamux now autotunes the receive window size.
