### ISSUE TITLE
Discuss: Consolidating dependencies and utils

### ISSUE THREAD

**Issue by raulk** [libp2p/go-libp2p#439]
In the context of the [Ethereum 1.0 whisperv6 libp2p implementation](https://github.com/ethereum/go-ethereum/pull/16419), I'm analysing the dependency tree of libp2p. 

We're using a variety of mono-repo utils and not-so-utils (i.e. actual components) from whyrusleeping and jbenet personal repos:

```
github.com/jbenet/go-temp-err-catcher
github.com/jbenet/goprocess
github.com/jbenet/goprocess/context
github.com/jbenet/goprocess/periodic
github.com/jbenet/goprocess/ratelimit
github.com/whyrusleeping/go-logging
github.com/whyrusleeping/go-multiplex
github.com/whyrusleeping/go-notifier
github.com/whyrusleeping/go-smux-multiplex
github.com/whyrusleeping/go-smux-multistream
github.com/whyrusleeping/go-smux-yamux
github.com/whyrusleeping/mafmt
github.com/whyrusleeping/multiaddr-filter
github.com/whyrusleeping/yamux
```

These are stable dependencies now. I propose to consolidate a little bit, by creating a `libp2p/go-utils` and shuffling others into existing repos:

| original                       	| target                        	|
|--------------------------------	|-------------------------------	|
| jbenet/go-temp-err-catcher     	| libp2p/go-utils/err           	|
| jbenet/goprocess/...           	| libp2p/go-utils/process/...       	|
| whyrusleeping/go-logging       	| libp2p/go-utils/log           	|
| whyrusleeping/go-notifier      	| libp2p/go-utils/notifier      	|
| whyrusleeping/mafmt            	| multiformats/multiaddr/fmt    	|
| whyrusleeping/multiaddr-filter 	| multiformats/multiaddr/filter 	|

This makes the conglomerate easier to maintain, reduces the dependency burden (both physically and mentally), and rationalises the repo panoply a little bit (look at the amount of [vendored files](https://github.com/ethereum/go-ethereum/pull/16419/files) libp2p brings into a build). Furthermore, we don't lose the import granularity, as each "util" remains in its own package, so the Unix philosophy "Make each program do one thing well" is still honoured.

---

Note: I'm not convinced with `libp2p/go-utils` is the right place though. Some of these utils are used in IPFS and other projects, so perhaps it should be a common repo for all things PL? `protocol/go-utils`?

**Comment by raulk** [comment]
On a related note, how are we feeling about these components:

* whyrusleeping/go-multiplex
* whyrusleeping/go-smux-multiplex
* whyrusleeping/go-smux-multistream
* whyrusleeping/go-smux-yamux
* whyrusleeping/yamux (fork)

Should we pull them into the libp2p org?

**Comment by jbenet** [comment]
- I'm not going to move goprocess, that does not belong in libp2p nor ipfs. 
  - it's a general utility. 
  - Ask for admin perms, you can own it there. 
  - feel free to mainatain separate forks if you want. treat it as any 3rd party dep you might use from other open source devs.
  - Important point: interface of goprocess should not change at this point. if you want to change it (probably worthwhile to make a better UX/API), consider making a different package (goprocess2, or something else)

- for go-temp-err-catcher -- won't move it either. This one is very simple. feel free to create a fork in libp2p. Im not sure what other tools use this (maybe zero), dont want to break downstream users. (eg if you change the interface). Unlike code in node and other better-package-managed languages, go users may break.

I think those are my only two. That should resolve this for you from my side.

**Comment by raulk** [comment]
@jbenet understood. Just one note:

> I'm not going to move goprocess, that does not belong in libp2p nor ipfs.

I had acknowledged that. Hence suggested moving into somewhere common, e.g. `protocol/go-utils`.

**Comment by Stebalien** [comment]
@raulk

Part of his point is that he doesn't want to *move* it. We can fork it, but there are existing users expecting it to be where it is. I'm also not sure that's a sustainable approach. We're going to depend on third-party libraries and we shouldn't maintain forks of *everything*.

If it gets to a point where we need to make a change but juan isn't around to accept PRs, then we can consider forking it (or getting write access).

**Comment by Stebalien** [comment]
So, if the urls change, github will auto-redirect. However, users depending on *both* locations will end up with two different packages (which won't interop).

**Comment by raulk** [comment]
User feedback on #445.

**Comment by whyrusleeping** [comment]
@raulk definitely makes sense to move the go-smux-* repos, as those are libp2p specific. Would prefer to keep my fork of yamux as its not libp2p specific at all

**Comment by marten-seemann** [comment]
This has been resolved. go-libp2p is now (mostly) a mono-repo, to the point where all true libp2p components (up the host, i.e. excluding kad and gossipsub) live in this repo.
