### ISSUE TITLE
autorelay module

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p#444]
It is becoming apparent that advertising unspecific relay addresses and dialing them through trying known relays is not a scalable solution (in the number of relays).

We need an `autorelay` module that attaches to a host and does the following:
- Discovers relays through a high level interface -- eg DHT providers, rendezvous
- Selects relays (eg for minimum latency) and keeps connections open to them, even in the face of connection manager pruning
- Advertises relay-specific addresses.

Similarly, HopRelays will have to advertise themselves through the appropriate discovery mechanism.

**Comment by vyzo** [comment]
It could also be combined with AutoNAT to make intelligent decisions about relay address advertising based on NATStatus. 
If the node is publicly dialable, then the module shouldn't bother with relay address advertising.

**Comment by Stebalien** [comment]
SGTM. The first implementation could literally hard-code some known-good nodes if we want to get something out the door.

**Comment by vyzo** [comment]
We could do that and it could work for small scale (eg use the bootstrappers), but I don't think it will cost us much to implement with discovery from the get go.
We can start with DHT rendezvous, which should cover us for the immediate future, and then transition to the redenzvous protocol.

See also #446.

**Comment by vyzo** [comment]
Actually, let's just also have a fixed relay option (say we pass a fixed discovery interface that returns the known relays).
It is useful for applications that want to use their own relays without needing the DHT (or the discovery stack in general).

**Comment by bigs** [comment]
do we want to use a small pool of relays to connect to many nodes or do we want to discover relays more generally on a per relayed-peer basis? perhaps a connection manager could prevent us from taxing a single relay too hard?
