### ISSUE TITLE
Investigate protocol mux failures

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p#447]
There seems to be an inordinate number of non-eof failures in [`BasicHost.newStreamHandler`]( https://github.com/libp2p/go-libp2p/blob/master/p2p/host/basic/basic_host.go#L225) (see #443), usually with a connection reset. 
Investigate these failures, as we shouldn't be getting so many of them.

**Comment by marten-seemann** [comment]
Haven't heard any complaints about this recently. https://github.com/libp2p/specs/issues/479 is probably the best way to improve debuggability here.
