### ISSUE TITLE
Dialing specific relay addresses through routed hosts

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p#448]
We have a problem with dialing specific relay addresses of the form `/ipfs/QmRelay/p2p-circuit/ipfs/QmTarget`: the relay transport is attached to the basic host, so it will not be able to find `QmRelay` unless we have connected to the peer in the past or it somehow made its way to our Peerstore.
This will become of major importance as we enable relay by default, phase out unspecific relay addresses and move to specific relay address advertising (see #441 and #444).

Suggested Solution:
- Modify the routed host so that it comprehends relay addrs in `Connect`, and issues a `FindPeer` for the relay when it sees a relay-specific address.

**Comment by vyzo** [comment]
cc @Stebalien

**Comment by Stebalien** [comment]
Grumble... we can do that as a stop-gap but I'd *like* to push routing down to the swarm. That is, don't give the swarm a peerstore, give it a peer router (or, even better, some kind of dial driver). This would fix things like https://github.com/libp2p/go-libp2p/issues/351 (and, in general, make peer routing suck less).

However, someone would need to own it and make it happen it would be a non-trivial change.

---

Not going too far off topic, yes, that sounds like a reasonable stop-gap solution. It would be similar to what we do with dnsaddr addresses.
