### ISSUE TITLE
Connection Closing

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#45]
we need to decide how to choose when to disconnect from a given peer. Right now, we never disconnect after making a connection unless that connection gets dropped.

**Comment by jbenet** [comment]
We'll want something like this. take this with a grain of salt:
- swarm lets each protocol register a value per peer, one of `{Active, Passive}` 
  - Active = keep conn open 
  - Passive = i'll use conn if it's open but don't keep it open on my behalf
- If all passive, swarm disconnects.
- The value can be passed in to `Connect` or `Dial` too.

**Comment by lgierth** [comment]
Sounds good to me on first sight

>  lets each protocol register a value per peer

but this I'd invert, protocols don't need to be aware of the swarm. the swarm can just ask them whether they're still interested in the connection for a given peerid. this way you end up with only one control flow for this.

**Comment by diasdavid** [comment]
@whyrusleeping do you still have the notes from last lab week (I wrote them in paper and I believe we also opened a issue, trying to find it)

**Comment by davidak** [comment]
I think we want a healthy and efficient network. So we need connections with low latency but also some with good connections to the whole network, so we can find the data we want. We probably should at least know every peer in the local network, so we can ask them if they have the data we want before asking peers on the internet.

**Comment by thomas92911** [comment]
#474

**Comment by anacrolix** [comment]
I think there was a lot of discussion of connection pruning recently, I can't find anything on GitHub that reflects some of the talking points though.
