### ISSUE TITLE
The urls for the go-libp2p impl's need a refresh

### ISSUE THREAD

**Issue by daviddias** [libp2p/go-libp2p#450]
Found out through https://news.ycombinator.com/item?id=18163708. I tried a few and got some broken urls. For example:

- 404 https://github.com/libp2p/go-libp2p/p2p/protocol/ping
- Archived/Deprecated https://github.com/libp2p/go-libp2p-conn

Can we get a volunteer from the go-libp2p team refresh the impls list on libp2p.io?

**Comment by marten-seemann** [comment]
libp2p.io should be up to date now.
