### ISSUE TITLE
Listen on insecure transport has no peerID

### ISSUE THREAD

**Issue by xux1217** [libp2p/go-libp2p#452]
There are three node A, B, C and use insecure transport.

A is a listener, now B connect to A, the conn in A can't get the peerID of B, because the conn.RemotePeer() is set by handshake of secure transport.

And then C connect to A, A would recognize the conn is from B(actually A get the peerID of B and C is always nil), and set error protocols.

**Comment by xux1217** [comment]
I think maybe we should use ID Service to set the peerID(if not set before) of the conn finally.

**Comment by Stebalien** [comment]
I'd rather not add this to the identify protocol as the insecure protocol exists primarily for testing. However, we can probably change the insecure transport (or introduce a new version) to send the peer ID.

**Comment by xux1217** [comment]
You are right, change the insecure transport is the best. And I think when I use the protect network in local area, use the insecure transport  would faster.

**Comment by Stebalien** [comment]
> And I think when I use the protect network in local area, use the insecure transport would be faster.

Slightly but not by much. I don't recommend it.

**Comment by Stebalien** [comment]
FYI, if you want to take a stab at fixing this, you'd need to modify https://github.com/libp2p/go-conn-security/blob/master/insecure/insecure.go.

**Comment by mhchia** [comment]
The public key is sent in Identify protocol but only used to verify if it matches the peerID. Does it make sense to change the Identify, to save the corresponding peerID of the public key if peerID is not present(i.e. empty) in the first place? This way we don't need to modify the process to establish an insecure connection, which breaks the interoperability.

**Comment by raulk** [comment]
IIUC, the issue is that the receiving swarm (network implementation) will have no peer ID to store the incoming connection under. The dialing side has no problem because the libp2p APIs oblige you to have a peer ID to dial. So indeed, it seems like the _insecure_ channel should simply exchange peer IDs with no cryptographic validation.

**Comment by mhchia** [comment]
@raulk Thanks for the reply!

> IIUC, the issue is that the receiving swarm (network implementation) will have no peer ID to store the incoming connection under. The dialing side has no problem because the libp2p APIs oblige you to have a peer ID to dial.

Yes, that is what I understand currently.

> So indeed, it seems like the insecure channel should simply exchange peer IDs with no cryptographic validation.

Do you mean we just modify the process establishing the insecure channel? For instance, after negotiating the security to *insecure*, the dialing node passes its peer ID to the dialed node and the dialed node just receive and set the dialing nodes peer ID.

Just want to explain again what currently understand and what I want to do, please correct me if I'm wrong:

After a connection is established(security + muxed), the dialed node opens a stream to the dialing node's "Identify protocol". The dialing node sends its public key and addresses ...etc to the dialed node. Currently, the dialed node "consumes" these data, but for the public key, the dialed node only verifies if this public key corresponds to the dialing nodes' peer ID. The dialed node does not store the peer ID derived from the public key if at that moment it doesn't know the peer ID of the dialing node.

https://github.com/libp2p/go-libp2p/blob/e69d17141ca58ba6afbf13098e90c9377938e590/p2p/protocol/identify/id.go#L372-L424

I am thinking that the dialed node can just store the dialing nodes' peer ID which is derived from the public key to the Connection, and therefore the exchange is complete(dialed node knows the peer ID of the dialing node, and of course dialing node knows the one of the dialed node). This way it seems we don't need to modify the existing insecure connection establishing process.

**Comment by Stebalien** [comment]
> Do you mean we just modify the process establishing the insecure channel? For instance, after negotiating the security to insecure, the dialing node passes its peer ID to the dialed node and the dialed node just receive and set the dialing nodes peer ID.

Yes. We can just make that a part of the "protocol". Really, most of libp2p breaks without a valid peer ID so we should try to make sure we have one.

**Comment by marten-seemann** [comment]
This should have been solved by the introduction of [plaintext v2](https://github.com/libp2p/specs/tree/master/plaintext).
