### ISSUE TITLE
InfoFromP2pAddr unable to parse Multiaddr from Host

### ISSUE THREAD

**Issue by lthibault** [libp2p/go-libp2p#459]
Hello, 

Please consider the following test-case:

```go
package main

import (
    "log"
    "context"

    libp2p "github.com/libp2p/go-libp2p"
    ps "github.com/libp2p/go-libp2p-peerstore"
)

var c = context.Background()

func main() {
    h0, err := libp2p.New(c)
    if err != nil {
        panic(err)
    }    

    addr0 := h0.Addrs()[1]

    _, err := ps.InfoFromP2pAddr(addr0)
    if err != nil {
        panic(err)
    }
}
```

This snippet panics with `invalid p2p multiaddr`.

This is surprising since `Host.Addrs()` returns a list of `Multiaddr` objects, so why shouldn't these be parsable?  I see two possibilities:

1. There is a bug in `InfoFromP2pAddr`
2. There is no bug, but there's a non-documented gotcha (which should be documented plainly)

Thoughts?

**Comment by Stebalien** [comment]
The addrs returned by `h0.Addrs()` *are* multiaddrs, they just aren't *p2p* multiaddrs. That is, they don't end with `/ipfs/QmId...` (or the new `/p2p/QmId...` which should make the `p2p` part clear).

However, this function *should* be documented. Mind adding some?

**Comment by lthibault** [comment]
@Stebalien  Ah okay!  Makes sense.

Follow-up question:  how can I get a p2p Multiaddr from a `Host` instance?  I imagine there's a bit of indirection here, but would you mind sharing a snippet?

I'm absolutely happy to document the function.  What's the usual use-case for wanting a non-p2p multiaddr?

**Comment by raulk** [comment]
@lthibault To my knowledge, simplest way right now is to create the struct yourself:

```
pi := PeerInfo{
        ID: host.ID(),
        Addrs: host.Addrs(),
}
```

**Comment by lthibault** [comment]
Brilliant!  I was expecting there to be some magic involved, but explicit creation suits me just fine! 😃 

Thanks for your work on this project.  I've been waiting _years_ to find something like this.
