### ISSUE TITLE
dht.sendMessage(ctx, p, pmes)

### ISSUE THREAD

**Issue by lele012** [libp2p/go-libp2p#466]
Hi：
When I send data (the size of "pmes" is 25 Bytes) at 5 times per second to another peer by " dht.sendMessage(ctx, p, pmes) " , in theory, the sending traffic is 25×8×5 = 1000bps , but the actual sending traffic is 16kbps , why ?

**Comment by Stebalien** [comment]
1. TCP overhead.
2. SECIO overhead (32 bytes from the MAC alone).
3. Stream muxer overhead.

If you're sending messages to *different* peers, there's also overhead in opening new streams/negotiating the stream protocol.

If you're connecting to new peers, there'll be a *ton* of overhead establishing the connection itself.

**Comment by lele012** [comment]
OK，thanks。
