### ISSUE TITLE
mDNS response

### ISSUE THREAD

**Issue by richardschneider** [libp2p/go-libp2p#469]
Using wireshark with ipfs version 0.4.18, I've discovered that IPFS sends the mDNS response to the query originator address NOT to `224.0.0.251`.

This means that other peers will not see the response and basically breaks the whole idea of passive monitoring.

**Comment by Stebalien** [comment]
> This means that other peers will not see the response and basically breaks the whole idea of passive monitoring.

It's *also* incompatible with multiple mDNS listeners on the same port. Operating systems will deliver packets to all applications listening on the same port when sent to 224.0.0.251 but not when sent to the host's IP address.
