### ISSUE TITLE
Interface refactors once auto-relay PR merged

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/go-libp2p#472]
Following some synchronous discussion in the libp2p bi-weekly meeting today, resolved:

- https://github.com/libp2p/go-libp2p/pull/454 is good to merge 🍾
- Ideally, interfaces that may change should be marked as `unstable` in that PR
- @vyzo, @Stebalien and @bigs should quickly figure out how to refactor interfaces before users start relying on them.  Two main areas identified by @Stebalien:
  1. push identify method
  1. revise the identify service to push new addresses

I'll let you all discuss these matters here.  Marking as high priority so that it does not get forgotten. 😀

**Comment by marten-seemann** [comment]
I'm not sure I understand what exactly should be refactored, but

> ...  should quickly figure out how to refactor interfaces before users start relying on them

I suppose that ship has sailed.
