### ISSUE TITLE
how to hold a connection for a long time

### ISSUE THREAD

**Issue by thomas92911** [libp2p/go-libp2p#474]
I have two ipfs nodes, A is in nat, B is public, I need B to do relay service to A.

So, I need to keep a long time connection between A and B.

How to do it

Now my approach is

A:
for {
     Ipfs swarm connect B
}

thomas92911 from (ARS.China)

**Comment by raulk** [comment]
^^ for now that's the way. I'm conceptualising a new connection manager interface that, amongst other things, will support locking connections and getting callbacks when the lock expires.

**Comment by thomas92911** [comment]
> You can tag the connection if you are using a connection manager.
> See `Host.ConnManager().TagPeer()` for the interface; you should pass the `libp2p.ConnManager()` option to the constructor.



> ^^ for now that's the way. I'm conceptualising a new connection manager interface that, amongst other things, will support time-locking connections, and getting callbacks when the lock expires.

 thx
