### ISSUE TITLE
Autorelay test is flaky

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#477]
> autorelay_test.go:186: No relay addrs advertised

**Comment by Stebalien** [comment]
I'm disabling this test as it's failing _every_ test run.

@vyzo anything we can do about this?

**Comment by vyzo** [comment]
Haven't figured out a good way to deflake it, other than make it take longer.

**Comment by Stebalien** [comment]
I've tried 10 seconds but that didn't seem to be enough. I'm thinking there may be a race somewhere, maybe?

**Comment by vyzo** [comment]
we need to adjust the other delays as well; and yes, there is likely a race in the test.
