### ISSUE TITLE
Build failure after `gx-go link go-libp2p`

### ISSUE THREAD

**Issue by cannium** [libp2p/go-libp2p#482]
Current ipfs master version could not be built after `gx-go link go-libp2p`, something inconsistent
```
# gx/ipfs/QmXRphxBT4BH2GqGHUSbqULm7wNsxnpA2NrbNaY3DU1Y5K/go-bitswap/testnet
../../../../../gx/ipfs/QmXRphxBT4BH2GqGHUSbqULm7wNsxnpA2NrbNaY3DU1Y5K/go-bitswap/testnet/peernet.go:30:30: cannot use client (type "gx/ipfs/QmahxMNoNuSsgQefo9rkpcfRFmQrMN6Q99aztKXf63K7YJ/go-libp2p-host".Host) as type "gx/ipfs/QmVrjR2KMe57y4YyfHdYa3yKD278gN8W7CTiqSuYmxjA7F/go-libp2p-host".Host in argument to network.NewFromIpfsHost:
	"gx/ipfs/QmahxMNoNuSsgQefo9rkpcfRFmQrMN6Q99aztKXf63K7YJ/go-libp2p-host".Host does not implement "gx/ipfs/QmVrjR2KMe57y4YyfHdYa3yKD278gN8W7CTiqSuYmxjA7F/go-libp2p-host".Host (wrong type for ConnManager method)
		have ConnManager() "gx/ipfs/QmQSucBpqUVQ5Q1stDmm2Bon4Tq4KNhNXuVmLMraARoUoh/go-libp2p-interface-connmgr".ConnManager
		want ConnManager() "gx/ipfs/QmR8DgkC3Xnc1TnfH1DvZtLRzPKJBrWfeDKseeXnUY6CN5/go-libp2p-interface-connmgr".ConnManager
```
I think you might have some internal tools to handle it. Please fix.

**Comment by hannahhoward** [comment]
Yea sorry folks this is my doing -- had to publish new versions up the chain for a small package update (go-ipfs-delay) but the final set up updates is not merged into go-ipfs master -- and is in the PR referenced above.

**Comment by saresend** [comment]
Hey! Sorry to jump on this issue, but I'm running into similar problems with go-libp2p where the dependencies aren't lining up with what libp2p is expecting. I'm very new to how gx handles dependencies and I was wondering what specifically the workaround here is? Thanks!

**Comment by cannium** [comment]
@saresend checkout branch `gx/update-kque0y` of go-ipfs

**Comment by Stebalien** [comment]
This has been merged and fixed.
