### ISSUE TITLE
go-libp2p example make deps not work

### ISSUE THREAD

**Issue by SimHR** [libp2p/go-libp2p#483]
![screenshot from 2018-11-13 19-52-55](https://user-images.githubusercontent.com/13049062/48408890-c82b2880-e77d-11e8-9b67-92ca1f1ba1c2.png)

what should i do...?

**Comment by Stebalien** [comment]
You'll need to update your dependencies (try `go get -t -d -u ./...`). Specifically, make sure to update github.com/multiformats/go-multihash
