### ISSUE TITLE
How do I test autorelay?

### ISSUE THREAD

**Issue by cannium** [libp2p/go-libp2p#487]
In `go-ipfs`, DHT service is initialized after libp2p, in `startOnlineServicesWithHost`:
```go
	peerhost, err := hostOption(ctx, n.Identity, n.Peerstore, libp2pOpts...)


	if err != nil {
		return err
	}


	if err := n.startOnlineServicesWithHost(ctx, peerhost, routingOption, pubsub, ipnsps); err != nil {
		return err
	}
```
(https://github.com/ipfs/go-ipfs/blob/31099e882469fab12a98f2069e38c847f0b1188c/core/core.go#L264-L272)

But the new autorelay feature requires `cfg.Routing`, which is DHT service:

https://github.com/libp2p/go-libp2p/blob/4341acb1b16d14020571f9cb99b4987e7c11a4df/config/config.go#L169-L198

So we have a dependency loop here(the reason why refactoring is necessary) and I just can't enable the feature. Now I only need a somewhat hacky way to test the feature, I'd like to know what did you do in your tests?

(btw, I had [an idea about refactoring](https://github.com/libp2p/go-libp2p/issues/467#issuecomment-436153406),  I'll write some snippets to elaborate the idea if interested)

**Comment by vyzo** [comment]
There is no dependency loop; you pass it a _constructor_ which takes a host, and can then construct the dht from that host.

**Comment by vyzo** [comment]
Btw, I am working on adding the feature to ipfs, will open pr in the next couple of days.

**Comment by cannium** [comment]
The only concrete type I could find implements `PeerRouting` is `IpfsDHT`, and its initialization requires libp2p `Host`. Could you fill me more info?

**Comment by vyzo** [comment]
You have a `Host` object in the constructor.
So:
```go
libp2p.New(..., libp2p.Routing(func(h host.Host) (routing.PeerRouting, error) {
  // make the DHT with the given Host
  return dht.New(ctx, h, opts...)
}
```

**Comment by vyzo** [comment]
For ipfs integration see https://github.com/ipfs/go-ipfs/pull/5785
