### ISSUE TITLE
question: how to create fake multiaddr without `/ipfs` info?

### ISSUE THREAD

**Issue by lzl124631x** [libp2p/go-libp2p#488]
I want to migrate my project to use `go-libp2p`. The previous code is solely relying on IP and PORT. As the first step, I want to use IP and PORT to create a fake `multiaddr` as the target address, e.g. `targetAddr, err := multiaddr.NewMultiaddr(fmt.Sprintf("/ip4/%s/tcp/%s", ip, port))`. But this address is invalid because `multiaddr` without `/ipfs/xxx` is regarded as invalid addr. [reference](https://github.com/libp2p/go-libp2p-peerstore/blob/master/peerinfo.go#L36)

Eventually I definitely will use authentic multiaddr, but during the migration, is it possible to let me create fake `multiaddr` by only using IP and PORT? Thanks!

**Comment by upperwal** [comment]
> is it possible to let me create fake multiaddr by only using IP and PORT?

Yes, a multiaddr with IP and port, something like ```/ip/127.0.0.1/tcp/3000``` is a valid multiaddr. You should not use ```InfoFromP2pAddr``` for your use case because it uses ```/ipfs``` as the last part. Just create your own. Check [this](https://github.com/multiformats/go-multiaddr#endecapsulate) out.

**Comment by lzl124631x** [comment]
Thanks! @upperwal
