### ISSUE TITLE
Question: Arbitrary number of Peers per Host ... possible?

### ISSUE THREAD

**Issue by mikiquantum** [libp2p/go-libp2p#491]
Hi everyone, 

We would like to be able to associate an arbitrary number peer ids to a host. 
At the moment a Swarm is associated with a local ID so that means that all incoming connections will be authenticated only against that one local ID.
Is it currently possible to have a supported scenario where multiple PeerIDs are associated to one host? Sort of a custodian model approach.
That way we do not need to create one host per peer and be limited by the max number of ports available (we are using a tcp transport).
Or is there any other recommended approach to solve this architecture?

Thanks!

**Comment by upperwal** [comment]
I don't think multiple peer ID's per host is possible. But you can have multiple streams (which are multiplexed) per host. You can simulate multiple peer ID's using protocols by generating a random peer ID and use it as  protocol ID in ```host.NewStream``` and ```host. SetStreamHandler```.

This way you will have a single connection with many multiplexed streams. So, ideally you can have as many streams as you want. 

What I can't tell you is the overhead associated with starting thousands of streams (64511 to be exact: number of ports available excluding 1024 ports). Libp2p negotiate protocols each time a peer connects with some other peer and now it has to negotiate 64k protocols for each connection.

**Comment by mikiquantum** [comment]
Thanks @upperwal,

I tested out starting up 100k streams identified by peerId like `/echo/$PeerID/0.0.1` and performance for protocol negotiation does not increase much, around 270.001µs in a local setup. Agreed that there will be other performance limits when processing concurrent txs.

What do you think about turning this into a feature request? Associating, authenticating and opening secure tunnels to arbitrary number of peers within same host sounds very useful for a custodian model that overcome some physical constraints of the host (performance, ports ...)

Cheers!

**Comment by upperwal** [comment]
> I tested out starting up 100k streams identified by peerId like ```/echo/$PeerID/0.0.1``` and performance for protocol negotiation does not increase much, around 270.001µs in a local setup

This looks promising. So, this overhead is with a peer connected to **one** peer with 100k streams? What about a peer connected to 20 peers with 100k streams each.

 > What do you think about turning this into a feature request? Associating, authenticating and opening secure tunnels to arbitrary number of peers

This is what protocols are for. How is your 'new feature' different from protocols in libp2p?

**Comment by Stebalien** [comment]
Having multiple identities is still useful as it allows multiple independent applications to use the same connections. We'll eventually need this for the libp2p daemon.

Unfortunately, while future security transports may support this, our *current* transport doesn't *tell* the remote host the peer it's expecting. Therefore, that peer needs to rely on the port to know which peer to identify as.

My current thinking is that we'll have "sub" hosts. That is, peers will first connect to the outer host and then to the inner host: https://github.com/libp2p/libp2p/issues/37. At the end of the day, this will "just" be another libp2p service.

**Comment by mikiquantum** [comment]
@upperwal I believe the key difference in this approach is to be able to use secio but for the "final" peer (all connections are opened using the target peer keys and not the host ones). 
That way the only thing the local peers share is the host interface/port.

Visually:
![mvimg_20181128_104126](https://user-images.githubusercontent.com/14960066/49147051-dfccea00-f303-11e8-9160-0d82e8455267.jpg)

Simple steps:
1. Peer0 (hosted in Host0) wants to connect to Peer2 (hosted in Host1), gets full multiaddr from DHT (which contains the network info of Host1+Peer2)
2. Peer0 uses secio and opens a secure tunnel checking that Host2 has the correspondent keys for Peer2. 
3. Negotiates protocol, opens stream ...

That way we can have:
- Multiple encrypted connections within same Host (no leaks among each other)
- If one peer key gets compromised it doesnt affect the rest of the peers hosted by the node

@stebalien Looking at https://github.com/libp2p/libp2p/issues/37, it looks promising, just one question:

At the end of the handshake is there an specific tunnel opened between the first peer and the inner peer? And only the outer peer is used to have an open authentication stream between hosts?

Cheers!

**Comment by Stebalien** [comment]
> At the end of the handshake is there an specific tunnel opened between the first peer and the inner peer? And only the outer peer is used to have an open authentication stream between hosts?

No. In the protocol I described, the outer host is trusted (e.g., run by the kernel) and the inner host only *authenticates*. I'm trying to avoid:

1. Having multiple underlying TCP, UDP, etc . connections.
2. Double encryption.
3. Recursive stream multiplexing.

---

If we're willing to drop 2 and 3, we can just use the existing p2p-circuit protocol. If we're willing to drop 1, we'd have to make a new protocol that picks the remote peer *before* securing the connection.

Thinking about this a bit, the latter solution is actually doable (just a bit tricky). It's probably best done by using *multiple* hosts but having all hosts share a single special transport peer-picking transport.

**Comment by mikiquantum** [comment]
Thanks @Stebalien.
> No. In the protocol I described, the outer host is trusted (e.g., run by the kernel) and the inner host only authenticates.

Actually, I do not think we need to drop any of the requirements (at least for our use case) as long as the inner peer is _authenticated_ it will work for us. What do you have in mind for the identity authentication piece? Reusing secio auth schema only?

From the DHT bootstrap perspective, will the EphemeralID Host add peer records in the DHT for each of the inner peers at bootstrap time? So making a temporary inner peer "host" so the DHT handshake works for each inner peer? Or that will happen some other way.
Then the rest happens the way you described in https://github.com/libp2p/libp2p/issues/37.

> Thinking about this a bit, the latter solution is actually doable (just a bit tricky). It's probably best done by using multiple hosts but having all hosts share a single special transport peer-picking transport.

Following on this solution, it would be nice to be able to have independent encrypted tunnels per Identity hosted, but as you mention defeats the purpose of reusing connections. Is that something that can be done later on, as an option?
Meaning starting up a host server in 2 different modes:
- Reuse connections in host (your current proposal)
- Encrypt independent connections to inner peers (future?)
And for now only implement `Reuse connections`.

Just to clarify, when you mention `multiple hosts but having all hosts share a single special transport peer-picking transport.` Is it one "physical" outer host that has multiple virtual peers? So only one port will be needed to be assigned to the outer one?

**Comment by upperwal** [comment]
@mikiquantum thanks for the diagram. I can see how peers within a host can run in its own secure environment. This could be helpful in situations where trust-less applications can run multiple peers within the same host.

> Peer0 uses secio and opens a secure tunnel checking that Host2 has the correspondent keys for Peer2.

Is peer2 sharing the keys with host2? This could be bad. Host2 can act like a gateway. It can receive a connection request and just redirects it to peer2 which secures the channel and wraps it around some header for host2 to know where to send it. This way outer host acts as a stream multiplexer. It can only see encrypted data by a peer* + some metadata for routing.

**Comment by mikiquantum** [comment]
> Is peer2 sharing the keys with host2? This could be bad.

I agree depending on how much trust you have in the Host2. In our scenario the host2 acts as a well known and trusted custodian for many peers, that can't or won't configure their own peer node, but they still want to have an independent identity within our protocol, so if they decide can move their peer hosted by host2 to its own control, even without changing peerIDs.

> It can receive a connection request and just redirects it to peer2 which secures the channel and wraps it around some header for host2 to know where to send it. This way outer host acts as a stream multiplexer. It can only see encrypted data by a peer* + some metadata for routing.

How would that differ from using circuit relayers? As far as I understand the relayers are not aware of the content (end to end encrypted). Unless you are thinking on encrypting streams depending on source/target identity peer, which is closely related to @Stebalien proposal?

**Comment by Stebalien** [comment]
> Actually, I do not think we need to drop any of the requirements (at least for our use case) as long as the inner peer is authenticated it will work for us. What do you have in mind for the identity authentication piece? Reusing secio auth schema only?

Something like that (or possibly something even simpler like a certificate on the *outer* peer's key signed by the *inner* peer).

> From the DHT bootstrap perspective, will the EphemeralID Host add peer records in the DHT for each of the inner peers at bootstrap time?

It would have to add records for each inner peer. That is, when we create a new inner peer, the outer node would add a (signed) record to the DHT mapping the inner peer to the outer peer.

Note 1: We don't actually *have* a way to do this with the DHT yet. That is, we don't have explicit "peer address records". Instead, peers insert themselves into the DHT simply by connecting to their neighboring (by xor distance) nodes in the DHT.

Note 2: In my current thinking, the *inner* peer would rarely, if ever, join the DHT. There's no reason it *couldn't*, it's just more efficient to have a single outer peer participate in the DHT.

> Following on this solution, it would be nice to be able to have independent encrypted tunnels per Identity hosted, but as you mention defeats the purpose of reusing connections. Is that something that can be done later on, as an option?

There's no reason not to support both.

> Is it one "physical" outer host that has multiple virtual peers? So only one port will be needed to be assigned to the outer one?

Yes. The address would likely look something like `/ip4/.../tcp/4001/virtual/p2p/Qm...`. When dialing, the virtual transport would negotiate the correct peer before securing/multiplexing the connection.

This should actually be pretty easy to support. The only *tricky* part will be making the "virtual" transport work for both the websocket, tcp, utp, etc. transports. Unfortunately, I took a shortcut in the last transport refactor that makes this a bit complicated... (well, we'd have to create a registry of "unsecured stream transports").

That aside, this should actually be pretty trivial to implement (if you only care about making it work over raw tcp sockets).

> >  It can receive a connection request and just redirects it to peer2 which secures the channel and wraps it around some header for host2 to know where to send it. This way outer host acts as a stream multiplexer. It can only see encrypted data by a peer* + some metadata for routing.

> How would that differ from using circuit relayers? As far as I understand the relayers are not aware of the content (end to end encrypted). 

Correct, this is equivalent circuit-relay.

**Comment by mikiquantum** [comment]
>Note 2: In my current thinking, the inner peer would rarely, if ever, join the DHT. There's no reason it couldn't, it's just more efficient to have a single outer peer participate in the DHT.

I think that makes sense when the one that opens the connection is a remote peer, what about the case where is the inner peer who opens a connection against some other remote peer (single tenant). It will use the outer peer ID to open a secure channel against that remote peer and then identify the inner PeerID, so the remote peer knows that "real from ID"? Or the handshake in that scenario would be done from inner peerID to remote peerID?

> Yes. The address would likely look something like /ip4/.../tcp/4001/virtual/p2p/Qm.... When dialing, the virtual transport would negotiate the correct peer before securing/multiplexing the connection.

Cool

**Comment by Stebalien** [comment]
> It will use the outer peer ID to open a secure channel against that remote peer and then identify the inner PeerID, so the remote peer knows that "real from ID"? 

This one.

**Comment by mikiquantum** [comment]
@Stebalien and @upperwal, thank you!

I think we can close this issue knowing that there is a plan/proposal that will support our use case.

If I can help designing/reviewing/implementing some of the tasks related to https://github.com/libp2p/libp2p/issues/37, please let me know. 
In any case I will keep an eye on the progress of it.

Cheers!
