### ISSUE TITLE
question: how can I use customized privKey and pubKey generation and signing scheme?

### ISSUE THREAD

**Issue by lzl124631x** [libp2p/go-libp2p#492]
I see libp2p supports a set of [schemes](https://github.com/libp2p/go-libp2p-crypto/blob/master/key.go#L120). But I need to use another scheme. Is it doable? How? Thanks!

**Comment by lzl124631x** [comment]
For now, I want to use a very very dumb way -- use ip + port as the privKey. But I haven't yet found a way to let libp2p accept it.

**Comment by vyzo** [comment]
This is not a good idea, you might as well disable transport security instead of doing something like this.
Also, how are you going to sign with ip+port for private key?

**Comment by lzl124631x** [comment]
I'm new to p2p world. Assume we have a bunch of nodes using libp2p online and with the same protocol, how can they reach each other? This is peer discovery. In libp2p how do we solve this issue?

**Comment by vyzo** [comment]
There a couple of options for discovery: there is mdns for local discovery, and you can use the dht for global discovery.

**Comment by lzl124631x** [comment]
@vyzo Thanks for your answer!

Back to the original question, is it possible to use customized Digital Signature Algorithm?

**Comment by vyzo** [comment]
You can implement the PubKey/PrivKey interface with your custom algorithms.
