### ISSUE TITLE
ERROR net/identi: did not have own public key in Peerstore

### ISSUE THREAD

**Issue by lzl124631x** [libp2p/go-libp2p#493]
I found that if I use `libp2p.NoSecurity` in `libp2p.New` I'll get

```
ERROR net/identi: did not have own public key in Peerstore id.go:190
```

After commenting the `NoSecurity` out, the error is gone.

Is this by design? Should I just ignore this error when using `NoSecurity`?

**Comment by upperwal** [comment]
Yeah, just ignore it. This happens because ```NoSecurity``` option will not store the public-private key pair in the peerstore. ```cfg.Insecure == true``` if you pass ```NoSecurity```

https://github.com/libp2p/go-libp2p/blob/e15828972d59c96952829fe19e0784ad71884721/config/config.go#L99-L102

and ```Peerstore.PubKey``` will return ```nil```

https://github.com/libp2p/go-libp2p/blob/e15828972d59c96952829fe19e0784ad71884721/p2p/protocol/identify/id.go#L188-L191

@Stebalien Shouldn't it be a ```Warning``` instead of an ```Error```?

**Comment by lzl124631x** [comment]
Thanks @upperwal. I agree with you. Using a built-in feature correctly doesn't deserve an error. Agree with `Warning`. Or don't show warning/error for the `ownKey` check if `NoSecurity` is used, since it's intentional.

**Comment by Stebalien** [comment]
> Using a built-in feature correctly doesn't deserve an error. Agree with Warning

It's a built-in feature for debugging only. Under any other circumstances, it's a pretty fatal error.

However, IIRC, we don't even have a *peer* ID so we can probably check if the peer ID is empty and skip this if it is.

**Comment by upperwal** [comment]
@Stebalien Yeah, it's true for inbound connection but not for outbound connection.

```go
// SecureOutbound *pretends to secure* an outbound connection to the given peer.
func (t *Transport) SecureOutbound(ctx context.Context, insecure net.Conn, p peer.ID) (security.Conn, error) {
  return &Conn{
    Conn:   insecure,
    local:  t.id,
    remote: p,
  }, nil
}
```

How about not setting ```remote``` here. This way both remote addresses will be empty.

**Comment by Stebalien** [comment]
Ah... Unfortunately, that causes problems *elsewhere* where we make sure we dial the correct peer. 

On second thought, maybe we should check if we have the *private* key before logging. If we don't, then we know we're not operating in "secure" mode. This is what we do in the swarm when dialing.

**Comment by upperwal** [comment]
> On second thought, maybe we should check if we have the private key before logging. If we don't, then we know we're not operating in "secure" mode. 

This works!
