### ISSUE TITLE
go-libp2p Q1 2019 OKRs

### ISSUE THREAD

**Issue by mgoelzer** [libp2p/go-libp2p#503]
We're working in this sheet:  https://docs.google.com/spreadsheets/d/11GKG1DBRIIAiQnHvLD7_IqWxDGsVdaZFpxJM6NWtXe8/edit#gid=438591000

Discussion welcome here on the issue or in the sheet.

**Comment by vyzo** [comment]
There is an open pr for autorelay in ipfs, it should get merged soon enough.
Next step is deployment of relays.

**Comment by mgoelzer** [comment]
@vyzo Thanks - that's helpful.  What are your interests for Q1?  Do you want to work on some of the NAT traversal stuff like hole punching and STUN/ICE?  Or do you think there is still a lot of work left on AutoRelay and seeing how well they work in the wild?

**Comment by vyzo** [comment]
there is a bit of work as we have to observe the deployment and effectiveness, but sure let's get started on NAT traversal.

**Comment by lnykww** [comment]
Is there a development plan for coral?  go-libp2p-coral-dht  has not been updated for a long time. Will this project continue to be developed?

**Comment by bigs** [comment]
@lnykww the current thinking is that we incorporate coral's concepts as a part of a broader overhaul of our DHT code, in which we will introduce "overlay DHTs". we imagine these as feeling a bit like namespaces, which would allow us to more easily execute DHT actions within our level 0-2 clusters. work on this will likely begin this quarter.

**Comment by lnykww** [comment]
@bigs  Do you means that the cluster of coral is a namespace above the normal dht?
