### ISSUE TITLE
Cannot build v6.0.29 (go-libp2p/p2p/host/relay)

### ISSUE THREAD

**Issue by stefanhans** [libp2p/go-libp2p#508]
In some places, I've got the following problem:

>  go build                                                 
> github.com/libp2p/go-libp2p/p2p/host/relay
> github.com/libp2p/go-libp2p@v6.0.29+incompatible/p2p/host/relay/autorelay.go:208:6: undefined: manet.IsPublicAddr
> github.com/libp2p/go-libp2p@v6.0.29+incompatible/p2p/host/relay/autorelay.go:246:8: undefined: manet.IsPrivateAddr
> grep github.com/libp2p/go-libp2p ../go.mod | grep v6.0.29
> github.com/libp2p/go-libp2p v6.0.29+incompatible

If I change the go.mod to `v6.0.23` it builds

**Comment by vyzo** [comment]
you need an up-to-date go-multiaddr-net.

**Comment by stefanhans** [comment]
I do have `
        github.com/multiformats/go-multiaddr-net v1.6.3
`

**Comment by stefanhans** [comment]
I do not understand exactly why, but it seems a problem with Go modules. Using `make` works

Using `go mod init && go mod vendor` has problems (https://github.com/ipfs/go-ipfs/issues/5850)

For me the issue can be closed.

**Comment by Stebalien** [comment]
It may have been due to a missing tag. The latest is 1.7.1 (now tagged).

**Comment by stefanhans** [comment]
oops

I tried `make` and `go mod` with the same result

 go run host.go 
# github.com/multiformats/go-multiaddr-net
../../../../../pkg/mod/github.com/multiformats/go-multiaddr-net@v1.7.1/convert.go:75:10: undefined: multiaddr.NewComponent
../../../../../pkg/mod/github.com/multiformats/go-multiaddr-net@v1.7.1/convert.go:77:15: undefined: multiaddr.NewComponent
../../../../../pkg/mod/github.com/multiformats/go-multiaddr-net@v1.7.1/convert.go:84:17: undefined: multiaddr.NewComponent
../../../../../pkg/mod/github.com/multiformats/go-multiaddr-net@v1.7.1/convert.go:111:2: undefined: multiaddr.ForEach
../../../../../pkg/mod/github.com/multiformats/go-multiaddr-net@v1.7.1/convert.go:111:23: undefined: multiaddr.Component
../../../../../pkg/mod/github.com/multiformats/go-multiaddr-net@v1.7.1/convert.go:115:9: undefined: multiaddr.P_IP6ZONE
../../../../../pkg/mod/github.com/multiformats/go-multiaddr-net@v1.7.1/convert.go:268:9: undefined: multiaddr.NewComponent
../../../../../pkg/mod/github.com/multiformats/go-multiaddr-net@v1.7.1/ip.go:63:10: undefined: multiaddr.SplitFirst
../../../../../pkg/mod/github.com/multiformats/go-multiaddr-net@v1.7.1/ip.go:79:10: undefined: multiaddr.SplitFirst
../../../../../pkg/mod/github.com/multiformats/go-multiaddr-net@v1.7.1/ip.go:94:10: undefined: multiaddr.SplitFirst
../../../../../pkg/mod/github.com/multiformats/go-multiaddr-net@v1.7.1/ip.go:94:10: too many errors

**Comment by stefanhans** [comment]
But `go get -d -u ./...` instead of `make` or `go get -t -d ./...`, resp., works :smiley:

**Comment by Stebalien** [comment]
I've also updated the tags on go-multiaddr.

However, for now, you *really* should be explicitly picking the git commits until we add proper go mod support.

**Comment by stefanhans** [comment]
Now I know :relieved:

**Comment by hsanjuan** [comment]
Do we need to add tags to things?

**Comment by Stebalien** [comment]
We need to *retag* everything. Unfortunately, we have a bunch of things that are > 1.0 because we haven't been following semver (we've been using gx).
