### ISSUE TITLE
Autorelay is announcing a bare-IP multiaddr

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#510]
That is, `/ip4/.../ipfs/...` (no tcp/udp).

**Comment by Stebalien** [comment]
Or maybe it's autonat? No idea but this only happens after autonat decides that I'm undialable.

**Comment by vyzo** [comment]
It's autorelay and it's on purpose -- we'd like to preserve the original IP address in order to facilitate the dialer in making decisions whether to try private IPs.
We can remove if you think it's undesirable.

**Comment by vyzo** [comment]
to facilitate the v2 dialer that is, current dialer will dial the private addresses anyway.

**Comment by vyzo** [comment]
#511 removes the raw public address from the announcement.

**Comment by Stebalien** [comment]
Ah, I forgot about that. Seeing this show up in `ipfs id` is mildly confusing but this seems important.

What if we announce `/p2p/QmRelay/ip4/PUBLIC/tcp/4001/p2p/QmTarget`? Thoughts @raulk/@vyzo?

**Comment by vyzo** [comment]
Kind of defeats the purpose, the dialer will have to fish a private ip out of a relay address.
Regardless, I think we can turn it off until we actually have a dialer that takes advantage of it, at which point we can reinstate it (or decide on a better mechanism).

**Comment by Stebalien** [comment]
> Kind of defeats the purpose, the dialer will have to fish a private ip out of a relay address.

Not sure what you mean here.

**Comment by vyzo** [comment]
Well, the dialer (v2) will have to use a public address from which to decide whether the private addresses are applicable.  Having it flat out as an undialable address facilitates the selection.
In principle we could do the same with embedding the public ip in the relay address, it's just a bit more work for the dialer (and a bit more confusion).

**Comment by vyzo** [comment]
Also, there is no clean mapping of public addresses to relay addresses, as we might have multple public ones, each mapping to potentially multiple relay addresses -- a bit of combinatorial explosion.

**Comment by Stebalien** [comment]
> Also, there is no clean mapping of public addresses to relay addresses, as we might have multple public ones, each mapping to potentially multiple relay addresses -- a bit of combinatorial explosion.

Good point. Yeah, let's merge that PR while we think about this. The best solution may be to just filter this in the UI.

**Comment by Stebalien** [comment]
@vyzo is there an open issue discussing this?
