### ISSUE TITLE
Race condition in mock_conn 

### ISSUE THREAD

**Issue by iulianpascalau** [libp2p/go-libp2p#533]
Hello

I think I have found a race condition in mock_conn.go, function GetStreams. 
A c.RLock() - c.RUnlock() pair is missing. 
And by the way, wasn't suppose to call allStreams as the funcs basically do the same thing.

Thanks

**Comment by raulk** [comment]
Hey, thanks for the report. Would you mind submitting a PR?

**Comment by iulianpascalau** [comment]
Will do.

**Comment by iulianpascalau** [comment]
PR created https://github.com/libp2p/go-libp2p/pull/535
