### ISSUE TITLE
Too many routing addresses?

### ISSUE THREAD

**Issue by acruikshank** [libp2p/go-libp2p#537]
Running `go-filecoin swarm findpeer QmQ7vgoYkCSpLgMxieXa2zTcMpDkHozVDKxA5uAeL7Z8X` which calls `Router.FindPeer(id)` (https://github.com/filecoin-project/go-filecoin/blob/0be63f9ec58c1567752ebb51c856917b51c2e4a4/api/impl/swarm.go#L105) Where `Router` is an `IpfsRouting` (https://github.com/filecoin-project/go-filecoin/blob/0be63f9ec58c1567752ebb51c856917b51c2e4a4/node/node.go#L164).

This is me on hotel WIFI pinging another laptop in the same room. The output is:

```
/ip4/24.43.192.3/tcp/7280
/ip4/24.43.192.3/tcp/7281
/ip4/127.0.0.1/tcp/6000
/ip4/10.20.10.135/tcp/6000
/ip4/24.43.192.3/tcp/7283
/ip4/24.43.192.3/tcp/7284
/ip4/24.43.192.3/tcp/7282
/ip4/24.43.192.3/tcp/7246
```

This is more addresses than we expect. It this correct? Could someone explain it? We're working through some other issues with with our routing.

**Comment by phritz** [comment]
specifically:
- should we be filtering the addresses we advertise do you think to remove the non-routable ones? 
- is it a feature to be advertising every port on which we're listening?

cc @ZenGround0

**Comment by aschmahmann** [comment]
We no longer advertise more than two detected ports per IP address + protocol combination
