### ISSUE TITLE
Reduce package sprawl

### ISSUE THREAD

**Issue by anacrolix** [libp2p/go-libp2p#540]
I think the developer experience would be better served by having less Go repositories. Lots of small repos makes sense for some languages, but not so much for Go. In particular issue management could be centralized (a common practice in for example the Go core), and smaller repos merged where it makes sense. For example any repos that have no value to outside projects (kbucket is a good example, it's strongly coupled to libp2p concepts like peer IDs and has abstraction inversion specific to our main DHT implementation).

**Comment by prestonvanloon** [comment]
+1 to this. We have roughly 40 (direct or transitive) dependencies on libp2p repositories at https://github.com/prysmaticlabs/prysm.

**Comment by raulk** [comment]
Yes, I'm strongly in favour of this, and we're actively moving in that direction. There are other issues about this. Track #829 for updates.

**Comment by anacrolix** [comment]
What was the resolution?

**Comment by marten-seemann** [comment]
> What was the resolution?

We will continue to reduce package sprawl, as tracked in the other, more specific issues.
