### ISSUE TITLE
Does observed addrs really useful in the case of symmetric nat?

### ISSUE THREAD

**Issue by lnykww** [libp2p/go-libp2p#547]
In the case of symmetric nat, the observed address is not filtered. The peer may see a large number of host addrs set.

**Comment by raulk** [comment]
@vyzo can help here.

**Comment by Kubuxu** [comment]
I've fixed thing like that in the past, the fix was to make sure we observe an address at least N time. We should check if `identify` protocol and obsaddr.go works as supposed.

It might be also a case of threshold being too low (4 time in an hour).

**Comment by lnykww** [comment]
thanks
