### ISSUE TITLE
Question: How to understand number of currently connected peers?

### ISSUE THREAD

**Issue by prestonvanloon** [libp2p/go-libp2p#548]
Hi, I'm trying to understand how many peers are currently connected to a give `host`.

When I access `host.Peerstore().Peers()`, this returns a list of all peers that have ever connected to this host whether they are currently connected or disconnected. I'm finding the information a bit lacking on what is the purpose of an AddrBook vs KeyBook and if either of these could possibly contain the information I am looking for.

Is there a way to determine how many peers are currently connected to a given host?

**Comment by Stebalien** [comment]
`host.Network().Peers()`

AddrBook/KeyBook store addresses (IP, port, etc.) and public keys of known peers (in case we want to connect to them again in the future.

**Comment by prestonvanloon** [comment]
Thanks!
