### ISSUE TITLE
How to disable transport reuse?

### ISSUE THREAD

**Issue by QiangYuzhou** [libp2p/go-libp2p#560]
I want to new a Host. And the DisableReuseport filed in transports seems to be false by default. 
My solution is to configure libp2p to use the given transport so that I could edit this filed manually.
I think it's not a good way. There should be a better solution to set the DisableReuseport filed to be true. And I wanna know how? 
Thanks a lot for your help!

**Comment by iulianpascalau** [comment]
There is a limitation in using libp2p.Transport() option func.
If you want to manually pass a TcpTransport object, you will need an *Upgrade pointer which is not yet available (at the moment of configuring options)
Second, if you pass a constructor func that will try to make a new TcpTransport, will result in error when trying to instantiate Host object as it will find 2 tcp transports (a default one with disableReusePort set to false and the one that was manually added with disableReusePort set to true). 
I find this DisableReuse port quite useful as there are cases when I do not want more hosts to share the same port.

**Comment by QiangYuzhou** [comment]
Still I don't know how set DisableReuse port true. But I've checked  if this port had been occupied, so I could choose another port.

**Comment by Stebalien** [comment]
This could be better documented...

```go
import (
	"context"

	libp2p "github.com/libp2p/go-tcp"
	tptu "github.com/libp2p/go-libp2p-transport-upgrader"
	tcp "github.com/libp2p/go-tcp-transport"
)

func main() {
	host, err := libp2p.New(context.Background(), libp2p.Transport(func(u *tptu.Upgrader) *tcp.TcpTransport {
		tpt := tcp.NewTCPTransport(u)
		tpt.DisableReuseport = true
		return tpt
	}))
    // ...
}
```

**Comment by iulianpascalau** [comment]
Thanks for the help, works! 
I have found out why my previous try didn't work: I have tried the above mentioned option func **with** libp2p.DefaultTransports.

**Comment by Stebalien** [comment]
Yeah, that'll create two transports.

**Comment by iulianpascalau** [comment]
It should be stated somewhere that when you do not reuse ports if, for example, there are 2 hosts, one listening to ipv4/0.0.0.0/tcp/20000 and the other is listening to ipv4/0.0.0.0/tcp/20001, when I connect host 1 to host 2, the second host will see a connection coming from a random port (not 20000). 
Judging from this behavior, I'm guessing libp2p will actually open 2 connections for each connected host.

**Comment by Stebalien** [comment]
>  Judging from this behavior, I'm guessing libp2p will actually open 2 connections for each connected host.

No, it just won't reuse the same port we're listening on.

With reuseport:

* Listen on port 20000
* Dial from port 20000 to 20001

Without reuseport:

* Listen on port 20000
* Dial from a random port to port 20001 (one connection, it just doesn't reuse the listening port)
