### ISSUE TITLE
Is it possible to broadcast messages(anonymously)?

### ISSUE THREAD

**Issue by rairyx** [libp2p/go-libp2p#566]
I'd like to broadcast text messages to every node in the network, is it possible? and how to make the sender anonymous?

**Comment by gpestana** [comment]
What do you mean by "every node in the network"? You can fanout messages using [pubsub](https://github.com/libp2p/go-libp2p-pubsub) to a set of peers that subscribed to a specific channel.

As for doing so anonymously, you'll have to either use Tor as transport (as in https://github.com/OpenBazaar/go-onion-transport) or implement some mechanism to preserve (local) privacy of the peers, e.g. by implementing onion routing on top of the DHT (e.g. as in https://github.com/hashmatter/libp2p-onion-routing) or some other mechanism. As far as I know, libp2p does not offer any privacy preserving mechanisms, but instead focus on implementing the overlay/networking stack instead.

**Comment by rairyx** [comment]
Thanks for the answer! @gpestana I already figured out a way integrating Dandelion on top of libp2p's pubsub [](https://github.com/rairyx/raven)
