### ISSUE TITLE
Upgrader security handshake exception

### ISSUE THREAD

**Issue by Harrywang55666** [libp2p/go-libp2p#573]
This is `mylibp2p` package. The mylibp2p.Host can choose the best(ping least duration) bootstrap peer to be relay its hop peer, and the peer would add an address like `/ipfs/[bootstrap-peer-id]/my-circuit/ipfs/[peer-id]`. Suppose peerA dial peerB through peerC. I have tested that the peerA could actually dial peerB, but both of them wouldn't do security handshake most of time, because the handshake would successful. When they failed, I found the peerC's logs about peerA had sent peerB 20 bytes data, while peerB sent 0 bytes to peerA. I also read the 20 bytes data at peer B running instance successfully...It looks like peerB could not response the handshake of peerA... Is anything wrong about my package?
👇
[mylibp2p.zip](https://github.com/libp2p/go-libp2p/files/3047107/mylibp2p.zip)

**Comment by Stebalien** [comment]
I'm having trouble following your explanation. Could you walk through this step-by-step?
