### ISSUE TITLE
Relay Swarm

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#575]
This morning, we noticed a bunch of peers swarming and overloading our relays. We initially thought this might be malicious but, on further inspection, it looks like there were just some popular nodes running behind relays (causing a bunch of peers to connect to them).

However, we're still concerned some peers may be routing traffic through relays when they shouldn't be. This issue exists so we can report our findings as we investigate this.

**Comment by Stebalien** [comment]
Idea: Maybe we're somehow gossiping relay observed relay addresses.

So, this is what I originally thought was happening:

1. Node P runs a DHT from behind a relay R.
2. Node A connects to node P through R.
3. Node P observes the relay address and stores it.
4. Node B tries to find node A in the DHT and asks node P.
5. Node P gives node B the observed _relay_ address.

However, I no longer think this is happening. We only add the observed peer's address to our peerstore if the transports are consistent with an address they claim to be listening on. That means that, if they're listening on a _relay_, we may decide to advertise a different relay. However, that's not _that_ big of an issue because we'll only do this if they're connected to us through that other relay (mostly).

**Comment by Stebalien** [comment]
Idea: Maybe we're storing observed relay addrs.

So, we _are_ but we shouldn't ever be announcing them, at least in go-ipfs, because we filter out all relay addresses by default. The only ones we don't filter out are ones we _explicitly_ choose in the autorelay host.

**Comment by vyzo** [comment]
I think we are definitely gossiping observed relay addresses, quickly causing our address set to expand to all relays.
