### ISSUE TITLE
Identify should _replace_ addresses

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#579]
Currently, we add all addresses a peer tells us about using identify. Really, we should _replace_ the addresses we know for the peer as we likely have out-of-date information.

May relate to: https://github.com/libp2p/go-libp2p/issues/575

**Comment by vyzo** [comment]
Yes, we need to stop being additive and trust the peer itself.

**Comment by Stebalien** [comment]
So, this also appears to be affecting autorelay. With autorelay, we push new addresses after we pick a relay. Unfortunately, this means our peers will continue to show both addresses instead of replacing the old ones.

This also explains why we're seeing peers advertising both types of addresses.

**Comment by vyzo** [comment]
So this should be straightforward, we can simply do `SetAddrs` in identify instead of `AddAddrs`.

**Comment by vyzo** [comment]
Implemented in #599.
