### ISSUE TITLE
Address observations should be dropped when overloaded

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#584]
We should consider rewriting the address observation system to:

1. Use a single observation worker.
2. Drop observations when we get overloaded (i.e., write to a channel with a select and a default case).

(cc @vyzo)

**Comment by vyzo** [comment]
Given the discovery of 1.2M stuck goroutines in a relay, this should be a priority.
Perhaps we should consider having an option to disable it altogether for cases of public nodes with known ips.

**Comment by Stebalien** [comment]
Yeah, we can probably have some heuristic like: "if we've received N inbound connections in the last M minutes, ignore any observed addresses". However, I'm not sure how that'll interact with autonat and changing networks.
