### ISSUE TITLE
which go-libp2p version should I use for go 1.10.3

### ISSUE THREAD

**Issue by cuizhiqiang0** [libp2p/go-libp2p#588]
my go version is 1.10.3, for some reason I cannot update it. The latest libp2p requires go version > 1.11, so can anyone tell me which p2plib version depends the 1.10.3 go?

**Comment by Stebalien** [comment]
Don't pick a libp2p version to match your go version, you'll miss out on a bunch of really important fixes. Can you not update your toolchain?

**Comment by cuizhiqiang0** [comment]
> Don't pick a libp2p version to match your go version, you'll miss out on a bunch of really important fixes. Can you not update your toolchain?

I am afraid I can not update go version, because other applications depends the low version go. To keep availability of other applications it would be best not update version

**Comment by Stebalien** [comment]
Then to answer your question, I have no idea. You'll have to use a version at least before `gx/v6.0.29` but I have no idea beyond that.

**Comment by cuizhiqiang0** [comment]
> Then to answer your question, I have no idea. You'll have to use a version at least before `gx/v6.0.29` but I have no idea beyond that.

Thank you very much
