### ISSUE TITLE
Remove gx support from builds

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p#589]
We are at a point now where there are changes in gomod that refuse to build in gx, without updating the gx packages.
But we have agreed to stop doing that, as gx is no considered deprecated.
We need to remove the gx build type from CI builds.

**Comment by vyzo** [comment]
I have started killing the gx builds from travis as I go, as discussed with @Stebalien.

We also need to start killing the package.json files.

**Comment by raulk** [comment]
SGTM. We can do this across the board easily leveraging https://github.com/libp2p/workspace-go-libp2p.

**Comment by Stebalien** [comment]
I'd actually leave CI support until we've removed the package.json files. That is, every time CI fails, remove gx and the package.json file until we have none left.

**Comment by raulk** [comment]
What’s the reason to do this gradually? I prefer a scripted Big Bang approach honestly.

**Comment by vyzo** [comment]
Yeah, let's just do it!

**Comment by raulk** [comment]
Ok, the confusion comes from the title. I think we should just remove gx support altogether. This unfolds into:

* rm `package.json`
* rm `.gx` directory
* rm `Makefile`
* sed -i '/BUILD_DEPTYPE=gx/d' .travis.yml

I'll do a prototype PR on go-libp2p-peerstore, have you guys review it, and then apply the changes directly on master across the board. SGTY?

**Comment by raulk** [comment]
Oh, and update READMEs accordingly @yusefnapora

**Comment by vyzo** [comment]
We should probably keep the `.gx` directory around a while longer.

**Comment by vyzo** [comment]
> sed -i '/BUILD_DEPTYPE=gx/d' .travis.yml

We also need to delete from the caching.

**Comment by raulk** [comment]
> We should probably keep the .gx directory around a while longer.

IUC, `.gx/lastpubver` is only used when **importing** a new dependency afresh from Github. I'd rather fail than mislead users into thinking they're importing the last release of the module, when they're not. We can add the a footnote in our README with the hash of the last published version, for posterity.

> We also need to delete from the caching.

Yup.

**Comment by vyzo** [comment]
R.I.P. gx; you were good to us.

**Comment by raulk** [comment]
I do have to admit, I'm kinda welling up as I do this.

**Comment by raulk** [comment]
So here's the script to pull the trigger, to be run from the root of https://github.com/libp2p/workspace-go-libp2p.

Let's wait for @Stebalien to LGTM too.

```
#!/usr/bin/env bash
set -euo pipefail

git submodule foreach git reset --hard origin/master
./workspace.sh refresh
git submodule foreach rm -rf package.json Makefile
git submodule foreach sed -i '' '/BUILD_DEPTYPE=gx/d; /GOPATH\/src\/gx/d' .travis.yml
git submodule foreach 'cat << EOF >> README.md

---

The last gx published version of this module was: $(cat .gx/lastpubver)
EOF'

git submodule foreach rm -rf .gx
git submodule foreach git add -A
git submodule foreach git commit -m "farewell gx; thanks for serving us well."
git submodule foreach 'git --no-pager log --oneline -5; read -p "push? [y/n] " yn; if [[ $yn =~ [Yy] ]]; then git push origin master; else echo "skipping"; fi;'
```

**Comment by yusefnapora** [comment]
I'll do a pass through the readmes after the trigger-pulling. Do we want to simply remove all mention of gx? 

Maybe we could put a note in the go-libp2p readme about  working with gomod using the workspace and the gx deprecation. Then in the module readmes, we can link to that section and remove any refs to gx.

**Comment by raulk** [comment]
@yusefnapora +1 on a README section for developers on go-libp2p with instructions on using the workspace. Feel free to send a PR on the workspace itself to make the README.md more user-friendly (I don't think I was at my best when I wrote it).

Re: modules, just a usage section indicating that we're gomod compatible, and therefore users can add this module by importing it directly in their source files and relying on the go toolchain to resolve it and update their `go.mod` file, should be enough.

**Comment by Stebalien** [comment]
LGTM.

**Comment by raulk** [comment]
It's done! 🎉

**Comment by raulk** [comment]
Announcement in forums: https://discuss.libp2p.io/t/decommissioning-gx-builds-in-go-libp2p/84
