### ISSUE TITLE
Proposal: auto-add relay peer on connection

### ISSUE THREAD

**Issue by requilence** [libp2p/go-libp2p#612]
For now, we only looking for relay peers via DHT and it doesn't work all the times.
In case you have connected somehow to the relay peer, it will be not used for your relay address. 

Is it any special reason behind this? 
BTW I made the PR so you can get the idea

**Comment by vyzo** [comment]
The "relay-hop" tag is only added if we are connected to this relay and we are using it as a relay already, so the pr is not in the right direction.

We could try to utilize random peer discovery with `CanHop` queries similar to how we do it when `OptDiscovery` is enabled to support unspecific relay addr dialing.

But is this any more reliable than using the DHT? Most relays are dedicated nodes which are unlikely to be discovered without active discovery mechanisms.

**Comment by requilence** [comment]
> The "relay-hop" tag is only added if we are connected to this relay and we are using it as a relay already

@vyzo I made tests and this PR works for me
- I have one bootstrap node with enabled relay-hop
- NAT status detected as private
- Without this code, it connects to this bootstrap node but never adds it to the relays map so circuit addr is not injected (i don't have any other relays, so it less than DesiredRelays)
- With this PR it works. After a few moments node was connected it has "relay-hop" tag, peer added to the relays map and circuit addr is injected for my peer 

So it seems like currently,  it connects to this relay node, marks it with "relay-hop" tag. But not using it to generate circuit addresses for my node

**Comment by vyzo** [comment]
But where is the tag coming from?

**Comment by requilence** [comment]
from here
https://github.com/libp2p/go-libp2p-circuit/blob/master/notify.go#L49

so node added to the relays list and used for dials but not using for autorelay

**Comment by vyzo** [comment]
Ah, this is added from discovery. Regardless, I don't think we can rely on this as there are timing conditions and it penalizes dedicated relays.

**Comment by vyzo** [comment]
To elaborate, you have a very limited scenario that doesn't match the live environment in the wild.
In the wild:
- bootstrappers are not relays; they can't take the load.
- relays (at least the ones operated by us) are dedicated nodes that you are unlikely to connect to unless you discover them through the DHT.
- we plan to add a relay selection strategy based on ping latency, as locality affects performance.

Adding this may support limited interaction scenarios like the one you describe, but will be detrimental to the system in the wild.

**Comment by vyzo** [comment]
For your scenario, where you have your own bootstrap peers, why can't you still discover the relay through the DHT? It might take a little longer to kick in (there is the DHT bootstrap time, but also the delay in advertising which is currently _15 minutes_).

You may want to lower the advertise delay by setting `AdvertiseBootDelay` -- see https://github.com/libp2p/go-libp2p/blob/master/p2p/host/relay/relay.go#L13

**Comment by requilence** [comment]
I don't know. It doesn't found through the DHT it even after hours :( I will debug this separately

BTW I have just found that autonat discovery using the same approach, but it seems that it is not utilizing DHT at all https://github.com/libp2p/go-libp2p-autonat/blob/master/notify.go#L26

**Comment by vyzo** [comment]
Yes, autonat is expected to be available in the bootstrappers so that you can get a quick first dial back.
Relays typically also run the autonat service, so once you've connected to one you don't have to use the bootstrappers any more.

**Comment by Stebalien** [comment]
We now recommend using pre-defined relays as randomly discovered relays on the network tend to be extremely unreliable.
