### ISSUE TITLE
Alias in commonly used types

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#618]
I have a dream of being able to use go-libp2p and only needing to import one package. To get there, we could alias in several of the most commonly used types, like host, peer ID, peer info, multiaddr, and maybe a few others. 

Using aliases means these types are interchangeable with the real types, but makes the developer ergonomics much better.

Related: #287

**Comment by raulk** [comment]
This is gonna be a short-lived dream, @whyrusleeping, because it’s already being taken care of in the core refactor: https://github.com/libp2p/go-libp2p-core/blob/consolidate-skeleton/alias.go

:-)

**Comment by whyrusleeping** [comment]
@raulk youre my favorite person of the day
