### ISSUE TITLE
As a developer I can filter/blacklist peers

### ISSUE THREAD

**Issue by frrist** [libp2p/go-libp2p#620]
### Description
In go-filecoin when a node fails the [hello protocol](https://github.com/filecoin-project/go-filecoin/tree/beecac52e8b86995a050672d0907f5bed4502637/protocol/hello) (because they have a different genesis block or wrong version) [we disconnect from them](https://github.com/filecoin-project/go-filecoin/blob/beecac52e8b86995a050672d0907f5bed4502637/protocol/hello/hello.go#L91-L103). However, we will frequently reconnect to them immediately. This is undesirable as we would prefer to not reconnect to this peer again for some time. 
A [solution we initially considered](https://github.com/filecoin-project/go-filecoin/pull/2695/files#diff-a348bd8f91eeee23380b03033d246a96R95) was the [Backoff method](https://github.com/libp2p/go-libp2p-swarm/blob/0fc01368da4ae9ce28fc261131494af3eda9aace/swarm_dial.go#L147) in go-libp2p-swarm, but we were informed this component is for internal use only.

### Acceptance criteria
- As a developer I can configure my application to: 
  - avoid reconnecting to a peer for some configurable amount of time. (e.g. in go-filecoin a peer may keep the same peerID but update its version, we would not want to blacklist a peer in this scenario).
  - Completely blacklist a peer from reconnecting.

**Comment by aschmahmann** [comment]
This closed by #872
