### ISSUE TITLE
Release process for go-libp2p and modules

### ISSUE THREAD

**Issue by yusefnapora** [libp2p/go-libp2p#628]
As libp2p matures, we want our engineering practices to mature along with it, and one opportunity for growth is to standardize our release process in a way that improves the experience of developing and using libp2p.

This issue was prompted by some internal discussions at Protocol Labs, and I've tried to capture the main points. Tagging the people involved to get some eyes on: @raulk @vyzo @Stebalien @whyrusleeping @hsanjuan @bigs @vasco-santos 

Related: https://github.com/libp2p/go-libp2p/issues/621

## Goals

Whatever process we adopt should be in service of these high-level goals:

- No broken releases. End users should feel confident in updatating to new go-libp2p releases, and they should be made fully aware of any backwards-incompatible changes.

- Release notes! All releases of go-libp2p and its various modules should include release notes that describe the changes since the last release.

- Releases should be easy. Manual work and decision making should be avoided if an automated / tool-assisted solution can be built without crazy amounts of effort.

- Early adopters should be able to easily get the latest features and fixes. Users that are excited about new functionality or need fixes from a module should be able to depend on the latest published version of that module, independent of the go-libp2p "entry point" module's release cycle.

### Adopt a regular release cadence for go-libp2p

Rather than making a judgement call about when to release new go-libp2p versions with each change, we suggest issuing new releases on a regular, scheduled cadence. The ideal cadence isn't yet clear, but might start with monthly releases.

This brings up the question of version numbers, with [calendar versioning](https://calver.org/) seeming like a sensible choice for go-libp2p. Calendar versioning can be controversial, as it's not clear at a glance whether breaking changes that would require a new major version are included, as is the case with [semver](https://semver.org/). 

As go-libp2p is still on major version `0`, we have yet to use semver to communicate breaking changes. As such, adopting calendar versioning doesn't seem like it breaks user expectations, but further discussion might reveal strong feelings.

Note that only the go-libp2p entry-point module would adopt calendar versioning under this proposal, while modules would continue with their current versioning schemes.

### Tag new patch releases for modules for (most) PR merges

The idea here is that most PRs that land in a module provide useful functionality that end users might want to adopt right away, and by publishing patch releases once the PR lands we enable that without requiring users to pin specific git commits or chase the `master` branch.

Some pros and cons that came out of discussion so far:

Pro:
- Removes a decision from the merge process (should I release or not)
  - also makes it harder to forget to release after merge
- Allows users and libp2p devs to try out new functionality before it lands in go-libp2p releases
- Users who don't care about the new functionality can ignore the patch releases and stick to what go-libp2p provides

Con:
- Potentially "noisy", especially if users feel like they need to always have the latest changes
- Without automation, adds developer overhead when merging PRs
- Some PRs won't justify new patch releases (e.g. changes to CI setup & READMEs, etc). So this doesn't completely eliminate the decision of whether to release on merge

### Run integration tests on go-libp2p when modules update

To avoid broken releases, we want to make sure that we have some kind of integration testing that runs whenever a module merges new changes to master and/or publishes a new release.

At the moment, the process we're thinking of looks like this:

- Dev merges a PR to a go-libp2p module
- A CI job is triggered in the `workspace-go-libp2p` repo that tests the new `master` for the module. This job should run the test with the following versions of other (unchanged) modules:
  - The latest tagged release
  - The release used by the current version of `go-libp2p`
  - The `master` branch of all modules.

The last configuration (`master` of all modules) should generate a warning if it fails, but shouldn't be considered a blocker and doesn't fail the CI job as a whole.

One question that falls out of all this is when do we tag the updated module as a new release? From a developer perspective, the simplest thing is probably to tag it as soon as it lands in `master`, which would be before the integration tests run. However, that means we might publish patch releases that can't be integrated into go-libp2p and only learn about the incompatibility after we publish. This isn't a huge deal, since we can publish a new patch with the fixes, but it isn't ideal.

An alternative could be for the CI job in `workspace-go-libp2p` to tag the module after the job completes successfully, however this would require some effort to do well. The CI job would need write permission to all module repos to publish the tag, and we'd need some kind of "staging area" for the release notes, so the CI job could include those with the release.

### Version "bubbling" should not require PRs

A consequence of frequent module patch releases is that we'll frequently want to update the version of dependant modules' `go.mod` files, aka "bubbling up" the dependency. Our current process is to make PRs for this, which the PR author usually merges right away, as the vetting has already been done before bubbling. As patches become more frequent, we believe this will lead to a lot of noise in the PR history, especially for `go-libp2p`.

The proposal is to do depdendency bubbling with direct commits to `master` to cut down on noise. However, a useful feature of the PR process is that repo watchers get notified when dependencies change. This is something we'd like to keep, so we're proposing that a bot can watch for changes to `master` that update dependencies, and automatically notify repo watchers.

## Next steps

After some discussion, what we want to end up with is a plan and the tooling that can support it. For the proposals above, we likely need a bot that watches go-libp2p repos and can:

- trigger CI jobs,
- (maybe) tag module releases when CI succeeds
- notify watchers when dependencies update.

We also want to come up with some tooling to assist in the release process, which could be a script that applies an annotated git tag containing some release notes and possibly builds a changelog from commit / PR history.

Thoughts?

**Comment by vyzo** [comment]
I am a little sceptical about auto-tagging, and I don't mind manual tagging through the github release interface.

**Comment by Stebalien** [comment]
I'm all for enforcing a more thorough CI on releases but it still needs to be pretty fast. Ideally, we'd be able to stall a tag push on some CI running but, unfortunately, GitHub doesn't allow for this kind of hook.

If we're willing to write a bot, we could just ask the bot to cut a release:

* Mention "@libp2p-bot release" on a PR. Unfortunately, that _requires_ a PR.
* Create an issue and assign it to @libp2p-bot. The annoying part of this is that the issue will need to link to the commit to release.
* Comment on the commit to be be released. Commenting on commits just isn't something that's done all that often on github.
* Create a Release PR that updates the changelog and assign it to some release bot. That bot would then merge that PR and tag the release (when ready). This is probably too heavy weight.

> As go-libp2p is still on major version 0, we have yet to use semver to communicate breaking changes. As such, adopting calendar versioning doesn't seem like it breaks user expectations, but further discussion might reveal strong feelings.

Go modules expects semver. We _could_ version like `0.1.20190505`, I guess, but I don't really see the benefit.

> Tag new patch releases for modules for (most) PR merges.

Releases should always involve a human. We sometimes make batch-changes that all need to be merged at the same time. Also, we do, occasionally, break master (e.g., due to a lack of tests).

> The proposal is to do depdendency bubbling with direct commits to master to cut down on noise. However, a useful feature of the PR process is that repo watchers get notified when dependencies change. This is something we'd like to keep, so we're proposing that a bot can watch for changes to master that update dependencies, and automatically notify repo watchers.

Does that really buy us anything?

**Comment by hsanjuan** [comment]
> Release notes! All releases of go-libp2p and its various modules should include release notes that describe the changes since the last release.Release notes! All releases of go-libp2p and its various modules should include release notes that describe the changes since the last release.Release notes! All releases of go-libp2p and its various modules should include release notes that describe the changes since the last release.Release notes! All releases of go-libp2p and its various modules should include release notes that describe the changes since the last release.

I'd love release notes on modules with lots of activity or umbrellas, basically the flagships of go-libp2p, kad-dht, and pubsub. Maybe for minor version bumps after complex, breaking changes. But this might be overkill for smaller modules with just new patch versions tags. I usually simply look at the commits to see what changed since the previous tag.

Let's be sensible and invest time improving the tech and not creating processes that are so strict and burdensome that need to build custom bots. Bots that will then need to be maintained. If a change deserves release notes, make an annotated tag, otherwise just tag and move on. At least I think this would work for the majority of smaller repos in libp2p.

**Comment by vasco-santos** [comment]
One of the things that are not included in this discussion and I believe to be essential is the interop tests once a new release of `go-libp2p` is going to happen. 

In this context, I believe that before having a "final" release, we should create a release candidate that should be used to test interoperability with the other implementations. As libp2p is getting more mature, it is essential that we do not break interop.

**Comment by bigs** [comment]
thanks so much for pulling this together, this is huge. a few thoughts:

for workspace-go-libp2p, i think it's critical that tooling give us a few options
- point selective (all,whitelist) repos to HEAD
- point selective (all,whitelist) repos to LATEST RELEASE

could we take some sort of hybridized approach for release versioning? something like `MAJOR.YY.MM.PATCH`? under this scheme, we'd only issue patch releases for security fixes and bug fixes. 

do we cut a new release when there are no changes? i'd imagine not.

if we move to a release schedule like this, we'll probably want to start enforcing commit squashing when merging PRs, as it makes it much simpler to review the changes merged between releases.

**Comment by marten-seemann** [comment]
We're in a much better position now, especially due to:
* go-libp2p being a mono-repo
* test plans being run as part of https://github.com/libp2p/test-plans
