### ISSUE TITLE
identify push needs to only send updated information

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p#630]
Currently we are sending everything, which wastes bandwidth and elicits multi-lock contention.
Our spec allows us to ignore missing fields, so we should change it to only send addresses and possibly protocols.

**Comment by Stebalien** [comment]
This now accounts for _half_ my inbound bandwidth:

* 38 MiB dht chatter (likely responses to my requests)
* 29 MiB bitswap
* 16 MiB in, 18 MiB out identify
* **126 MiB** in, 3.1 MiB out(?) identify push

(not sure where the rest of it is, probably random custom protocols I don't speak)?

**Comment by vyzo** [comment]
wow, that's a lot!

**Comment by raulk** [comment]
Identify deltas are being introduced in #659.

**Comment by marten-seemann** [comment]
... and removed in https://github.com/libp2p/go-libp2p/issues/1974 :)
