### ISSUE TITLE
Example projects that use libp2p

### ISSUE THREAD

**Issue by JustinDrake** [libp2p/go-libp2p#64]
I come from the [OpenBazaar project](https://www.openbazaar.org) and I am new to `go-libp2p` and `go-ipfs`. Are the examples that use `libp2p` in a production environment? Where's the best place to learn `libp2p` by example?

**Comment by whyrusleeping** [comment]
Right now, the only production use of go-libp2p (that i know of) is in go-ipfs. We would love to work with others on helping them use libp2p for their projects too if theres any interest.

**Comment by JustinDrake** [comment]
Cool. Paging @hoffmabc and @cpacia from the OpenBazaar project that are looking to use `go-libp2p` in production.

**Comment by hoffmabc** [comment]
Yep we will be using it.

**Comment by whyrusleeping** [comment]
@hoffmabc @cpacia I'd love to have a chat sometime with you guys about integrations and work with you to make sure everything goes smoothly. This is very exciting :)

**Comment by diasdavid** [comment]
Adding myself to this thread :) Interested on participating on these conversations.

**Comment by JustinDrake** [comment]
@whyrusleeping @diasdavid OpenBazaar's current plan is to reuse most of the `go-libp2p` codebase but make a network fork to allow for longer TTL on certain types of DHT data. What do you guys think? Is a network fork meaninful? cc @cpacia and inviting @michaelfolkson

**Comment by JustinDrake** [comment]
Forwarding @cpacia's comment from Slack:

> The ttl is 24 hours by default. It's too short for the messaging system. That would mean if a message recipient doesn't come back online in 24 hours they wont receive your message. I've changed it to 7 days for message pointers.

**Comment by Kubuxu** [comment]
I wouldn't use DHT for storing messages hashes, it is too unreliable in my opinion for that purpose (and how do you retrieve message to someone from DHT?), there isn't anything ready for messages yet, but once pubsub is implemented fully if you add OrbitDB to that system similar to [patchwork](https://github.com/ssbc/patchwork/) should be quite easy to implement.

**Comment by whyrusleeping** [comment]
The dht could be used for that just fine i think, you would just need to have both parties online within one TTL of eachother to complete a message pass (once you modify the dht to allow storage of arbitrary non-hash message data, which is pretty simple). You wouldnt necessarily be 'splitting the network' but theres no real worry around a 'network split'

**Comment by JustinDrake** [comment]
Here's a video that shows what the OpenBazaar team has done so far:

https://www.youtube.com/watch?v=HG1eKf-Aj0o

**Comment by whyrusleeping** [comment]
@JustinDrake that looks great!

**Comment by cpacia** [comment]
I haven't modified what type of data is stored in the dht. It's still a
provider object (peer id and addresses).

The key is a hash of the (prefix) of the recipient ID and the provider
address is the location of the ciphertext encoded as a multiaddr.

The peer ID field in the provider obj is not needed for my purpose so I use
it as a flag to identify this provider as a message pointer for the purpose
of using a different ttl.

The first 12 bytes are zeros and the remainder is random.

If it finds a provider with peer ID that starts with 12 zeros it applies
the 7 day ttl. Otherwise the ttl is left at 24 hours for regular ipfs
providers.

**Comment by zippy** [comment]
Adding myself to this thread as we're going to be using libp2p for holochain (http://ceptr.org/projects/holochain)

**Comment by bigs** [comment]
would love to get someone to contribute a little blurb to our readme with projects using libp2p

**Comment by marten-seemann** [comment]
We now have this: https://github.com/libp2p/go-libp2p#notable-users
