### ISSUE TITLE
Write coalescing breaks against buggy secio 

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#644]
The bug fixed in https://github.com/libp2p/go-libp2p-secio/pull/44 is causing problems with the new write coalescing patches. To reproduce:

* Build the latest go-ipfs master.
* Build go-ipfs 0.4.20.

Connect them and try to pin. This will fail.

To verify that this is really the issue, you can upgrade secio in 0.4.20 and _only_ secio and the bug magically goes away.

Unfortunately... I think the only solution is to disable write coalescing for a release or two until the network upgrades.

**Comment by vyzo** [comment]
Yeah, let's enable in next release.

**Comment by marten-seemann** [comment]
How can write coalescing break anything? All that Write should care about is the bytes in the slice passed to it, right?

**Comment by vyzo** [comment]
@marten-seemann check the details of the bug; secio would read more than requested if there was spare capacity in the buffer (which is frequent due to buffer pooling). The reader would then ignore the extra data or crash in the case of mplex.

**Comment by Stebalien** [comment]
Most (at least 93%, likely more) has upgraded. These changes have been un-reverted and will be in go-ipfs 0.5.0.
