### ISSUE TITLE
make: dep: Command not found make: *** [Makefile:8: deps] Error 127

### ISSUE THREAD

**Issue by Itsuman1** [libp2p/go-libp2p#645]
**my env**
GOARCH="amd64"
GOBIN="/bin/bin"
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/go-1.11"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.11/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build385737357=/tmp/go-build -gno-record-gcc-switches"

**Comment by Stebalien** [comment]
Please explain exactly what you tried to do and what went wrong.

Note: go-libp2p no longer _has_ a makefile.

**Comment by foreverppaul** [comment]
> Please explain exactly what you tried to do and what went wrong.
> 
> Note: go-libp2p no longer _has_ a makefile.

I also find that go-libp2p has no makefile, so what should i do if i want to make this package?

**Comment by Stebalien** [comment]
This package is a library, there's nothing to make. You can find examples showing how to use it in https://github.com/libp2p/go-libp2p-examples.
