### ISSUE TITLE
Keyspace/Kbucket packages

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#646]
1. go-libp2p-peerstore has a "queue" package that probably doesn't belong there.
2. That queue package depends on github.com/whyrusleeping/go-keyspace.
3. go-libp2p-kbucket has a _duplicate_ keyspace package that appears to be identical.

We should clean this up.

**Comment by raulk** [comment]
@mvid is this something you’d like to take on? cc @bigs

**Comment by mvid** [comment]
@raulk on it

**Comment by mvid** [comment]
To clarify, pull the queue package into it's own repo, or is there another repo where it would be appropriate to keep it?
Then have that new queue repo depend on go-libp2p-kbucket/keyspace instead of go-keyspace

**Comment by bigs** [comment]
i'd advocate for adding this into a core subpackage. maybe `go-libp2p-core/keyspace` and `go-libp2p-core/queue`

**Comment by Stebalien** [comment]
Those packages are _very_ Kademlia specific. I'm not sure they really belong in the core interfaces package.

**Comment by vyzo** [comment]
yeah, let's not bloat `go-libp2p-core`. We don't want to end up with halfway monorepo.

**Comment by bigs** [comment]
cool. @mvid let's move queue and keyspace into go-libp2p-kad-dht, and make sure the references are cleaned up elsewhere.

**Comment by mvid** [comment]
I have an open PR for the consolidation. I have also opened a PR marking the existing queue package as deprecated. 
I assume the next step is to clean up all of the libp2p references to use go-libp2p-kad-dht/queue instead of go-libp2p-peerstore/queue, is there a way of locating all of those?

**Comment by marten-seemann** [comment]
> go-libp2p-peerstore has a "queue" package that probably doesn't belong there.

Not any more.
