### ISSUE TITLE
go get -u fails with go 1.12.5, win64

### ISSUE THREAD

**Issue by dowlandaiello** [libp2p/go-libp2p#647]
Pretty straightforward, was just updating my modules as per usual (no code changed, just a routine module update). `go get -u` (with `GO111MODULES=on` in the GOPATH) seemed to be bugging out at transport-upgrader and basic host. Logs:

```zsh
go: finding github.com/whyrusleeping/mdns latest
# github.com/libp2p/go-libp2p-transport-upgrader
R:\Go\pkg\mod\github.com\libp2p\go-libp2p-transport-upgrader@v0.0.4\upgrader.go:80:12: undefined: ipnet.ForcePrivateNetwork
# github.com/libp2p/go-libp2p/p2p/host/basic
R:\Go\pkg\mod\github.com\libp2p\go-libp2p@v0.0.30\p2p\host\basic\basic_host.go:145:32: cannot use h (type *BasicHost) as type host.Host in argument to identify.NewIDService:
        *BasicHost does not implement host.Host (wrong type for Mux method)
                have Mux() *multistream.MultistreamMuxer
                want Mux() "github.com/libp2p/go-libp2p-core/protocol".Switch
R:\Go\pkg\mod\github.com\libp2p\go-libp2p@v0.0.30\p2p\host\basic\basic_host.go:172:32: cannot use h (type *BasicHost) as type host.Host in argument to ping.NewPingService:
        *BasicHost does not implement host.Host (wrong type for Mux method)
                have Mux() *multistream.MultistreamMuxer
                want Mux() "github.com/libp2p/go-libp2p-core/protocol".Switch
```

**Comment by dowlandaiello** [comment]
Quick note: This seems like an upstream issue. Just tried `go get -u` on a super simple libp2p hello world project, same error.

**Comment by Stebalien** [comment]
Yes, this is an issue as we've made some changes to our dependencies but haven't finished bubbling them up. Please use `go get -u=patch` for now.

**Comment by hsanjuan** [comment]
hello, you can do `go get github.com/libp2p/go-libp2p-host@v0.0.3` and `go get github.com/libp2p/go-libp2p-interface-pnet@v0.0.1`. That should fix those problems (they may come up when running with `-u=patch` too depending on your project).

**Comment by raulk** [comment]
Posted a NOTICE under #649. Thanks for the patience, it’ll be worth it. For now, please follow @hsanjuan’s instructions.

**Comment by Stebalien** [comment]
Closing in favor of #649.
