### ISSUE TITLE
NOTICE: Refactor in progress — refrain from updating dependencies

### ISSUE THREAD

**Issue by raulk** [libp2p/go-libp2p#649]
We are currently landing a long-awaited refactor across all libp2p repos that will make life significantly easier for everybody 🎉 Read the details here: #602.

**This refactor will be fully backwards-compatible for 99% percent of users.**

Due to the way gomod works, and the modular nature of libp2p, this couldn’t be automated.

We are halfway through, and we hope to be finished by Monday 27th May end of day, or sooner.

Until then, please do not upgrade your go-libp2p dependencies, or if you do, only apply patch upgrades (not minor version bumps).

If starting a new project, please use gomod with go-libp2p v0.0.30.

We’ll close this issue when the build is fully consistent again.

Thank you for your cooperation. The result will be worth the tiny pain! 🙌

**Comment by postables** [comment]
It might be beneficial to disperse this across different channels. I just did a dependency update and absolutely rekt my branch :P

**Comment by raulk** [comment]
UPDATE: Codebase-wide refactor is now complete and dependency upgrades should now lead to a consistent build. It's late here and I will do a sanity check tomorrow before I close this issue.

Thanks for your patience! 🙏

**Comment by raulk** [comment]
We have now successfully verified the build is consistent and backwards-compatible. All done here!
