### ISSUE TITLE
go get go-libp2p

### ISSUE THREAD

**Issue by keyvdir** [libp2p/go-libp2p#650]
I found a combination of libp2p and mux from this respo:
https://github.com/sumantabose/go-p2p-blockchain/tree/master/01-p2p-mux

I need to make it for my school project.

But when i try to go get libp2p respo it gave me this output

<details><summary>Output</summary><br><pre>
MacbookAir13:~ macbookair13$ go get github.com/libp2p/go-libp2p
# github.com/libp2p/go-libp2p/p2p/host/routed
go/src/github.com/libp2p/go-libp2p/p2p/host/routed/routed.go:153:20: cannot use rh.host.Mux() (type "github.com/libp2p/go-libp2p-core/protocol".Switch) as type *multistream.MultistreamMuxer in return argument: need type assertion
go/src/github.com/libp2p/go-libp2p/p2p/host/routed/routed.go:190:5: cannot use (*RoutedHost)(nil) (type *RoutedHost) as type "github.com/libp2p/go-libp2p-core/host".Host in assignment:
	*RoutedHost does not implement "github.com/libp2p/go-libp2p-core/host".Host (wrong type for Mux method)
		have Mux() *multistream.MultistreamMuxer
		want Mux() "github.com/libp2p/go-libp2p-core/protocol".Switch
# github.com/libp2p/go-libp2p/p2p/host/basic
go/src/github.com/libp2p/go-libp2p/p2p/host/basic/basic_host.go:145:32: cannot use h (type *BasicHost) as type host.Host in argument to identify.NewIDService:
	*BasicHost does not implement host.Host (wrong type for Mux method)
		have Mux() *multistream.MultistreamMuxer
		want Mux() "github.com/libp2p/go-libp2p-core/protocol".Switch
go/src/github.com/libp2p/go-libp2p/p2p/host/basic/basic_host.go:172:32: cannot use h (type *BasicHost) as type host.Host in argument to ping.NewPingService:
	*BasicHost does not implement host.Host (wrong type for Mux method)
		have Mux() *multistream.MultistreamMuxer
		want Mux() "github.com/libp2p/go-libp2p-core/protocol".Switch
</pre></details>

I'm very new in Go Language and i'm using go version 
`go version go1.12.4 darwin/amd64.` 
Please help me... thank you.

**Comment by Stebalien** [comment]
See: https://github.com/libp2p/go-libp2p/issues/649.

To fix this:

0. Export `GO111MODULE=on`.
1. Run `go mod init` in that directory (`01-p2p-mux`).
3. Run `go get github.com/libp2p/go-libp2p@latest`.
4. Run `go mod tidy`.
