### ISSUE TITLE
Support Direct Connection Upgrade through Relay

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p#651]
The draft in https://github.com/libp2p/specs/pull/173 specifies a mechanism for upgrading relay connections to direct connections using hole punching.

This issue is here to track implementation changes necessary to support it
- [ ] The swarm needs to support direct dial with user-specified addresses (bypassing the peerstore), even when there is an existing relay connection
- [ ] The swarm needs to be able to prioritize direct connections over relay connections once they exist.
  The current logic picks the connection with the most streams.
- [ ] The most difficult part: multistream is an interactive protocol with a designated initiator (the outbound peer).
  This breaks with simultaneous open, which may result in both peers being the initiators.
  To make things even more complicated, we might end up with a peer accepting and a peer connecting.
  We may have to delay deployment until multistream/2.0 is ready.

**Comment by raulk** [comment]
Here's one possible adaptation to multistream 1.0 to cope with TCP simultaneous open, while keeping backwards compatibility. Let's call it _ms1.1_, although only theoretically; we can't use this ID on the wire because, go-multistream expects an _exact match_ and does not entertain multiple versions in the header.

> (Context: We've discussed poison bits (1 for initiator, 0 for responder) to short-circuit the connection in case the AND is true, but that's a backwards-incompatible change. I believe all solutions proposed until now are backwards-incompatible.)

After the initial `/multistream/1.0.0` announcement, the node believing it is the initiator signals this belief by sending what seems like an ordinary protocol selection:

```
/p2p/initiator/1.0.0/<my peer ID>
```

Various things can happen:

1. Both parties believe they're the initiator (TCP simultaneous open), and:
    a. they both support _ms1.1_, in which case each party sees the signal and they resolve the conflict by either: (a) assigning the initiator role to the highest peer ID in-band, (b) closing the connection and having the highest peer restart it.
    b. only one party supports _ms1.1_, the legacy party will error, but the upgraded party can detect this situation and restart the connection (hoping the router will keep this mapping alive in TIME_WAIT).

2. Only one party believes they're the initiator (no TCP simultaneous open), and:
    a. they both support _ms1.1_, the responder confirms by responding with `/p2p/responder/1.0.0`.
    b. only the initiator supports _ms1.1_, they'll send `/p2p/initiator/1.0.0/<my peer ID>`, but they'll simply get a `na` back. Nothing breaks.
    c. only the responder supports ms1.1, nothing special happens.

**Comment by vyzo** [comment]
I would like to avoid having to restart the conneciton, it's very complicated to implement and not certain it will work. 
But given that we will roll out the connection upgrade protocol together with the multistream upgrade, we should be ok.
So in 1i we should assign as the initiator the highest peer ID in band and not restart the connection (a).

**Comment by raulk** [comment]
@vyzo yeah, that option has higher chances of success, however it implies changes in libp2p that may break the abstractions quite a bit.

**Comment by Stebalien** [comment]
See https://github.com/libp2p/go-tcp-transport/issues/21 for a list of solutions.

**Comment by marten-seemann** [comment]
v0.16.0 shipped DCUtR support.
