### ISSUE TITLE
Figure out why MDNS is announcing port 4001

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#652]
See: https://github.com/ipfs/go-ipfs/issues/6389#issuecomment-497471285.

This is a regression (go-ipfs 0.4.20 works, 0.4.21 doesn't).

**Comment by sanderpick** [comment]
Hey @Stebalien - I've been running into this... should have looked here sooner.

I believe this is a result of the host not having any addresses set when the MDNS server starts.

```
16:45:38.479 DEBUG       mdns: Handling MDNS entry: 192.168.0.6:4001 12D3KooWGUxThtVHzfwUCjWfEhEdtjiLYhhwJ9E1aQZqTyTW764b mdns.go:155
16:45:38.480 WARNI    p2pnode: trying peer info:  {12D3KooWGUxThtVHzfwUCjWfEhEdtjiLYhhwJ9E1aQZqTyTW764b: [/ip4/192.168.0.6/tcp/4001]} discovery.go:23
```

4001 is just the default:

```
https://github.com/libp2p/go-libp2p/blob/master/p2p/discovery/mdns.go#L71
```

If I move the port acquisition into the polling logic, the host eventually has addresses and the server can be started.

**Comment by Stebalien** [comment]
Thanks for catching this!
