### ISSUE TITLE
mdns browser (lookup)

### ISSUE THREAD

**Issue by JackBekket** [libp2p/go-libp2p#658]
Hello! I want to implement mdns lookup feature in my app, could anyone kindly provide me information about how to make this? Useful link's would also be great!

I'm trying to get all mdns advertisments from router device like here: https://chrome.google.com/webstore/detail/mdns-browser/kipighjpklofchgbdgclfaoccdlghidp

**Comment by Stebalien** [comment]
The mdns library I recommend is https://github.com/grandcat/zeroconf although that still has some known race conditions. Libp2p doesn't really expose MDNS directly. Instead, it uses it internally to automatically connect to nearby nodes.

If you want to discuss this further, I recommend you ask on https://discuss.libp2p.io. You're more likely to get a response there.
