### ISSUE TITLE
p2p/net/swarm: Fails to build due to dependency vendoring dependencies

### ISSUE THREAD

**Issue by shazow** [libp2p/go-libp2p#66]
```
github.com/ipfs/go-libp2p/p2p/net/swarm $ go build
# github.com/ipfs/go-libp2p/p2p/net/swarm
./swarm.go:112: cannot use PSTransport (type streammux.Transport) as type streammux.Transport in argument to peerstream.NewSwarm:
    streammux.Transport does not implement streammux.Transport (wrong type for NewConn method)
        have NewConn(net.Conn, bool) (streammux.Conn, error)
        want NewConn(net.Conn, bool) (streammux.Conn, error)
```

Looks like `swarm.go` imports `github.com/jbenet/go-peerstream` which has its own vendored version of `streammux.Conn` which of course makes it a distinct type from the unvendored `streammux.Conn` we're expecting.

The solution would be for @jbenet to unvendor things from go-peerstreap (like go-libp2p did recently, yay) or to avoid dependencies which have vendoring policies inconsistent with this project.

**Comment by whyrusleeping** [comment]
@shazow thanks for reporting. I'll see if i can get this done.

**Comment by shazow** [comment]
My local solution was to remove the substring `github.com/jbenet/go-peerstream/Godeps/_workspace/src/` from `github.com/jbenet/go-peerstream/*.go` (then you can nuke the Godeps dir too).

**Comment by diasdavid** [comment]
This should be golden, @shazow do you confirm?

**Comment by shazow** [comment]
@diasdavid Sorry it's going to be a while before I'm back to doing IPFS stuff. I'll take your word for it, we can re-open if there are issues in the future. :)
