### ISSUE TITLE
cannot make

### ISSUE THREAD

**Issue by XinyaYang0506** [libp2p/go-libp2p#663]
Hi! 
I ```go get``` the repo and ```cd``` to the directory and then typed ```make```. However, I got error message saying that ```make: *** No targets specified and no makefile found.  Stop.``` It seems that there is no makefile. Can anyone help me on that? Thanks!

**Comment by Stebalien** [comment]
There is no Makefile, you don't need to use make. Check out the examples in https://github.com/libp2p/go-libp2p-examples.
