### ISSUE TITLE
mocknet should allow host customization via options

### ISSUE THREAD

**Issue by raulk** [libp2p/go-libp2p#673]
Mocknet uses a fixed set of host options, and it's not possible for tests to customize them, by for example changing the peerstore, the muxer, or disabling the ID service (which is superfluous for many tests, and imposes unnecessary goroutine overhead that trips up the race detector with no gain).

**Comment by marten-seemann** [comment]
mocknet is now (and has been for a quite a while) in maintenance mode. I'd consider making changes when and if there's a specific ask.

Closing this issue, since it's not actionable.
