### ISSUE TITLE
Revamp go-libp2p Release Flow

### ISSUE THREAD

**Issue by daviddias** [libp2p/go-libp2p#677]
Hi libp2p Team 👋

As you might have noticed, go-ipfs is doing a big push to re-haul its release process -- https://github.com/ipfs/go-ipfs/pull/6482 -- and we realized that in order for it to be a successful and smooth operation, we will need your collaboration. More concretely, it would be awesome to:

- Detach releases of go-ipfs from go-libp2p. This will enable go-ipfs to only worry about latest changes on go-ipfs code when performing a release
- Revamp the go-libp2p release flow and include partner testing (one of the partners being go-ipfs)
- Include some kind of semantic versioning that we can rely on (e.g. 0.0.X -> patch version, something we know we can trust and update while doing a release vs. 0.X.0 -> minor version, a warning to not update without even more rigorous and new testing)

Adopting a revamped release flow will mimic in someways the synergy that exists between [js-libp2p release flow](https://github.com/ipfs/js-ipfs/issues/2192) and [js-ipfs release flow](https://github.com/libp2p/js-libp2p/issues?utf8=%E2%9C%93&q=is%3Aissue+RELEASE+%F0%9F%9A%80+is%3Aclosed+) that enables both projects to co-exist and co-release without blocking one on the other.

How does this sound at first glance to you?

It might be better to use the next Monday sync to talk about this in more detail, nevertheless I wanted to kick off things with an issue to start planting the seeds for thought :)

**Comment by marten-seemann** [comment]
I think our current release flow captures this pretty well.
