### ISSUE TITLE
Seems private key is needed when creating a new transport, whereas the `insecure.New` function lacks that as an argument..

### ISSUE THREAD

**Issue by ZJJ1991** [libp2p/go-libp2p#678]
https://github.com/libp2p/go-libp2p/blob/15764f7bb21ae2a9095573c0acb1b331f6b74650/config/security.go#L54

Hi libp2p team,
I happen to encounter an error caused by the following code. Seems the private key is needed in order to make an insecure transport.

```
../../libp2p/go-libp2p/config/security.go:56:49: not enough arguments in call to insecure.New
	have (peer.ID)
	want (peer.ID, "github.com/libp2p/go-libp2p-core/crypto".PrivKey)
```

**Comment by Kubuxu** [comment]
Looks like https://github.com/libp2p/go-libp2p-core/pull/37 was released too early.

**Comment by ZJJ1991** [comment]
Yep, I see. The new version of `go-libp2p-core` doesn't comply to `go-libp2p`.

**Comment by raulk** [comment]
@ZJJ1991 sorry for the breakage. We moved too fast on the PR that @Kubuxu pointed out. I have now reverted the changes and made a new go-libp2p-core release: https://github.com/libp2p/go-libp2p-core/releases/tag/v0.0.9. Could you upgrade your deps and confirm that the API breakage is fixed?

**Comment by ZJJ1991** [comment]
@raulk Hi Rauk, it's not a big problem, never mind. The breakage is literately fixed now.
