### ISSUE TITLE
What are the real use cases can we try to solve with libp2p?

### ISSUE THREAD

**Issue by tirupatibg** [libp2p/go-libp2p#690]
I see in the examples that we can do have a chat with auto discovery of nodes. Other than the what would be real use cases can be solved by libp2p.

**Comment by Stebalien** [comment]
Check out:

* https://libp2p.io/
* https://github.com/libp2p/libp2p
* https://ipfs.io/ (an application built on libp2p)
* https://www.youtube.com/channel/UCBPd00n1y9AwbdFHQrO2agw

Eth2 and Filecoin are also being built on libp2p.

**Comment by Stebalien** [comment]
Let's continue this discussion on https://discuss.libp2p.io/.
