### ISSUE TITLE
How to get get the public IP and the external port of a peer when it connected to a bootstrap node

### ISSUE THREAD

**Issue by HansonYip** [libp2p/go-libp2p#692]
There were one peer A and one bootstrap peer B. Peer A was behind a NAT and peer B had a public IP. Node A used `NATPortMap`  to enable **UPNP** successfully, but when it connected to peer B, it advertised its internal IP and port to the peer B intstead of public IP (Router / NAT IP) and external port. So other peers could not connect to peer A with a valid address.

**Comment by HansonYip** [comment]
@Stebalien Hi, guy. So is this a bug?

**Comment by Stebalien** [comment]
It should advertise _both_ the private and public addresses if UPNP works.

1. How did you determine that UPNP worked? Did your router tell you?
2. What's the output of `host.Addrs()`? Those are the addresses reported by the host.

**Comment by HansonYip** [comment]
@Stebalien The UPNP information of the router showed that there was an item about libp2p as below.
![image](https://user-images.githubusercontent.com/38805685/62095091-e7d59300-b2b1-11e9-93cc-1fdc156478fe.png)

And some logs also may be a proof for that. 
```bash
10:09:38.989 DEBUG        nat: Attempting port map: tcp/6666 nat.go:174
10:09:38.998 DEBUG        nat: NAT Mapping: %!s(int=60211) --> %!s(int=6666) (tcp) nat.go:199
10:09:59.001 DEBUG        nat: Attempting port map: tcp/6666 nat.go:174
10:09:59.010 DEBUG        nat: NAT Mapping: %!s(int=60211) --> %!s(int=6666) (tcp) nat.go:199
10:10:19.010 DEBUG        nat: Attempting port map: tcp/6666 nat.go:174
10:10:19.024 DEBUG        nat: NAT Mapping: %!s(int=60211) --> %!s(int=6666) (tcp) nat.go:199
10:15:25.746 DEBUG   addrutil: InterfaceAddresses: from manet: [/ip4/127.0.0.1 /ip6/::1 /ip6/fe80::1 /ip6/fe80::10c3:a040:2eaf:6441 /ip6/fdd6:d333:6dc5:0:83c:c9f3:1a14:e1b8 /ip6/fdd6:d333:6dc5:0:511e:fae7:b82f:ee3d /ip4/10.10.1.112 /ip6/fe80::60ec:e5ff:fe45:5cb0 /ip6/fe80::3885:a5c:231f:738 /ip6/fe80::738:bd12:e09d:dc34 /ip6/fe80::aede:48ff:fe00:1122] addr.go:121
10:15:25.747 DEBUG   addrutil: InterfaceAddresses: usable: [/ip4/127.0.0.1 /ip6/::1 /ip6/fdd6:d333:6dc5:0:83c:c9f3:1a14:e1b8 /ip6/fdd6:d333:6dc5:0:511e:fae7:b82f:ee3d /ip4/10.10.1.112] addr.go:133
10:15:25.747 DEBUG   addrutil: adding resolved addr: /ip4/0.0.0.0/tcp/6666 /ip4/127.0.0.1/tcp/6666 [/ip4/127.0.0.1/tcp/6666] addr.go:64
10:15:25.747 DEBUG   addrutil: adding resolved addr: /ip4/0.0.0.0/tcp/6666 /ip4/10.10.1.112/tcp/6666 [/ip4/127.0.0.1/tcp/6666 /ip4/10.10.1.112/tcp/6666] addr.go:64
10:15:25.747 DEBUG   addrutil: ResolveUnspecifiedAddresses: [/p2p-circuit /ip4/0.0.0.0/tcp/6666] [/ip4/127.0.0.1 /ip6/::1 /ip6/fdd6:d333:6dc5:0:83c:c9f3:1a14:e1b8 /ip6/fdd6:d333:6dc5:0:511e:fae7:b82f:ee3d /ip4/10.10.1.112] [/p2p-circuit /ip4/127.0.0.1/tcp/6666 /ip4/10.10.1.112/tcp/6666] addr.go:109
```

For peer A, the ouput of `host.Addrs()` is
```bash
10:21:47.218  INFO rendezvous: [/ip4/127.0.0.1/tcp/6666 /ip4/10.10.1.112/tcp/6666] chat.go:188
```

**Comment by Stebalien** [comment]
@bigs could you look into this? We're clearly mapping the port and then _not_ advertising it. This may be a bug in:

https://github.com/libp2p/go-libp2p/blob/master/p2p/host/basic/natmgr.go#L120-L215

@HansonYip what version of go-libp2p are you using? (`go list -m all`).

**Comment by bigs** [comment]
yep, i'll dive in @Stebalien @HansonYip

**Comment by HansonYip** [comment]
@bigs @Stebalien Thank you all guys. I found what the problem was that my router is under another NAT.  Therefore `host.Addrs` didn't include the router's private IP.
Thanks again.

**Comment by Stebalien** [comment]
Ah. Yeah, libp2p can't handle double NATs yet.
