### ISSUE TITLE
Nov 18 sync up notes

### ISSUE THREAD

**Issue by diasdavid** [libp2p/go-libp2p#7]
These are the notes of the meeting had on Wed Nov 18, might be useful for more people:
- go-lib2p has two main entry points, `p2p/net/swarm` and `p2p/host`
- `host` is what is known in libp2p spec as `libp2p.Node`. Calling it `Node` is makes more sense than `host`, because ultimately, libp2p abstracts the host to enable true addressing per process
- routed host is the `libp2p.figuredItOut()` idea. The figuredItOut idea is when libp2p finds a way to contact a peer through its means (transports available, routing mechanisms, or even in the future have some machine learning to know which are the best ways to contact a peer at a given time)
- example on how to use go-libp2p right now https://gist.github.com/whyrusleeping/4fe7dd6caa090881c8c6
- go-libp2p uses gx, meaning you must install gx and gx-go
  - go get -u github.com/whyrusleeping/gx
  - go get -u github.com/whyrusleeping/gx-go

**Comment by jbenet** [comment]
- `RoutedHost` can be replaced by a clever Nat+Routing Transport
