### ISSUE TITLE
Make LibP2PVersion configurable and dedup with UserAgent

### ISSUE THREAD

**Issue by raulk** [libp2p/go-libp2p#714]
See:

https://github.com/libp2p/go-libp2p/blob/c73d2b9c8ee65326fe6c1b76a05a6b6cdcf223b9/p2p/protocol/identify/id.go#L34

As explained in the following comment introduced in #702, IPFS needs this value to stay fixed, but libp2p is an independent project and many downstream users don't care about IPFS compatibility:

```
XXX: Don't change this till 2020. You'll break all go-ipfs versions prior to
0.4.17 which asserted an exact version match.
```

Proposed path forward:

1. Deduplicate ClientVersion/UserAgent and LibP2PVersion. Right now it's not clear what the purpose of each is.
2. `LibP2PVersion` signals the go-libp2p version, and it's overridable but discouraged to do so. Only used by IPFS to force the backwards compatibility they need.
3. `UserAgent` announces the name/version of the application using libp2p. It is strongly encouraged for the application to set it, and it defaults to `LibP2PVersion` if unset.

**Comment by Stebalien** [comment]
Ok, all old nodes have been kicked off the network as SECIO has been removed. So, this can now (finally) move forward.

**Comment by marten-seemann** [comment]
This is now configurable via `identify.UserAgent`.
