### ISSUE TITLE
If we don't observe an address for 10 minutes, we stop announcing it.

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#716]
We really need to be smarter about this.

1. Identify (or some other protocol) should send _negative_ observations (I tried dialing X and failed).
2. We may want to consider _keeping_ observed addrs as long as the connection that made the observation is still open. Unfortunately, this is a bit annoying to track.

**Comment by MichaelMure** [comment]
I very much might be incorrect here, but I believe this would also avoid propagating the localhost or private IPs in the network and have everyone try to dial them.

**Comment by Stebalien** [comment]
See #436.

**Comment by marten-seemann** [comment]
This would have be solved by AutoNAT v2 (https://github.com/libp2p/specs/issues/503).
