### ISSUE TITLE
Close the peerstore

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#718]
Libp2p doesn't currently close the peerstore, this leaves a GC goroutine hanging around.

On the other hand, I'm not sure if libp2p _should_ close the peerstore if it didn't create it.

**Comment by aschmahmann** [comment]
Perhaps a related issue is that the in memory peerstore address book does not take a context, while the datastore based one does.

This combined with the lack of closing a peerstore means that the memory peerstore leaks goroutines.

**Comment by marten-seemann** [comment]
Looks like this was fixed by #1037.
