### ISSUE TITLE
conn.RemoteMultiaddr returning incomplete multiaddress for relayed connections

### ISSUE THREAD

**Issue by albrow** [libp2p/go-libp2p#723]
I'm not sure exactly how to title this issue. Let me explain what we're trying to do and what is happening.

For [0x Mesh](https://github.com/0xProject/0x-mesh) we want to be able to ban/blacklist IP addresses associated with obvious spammers/griefers. To do this, we need a way to get the IP address from a given connection. However, for relayed connections it looks like `conn.RemoteMultiaddr` is giving us incomplete multiaddresses which do not contain an IP address.

Here's some example code:

```go
for _, conn := range host.Network().ConnsToPeer(remotePeerID) {
	fmt.Println(conn.RemoteMultiaddr())
}
```

Relayed connections are being printed out as e.g., `/ipfs/16Uiu2HAkykwoBxwyvoEbaEkuKMeKrmJDPZ2uKFPUKtqd2JbGHUNH/p2p-circuit`. I would expect these multiaddresses to include the IP address of the relay host (e.g., `/ip4/18.200.96.60/tcp/60558/ipfs/16Uiu2HAkwsDZk4LzXy2rnWANRsyBjB4fhjnsNeJmjgsBqxPGTL32/p2p-circuit`).

Is this the expected behavior for `conn.RemoteMultiaddr` for relayed connections? If so, is there a way for us to get the IP address of the relay host?

**Comment by albrow** [comment]
@vyzo, @raulk recommended I ping you about this issue.

**Comment by Stebalien** [comment]
You'll need to:

1. Extract the peer ID (the one before the `/p2p-circuit`).
2. Call `host.Network().ConnsToPeer(relayID)`.
3. Walk through the addresses on the returned connections.

We do it this way because relayed connections aren't _necessarily_ bound to a specific underlying connection. For example, we may introduce connection migration in the future which would allow these relayed streams to migrate between underlying connections.

**Comment by albrow** [comment]
@Stebalien thanks! That should solve the immediate issue and allow us to get the IP address.

If you're willing to answer, I still have some follow-up questions that would help my own understanding. This is my first time encountering multiaddress that start with `/ipfs`, so forgive me if these questions are silly.

It seems odd to me that libp2p sometimes includes the IP, protocol, and port for relayed connections and sometimes does not. For example, `host.Addrs()` returns multiaddresses in the longer form (e.g., `/ip4/18.200.96.60/tcp/60558/ipfs/16Uiu2HAkwsDZk4LzXy2rnWANRsyBjB4fhjnsNeJmjgsBqxPGTL32/p2p-circuit`). We also use the longer form for dialing and advertising/peer discovery. What is the reason for this difference? Is it possible to use multiaddresses that start with `/ipfs` for dialing or peer discovery?

Also, even if the underlying connection for a relayed connection can change, it still seems like it would be possible for `ConnsToPeer(remotePeerID)` to report the full multiaddress that is _currently_ being used for the underlying connection? This is essentially what `ConnsToPeer(relayID)` is doing anyways. It reports the connections and addresses that are currently being used to communicate with the relay host. Maybe there's some implementation detail under the hood that is affecting the behavior?

**Comment by Stebalien** [comment]
> For example, host.Addrs() returns multiaddresses in the longer form.

Those are the addresses we advertise.

We do that so peers don't have to first lookup the relay before they can dial us. If we published `/ipfs/16U.../p2p-circuit`, we'd need to look up the relay peer in the DHT to dial it. However, by publishing the _full_ address, we can skip that step.

> Is it possible to use multiaddresses that start with /ipfs for dialing or peer discovery?

Yes. However, you'd need _some_ way to lookup addresses by peer ID (e.g., a DHT).

> Also, even if the underlying connection for a relayed connection can change, it still seems like it would be possible for ConnsToPeer(remotePeerID) to report the full multiaddress that is currently being used for the underlying connection?

We can't (or at least shouldn't) change the address associated with a connection after the fact. 

However, thinking about this a bit more, I'm not actually sure why we don't just return the full address. It's actually _simpler_ that way: https://github.com/libp2p/go-libp2p-circuit/pull/80

**Comment by vyzo** [comment]
I think there was some reason to not return the full multiaddr, but it elides me now; probably not a very good one.
We should just fix the address returned by circuit to be the full multiaddr, as the linked pr does.

**Comment by vyzo** [comment]
Note that using the reported relay address for blocking purposes will block all peers that use that node as a relay; not sure this is what you want.

**Comment by albrow** [comment]
@vyzo yeah that is what we want. We're going to separately add controls so that well-behaving relay hosts will not trigger the bandwidth limits. We want a way to detect misbehaving relay hosts.

**Comment by albrow** [comment]
Also thank you for your answers. I agree that it would make the most sense to just always return the full multiaddress unless you remember/find some good reason not to.
