### ISSUE TITLE
Can we run a bootstrap node Behind a NAT

### ISSUE THREAD

**Issue by rahullenkala** [libp2p/go-libp2p#725]
I am trying to create my own bootstrap node(https://github.com/BenDerPan/simple-bootstrap-node/blob/master/main.go) and make changes with this example(https://github.com/libp2p/go-libp2p-examples/tree/master/chat-with-rendezvous)

It works fine if I run bootstrap node in local network but if I run bootstrap node in different network I am getting a **I/O timeout error** 

Note :I added libp2p.NATPortMap to the new constructor in both programs 

@upperwal @Stebalien  @whyrusleeping

**Comment by Stebalien** [comment]
You _can_, in theory, run the bootstrap node behind a NAT as long as:

1. That node is able to configure its router to forward ports.
2. That node is able to accurately determine it's external IP address (e.g., the router doesn't lie).
3. The nodes boostrapping off of this NATed bootstrap node know a static, reliable, public address for this bootstrap node.

However, I'm guessing that your router _isn't_ forwarding ports when asked. Alternatively, NAT port mapping can take seconds to minutes. If you start the bootstrap node and then try to use it immediately, it may not yet be reachable.

Regardless, please ask questions on https://discuss.libp2p.io. The issue trackers are for bug reports and questions often get ignored.
