### ISSUE TITLE
Does dht.FindProviders() have bug?

### ISSUE THREAD

**Issue by hyunsooda** [libp2p/go-libp2p#728]
A user can announce own's existence using dht.Provide().

Let's say 2 users are connected to each other and one user exit the network so there is only one user in the network currently. 
The user out of network cannot announce own's existence using dht.Provide() itself because own's process is not running. yes this is very definite, but the user existed in the network is calling dht.FindProviders() and it returns the information of user leaved repeatedly.
This is very strange point... why the user leaved send repeatedly?

How can I turned off sending the announce from the user leaved?...

**Comment by aschmahmann** [comment]
When a user does a `dht.Provide` that record persists for 24hrs unless it's replaced with another record from that user (e.g. one that has the same peerID, but a different multiaddress).

In general DHT delete is hard/problematic: See https://discuss.ipfs.io/t/how-to-update-dht-after-garbage-collection/1417 and other DHT delete issues on Github for more info.

> why the user leaved send repeatedly

This is not happening even if the providing node is turned off that provider record will still persist for 24 hrs.

**Comment by hyunsooda** [comment]
Thanks for replying :)

In your Last statement, 

> This is not happening even if the providing node is turned off that provider record will still persist for 24 hrs.

Isn't that bug? it doesn't make sense that dead node still send his existence to his connected nodes.
Anyway, you meant that I should remove the dead peers manually if I don't want to get any message from dead node? It's really not good solution.

**Comment by Stebalien** [comment]
> Isn't that bug?

There's no good alternative:

* The disconnecting node can't really do anything. Usually, nodes disconnect because they go offline and they _usually_ can't perform some kind of expensive disconnect operation.
* Periodically checking provider records to see if the provider is still there would be prohibitively expensive.
* Peers _using_ provider records could proactively tell peers _hosting_ provider records that the record is no longer valid (the peer is offline). However:
   * That error may be ephemeral (the peer may come back online soon).
   * This could easily be abused as there's no way to _prove_ that the provider is offline.

There _are_ solutions to this problem but they'll likely require incentives (e.g., money, blockchains, etc.) and/or reputation.

**Comment by raulk** [comment]
Sidenote: even if the provider continued to be online, you might not be able to connect to it, e.g. maybe it's behind a (geographical) firewall, or you don't have a route to them, or there's a routing incident along the way.

It's hard to implement consistent data stores in a p2p fashion. Eventual consistency is the norm, with mechanisms to confirm validity of a record. In this case, that mechanism is finding and connecting to the peer.

**Comment by hyunsooda** [comment]
Hi @Stebalien . Thanks for kind replying :)

In the paper, Kademlia Protocol, the base of your library, Says that each node send ping packet to his friends periodically and this is called '**refresh**' in the paper.

You said two key points, one is expensive operation and another is to saying the dead peer send a FIN packet to alive nodes that he knows by searching DHT table.

Last point is actually impossible because dead node never guarantees that he send FIN packet before dying. for example, in case of interrupt like CTRL+C, it is possible but there are more case we don't know than it.

In the first point, I don't know why you think sending ping packet(**Refresh**) periodically is expensive.
The paper no says about this. Can you explain the reason?

Sorry for my English

**Comment by raulk** [comment]
@hyunsooda PING packets are used to check for liveness of **peers in the routing table**, not of provider records. Current libp2p transports reliable ones (TCP, QUIC), which perform keepalives and notify the application when the connection is terminated. Therefore we don't need PING packets like you do in UDP.

Even if we repurposed PINGs to check liveness of providers, single observations of connectivity are not enough:

1. What if the node that's checking the provider record is behind a firewall themselves, i.e. the provider is connectable, just not _from them_.
  * The DHT is a collaborative data structure; even if _you_ aren't able to connect to a given peer, others may be.
2. What if the provider had a short connection glitch?
  * The cost of coordinating the removal and re-addition of provider records is non-negligible.
3. Popular providers will get swamped in PING traffic.

Solutions for a p2p network to come to consensus about peer routability and availability are complicated.

**Comment by marten-seemann** [comment]
Closing. I don't think there's anything actionable here.
