### ISSUE TITLE
Upgrade all go-libp2p-* modules to go1.13

### ISSUE THREAD

**Issue by raulk** [libp2p/go-libp2p#736]
[Halloween 🎃 brought us go1.13.4](https://groups.google.com/forum/#!topic/golang-nuts/rkSaxR1oz0c).

It's time to upgrade our builds to go1.13 🚀 

If there's a reason not to, please raise it within 24h on this issue.

**Comment by Stebalien** [comment]
Because it's a lot of work? I mean, it makes sense to bump the minimum version on a per-module basis as-needed. But we probably don't need to do it up-front.

**Comment by Stebalien** [comment]
FYI, https://github.com/0xProject/0x-mesh/issues/480

**Comment by Stebalien** [comment]
Ok, I updated CI as we were getting some failures due to needing 1.12 and I didn't want to do this twice.
