### ISSUE TITLE
Need to know if a stream handler was set.

### ISSUE THREAD

**Issue by Jorropo** [libp2p/go-libp2p#745]
I'm making a new test protocol, `webrtc-aside` the goal is to use any stream and upgrade it to webrtc, (it simply use stream for sdp exchange) so it would be instantly compatible with relay, ws, ...

The only problem is finding stun server but I'm still thinking to it.

The problem is if 2 listen are made the second one overide the first (stalling the first, (and a close of the first would stall the second)) but I want listen to return an error if there is already an stream handler.
So I want `AddHandler` (or a new func `AddHandlerSafe` avoiding a refactor) to return error if there is already an stream set (and not setting the new handler).
It also need to be TOCTOU free, so adding a func `IsHandlerSet` might be usefull else where but not in this case.

**Comment by Stebalien** [comment]
Why do you need to dynamically register stream handlers? Can you not register a single stream handler for your protocol when the application starts?

**Comment by Jorropo** [comment]
Its because this is an libp2p transport and I must start the handler in the listen func wich may get called multiple times (I can't just register in the NewTransport because that can lead to memory leak (with some conn never been accepted)).
As @vyzo said I switched to the use of sync ([resync](https://github.com/matryer/resync)) the creation of the listener use `Do` and the Close `Reset` that work even if that pretty.
