### ISSUE TITLE
host.Connect will say it is connected to a peer even when it is not

### ISSUE THREAD

**Issue by SamTS** [libp2p/go-libp2p#750]
Sometimes when calling host.connect(ctx, peer) it will return with no errors even when there is no way the host is connected to the peer, such as when the computer's internet is turned off. This does not occur every time but will happen now and again if connection are tried close to network connectivity being toggled back and forth.

**Comment by marten-seemann** [comment]
@Stebalien's last comment seems to be the best solution for this problem. Really, in _any_ network, you can never guarantee that the machine you're speaking with didn't go down.
