### ISSUE TITLE
port mapping issue with nat behind nat

### ISSUE THREAD

**Issue by optman** [libp2p/go-libp2p#769]
I don't see any reason to use observed address instead of router WAN address here!

https://github.com/libp2p/go-libp2p/blob/28d32bb06751c569a63aef1b3d35cf15c49d06d3/p2p/host/basic/basic_host.go#L736

https://github.com/libp2p/go-libp2p/blob/28d32bb06751c569a63aef1b3d35cf15c49d06d3/p2p/host/basic/basic_host.go#L748

If WAN address is not a public address,  it will be a internal router in most case i think. If you use the outer router WAN address( the observed address) and internal router mapped port combination as listen address,  it wouldn't work! Even worse, it will prevent the hosts behind the outer router to access the hosts behind the internal router. 

It is not unusual NAT inside a big NAT. So please don't check WAN public addressable here, just use it,  then all hosts behind the same big NAT will be happy connected, at least.

**Comment by Stebalien** [comment]
So, this hack is there to explicitly deal with crappy routers that report the wrong external address (e.g., my tp-link which reports its internal address).

We can probably just announce both addresses. Want to file a patch for that?
