### ISSUE TITLE
DHT should be part of `go-libp2p` instead of `go-ipfs`

### ISSUE THREAD

**Issue by vasco-santos** [libp2p/go-libp2p#773]
Taking into account the objective of creating interop tests for `libp2p`, as well as for `libp2p-kad-dht` and my current focus on creating DHT interop tests on `IPFS` [interop#36](https://github.com/ipfs/interop/pull/36), I noticed that the DHT in `JS` land is a piece of `js-libp2p`, while in `GO` land, the DHT is used directly by `go-ipfs`, and not through `go-libp2p` [go-ipfs/core/core.go#L514](https://github.com/ipfs/go-ipfs/blob/30414a4c3458123fc22bb835aca07518f315e866/core/core.go#L514).

This does not feel right to me since the DHT is a really important part of  `libp2p` and considering our focus on interop tests, as well as creating testbed scenarios, we must have the DHT available in `libp2p`.

I found a really old issue [go-libp2p#56](https://github.com/libp2p/go-libp2p/issues/56) for tackling this, and what happened was to remove the implementation of the DHT from `go-ipfs` to a specific module, but keeping its use directly on `go-ipfs`.

Is there anything blocking this?

cc @bigs @Stebalien @diasdavid

**Comment by marten-seemann** [comment]
The DHT is currently living in https://github.com/libp2p/go-libp2p-kad-dht, so this is resolved (?).
