### ISSUE TITLE
Don’t add NAT’d peers to the Routing Table

### ISSUE THREAD

**Issue by jacobheun** [libp2p/go-libp2p#782]
## Design notes

- When adding an inbound node (inbound connection) to the routing table, perform the following tests, in this order:
    1. Reject the peer if it advertises relay addresses, or only private/localhost addresses.
        - Consider running a separate local-only DHT.
    2. Optionally, try dialing them back. We should rely on AutoNAT as our first choice, and only switch to this version if that isn't sufficient. Add a feature flag (option) to enable this feature.
        - The simplest approach to conduct a dial to a peer that we’re already connected to is to use a secondary libp2p host, like go-libp2p-autonat-svc does.
- (Optional) Enable the AutoNAT service on all nodes by default (with rate limits).
(requires Reliable AutoNAT)

## Testing mechanics

Testing with the code from the disjoint lookups and correctly terminating queries, dial up the number of undialable nodes to 95% and make sure everything works.

## Success Criteria
Content and peer routing work when 90% of the network is undialable.

**Comment by aarshkshah1992** [comment]
There are some ideas in this paper that _could_ be of help when we get to this. I'll make sure to come up with a proposal based on the paper when we start working on this.

https://www.researchgate.net/publication/224602685_Connectivity_properties_of_Mainline_BitTorrent_DHT_nodes
