### ISSUE TITLE
Network forming for DHT testing

### ISSUE THREAD

**Issue by jacobheun** [libp2p/go-libp2p#783]
## Design notes

-   Form a stable network we can test against.
-   Approaches:
    -   **(pre-verify)** Test on a larger network with a larger K and a larger connection limit.
        1.  Answer the question: was the partitioning we had observed previously a by-product of testing against small networks?
    -   **(preferred)** Starting with two parameters: preseed and a % of peers to connect to, form a random network.
        1.  Report to the sync service, on a pre_initialize barrier. Get the seq number.
        2.  Seed PRNG from preseed + seq.
        3.  Generate our private key from the seed.
        4.  Start the libp2p host and report to the sync service under the Peers subtree.
        5.  Wait for all other peers to report to the sync service.
        6.  With the PRNG.Next(), you pick as many nodes as % (subset to connect to).
        7.  Connect to those peers.
        8.  Run DHT Bootstrap.
    -   (possibly combined with the previous approach) Test gradual network forming. For each node (or for 1, 2, 4, 8, etc...).
        1.  Start it.
        2.  Connect to a random node.
        3.  Bootstrap/refresh routing table.
        4.  Repeat.
        5.  Importantly; _don't_ connect all nodes to bootstrappers, wait for all nodes to finish, _then_ refresh.

    -   Test procedurally forming a good kademlia network (connect to the K closest peers, etc.).

## Testing mechanics

-   Repeatedly run DHT queries and the connection manager and verify that we can still perform queries.

## Success criteria

-   We are able to form a stable network that doesn't have lone, poorly connected nodes or partitions.

We can either reliably generate stable networks like this_or_ have a set of seeds/pre-defined stable networks on which we can test subsequent epics.

**Comment by aschmahmann** [comment]
I'm currently doing some investigating of this as part of doing some debugging via the FindPeers DHT test.

A couple notes based on what I've implemented so far:
1) Generating the private key from the seed requires either doing some hackery (e.g. messing with the first few bits of randomness fed into the RSA key generator) or using Elliptic Curve Keys instead of RSA
    - https://github.com/libp2p/go-libp2p-examples/issues/20
2) The `Connect` function currently errors during a failed dial. We either need to allow failed dials or intentionally not perform dials against peers that are supposed to be undialable.
    - If we decide the latter then we need to be able to figure out from a peerID (or an explicit sync service value) whether the peer should be dialable or not.

**Comment by jacobheun** [comment]
Closing this as we've been able to reliably test with 1k+ nodes in https://github.com/ipfs/testground
