### ISSUE TITLE
Autorelay should listen to AutoNat events rather than polling

### ISSUE THREAD

**Issue by willscott** [libp2p/go-libp2p#806]
currently, [autorelay](https://github.com/libp2p/go-libp2p/blob/master/p2p/host/relay/autorelay.go#L97) polls autonat status for changes.

[AutoNat](https://github.com/libp2p/go-libp2p-autonat/blob/master/autonat.go#L78-L80) now emits changes on the event bus, and watching events should be preferred to polling.

**Comment by marten-seemann** [comment]
It doesn't any more. Not sure when we actually fixed this.
