### ISSUE TITLE
Respect mux.ErrReset in all Multiplexer implementations.

### ISSUE THREAD

**Issue by Wondertan** [libp2p/go-libp2p#814]
## Background
Currently, relying on `mux.ErrReset` is not helpful and even useless, while cases for handling it do exist. Allmost all the `mux.MuxedStream` implementations return their own errors after `Reset()` or any internal connection issues:
* [QUIC](https://github.com/lucas-clemente/quic-go/blob/master/interface.go#L121)
* [yamux](https://github.com/libp2p/go-yamux/blob/master/const.go#L63)
* [mocknet](https://github.com/libp2p/go-libp2p/blob/master/p2p/net/mock/mock_stream.go#L32)

Only `mplex` [returns](https://github.com/libp2p/go-mplex/blob/master/stream.go#L115) `mux.ErrReset`, but that forces `go-mplex` to depend on `go-libp2p-core` (libp2p/go-yamux#6)

In addition, it might be helpful to define `mux.ErrClosed` to be returned on `Write()` after `Close()`, but it seems irrelevant cause of libp2p/go-libp2p-core#10

## Resolving
All the listed multiplexers(except `mocknet`) have libp2p wrappers based in their own repos, so the solution is to redefine stream types in libp2p wrapping repos with checks of internal reset error to be replaced with `mux.ErrReset`, while `mocknet` may use it directly.  Also, muxer testing suite should be updated to test for `mux.ErrReset`.

**Comment by Stebalien** [comment]
All merged. Thanks!
