### ISSUE TITLE
The Identify/push/delta protocols are async and racy

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#823]
We broadcast updates async so the other side could end up processing them in any order. We need to serialize updates per-peer.

Additionally, if we're going to support both identify delta and identify push, we should use identify push to send protocol update events when identify delta isn't supported. To do this, we should:

1. Have a single loop subscribing to address + protocol updates.
2. Send at most one update to a peer at a time (e.g., by having one on-demand worker per peer).
3. If we receive one or more update events while sending an update to a peer, we should aggregate these updates.

**Comment by aarshkshah1992** [comment]
For posterity

> We broadcast updates async so the other side could end up processing them in any order. We need to serialize updates per-peer.

**The race is as follows:**
* We detect an address change(by polling the host addresses every minute) and a local protocol update (by listening to `EvtLocalProtocolsUpdated` on the event bus) almost "simultaneously".
* The address change makes us push a snapshot of our current Identify state on the `IDPush` protocol.
* The protocol update makes us push a list of protocols we have added/removed on the `IDDelta` protocol.
* The handler for the `IDPush` protocol on the reciving peer overwrites the protocols for the sending peer by calling `Peerstore().SetProtocols`. 
* If it so happens that the Identify state on the `IDPush` protocol contains the "stale" protocols (the one before the `EvtLocalProtocolsUpdated` was fired) but are processed/written to the peerstore by the receiving peer AFTER the protocols sent by `IDDelta`,  the receiving peer will end up with a stale state of the protocols that the sender supports.

**Comment by aarshkshah1992** [comment]
This change needs to be made agains https://github.com/libp2p/go-libp2p/pull/747 because of the dependency on the `EveLocalAddressChanged` event.

**Comment by aarshkshah1992** [comment]
@Stebalien Let's get this on for 0.6 ?

**Comment by aarshkshah1992** [comment]
@jacobheun Give that both we now plan to support Signed records in the DHT, getting this in as part of 0.6 is important.

**Comment by aarshkshah1992** [comment]
### Proposal to solve races between Identify, Push and Delta.
---
### Phase 1: Solve race between Push and Delta:
  * We introduce per-peer state which includes the "last Identify message" sent to the peer and a buffered channel that we can write address and protocol change events to.
* We have an event-loop/mono-routine that guards the above mentioned state and reacts to events coming on the channel for that peer.
* After reading a message from the channel:
     * If it's an address change event:
          * We construct a Push message **using the peerstore**(not the contents of the event).
          * Open a Push stream and send the message to the other peer.
          * After the message has been successfully read & consumed by the other side(`helpers.FullClose(s)`), we update the "last Identify message" state and free the event loop.
     * If it's a protocol change event:
          *  We construct a Delta message by doing a diff between the "last Identify message" state AND the protocols supported by us in the peerstore.
          * Open a Delta stream and send the message to the other peer.
          * After the message has been consumed by the other side, we apply the Delta to the "last Identify message" state to update it and free the event loop.

**Initiation and Cleanup**:
    * We initialise the per-peer state, buffer channel and event loop when we make our "first connection" to the peer by hooking onto to the Swarm Connectedness event that the IDService already listens to.
  * We cleanup all these per-peer allocations when we lose connectivity with the peer by listening to the Swarm Disconnected event.

**Comment by Stebalien** [comment]
> We introduce per-peer state which includes the last Identify/Push message sent to the peer and a buffered channel that we can write address and protocol change events to.

A simple signal channel (`chan struct{}` with a buffer of 1) should be enough. Or we could have one for address updates, and one to signal protocol updates.

> Thus, an Identify response usually wont be "blocked" by Push and Delta pushes.

Getting multiple connections isn't actually all that hard, unfortunately. For example:

1. Peer 1 notices a disconnect, and creates a new connection.
2. Peer 2 hasn't yet noticed the disconnect so it sees two connections.
3. Peer 1 identifies the new connection.
4. Peer 2 pushes an update.

I agree that races like this won't happen _all_ that frequently and an exclusive lock may be fine. But I'd like to avoid it if possible.

> Phase 2: Solve race between Identify and Phase1:

My lock-free solution: If identify-push/delta race with an identify request, make sure that:

1. We don't send any _additional_ identify-push/delta data until we're done responding to the identify request.
2. We respond to the identify request with the _same_ state we're pushing (not newer, not older).

If we do that, it won't matter in which order the peer gets the information because it'll be identical either way. Furthermore, if we _have_ newer data, we'll just push it once we finish responding to the identify request.

Possible design:

1. Keep a "last identify state" variable and guard it under a read/write lock.
2. Before sending an identify-push/delta, update this state under a write-lock. This will block on any in-progress identify responses.
3. When responding to an identify request, if we've already sent or started sending a push/delta, take the _read_ lock, send the last-pushed identify state, and release the read lock once the stream is fully closed.

Does this sound reasonable? I'm not the one implementing it so I'll trust your judgment.

**Comment by aarshkshah1992** [comment]
This has been released in #907 .
