### ISSUE TITLE
Address is not right when using 0.0.0.0 in windows 10

### ISSUE THREAD

**Issue by lzxm160** [libp2p/go-libp2p#825]
windows 10 with go version 1.13.5,run the following test:
```
func TestAddress(t *testing.T) {
	opts := []Option{
		ListenAddrStrings("/ip4/0.0.0.0/tcp/0"),
	}
	host, err := New(context.Background(), opts...)
	fmt.Println(host.Addrs(),":",err)
}
```
the returned address will be 169.254.*.* that's not the real address

**Comment by lzxm160** [comment]
I will try to fix later

**Comment by Stebalien** [comment]
That's the address it's getting from your system. It is a real address, it's just an automatic private IP address.

Is your system IPv6 only? If so, you need to listen on `/ip6/::/tcp/0`.

**Comment by lzxm160** [comment]
> That's the address it's getting from your system. It is a real address, it's just an automatic private IP address.
> 
> Is your system IPv6 only? If so, you need to listen on `/ip6/::/tcp/0`.

no,I test this with ubuntu,the result is right,but in windows it's generated 169.*.*.*,
it should be the right address instead of generated

**Comment by Stebalien** [comment]
Libp2p isn't making up addresses, it's getting them from the OS. If you need help debugging this issue, we'd be happy to help on https://discuss.libp2p.io.

(we can reopen this issue if it turns out to be a bug in libp2p but that seems unlikely)

**Comment by lzxm160** [comment]
> Libp2p isn't making up addresses, it's getting them from the OS. If you need help debugging this issue, we'd be happy to help on https://discuss.libp2p.io.
> 
> (we can reopen this issue if it turns out to be a bug in libp2p but that seems unlikely)

I found the reason,because my laptop have some disabled network cards.
Is there any filter to remove those ips?

**Comment by Stebalien** [comment]
1. You could explicitly listen on the IP addresses you care about.
2. You could filter the addresses you advertise by passing an ["address factory"](https://godoc.org/github.com/libp2p/go-libp2p#AddrsFactory)
