### ISSUE TITLE
Hit >80% code coverage on all libp2p packages

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p#83]
Similar to https://github.com/ipfs/go-ipfs/issues/3053 we want to have _really good_ test coverage on libp2p. Its the core on which ipfs and other future applications rest, and if libp2p doesn't work, the apps on top of it don't stand much of a chance. Here is a list of all the libp2p package (in this repo and outside of this repo) that we need to have coverage for:
- [ ] github.com/ipfs/go-libp2p/p2p/discovery
- [ ] github.com/ipfs/go-libp2p/p2p/host
- [ ] github.com/ipfs/go-libp2p/p2p/host/basic
- [ ] github.com/ipfs/go-libp2p/p2p/host/routed
- [ ] github.com/ipfs/go-libp2p/p2p/metrics
- [ ] github.com/ipfs/go-libp2p/p2p/metrics/conn
- [ ] github.com/ipfs/go-libp2p/p2p/metrics/stream
- [ ] github.com/ipfs/go-libp2p/p2p/nat
- [ ] github.com/ipfs/go-libp2p/p2p/net
- [ ] github.com/ipfs/go-libp2p/p2p/net/conn
- [ ] github.com/ipfs/go-libp2p/p2p/net/conreq
- [ ] github.com/ipfs/go-libp2p/p2p/net/filter
- [ ] github.com/ipfs/go-libp2p/p2p/net/mock
- [ ] github.com/ipfs/go-libp2p/p2p/net/swarm
- [ ] github.com/ipfs/go-libp2p/p2p/net/swarm/addr
- [ ] github.com/ipfs/go-libp2p/p2p/protocol
- [ ] github.com/ipfs/go-libp2p/p2p/protocol/identify
- [ ] github.com/ipfs/go-libp2p/p2p/protocol/ping
- [ ] github.com/ipfs/go-libp2p/p2p/protocol/relay
- [ ] github.com/ipfs/go-libp2p/p2p/test/backpressure
- [ ] github.com/ipfs/go-libp2p/p2p/test/reconnects
- [ ] github.com/ipfs/go-libp2p/p2p/test/util
- [ ] github.com/ipfs/go-libp2p/testutil
- [ ] github.com/ipfs/go-libp2p/testutil/ci
- [ ] github.com/ipfs/go-libp2p/testutil/ci/jenkins
- [ ] github.com/ipfs/go-libp2p/testutil/ci/travis
- [ ] github.com/ipfs/go-libp2p-peerstore
- [ ] github.com/ipfs/go-libp2p-peer
- [ ] github.com/ipfs/go-libp2p-loggables
- [ ] github.com/ipfs/go-libp2p-crypto
- [ ] github.com/ipfs/go-libp2p-secio
- [ ] github.com/ipfs/go-libp2p-transport

**Comment by zjiekai** [comment]
Hi, I'm trying to run test.

In the code package imports are prefixed with `github.com/libp2p/go-libp2p`. Why not `github.com/libp2p/go-libp2p`? What am I missing?

Here is what I am referring to https://github.com/libp2p/go-libp2p/blob/master/p2p/discovery/mdns.go#L18

**Comment by zjiekai** [comment]
There seems to be both `github.com/ipfs/go-libp2p` and `github.com/libp2p/go-libp2p`?

**Comment by whyrusleeping** [comment]
We're in the middle of moving the libp2p code from the ipfs org to the new
libp2p org. Each package has to be moved manually and updated, we just
haven't gotten around to it yet. This doesn't currently cause any problems
for the code

**Comment by zjiekai** [comment]
It's probably my lack of experience with golang getting me really confused.  

Should I wait for the transition settled? Or should I just make a copy and edit the code in `$GOPATH/src/github.com/libp2p/go-libp2p`? Or are there some magic that make the `go` command work? I'd really like to learn the trick to run the code if that's not too much trouble.

There will be a a talk about IPFS in devcon in China.  I'm trying to get started so if I get a chance to meet the IPFS guys I can ask some meaningful questions

**Comment by whyrusleeping** [comment]
@zjiekai did you get it working? If you provide me with the error messages of things going wrong I can be more helpful

**Comment by whyrusleeping** [comment]
@zjiekai also, an aside, i'm super excited for DEVCON 2 :)

**Comment by whyrusleeping** [comment]
To run the tests for go-libp2p, i would do the following:

First, get the code and deps:
```
go get -d github.com/libp2p/go-libp2p
cd $GOPATH/src/github.com/libp2p/go-libp2p
make deps
gx-go rewrite
```

Now, you're set to run the tests, to run *all* of them, do:

```
go test ./...
```

To run tests for a specific package, do:

```
go test ./p2p/net/swarm
```

You can add `-v` for more verbose information, and `-cover` for code coverage information:

```
go test -v -cover ./...
go test -v -cover ./p2p/net/mock
```

you can also generate html coverage reports by doing:

```
go test -v -coverprofile=cover.out ./p2p/net/swarm
go tool cover -html=cover.out
```


Let me know if i missed anything!

**Comment by zjiekai** [comment]
@whyrusleeping It's working now.  Thank you for the detailed write up. Super helpful!

**Comment by whyrusleeping** [comment]
@zjiekai awesome! Please let me know if you run into any other issues or have any questions

**Comment by petroav** [comment]
I'd like to contribute to this effort. Just opened https://github.com/libp2p/go-libp2p-loggables/pull/21 to kick things off. Anything I should keep in mind while writing tests? Special mocking frameworks you use or general guidelines I should follow?

I'll start with the utilities/miscellaneous repos as they're generally less intimidating and I'll open issues in the respective repos if I have questions.

**Comment by Stebalien** [comment]
We generally just use the standard go testing library without any additional testing frameworks. The best way to learn how we write tests is to look at the tests in `go-libp2p-swarm`, `go-libp2p-kad-dht`, and `go-libp2p-transport`.

**Comment by Stebalien** [comment]
This issue hasn't really helped motivate us to improve test coverage, although test coverage has been steadily getting better. So I'm going to close it.
