### ISSUE TITLE
EventBus subscribe/emit options are inconvenient to use

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#837]
At the moment, the event bus interface lives in go-libp2p-core but the subscription options all live in go-eventbus. This is mildly frustrating to use because one needs to import _both_ to pass any options (e.g., buffer sizes).

We should consider one of:

1. Moving the event bus to go-libp2p-core.
2. Making go-libp2p-core depend on the event bus and re-export the options.
3. Moving the subscribe/event options into go-libp2p-core.

**Comment by marten-seemann** [comment]
They now all live in the go-libp2p mono-repo.
