### ISSUE TITLE
Clarify subsystem configuration structure

### ISSUE THREAD

**Issue by willscott** [libp2p/go-libp2p#845]
Currently, several subsystems of libp2p (namely autorelay, the DHT, and autonat), are individually configured, and aren't exposed from libp2p with a single mental model.

For instance, we currently have a single option to "EnableAutoRelay", along with a mode "hop vs discovery".

Instead, it might be more understandable to expose options in the following way:
* `HostReachability` (default: Discover, options: Discover, Unreachable, Reachable).
* `NATService` (default: Off, options: Off, WhenReachable, On)
* `DHTService` (default: WhenReachable, options: Off, WhenReachable, On)

**Comment by Stebalien** [comment]
> * NATService (default: Off, options: Off, WhenReachable, On)
> * DHTService (default: WhenReachable, options: Off, WhenReachable, On)

I believe we can actually simplify both of these to "off" or "on" where "on" always means "when reachable". Then it's up to the user to specify "reachable", "unrachable", "detect".

**Comment by willscott** [comment]
The configuration for these has continued to evolve. closing this issue as obsolete
