### ISSUE TITLE
identify: flaky TestLocalhostAddrFiltering

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#854]
```
--- FAIL: TestLocalhostAddrFiltering (0.06s)

    id_test.go:268: expected one addr, found [/ip4/1.2.3.4/tcp/1234 /ip4/127.0.0.1/tcp/2345]
```

**Comment by willscott** [comment]
it appears that the underlying trigger here is a test which is spinning up two nodes, both on localhost, and both believing they have a localhost and a 1.2.3.4 address. When the underlying connection is made between the nodes, the connection should be made only between their 1.2.3 addresses, but it appears the nodes are seeing when they look at the conn that `conn.RemoteMultiaddr()` is a 127.0.0.1 address.

**Comment by willscott** [comment]
underlying issue is that the mocknet is choosing the link to actually use randomly

https://github.com/libp2p/go-libp2p/blob/master/p2p/net/mock/mock_peernet.go#L152

**Comment by aarshkshah1992** [comment]
Have skipped the test for now in this PR:

https://github.com/libp2p/go-libp2p/pull/747.

**Comment by Stebalien** [comment]
H

**Comment by marten-seemann** [comment]
It doesn't seem to flake any more: https://marcopolo.github.io/FlakyTests/.
