### ISSUE TITLE
Racy use of goprocess in host constructor

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#862]
In the host constructor, we construct a process that's auto-closed when the context is canceled. However, if the context is canceled before the constructor returns, we might try to close the process before we're done constructing the host. We need to reorder the logic in the basic host constructor to avoid this case.

**Comment by aarshkshah1992** [comment]
@Stebalien I'm inclined to just remove the use of goprocess here. Lmk if you think there's a solid reason to keep it around or I'll come up with a PR to get rid of it.

**Comment by Stebalien** [comment]
I'd love to get rid of it if we can do it without opening a huge can of worms...

**Comment by aarshkshah1992** [comment]
Merged.
