### ISSUE TITLE
Rename WithReachability option

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#874]
This option _did not_ pass the "wtf is this thing" test with @daviddias. We should consider calling it something like `ForceReachability` or even `AssumePublic`/`AssumePrivate`, ... I'm not sure. Just something else.

Thoughts @willscott?

**Comment by daviddias** [comment]
Just leaving my suggestion here, given that AutoNAT is a subsystem (AFAIK), I propose that it is something like libp2p.AutoNatAssumePublic or similar (as long as AutoNat is in the name) so that the reader and developer knows which subsystem consumes this option.
