### ISSUE TITLE
Libp2p does not recover due to dial backoff and context deadline exceeded

### ISSUE THREAD

**Issue by lightshine001** [libp2p/go-libp2p#879]
I have setup two peers A/B to connect by using libp2p.
Firstly, two peers A/B can connect each other. However, after I reboot peer B，peer B can't connect A successfully ever, with error dial backoff and context deadline exceeded. I have tried many times, and see same error msg.
The version is following.
	github.com/libp2p/go-libp2p v0.0.28
	github.com/libp2p/go-libp2p-crypto v0.0.2
	github.com/libp2p/go-libp2p-host v0.0.3
	github.com/libp2p/go-libp2p-net v0.0.2
	github.com/libp2p/go-libp2p-peerstore v0.0.6
![image](https://user-images.githubusercontent.com/9333725/78863135-6f8fb600-7a6b-11ea-8e2b-541b5b8f3aab.png)

![image](https://user-images.githubusercontent.com/9333725/78863104-630b5d80-7a6b-11ea-9ac2-61f20cf838db.png)

**Comment by Stebalien** [comment]
go-libp2p has changed quite a bit since v0.0.28 (released over a year ago at this point). Please open a new issue if this bug is still present in the latest release.
