### ISSUE TITLE
Swarm is producing a connection with remote IP the unspecified IPv6 address

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p#886]
While debugging the IP address tracking in gossipsub v1.1 (hardened edition) I ran into a very odd gremlin.
For every connection to a peer (with an actual IPv4 address), there was a second connection with the remote IP address reported as the unspecific IPv6 address (`::`).
This should be impossible in theory, and it caused quite a bit of grief.
We need to investigate how this is happening and fix the issue.

**Comment by Stebalien** [comment]
Which transport? What was the local IP?

**Comment by vyzo** [comment]
TCP; the other IP reported was an IPv4 at the 100.96.x.x range (lots of occurrences).

**Comment by vyzo** [comment]
the local IP is not known, I didn't keep track of it in my logging.

**Comment by vyzo** [comment]
I think this my be a bug in my own end, trying to demystify.

**Comment by vyzo** [comment]
I am pretty certain it was my bug at this point.
