### ISSUE TITLE
mdns doesn't working on windows

### ISSUE THREAD

**Issue by godcong** [libp2p/go-libp2p#894]
https://github.com/hashicorp/mdns/issues/51

this project looks not maintained.
and it has many bug wasn't fixed
the mainest is its can't works fine in windows

i tested this fork
https://github.com/micro/mdns
it works fine in the windows

perhaps,your team can merged it into the project

**Comment by Stebalien** [comment]
@aarshkshah1992 if you have a moment, could you look into this library? At a glance, it looks like it fixes several issues we have (e.g., it shares the 5353 port with other listeners).

**Comment by phanirithvij** [comment]
That repo no longer exists.

**Comment by godcong** [comment]
Any one following this?
Has this problem been solved? Still not resolved?

**Comment by Stebalien** [comment]
We're switching to grandcat/zeroconf pending https://github.com/grandcat/zeroconf/pull/100 and https://github.com/grandcat/zeroconf/pull/93.
