### ISSUE TITLE
Allow peerstore to write to a go-datastore

### ISSUE THREAD

**Issue by csasarak** [libp2p/go-libp2p#90]
I am working with @whyrusleeping to allow peerstore data to be stored to the hard disk when it takes up a certain amount of space as described in go-ipfs issue [#2484](https://github.com/ipfs/go-ipfs/issues/2848)

I'm opening this issue to discuss adding support for the go-datastore interface.

**Comment by jbenet** [comment]
wonder if we should reuse the record abstraction here @diasdavid? Basically
peerstore, providers, and so on all storing records and internally they can
be given a recordstore implementation backed by a go-datastore to store to
disk. Would seriously simplify the abstraction creep in all the modules.
(I.e. Only one module would know why a datastore is a thing).

I think @diasdavid already does something like this, or has suggested it in
the past.

**Comment by diasdavid** [comment]
do we need to sign the peer info objects? storing them as records would mean that, which might be a good thing and also, would write them to disk with some validity property.

**Comment by bigs** [comment]
I'm gonna take a go at this! There already seems to be some work done on the [go-libp2p-peerstore](https://github.com/libp2p/go-libp2p-peerstore/pull/10) project, though it seems quite stale. If I don't hear anything about reviving that change, I'll probably start fresh (taking ideas/inspiration from that PR) tomorrow.

**Comment by Stebalien** [comment]
This exists now.
