### ISSUE TITLE
Pipelined identify protocol "negotiation"

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#903]
Now that we're going to introduce multiple identify protocols, we'll need to negotiate to pick the right one. This could cost us multiple round-trips.

However, there's a simple hack to work around this: just send all protocols we speak up-front!

That is, instead of:

```
> /multistream/1.0.0\n
> /p2p/id/1.1.0
< /multistream/1.0.0\n
< na
> /ipfs/id/1.0.0\n
< /ipfs/id/1.0.0\n
< Identify Message
```

Send all protocols we speak together:

```
> /multistream/1.0.0\n
> /p2p/id/1.1.0
> /ipfs/id/1.0.0\n
< /multistream/1.0.0\n
< na
< /ipfs/id/1.0.0\n
< Identify Message
```

The trick here is that the receiver will _ignore_ any data from the initiator of the identify request.

**Comment by raulk** [comment]
Can't we just make the identify message for `/p2p/id/1.1.0` backwards compatible? Unless I'm missing something (which I probably am), it should be easily doable with Protobuf.

**Comment by Stebalien** [comment]
We can. But in that case, we'd need to keep the same protocol name.

**Comment by Stebalien** [comment]
(i.e., /ipfs/id/1.0.0)

**Comment by raulk** [comment]
Exactly, that’s precisely what I mean. Versioning protocols by outer protocol identifiers is _one_ way to version protocol. It’s practicable when it’s accompanied by an efficient protocol negotiation scheme. Multistream-select 1.0 is not that, it’s pretty wasteful, and working around it with a bespoke flow is something I’d like to avoid. Let’s version the protocol from _inside_ the protocol in this case. When we introduce a HELLO message in ms2.0, all this will become much better.

**Comment by Stebalien** [comment]
This is no longer an issue.
