### ISSUE TITLE
Remove deprecated Warning/Warningf log calls

### ISSUE THREAD

**Issue by travisperson** [libp2p/go-libp2p#908]
Both `Warning` and `Warningf` are deprecated in `go-log@v1.0.4` and removed in the newer v2. The current use of these deprecated methods impacts the ability to get proper caller information. Logs produced with these methods result in one of two callers inside of the go-log package.

Eg: `go-log@v1.0.4/log.go:180`, or `go-log@v1.0.4/log.go:175`.

This makes it more cumbersome to filter through logs when using tools like Kibana where filtering in/out a log line by caller is easier than trying to filter in/out a string of a message. It also makes it hard for anyone not familiar with the libp2p code base to understand where a log is coming from. For warning logs particular knowing the actual caller is important.

I've opened this same issue on two other libp2p repositories, there might be others but these are the ones I've seen before.

- https://github.com/libp2p/go-libp2p-pubsub/issues/321
- https://github.com/libp2p/go-libp2p-swarm/issues/213

**Comment by Stebalien** [comment]
Note: We've added these back (deprecated) in 2.0.6 because we're passing the logger to some libraries that expect these functions to be defined.

Does https://github.com/ipfs/go-log/pull/82 fix your issue? If so, I'll backport this change to the 1.0 branch.

**Comment by travisperson** [comment]
Ya, if we remove the additional caller when calling `Warning` / `Warningf` I think that is fine.
