### ISSUE TITLE
Filter advertised observed addresses

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#910]
Currently, we advertise all observed addresses that have enough votes. Instead, for each IP & transport set, we should advertise a few with the most observations.

Algorithm:

* Given `/ipX/.../{tcp,udp}/PORT/.....`, group observations by the key `/ipX/.../{tcp,udp}/0/.....`.
* For each group of observations:
  * Advertise the top 1-2 addresses observed by inbound connections.
  * Advertise the top 1-2 observations from outbound connections.

Why advertise both inbound/outbound? Port mappings may have changed.

Ideally, instead of just advertising 1-2, we'd look at standard deviations and advertise everything within 1 stdev of the most observed address (with a cutt-off of 3?).

**Comment by aarshkshah1992** [comment]
@Stebalien I went though how the observed addr manager works and understand what we are trying to accomplish here. Can you please just explain this one comment of yours in a bit more detail ?

> Why advertise both inbound/outbound? Port mappings may have changed.

**Comment by Stebalien** [comment]
Well, my thinking was that my NAT may have mapped me to one outbound port then switched that mapping to a new port.

If I continue advertising the inbound port only but am mostly making outbound requests (e.g., I'm a DHT client), I may not be advertising the correct address.

On the other hand, this seems like a _really_ unlikely case. It's probably safe to just announce addresses discovered from inbound connections.

**Comment by aarshkshah1992** [comment]
Merged in https://github.com/libp2p/go-libp2p/pull/917.
