### ISSUE TITLE
Filter advertised interface addresses

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p#911]
Currently, we advertise addresses of all interfaces. This will continue to be an issue until we fix #436 so we should at least _prioritize_ better addresses.

We can do this by extending the default address filter to filter interface addresses such that we advertise fewer interface addresses:

1. Always advertise localhost. This will be filtered by identify if necessary.
2. Find the "default" route and advertise that address (all transports).
3. Advertise addresses in the public address range (again, all transports).

Really, that's all we need to advertise. Given that we'll _also_ advertise observed addresses, if we happen to be connecting to other libp2p nodes, those addresses will show up in our observations so we don't need ti include them _here_.

**Comment by aarshkshah1992** [comment]
> Really, that's all we need to advertise. Given that we'll also advertise observed addresses, if we happen to be connecting to other libp2p nodes, those addresses will show up in our observations so we don't need ti include them here.

I am not sure what you mean. The only place we use/include the observed addresses is in the `h.Addrs()` call. So, we shouldn't we also filter them here ? Or do you mean #910 will take care of them ?

**Comment by Stebalien** [comment]
> Do you mean the LAN/private address ?

Yes. Specifically, I mean use https://github.com/libp2p/go-netroute/ to ask for the route to `0.0.0.0`. That _should_ give us our default local IP address.

> I am not sure what you mean.

I think I'm just being confusing.

Basically, in [`BasicHost.AllAddrs`](https://github.com/libp2p/go-libp2p/blob/077a81814f4357379d11dc93d40f48788e515fa0/p2p/host/basic/basic_host.go#L676), we :

1. Call `InterfaceListenAddresses` to get all of the addresses from our local interfaces.
2. Get the addresses from our NAT device.
3. Get our observed addresses.

I'm saying we should filter `InterfaceListenAddresses` to only include:

* localhost
* public addresses
* the _default_ address (as determined by go-netroute).

WRT observed addresses, I'm saying that even _if_ we filter out most of our interface addresses in the previous step, if any of them are actually being used, we should see them show up in our address observations so it shouldn't be a problem.

**Comment by aarshkshah1992** [comment]
@Stebalien I understand wha you mean and I can get started on this.

However, can you give some examples of the kinds of "bad address" that creep in from `InterfaceListenAddresses ` that we want to filter here ?

**Comment by Stebalien** [comment]
Docker container/network addresses, mostly. One can easily end up with a bunch of interfaces for different docker networks, each with a separate private IP address.

**Comment by aarshkshah1992** [comment]
@Stebalien 

Here's the problem:

We filter the addresses returned by `host.AllAddrs` like so:
```

// Addrs returns listening addresses that are safe to announce to the network.
// The output is the same as AllAddrs, but processed by AddrsFactory.
func (h *BasicHost) Addrs() []ma.Multiaddr {
	return h.AddrsFactory(h.AllAddrs())
}
```

At this point, we don't know which are the Interface addresses and which are the observed addresses. Identify calls this function to find out which addresses to advertise. So, how can Identify ONLY apply the filter to the Interface Addresses and not to the Observed addresses ?

I assume we don't want to to filter the Interface addresses inside the `h.AllAddrs` function as that function has a lot of callers and each of them will see the filtered set (not just Identify which wants the filtering for the advertisement).

**Comment by aarshkshah1992** [comment]
@Stebalien After thinking though this, I think we should change `host.Addrs()` call itself to incorporate this. Wdyt ?

**Comment by Stebalien** [comment]
Yes. Sorry, I meant modify `AllAddrs` itself, not modify identify.

The only thing we filter in identify is `localhost` (which we already do).

**Comment by aarshkshah1992** [comment]
Merged in https://github.com/libp2p/go-libp2p/pull/936.
