### ISSUE TITLE
Connectivity issues

### ISSUE THREAD

**Issue by iulianpascalau** [libp2p/go-libp2p#916]
We have some connectivity issues between our nodes that use some wrappers over the host and kad dht components. The components are instantiated with the following parameters:
```GO
	address := fmt.Sprintf("/ip4/0.0.0.0/tcp/%d", args.P2pConfig.Node.Port)
	opts := []libp2p.Option{
		libp2p.ListenAddrStrings(address),
		libp2p.Identity(p2pPrivKey),
		libp2p.NATPortMap(),
		libp2p.EnableNATService(),
	}
	
	h, err := libp2p.New(args.Context, opts...)
	....
	
	
	and
	
	protocolID := protocol.ID("/erd/kad/1.0.0")
	kademliaDHT, err := dht.New(
		ckdd.context,
		ckdd.hostConnManagement, //this is the host
		dht.ProtocolPrefix(protocolID),
		dht.RoutingTableRefreshPeriod(ckdd.routingTableRefresh),   // this is 300 seconds
		dht.RoutingTableRefreshQueryTimeout(peerDiscoveryTimeout), // this is 2 seconds
		dht.Mode(dht.ModeServer),
		dht.DisableProviders(),
		dht.DisableValues(),
	)
```

Suppose we have 3 peers (one that we call it seeder and 2 let's call them nodes). Nodes connect to the seeder as they know only that IP in the first place. The following scenarios cann occur:
1. all nodes can bind on all interfaces, there are no NATs and firewall allows inbound connections on opened ports; everything works as expected (all three nodes connect with each other => every node has 2 connections).
2. **seeder** without NAT, firewall allows inbound connections on the opened port; **node1** and node2** without NATs, firewall blocks inbound connections on the opened ports; connections are made only with the seeder => node1 and node2 are not connected between them.
3. **seeder** without NAT, firewall allows inbound connections on the opened port; **node1** without NAT, firewall allows inbound connections on the opened port, **node2** behind NAT; everything works as expected (all three nodes connect with each other => every node has 2 connections).     
4. **seeder** without NAT, firewall allows inbound connections on the opened port; **node1** without NAT, firewall blocks inbound connections on the opened ports; **node2** behind NAT; firewall blocks inbound connections on the opened ports; connections are made only with the seeder => node1 and node2 are not connected between them. This last scenario is *not always* valid, because through some NATs, there is still a chance for a connection between node1 and node2. If the NAT and the node could not negotiate NAT traversal, the connection will never be done (even if some more nodes join the network and help **node2** to find out his public IP).
We have tried using the `libp2p.EnableAutoRelay(), libp2p.DefaultStaticRelays()` options with limited success. We do not want to use relayers because of network bandwidth concerns.

Running with enabled logging, we saw errors like:
```
2020-05-11T11:49:22.150Z	DEBUG	dht	go-libp2p-kad-dht@v0.7.11/query.go:491	error connecting: failed to dial 16Uiu2HAmAxHRRg7cvyaRDLuS3LHZGbSJ64uEjvDrMbJXXKz9NZ2s: all dials failed
  * [/ip4/10.19.0.5/tcp/9999] dial tcp4 0.0.0.0:10000->10.19.0.5:9999: i/o timeout
  * [/ip4/165.22.19.97/tcp/9999] dial tcp4 0.0.0.0:10000->165.22.19.97:9999: i/o timeout
```
165.22.19.97 was the public IP of the node and port 9999 was closed by the firewall for inbound connections.

<details>
<summary>Version Information</summary>
<pre>
github.com/ElrondNetwork/elrond-go
cloud.google.com/go v0.26.0
github.com/AndreasBriese/bbloom v0.0.0-20190306092124-e2d15f34fcf9
github.com/BurntSushi/toml v0.3.1
github.com/ElrondNetwork/arwen-wasm-vm v0.3.16
github.com/ElrondNetwork/big-int-util v0.0.5
github.com/ElrondNetwork/concurrent-map v0.1.2
github.com/ElrondNetwork/elrond-go-logger v1.0.3
github.com/ElrondNetwork/elrond-vm v0.0.25
github.com/ElrondNetwork/elrond-vm-common v0.1.19
github.com/ElrondNetwork/elrond-vm-util v0.2.3
github.com/Kubuxu/go-os-helper v0.0.1
github.com/OneOfOne/xxhash v1.2.2
github.com/StackExchange/wmi v0.0.0-20180116203802-5d049714c4a6
github.com/aead/siphash v1.0.1
github.com/armon/consul-api v0.0.0-20180202201655-eb2c6b5be1b6
github.com/beevik/ntp v0.2.0
github.com/btcsuite/btcd v0.20.1-beta
github.com/btcsuite/btclog v0.0.0-20170628155309-84c8d2346e9f
github.com/btcsuite/btcutil v0.0.0-20190425235716-9e5f4b9a998d
github.com/btcsuite/go-socks v0.0.0-20170105172521-4720035b7bfd
github.com/btcsuite/goleveldb v0.0.0-20160330041536-7834afc9e8cd
github.com/btcsuite/snappy-go v0.0.0-20151229074030-0bdef8d06723
github.com/btcsuite/websocket v0.0.0-20150119174127-31079b680792
github.com/btcsuite/winsvc v1.0.0
github.com/cespare/xxhash v1.1.0
github.com/client9/misspell v0.3.4
github.com/coreos/etcd v3.3.10+incompatible
github.com/coreos/go-etcd v2.0.0+incompatible
github.com/coreos/go-semver v0.3.0
github.com/cpuguy83/go-md2man v1.0.10
github.com/davecgh/go-spew v1.1.1
github.com/davidlazar/go-crypto v0.0.0-20170701192655-dcfb0a7ac018
github.com/dgraph-io/badger v1.6.1
github.com/dgraph-io/ristretto v0.0.2
github.com/dgryski/go-farm v0.0.0-20190423205320-6a90982ecee2
github.com/dustin/go-humanize v1.0.0
github.com/elastic/go-elasticsearch/v7 v7.1.0
github.com/fsnotify/fsnotify v1.4.7
github.com/gin-contrib/cors v0.0.0-20190301062745-f9e10995c85a
github.com/gin-contrib/pprof v1.2.0
github.com/gin-contrib/sse v0.0.0-20170109093832-22d885f9ecc7
github.com/gin-gonic/gin v1.3.0
github.com/gizak/termui/v3 v3.1.0
github.com/go-check/check v0.0.0-20180628173108-788fd7840127
github.com/go-ole/go-ole v1.2.1
github.com/gogo/protobuf v1.3.1
github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
github.com/golang/mock v1.1.1
github.com/golang/protobuf v1.3.5
github.com/golang/snappy v0.0.1
github.com/google/go-cmp v0.3.0
github.com/google/gopacket v1.1.17
github.com/google/gops v0.3.6
github.com/google/renameio v0.1.0
github.com/google/uuid v1.1.1
github.com/gorilla/websocket v1.4.2
github.com/gxed/hashland/keccakpg v0.0.1
github.com/gxed/hashland/murmur3 v0.0.1
github.com/hashicorp/errwrap v1.0.0
github.com/hashicorp/go-multierror v1.1.0
github.com/hashicorp/golang-lru v0.5.4
github.com/hashicorp/hcl v1.0.0
github.com/herumi/bls-go-binary v0.0.0-20200324054641-17de9ae04665
github.com/hpcloud/tail v1.0.0
github.com/huin/goupnp v1.0.0
github.com/huin/goutil v0.0.0-20170803182201-1ca381bf3150
github.com/inconshreveable/mousetrap v1.0.0
github.com/ipfs/go-cid v0.0.5
github.com/ipfs/go-datastore v0.4.4
github.com/ipfs/go-detect-race v0.0.1
github.com/ipfs/go-ds-badger v0.2.3
github.com/ipfs/go-ds-leveldb v0.4.2
github.com/ipfs/go-ipfs-delay v0.0.0-20181109222059-70721b86a9a8
github.com/ipfs/go-ipfs-util v0.0.1
github.com/ipfs/go-ipns v0.0.2
github.com/ipfs/go-log v1.0.4
github.com/ipfs/go-log/v2 v2.0.5
github.com/jackpal/gateway v1.0.5
github.com/jackpal/go-nat-pmp v1.0.2
github.com/jbenet/go-cienv v0.1.0
github.com/jbenet/go-temp-err-catcher v0.0.0-20150120210811-aac704a3f4f2
github.com/jbenet/goprocess v0.1.4
github.com/jessevdk/go-flags v1.4.0
github.com/jrick/logrotate v1.0.0
github.com/json-iterator/go v1.1.5
github.com/kami-zh/go-capturer v0.0.0-20171211120116-e492ea43421d
github.com/kardianos/osext v0.0.0-20190222173326-2bc1f35cddc0
github.com/keybase/go-ps v0.0.0-20161005175911-668c8856d999
github.com/kisielk/errcheck v1.2.0
github.com/kisielk/gotool v1.0.0
github.com/kkdai/bstream v0.0.0-20161212061736-f391b8402d23
github.com/konsorten/go-windows-terminal-sequences v1.0.1
github.com/koron/go-ssdp v0.0.0-20191105050749-2e1c40ed0b5d
github.com/kr/pretty v0.2.0
github.com/kr/pty v1.1.1
github.com/kr/text v0.1.0
github.com/libp2p/go-addr-util v0.0.1
github.com/libp2p/go-buffer-pool v0.0.2
github.com/libp2p/go-conn-security-multistream v0.1.0
github.com/libp2p/go-eventbus v0.1.0
github.com/libp2p/go-flow-metrics v0.0.3
github.com/libp2p/go-libp2p v0.8.2
github.com/libp2p/go-libp2p-autonat v0.2.2
github.com/libp2p/go-libp2p-blankhost v0.1.4
github.com/libp2p/go-libp2p-circuit v0.2.1
github.com/libp2p/go-libp2p-core v0.5.3
github.com/libp2p/go-libp2p-crypto v0.1.0
github.com/libp2p/go-libp2p-discovery v0.3.0
github.com/libp2p/go-libp2p-kad-dht v0.7.11
github.com/libp2p/go-libp2p-kbucket v0.4.1
github.com/libp2p/go-libp2p-loggables v0.1.0
github.com/libp2p/go-libp2p-mplex v0.2.3
github.com/libp2p/go-libp2p-nat v0.0.6
github.com/libp2p/go-libp2p-netutil v0.1.0
github.com/libp2p/go-libp2p-peer v0.2.0
github.com/libp2p/go-libp2p-peerstore v0.2.3
github.com/libp2p/go-libp2p-pnet v0.2.0
github.com/libp2p/go-libp2p-pubsub v0.2.6
github.com/libp2p/go-libp2p-record v0.1.2
github.com/libp2p/go-libp2p-routing-helpers v0.2.3
github.com/libp2p/go-libp2p-secio v0.2.2
github.com/libp2p/go-libp2p-swarm v0.2.3
github.com/libp2p/go-libp2p-testing v0.1.1
github.com/libp2p/go-libp2p-tls v0.1.3
github.com/libp2p/go-libp2p-transport-upgrader v0.2.0
github.com/libp2p/go-libp2p-yamux v0.2.7
github.com/libp2p/go-maddr-filter v0.0.5
github.com/libp2p/go-mplex v0.1.2
github.com/libp2p/go-msgio v0.0.4
github.com/libp2p/go-nat v0.0.5
github.com/libp2p/go-netroute v0.1.2
github.com/libp2p/go-openssl v0.0.4
github.com/libp2p/go-reuseport v0.0.1
github.com/libp2p/go-reuseport-transport v0.0.3
github.com/libp2p/go-sockaddr v0.0.2
github.com/libp2p/go-stream-muxer v0.0.1
github.com/libp2p/go-stream-muxer-multistream v0.2.0
github.com/libp2p/go-tcp-transport v0.2.0
github.com/libp2p/go-ws-transport v0.3.0
github.com/libp2p/go-yamux v1.3.5
github.com/magiconair/properties v1.8.0
github.com/mailru/easyjson v0.0.0-20180823135443-60711f1a8329
github.com/mattn/go-colorable v0.1.1
github.com/mattn/go-isatty v0.0.5
github.com/mattn/go-runewidth v0.0.2
github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
github.com/miekg/dns v1.1.28
github.com/minio/blake2b-simd v0.0.0-20160723061019-3f5f724cb5b1
github.com/minio/sha256-simd v0.1.1
github.com/mitchellh/go-homedir v1.1.0
github.com/mitchellh/go-wordwrap v0.0.0-20150314170334-ad45545899c7
github.com/mitchellh/mapstructure v1.1.2
github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
github.com/modern-go/reflect2 v1.0.1
github.com/mr-tron/base58 v1.1.3
github.com/multiformats/go-base32 v0.0.3
github.com/multiformats/go-multiaddr v0.2.1
github.com/multiformats/go-multiaddr-dns v0.2.0
github.com/multiformats/go-multiaddr-fmt v0.1.0
github.com/multiformats/go-multiaddr-net v0.1.4
github.com/multiformats/go-multibase v0.0.1
github.com/multiformats/go-multihash v0.0.13
github.com/multiformats/go-multistream v0.1.1
github.com/multiformats/go-varint v0.0.5
github.com/nsf/termbox-go v0.0.0-20190121233118-02980233997d
github.com/onsi/ginkgo v1.12.0
github.com/onsi/gomega v1.9.0
github.com/opentracing/opentracing-go v1.1.0
github.com/pelletier/go-toml v1.6.0
github.com/pkg/errors v0.9.1
github.com/pkg/profile v1.3.0
github.com/pmezard/go-difflib v1.0.0
github.com/rogpeppe/go-internal v1.3.0
github.com/russross/blackfriday v1.5.2
github.com/shirou/gopsutil v0.0.0-20190731134726-d80c43f9c984
github.com/shirou/w32 v0.0.0-20160930032740-bb4de0191aa4
github.com/sirupsen/logrus v1.2.0
github.com/smola/gocompat v0.2.0
github.com/spacemonkeygo/openssl v0.0.0-20181017203307-c2dcc5cca94a
github.com/spacemonkeygo/spacelog v0.0.0-20180420211403-2296661a0572
github.com/spaolacci/murmur3 v1.1.0
github.com/spf13/afero v1.1.2
github.com/spf13/cast v1.3.0
github.com/spf13/cobra v0.0.5
github.com/spf13/jwalterweatherman v1.0.0
github.com/spf13/pflag v1.0.3
github.com/spf13/viper v1.3.2
github.com/src-d/envconfig v1.0.0
github.com/stretchr/objx v0.1.1
github.com/stretchr/testify v1.5.1
github.com/syndtr/goleveldb v1.0.1-0.20190318030020-c3a204f8e965
github.com/ugorji/go/codec v0.0.0-20181209151446-772ced7fd4c2
github.com/urfave/cli v1.20.0
github.com/wangjia184/sortedset v0.0.0-20160527075905-f5d03557ba30
github.com/whyrusleeping/go-keyspace v0.0.0-20160322163242-5b898ac5add1
github.com/whyrusleeping/go-logging v0.0.1
github.com/whyrusleeping/mafmt v1.2.8
github.com/whyrusleeping/mdns v0.0.0-20190826153040-b9b60ed33aa9
github.com/whyrusleeping/multiaddr-filter v0.0.0-20160516205228-e903e4adabd7
github.com/whyrusleeping/timecache v0.0.0-20160911033111-cfcb2f1abfee
github.com/x-cray/logrus-prefixed-formatter v0.5.2
github.com/xlab/treeprint v0.0.0-20180616005107-d6fb6747feb6
github.com/xordataexchange/crypt v0.0.3-0.20170626215501-b2862e3d0a77
go.opencensus.io v0.22.3
go.uber.org/atomic v1.6.0
go.uber.org/goleak v1.0.0
go.uber.org/multierr v1.5.0
go.uber.org/tools v0.0.0-20190618225709-2cfd321de3ee
go.uber.org/zap v1.14.1
golang.org/x/crypto v0.0.0-20200221231518-2aa609cf4a9d
golang.org/x/exp v0.0.0-20190121172915-509febef88a4
golang.org/x/lint v0.0.0-20190930215403-16217165b5de
golang.org/x/mod v0.1.1-0.20191105210325-c90efee705ee
golang.org/x/net v0.0.0-20190923162816-aa69164e4478
golang.org/x/oauth2 v0.0.0-20180821212333-d2e6202438be
golang.org/x/sync v0.0.0-20190423024810-112230192c58
golang.org/x/sys v0.0.0-20200223170610-d5e6a3e2c0ae
golang.org/x/text v0.3.2
golang.org/x/tools v0.0.0-20191216052735-49a3e744a425
golang.org/x/xerrors v0.0.0-20191011141410-1b5146add898
google.golang.org/appengine v1.4.0
google.golang.org/genproto v0.0.0-20190425155659-357c62f0e4bb
google.golang.org/grpc v1.20.1
gopkg.in/check.v1 v1.0.0-20190902080502-41f04d3bba15
gopkg.in/errgo.v2 v2.1.0
gopkg.in/fsnotify.v1 v1.4.7
gopkg.in/go-playground/assert.v1 v1.2.1
gopkg.in/go-playground/validator.v8 v8.18.2
gopkg.in/src-d/go-cli.v0 v0.0.0-20181105080154-d492247bbc0d
gopkg.in/src-d/go-log.v1 v1.0.1
gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
gopkg.in/yaml.v2 v2.2.4
honnef.co/go/tools v0.0.1-2019.2.3
rsc.io/goversion v1.0.0
</pre>
</details>

**Comment by raulk** [comment]
Looking at this.

**Comment by iulianpascalau** [comment]
If necessary, I can have a stripped down version for easy testing.

**Comment by raulk** [comment]
@iulianpascalau could you please distil what you expected to happen, and what happened? From parsing your 4 scenarios:

1. Looks correct.
2. Expected. If firewalls on node1 and node2 won't allow inbound connections, they can only make outbound connections. libp2p, by definition, cannot pierce through firewalls. We can do our best with NATs hole punching/mapping.
3. Expected. Seems like node1 connects to node2.
4. I think this is the scenario where you believe libp2p is at fault. But you say that both node1 and node2 are behind a firewall that doesn't allow inbound connections. Why do you expect that any of these nodes would be diallable then?

**Comment by raulk** [comment]
Discussed with @iulianpascalau out of band. There was an underlying misconception in the difference between NATs and firewalls, which led them to set up a testing scenario that was pathological. libp2p cannot traverse firewalls with DENY ALL rules for incoming connections -- that equates to performing an attack, and succeeding would mean we've discovered a vulnerability in that firewall.
