### ISSUE TITLE
Dialback Protocol

### ISSUE THREAD

**Issue by dirkmc** [libp2p/go-libp2p#925]
### Background

New users to IPFS typically expect to be able to add some data to IPFS on their local machine and then fetch it through the IPFS Gateway, or from a Pinning Service.

If the user's local machine is behind a NAT, another machine can't fetch the data.

### Dialback Protocol

One solution is for the publicly available node to request a "dialback" from the NATed node. Once the NATed node connects directly to the public node, the public node can fetch the data from the NATed node through this connection.

During a DHT query, each node reports its nearest neighbours - the NATed node should be connected to its nearest neighbours in the DHT. In order to request a dialback, the public node can find a neighbour to the NATed node and ask the neighbour to pass the dialback request to the NATed node. Participating nodes' peer records should indicate that they support the dialback protocol.

**Comment by aarshkshah1992** [comment]
@jacobheun This falls under the larger umbrella of NAT traversal. Assigning this to myself as this should be the first win in that path.

**Comment by marten-seemann** [comment]
This should be handled by our hole punching logic now.
