### ISSUE TITLE
TestIDService is flaky

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#944]
@Stebalien 

Tackling this with priority:

https://travis-ci.com/github/libp2p/go-libp2p/builds/167056100.

**Comment by aarshkshah1992** [comment]
It's really hard to reproduce the flakiness:

```
aarshshah@Aarshs-MacBook-Pro identify % go test -race -count=50 -run TestIDService
PASS
ok  	github.com/libp2p/go-libp2p/p2p/protocol/identify	380.844s
```

**Comment by vyzo** [comment]
travis is very slow and may be running with a single processor. 
We have no end in grief in the pubsub tests, which are by necessity timing dependent :(
