### ISSUE TITLE
Remove Connection Gater from transport constructors that take an Upgrader

### ISSUE THREAD

**Issue by aarshkshah1992** [libp2p/go-libp2p#951]
We don't need it because the `Upgrader` already has it. See:

https://github.com/libp2p/go-libp2p/pull/881#discussion_r428186604.

**Comment by marten-seemann** [comment]
This is needed because the QUIC constructor takes a `ConnectionGater` (but no `Upgrader`): https://github.com/libp2p/go-libp2p-quic-transport/blob/47b90e048cfc99b7cf9e7c377d6af9525483ef9f/transport.go#L129-L130
