### ISSUE TITLE
PeerID Encoding/Decoding is inconsistent with specs

### ISSUE THREAD

**Issue by aschmahmann** [libp2p/go-libp2p#975]
The PeerID text spec https://github.com/libp2p/specs/blob/master/RFC/0001-text-peerid-cid.md, makes no reference to allowing us to decode identity multihashes as PeerIDs and yet we do [here](https://github.com/libp2p/go-libp2p-core/blob/9cf214f5019d0aebb1f5dca184db276284e7639e/peer/peer.go#L173). 

Similarly, the Encode(peerID) function in [go-libp2p-core](https://github.com/libp2p/go-libp2p-core/blob/9cf214f5019d0aebb1f5dca184db276284e7639e/peer/peer.go#L193) is also not spec compliant since it just encodes every peerID as base58 instead of returning it as a CID (e.g. identity multihashes are returned as base58 encoded)

Is the bug in the spec or code? Are we able to keep the spec as is at this point, or do we have to change it to accommodate people already using the non-spec compliant code?

^ @stebalien @raulk @lidel

**Comment by Stebalien** [comment]
That was the original RFC. The spec has since been fixed:
https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md

**Comment by aschmahmann** [comment]
Ah ok. So that means we just have a bug in Encode then right?

**Comment by Stebalien** [comment]
No? Encode encodes in the legacy format for now.

**Comment by aschmahmann** [comment]
You're right it is consistent with the specs as it encodes in the legacy (base58) version. There's a separate issue to be raised here about whether we should upgrade to the newer version.

**Comment by aschmahmann** [comment]
Separate issue on upgrading is https://github.com/libp2p/go-libp2p/issues/976
