### ISSUE TITLE
Identify Push does not emit eventbus events

### ISSUE THREAD

**Issue by aschmahmann** [libp2p/go-libp2p#977]
Unlike its siblings `identify` and `identify/delta`, `identify/push` does not seem to emit events on the eventbus such as `EvtPeerIdentificationCompleted`, or `EvtPeerProtocolsUpdated`. It should emit both of these events.

Question: Is there any assumption in `EvtPeerIdentificationCompleted` that would prevent it from being used in identify push?

@Stebalien @aarshkshah1992

**Comment by Stebalien** [comment]
Related to #860.
