### ISSUE TITLE
Logging issue in go-libp2p

### ISSUE THREAD

**Issue by urbi001** [libp2p/go-libp2p#978]
I am using the below go version:
go version go1.14.4 linux/amd64
While executing 
go get "github.com/libp2p/go-libp2p", I get the below error:
# github.com/libp2p/go-libp2p-loggables
go-libp2p-loggables/loggables.go:19:26: undefined: log.Loggable
go-libp2p-loggables/loggables.go:20:9: undefined: log.Metadata
go-libp2p-loggables/loggables.go:27:21: undefined: log.Loggable
go-libp2p-loggables/loggables.go:28:9: undefined: log.Metadata
go-libp2p-loggables/loggables.go:33:23: undefined: log.Metadata
go-libp2p-loggables/loggables.go:38:9: undefined: log.Metadata
# github.com/libp2p/go-addr-util
go-addr-util/addr.go:101:5: log.Event undefined (type *log.ZapEventLogger has no field or method Event)
go-addr-util/addr.go:101:63: undefined: log.Loggable
go-addr-util/addr.go:106:10: undefined: log.Metadata
# github.com/libp2p/go-libp2p/p2p/protocol/identify
go-libp2p/p2p/protocol/identify/id.go:367:6: log.Event undefined (type *log.ZapEventLogger has no field or method Event)
go-libp2p/p2p/protocol/identify/id.go:367:67: undefined: log.Metadata
# github.com/libp2p/go-libp2p-secio
go-libp2p-secio/protocol.go:117:11: log.EventBegin undefined (type *log.ZapEventLogger has no field or method EventBegin)

Any clue will be helpful!

**Comment by Stebalien** [comment]
You need to use go modules.

**Comment by jpldcarvalho** [comment]
I have the same issue. @Stebalien can you give some detail on your answer? The libp2p-loggables import the logging from the ipfs/go-log, but it seems the default log module from go overrides. Any idea how to fix it?
