### ISSUE TITLE
Proposal: Closable Transport

### ISSUE THREAD

**Issue by Jorropo** [libp2p/go-libp2p#999]
# Use Case
While writing a tor transport I noticed that some transports runs some node beyond the listener (mainly overlay networks).
For example my tor transport runs a tor node and I need to close it at one point. I can't rely on the listeners to close it because it's not because a node stop listening on an address it will not then dial someone.
# Additions
I propose to add this in `go-libp2p-core/transport` :
```go
type ClosableTransport interface {
  Transport

  // Close is called when the libp2p node doesn't need the transport anymore (the is node closing).
  // After that the transport can safely assume no more Listen() or Dial() are gonna be done.
  // This is usefull for transport running overlay network.
  Close() error
}
```
Then in `host.Close()` the host would use reflection to terminate the transport when closing (after closing all listeners) :
```go
// Not actual working code, just an idea
var wg sync.WaitGroup
for _, v := range h.transports {
  ct, ok := v.(tpt.ClosableTransport)
  if ok {
    wg.Add(1)
    go func (t tpt.ClosableTransport){ // Needed because range is not thread safe
      defer wg.Done()
      t.Close()
    }(ct)
  }
}
wg.Wait()
```
(Also I can't rely on the garbage collector to do this work because I have some CGO code (or a system fork) and the garbage collector doesn't deal with that.)
## In the Future
If in the future a method to unhook transport from a libp2p is added the transport will be closable that way.

**Comment by aschmahmann** [comment]
Looks like this is related to #992. WDYT @Stebalien @vyzo @raulk

**Comment by Stebalien** [comment]
It seems reasonable, but I'm not sure if we even need an interface change for this. We can probably just add a `io.Closer`. See https://github.com/libp2p/go-libp2p-swarm/pull/227.

**Comment by vyzo** [comment]
I don't think we need an interface change for this; we can soft check if the transport implements `io.Closer` and just call it.

**Comment by Jorropo** [comment]
@vyzo @Stebalien yes thx, I didn't even though of that, that certainly prettier.
With a small comment aside of `go-libp2p-core/transport#Transport` this would be perfect (this shouldn't stay an hidded feature it must be in the doc somewhere).

**Comment by Jorropo** [comment]
Unexpected close (I was merging this in my repo for some mod replace rules and this somehow closed this).
I guess `Closes #xxx` works cross repo.

**Comment by marten-seemann** [comment]
Should the libp2p-quic-transport implement this?

**Comment by Jorropo** [comment]
> Should the libp2p-quic-transport implement this?

@marten-seemann 
That up to the transport, for quic yes it must,
That would solve the issue of quic not closing the shared socket when libp2p close (libp2p/go-libp2p#992).
